from app.seed.helpers import err, fill, mc, xf


def _exam(
    level_code: str,
    title: str,
    description: str,
    questions: list[dict],
    time_limit_sec: int = 1200,
    passing_score: int = 75,
) -> dict:
    return {
        "level_code": level_code,
        "title": title,
        "description": description,
        "time_limit_sec": time_limit_sec,
        "passing_score": passing_score,
        "questions": questions,
    }


EXAMS = [
    _exam(
        "A1",
        "Экзамен A1",
        "Базовая грамматика: to be, артикли, Present Simple и Continuous, there is/are, can, Past Simple и going to.",
        [
            mc("Выберите верную форму: She ___ a doctor.", ["am", "is", "are"], "is", "Для he/she/it глагол to be имеет форму is."),
            fill("I ___ from Canada. (be)", "am", "С местоимением I используется am."),
            xf("Сделайте вопрос: They are late.", "Are they late?", "В вопросе to be ставится перед подлежащим."),
            err("Исправьте: He are my brother.", "He is my brother.", "He требует форму is, не are."),
            mc("Выберите артикль: ___ hour ago I was here.", ["A", "An", "The"], "An", "Hour начинается с гласного звука, поэтому an."),
            fill("She ___ in Lisbon. (live)", "lives", "В Present Simple у he/she/it добавляется -s."),
            xf("Сделайте вопрос: They play tennis.", "Do they play tennis?", "В Present Simple вопрос строится с Do + подлежащее + глагол."),
            err("Исправьте: He don't like coffee.", "He doesn't like coffee.", "Для he нужно doesn't, не don't."),
            mc("___ a cat on the sofa.", ["There is", "There are", "It are"], "There is", "Один объект — there is."),
            fill("She ___ play the piano.", "can", "Can не меняется по лицам: she can."),
            err("Исправьте: I can to cook.", "I can cook.", "После can инфинитив без to."),
            fill("I ___ ill last week. (be)", "was", "I в прошедшем сочетается с was."),
            mc("She ___ a new laptop last month.", ["buy", "bought", "buys"], "bought", "Past Simple неправильного глагола buy — bought."),
            err("Исправьте: Did you went home?", "Did you go home?", "После did смысловой глагол стоит в первой форме."),
            fill("I ___ going to start a course.", "am", "Конструкция: I am going to + глагол."),
            mc("The cat is ___ the box. (внутри)", ["on", "in", "at"], "in", "Внутри объёма используется in."),
        ],
    ),
    _exam(
        "A2",
        "Экзамен A2",
        "Past Continuous, Present Perfect, сравнение, will, первый тип условных, модальные и used to.",
        [
            mc("While I ___ dinner, the phone rang.", ["cooked", "was cooking", "am cooking"], "was cooking", "Длительное действие в прошлом, прерванное другим, — Past Continuous."),
            fill("I have never ___ to Japan. (be)", "been", "Опыт с never выражается Present Perfect: have been."),
            xf("Сделайте сравнительную степень: This bag is (cheap) than that one.", "This bag is cheaper than that one.", "Односложные прилагательные образуют comparative через -er."),
            err("Исправьте: I have saw that film.", "I have seen that film.", "Третья форма see — seen."),
            mc("How ___ milk is left?", ["many", "much", "few"], "much", "Milk неисчисляемое, поэтому much."),
            fill("If it rains, we ___ stay at home.", "will", "First conditional: if + Present Simple, will + глагол."),
            xf("Сделайте вопрос: You have to wait.", "Do you have to wait?", "Have to в вопросе требует do."),
            err("Исправьте: She is more taller than me.", "She is taller than me.", "Taller уже сравнительная форма, more не нужен."),
            mc("I ___ walk to school when I was little.", ["use to", "used to", "using to"], "used to", "Прошлая привычка — used to + глагол."),
            fill("There isn't ___ sugar.", "any", "В отрицании с неисчисляемым существительным ставится any."),
            xf("Сделайте превосходную степень: He is (tall) in the class.", "He is the tallest in the class.", "Односложное прилагательное: the + -est."),
            err("Исправьте: I enjoy to swim.", "I enjoy swimming.", "После enjoy нужен герундий."),
            mc("This book is ___ than that one.", ["interesting", "more interesting", "most interesting"], "more interesting", "Длинные прилагательные образуют comparative через more."),
            fill("You ___ see a doctor. (совет)", "should", "Вежливый совет выражается should + глагол."),
            xf("Объедините через who: There is a woman. She lives next door.", "There is a woman who lives next door.", "Who вводит относительное придаточное о человеке."),
            err("Исправьте: I will to help you.", "I will help you.", "После will инфинитив без to."),
        ],
    ),
    _exam(
        "B1",
        "Экзамен B1",
        "Контраст времён, Present Perfect Continuous, второй тип условных, пассив, reported speech и связки.",
        [
            mc("I ___ this book last year.", ["have read", "read", "am reading"], "read", "Маркер last year требует Past Simple, не Present Perfect."),
            fill("She has been ___ here since Monday. (work)", "working", "Present Perfect Continuous: has been + -ing."),
            xf("Раскройте скобки: If I had more time, I (travel) more.", "If I had more time, I would travel more.", "Second conditional: if + Past Simple, would + глагол."),
            err("Исправьте: This house built in 1990.", "This house was built in 1990.", "Пассив прошедшего: was/were + третья форма."),
            mc("He said he ___ tired.", ["is", "was", "be"], "was", "В косвенной речи настоящее обычно сдвигается в прошедшее."),
            fill("I've lived here ___ 2018.", "since", "Since вводит точку начала периода."),
            xf("Сделайте пассив: They clean the office every day.", "The office is cleaned every day.", "Present Simple passive: is/are + третья форма."),
            err("Исправьте: Despite of the rain, we went out.", "Despite the rain, we went out.", "После despite предлог of не ставится."),
            mc("The film was so ___ that I left.", ["bored", "boring", "bore"], "boring", "Прилагательное на -ing описывает источник чувства."),
            fill("I wish I ___ taller. (be)", "were", "После wish о настоящем — прошедшая форма; were предпочтительнее.", ["was"]),
            xf('Передайте речь: "I am busy," she said.', "She said she was busy.", "Am сдвигается в was; кавычки снимаются."),
            err("Исправьте: I know him for ten years.", "I have known him for ten years.", "Действие, длящееся до настоящего, — Present Perfect."),
            mc("Take an umbrella. It ___ rain.", ["must", "might", "should to"], "might", "Might выражает возможность, не обязанность."),
            fill("She looks ___ her little brother. (заботится)", "after", "Phrasal verb look after значит «присматривать, заботиться»."),
            xf("Объедините через so: I missed the bus. I was late.", "I missed the bus, so I was late.", "So вводит следствие."),
            err("Исправьте: If I would be you, I would stay.", "If I were you, I would stay.", "В if-части второго типа would не ставится; стандарт — If I were you."),
        ],
    ),
    _exam(
        "B2",
        "Экзамен B2",
        "Третий и смешанный типы условных, modal perfects, have something done, инверсия и герундий против инфинитива.",
        [
            mc("If I had known, I ___ you.", ["would call", "would have called", "will call"], "would have called", "Third conditional: if + Past Perfect, would have + третья форма."),
            fill("You should have ___ her. (tell)", "told", "Should have + третья форма выражает упрёк о прошлом."),
            xf(
                "Сделайте third conditional: I didn't study. I failed.",
                "If I had studied, I wouldn't have failed.",
                "Нереальное прошлое: If I had studied, I wouldn't have failed.",
                ["If I had studied, I would not have failed"],
            ),
            err("Исправьте: I wish I would have more time. (о состоянии сейчас)", "I wish I had more time.", "Wish о настоящем состоянии требует Past Simple, не would have."),
            mc("The roof is leaking. We'll ___ soon.", ["have repaired it", "have it repaired", "repair have it"], "have it repaired", "Каузатив: have something done."),
            fill("By next June she ___ have finished the course.", "will", "Future Perfect: will have + третья форма."),
            xf("Сделайте инверсию: I had never seen such chaos.", "Never had I seen such chaos.", "Отрицательное наречие выносится, вспомогательный глагол встаёт перед подлежащим."),
            err("Исправьте: I am used to wake up early.", "I am used to waking up early.", "Be used to требует герундия: привычка к действию."),
            mc("I remember ___ the door. (помню, что сделал это)", ["to lock", "locking", "lock"], "locking", "Remember + -ing — воспоминание о прошлом действии."),
            fill("She must have ___ the train. (miss)", "missed", "Must have + третья форма — уверенный вывод о прошлом."),
            xf("Сделайте cleft-предложение: John broke the vase.", "It was John who broke the vase.", "It was + фокус + who/that выделяет деятеля."),
            err("Исправьте: Hardly I had sat down when the phone rang.", "Hardly had I sat down when the phone rang.", "После hardly нужна инверсия: had + подлежащее."),
            mc("___ the delay, we arrived on time.", ["Although", "Despite", "Whereas"], "Despite", "Despite стоит перед существительным; although требует придаточного."),
            fill("I wish you ___ make so much noise. (would)", "would", "Wish + would выражает раздражение и желание, чтобы поведение изменилось."),
            xf('Передайте вопрос: "Where do you live?" he asked me.', "He asked me where I lived.", "В косвенном вопросе порядок прямой, время сдвигается.", ["He asked me where I lived."]),
            err("Исправьте: If I would have known, I would have helped.", "If I had known, I would have helped.", "В if-части третьего типа — Past Perfect, не would have."),
        ],
    ),
    _exam(
        "C1",
        "Экзамен C1",
        "Инверсия, сослагательное наклонение, cleft и fronting, it's time / would rather, сложный пассив.",
        [
            mc("Not only ___ late, he also forgot the files.", ["he was", "was he", "he is"], "was he", "После Not only нужна инверсия: вспомогательный глагол + подлежащее."),
            fill("It's time we ___ home. (go)", "went", "It's time + подлежащее + Past Simple выражает, что действие давно пора совершить."),
            xf(
                "Сделайте инверсию: She had no sooner left than it started to rain.",
                "No sooner had she left than it started to rain.",
                "No sooner выносится, had встаёт перед подлежащим; than сохраняется.",
            ),
            err(
                "Исправьте: I demand that he leaves immediately.",
                "I demand that he leave immediately.",
                "После demand в формальном стиле — сослагательное leave без -s.",
                ["I demand that he should leave immediately"],
            ),
            mc("He is said ___ a fortune.", ["to have made", "having made", "that made"], "to have made", "Сложный пассив: is said + perfect infinitive о прошлом."),
            fill("I'd rather you ___ that. (not do)", "didn't do", "Would rather + другое лицо + Past Simple о настоящем или будущем.", ["did not do"]),
            xf("Выделите через What: I need a quiet room.", "What I need is a quiet room.", "Псевдоклефт What … is ставит нужный элемент в фокус."),
            err("Исправьте: Little he knows about the risks.", "Little does he know about the risks.", "После Little в начале предложения нужна инверсия с does."),
            mc("Unlikely ___ it may seem, the plan worked.", ["as", "like", "than"], "as", "Конструкция adjective + as + clause — уступительный оборот."),
            fill("Having ___ the report, she left. (finish)", "finished", "Perfect participle Having + третья форма показывает предшествование."),
            xf("Добавьте эмфазу do: I told you.", "I did tell you.", "Did + базовая форма усиливает утверждение в прошедшем."),
            err("Исправьте: Were he to ask I will agree.", "Were he to ask, I would agree.", "Инвертированное условие Were he to требует would, не will."),
            mc("The committee insisted that she ___ present.", ["be", "is", "was"], "be", "После insist that в формальном регистре — сослагательное be."),
            fill("Scarcely had we sat down ___ the fire alarm went off.", "when", "Scarcely/hardly … when — парная конструкция."),
            xf("Сократите относительное: The man who is sitting there is my boss.", "The man sitting there is my boss.", "Причастие настоящего заменяет who is + -ing."),
            err("Исправьте: I would rather to stay.", "I would rather stay.", "После would rather инфинитив без to."),
        ],
    ),
    _exam(
        "C2",
        "Экзамен C2",
        "Уступительные обороты, инвертированные условные, эллипсис и риторический порядок слов.",
        [
            mc("Much ___ I admire her, I cannot agree.", ["as", "like", "than"], "as", "Much as вводит уступку: «как бы сильно ни»."),
            fill("Had I ___ the truth, I would have acted sooner. (know)", "known", "Инвертированное условие Had I + третья форма = If I had known."),
            xf(
                "Инвертируйте условие: If she had been told, she would have refused.",
                "Had she been told, she would have refused.",
                "If опускается, had выходит на первое место.",
            ),
            err(
                "Исправьте: So convincing the argument was that nobody objected.",
                "So convincing was the argument that nobody objected.",
                "После So + прилагательное нужна инверсия was + подлежащее.",
            ),
            mc("He might well have ___ the email.", ["overlook", "overlooked", "overlooking"], "overlooked", "Might well have + третья форма — высокая вероятность прошлого."),
            fill("No sooner had the doors opened ___ the crowd rushed in.", "than", "Парная конструкция: no sooner … than."),
            xf(
                "Сделайте уступку с as: Although he is talented, he is modest.",
                "Talented as he is, he is modest.",
                "Прилагательное выносится: Talented as he is…",
                ["Talented as he is, he is modest."],
            ),
            err("Исправьте: Be that as it may be, we must proceed.", "Be that as it may, we must proceed.", "Устойчивое Be that as it may — без второго be."),
            mc("I'd just as soon you ___ here.", ["don't smoke", "didn't smoke", "not smoke"], "didn't smoke", "Would just as soon + другое лицо берёт Past Simple, как would rather."),
            fill("Far from ___ the problem, the new rule made it worse. (solve)", "solving", "Far from + герундий: «отнюдь не решив»."),
            xf("Сделайте псевдоклефт: She wants honesty.", "What she wants is honesty.", "What + клауза + is выделяет объект желания."),
            err(
                "Исправьте: Not until did he apologize I forgave him.",
                "Not until he apologized did I forgive him.",
                "Not until + клауза, затем инверсия в главной: did I forgive.",
            ),
            mc("Were it not ___ your help, we would have failed.", ["for", "to", "of"], "for", "Were it not for = If it were not for."),
            fill("I would sooner ___ than lie. (leave)", "leave", "Would sooner + голый инфинитив: предпочтение."),
            xf(
                "Инвертируйте: If it were not for the rain, we would go.",
                "Were it not for the rain, we would go.",
                "Were it not for заменяет If it were not for.",
            ),
            err("Исправьте: Rarely we see such precision.", "Rarely do we see such precision.", "После Rarely в начале нужна инверсия с do."),
        ],
    ),
]
