from app.seed.helpers import err, fill, mc, xf

EXTRA_EXAMS = {
    "A1": [
        mc("Выберите форму to be: They ___ students.", ["am", "is", "are"], "are", "They сочетается с are."),
        fill("Вставьте форму to be в вопросе: ___ she at home?", "Is", "Вопрос с to be: Is she…"),
        xf("Отрицание: We are ready.", "We aren't ready.", "are + not.", ["We are not ready"]),
        err("I have got hungry.", "I am hungry.", "Состояние — to be, не have got."),
        mc("Выберите артикль: I bought ___ university guidebook.", ["a", "an", "the"], "a", "University начинается с /j/."),
        fill("Вставьте is/are: There ___ some milk.", "is", "Milk неисчисляемое."),
        xf("Вопрос: She can swim.", "Can she swim?", "Can на первое место."),
        err("He going to call.", "He is going to call.", "Нужен is."),
        mc("Выберите предлог времени: See you ___ Friday.", ["in", "on", "at"], "on", "День недели — on."),
        fill("Вставьте Past Simple: Yesterday they ___ football. (play)", "played", "Past Simple правильного глагола."),
    ],
    "A2": [
        mc("Выберите время (Present Continuous): Look! She ___ a yellow coat today.", ["wears", "is wearing", "wore"], "is wearing", "Ситуация сегодня — Continuous."),
        fill("Вставьте have/has (Present Perfect): I ___ already finished.", "have", "Present Perfect."),
        xf("Сравнительная: My car is (fast) than yours.", "My car is faster than yours.", "-er для short adj."),
        err("There is many people.", "There are many people.", "People — множественное."),
        mc("Выберите модальную конструкцию обязанности: You ___ to wear a helmet here.", ["should", "have", "must to"], "have", "have to = обязанность извне."),
        fill("Вставьте Present Simple (Zero Conditional): If you heat ice, it ___. (melt)", "melts", "Zero conditional."),
        xf("Пассив: They make these cars in Japan.", "These cars are made in Japan.", "Present passive."),
        err("I used to playing tennis.", "I used to play tennis.", "used to + V1."),
        mc("Выберите превосходную степень: This is the ___ film I have ever seen.", ["better", "best", "most good"], "best", "Превосходная степень."),
        fill("Вставьте enough: She isn't old ___ to drive.", "enough", "enough после прилагательного."),
    ],
    "B1": [
        mc("Выберите время (результат сейчас): I ___ my keys. I can't find them.", ["lost", "have lost", "was losing"], "have lost", "Результат в настоящем — Present Perfect."),
        fill("Вставьте Past Continuous: They ___ dinner when we arrived. (have)", "were having", "Past Continuous, прерванное действие."),
        xf("Косвенная речь: «Do you like tea?» she asked.", "She asked if I liked tea.", "Yes/no вопрос → if + сдвиг времени.", ["She asked whether I liked tea"]),
        err("If I will see him, I will tell him.", "If I see him, I will tell him.", "В if first conditional — Present Simple."),
        mc("Выберите Past Passive: The windows ___ yesterday.", ["cleaned", "were cleaned", "are clean"], "were cleaned", "Past passive."),
        fill("Вставьте for или since: I've been waiting ___ an hour.", "for", "for + период."),
        xf("Составьте Second Conditional из двух фактов: I don't have money. I don't buy it.", "If I had money, I would buy it.", "If + past, would + V."),
        err("The man which called you is here.", "The man who called you is here.", "Человек — who."),
        mc("Выберите форму после suggested: She suggested ___ a taxi.", ["to take", "taking", "take"], "taking", "suggest + герундий."),
        fill("Вставьте относительное местоимение: He's the doctor ___ helped us.", "who", "who о человеке.", ["that"]),
    ],
    "B2": [
        mc("Выберите форму в каузативе have something done: I'm having my hair ___ tomorrow.", ["cutting", "cut", "to cut"], "cut", "have something done."),
        fill("Вставьте третью форму после can't have: She can't have ___ the news. (hear)", "heard", "can't have + V3 — вывод."),
        xf("Составьте Mixed Conditional (past → present): I didn't study. I don't have a job now.", "If I had studied, I would have a job now.", "Past condition, present result."),
        err("I look forward to meet you.", "I look forward to meeting you.", "to здесь предлог + герундий."),
        mc("Выберите инверсию после Not until: Not until midnight ___ the truth.", ["he realised", "did he realise", "he did realise"], "did he realise", "Инверсия после Not until."),
        fill("Вставьте Past Simple после I'd rather you: I'd rather you ___ here. (stay)", "stayed", "would rather + past о другом лице."),
        xf("Перепишите как it-cleft (It was … who …): Mary sent the email.", "It was Mary who sent the email.", "It was + focus + who."),
        err("Despite he was tired, he continued.", "Although he was tired, he continued.", "despite + noun; although + clause.", ["Despite being tired, he continued"]),
        mc("Выберите Past Perfect: By the time we arrived, the film ___.", ["started", "had started", "has started"], "had started", "Earlier past — Past Perfect."),
        fill("Вставьте to-infinitive после is thought: She is thought ___ abroad. (live)", "to live", "is thought + to-infinitive."),
    ],
    "C1": [
        mc("Выберите форму после Should you need help: Should you need help, ___ me.", ["call", "you call", "calling"], "call", "Should you = if you."),
        fill("Вставьте subjunctive после essential that: It is essential that he ___ on time. (arrive)", "arrive", "Mandative subjunctive.", ["should arrive"]),
        xf("Перепишите с фронтированием Never … (инверсия): I have never felt so cold.", "Never have I felt so cold.", "Never + inversion."),
        err("I suggested that she goes alone.", "I suggested that she go alone.", "suggest that + subjunctive.", ["I suggested that she should go alone"]),
        mc("Выберите инверсию после Only then: Only then ___ how serious it was.", ["I understood", "did I understand", "I did understand"], "did I understand", "Only then + inversion."),
        fill("Вставьте to в Were she to…: Were she ___ apply, she would get it.", "to", "Were she to apply."),
        xf("Сократите relative clause (Students taught …): Students who are taught well succeed.", "Students taught well succeed.", "Passive participle."),
        err("It's high time we go.", "It's high time we went.", "It's time + past."),
        mc("Выберите perfect infinitive после appear: The results appear ___ leaked.", ["to have been", "having", "to be have"], "to have been", "Perfect passive infinitive."),
        fill("Вставьте глагол: Much as I ___ him, I disagree. (like)", "like", "Much as + clause."),
    ],
    "C2": [
        mc("Выберите may в идиоме: Come what ___, we finish tonight.", ["can", "may", "might be"], "may", "Come what may = что бы ни случилось."),
        fill("Вставьте to: Suffice it ___ say the plan failed.", "to", "Suffice it to say."),
        xf("Перепишите с инверсией So … that: The speech was so dull that people left.", "So dull was the speech that people left.", "So + adj + inversion."),
        err("If I was to be honest, I would refuse. (formal)", "Were I to be honest, I would refuse.", "Formal inverted conditional."),
        mc("Выберите as в not so much … as: He is not so much a teacher ___ a performer.", ["than", "as", "but"], "as", "not so much … as."),
        fill("Вставьте may: Be that as it ___, we continue.", "may", "Be that as it may."),
        xf("Дополните эллипсис в ответе B (And so can / And … too): A: She can dance. B: And sing too.", "And she can sing too.", "Restore the elided clause.", ["And sing too"]),
        err("Hardly I opened the door when it slammed.", "Hardly had I opened the door when it slammed.", "Hardly + inversion + when."),
        mc("Выберите the more в the…, the…: The more he explained, ___ confused I became.", ["the more", "more", "the most"], "the more", "the …, the …"),
        fill("Вставьте been: Had it not ___ for her, we would have quit. (be)", "been", "Had it not been for."),
    ],
}
