"""Extra practice/test banks keyed by module slug + generic CEFR pads.

Practice and test banks are intentionally separate: expanders never copy practice into tests.
"""

from app.seed.helpers import err, fill, match, mc, order, xf

# --- Per-module extras (high-traffic A1 topics) ---

EXTRA_PRACTICE: dict[str, list] = {
    "articles-a1": [
        fill("I bought ___ umbrella.", "an", "Umbrella — гласный звук."),
        fill("___ Earth goes round the sun.", "The", "Уникальный объект."),
        mc("She wants ___ orange.", ["a", "an", "the"], "an", "Orange — гласный звук."),
        err("He is a honest man.", "He is an honest man.", "Honest начинается с гласного звука."),
        fill("Open ___ window, please. (конкретное)", "the", "Оба видят окно.", ["Open the window", "Open the window."]),
        mc("I don't drink ___ coffee.", ["a", "an", "— (нулевой)"], "— (нулевой)", "Неисчисляемое в общем смысле."),
        order("Соберите: door / the / close", "Close the door.", "Повелительное + the."),
        fill("She is ___ teacher.", "a", "Профессия в ед.ч. — a/an."),
        xf("Вставьте: ___ Alps are high.", "The Alps are high.", "Горные цепи — the."),
        match("Соотнесите: a / an / the", ["a book", "an hour", "the moon"], "a book=a; an hour=an; the moon=the", "Звук и уникальность."),
        fill("Pass me ___ pen on the desk.", "the", "Конкретная ручка."),
        err("I saw a interesting film.", "I saw an interesting film.", "Interesting — гласный звук."),
        fill("___ water is cold. (эта, в стакане)", "The", "Конкретная порция."),
        mc("___ cats like fish. (вообще)", ["The", "A", "— (нулевой)"], "— (нулевой)", "Класс в общем."),
        fill("Close ___ door.", "the", "Конкретная дверь.", ["Close the door", "Close the door."]),
    ],
    "nouns-plurals": [
        fill("one knife — two ___", "knives", "f/fe → ves."),
        mc("mouse →", ["mouses", "mice", "mouse"], "mice", "Особая форма."),
        err("three childs", "three children", "children."),
        order("Слова: are / children / happy / the", "The children are happy.", "The + N + be + adj."),
        fill("one leaf — many ___", "leaves", "f → ves."),
        mc("This ___ is mine.", ["books", "book", "bookes"], "book", "Ед.ч. this + N."),
        xf("one person → ?", "people", "Особая форма."),
        fill("two ___ of bread", "loaves", "loaf → loaves."),
        err("five deers", "five deer", "deer не меняется."),
        fill("a story — three ___", "stories", "y → ies."),
    ],
    "past-simple-verbs": [
        fill("She ___ home early. (go)", "went", "go — went — gone."),
        mc("They ___ the window. (break, past)", ["breaked", "broke", "broken"], "broke", "V2."),
        err("He buyed a ticket.", "He bought a ticket.", "buy — bought."),
        fill("I ___ the email yesterday. (write)", "wrote", "write — wrote — written."),
        order("Соберите: did / you / see / her", "Did you see her?", "Did + V1."),
        xf("make → past", "made", "make — made — made."),
        fill("We ___ lunch at 2. (have)", "had", "have — had — had."),
        mc("She ___ the keys. (find, past)", ["finded", "found", "founded"], "found", "find — found."),
        fill("He ___ to Paris last year. (fly)", "flew", "fly — flew — flown."),
        err("They taked the bus.", "They took the bus.", "take — took."),
    ],
    "word-order-a1": [
        order("Соберите: she / tea / drinks / often", "She often drinks tea.", "Подлежащее + частота + V."),
        fill("They ___ in London. (live)", "live", "S + V + place."),
        mc("Правильный порядок:", ["Likes she coffee?", "Does she like coffee?", "She does like coffee?"], "Does she like coffee?", "Do/Does + S + V1."),
        err("I every day go there.", "I go there every day.", "Частота в конце или перед V."),
        order("Слова: is / the / on / book / table / the", "The book is on the table.", "S + be + prep + place."),
        fill("___ you speak English?", "Do", "Do + you + V1."),
        xf("Переставьте: rarely / he / smiles", "He rarely smiles.", "Наречие частоты перед смысловым V."),
        match("Части предложения", ["She", "reads", "books"], "She=S; reads=V; books=O", "SVO."),
    ],
}

EXTRA_TEST: dict[str, list] = {
    "articles-a1": [
        fill("Please shut ___ gate. (одно на участке)", "the", "Конкретный объект.", ["Please shut the gate", "Please shut the gate."]),
        mc("I need ___ hour to finish.", ["a", "an", "the"], "an", "Hour — гласный звук."),
        err("She bought a apple.", "She bought an apple.", "Apple — гласный."),
        fill("___ Nile is long.", "The", "Реки — the."),
        order("Соберите: give / me / salt / the", "Give me the salt.", "Просьба + the."),
        mc("He never eats ___ meat.", ["a", "the", "— (нулевой)"], "— (нулевой)", "Общее неисчисляемое."),
        fill("She is ___ university student.", "a", "University — /j/ согласный звук."),
        xf("Любой билет: I need ___ ticket.", "I need a ticket.", "Неопределённый."),
        fill("Look at ___ sky!", "the", "Уникальный объект."),
        err("An useful tip helped me.", "A useful tip helped me.", "Useful — /j/."),
        fill("Put it on ___ shelf. (эта полка)", "the", "Конкретная полка."),
        mc("___ Japanese is difficult. (язык)", ["The", "A", "— (нулевой)"], "— (нулевой)", "Языки без артикля."),
        fill("I saw ___ owl at night.", "an", "Owl — гласный."),
        match("Выберите артикль", ["___ sun", "___ idea", "___ milk (вообще)"], "the; an; —", "Уникальность / впервые / общее."),
        order("Слова: open / door / the", "Open the door.", "Повелительное + the."),
    ],
    "nouns-plurals": [
        fill("one wolf — two ___", "wolves", "f → ves."),
        mc("tooth →", ["tooths", "teeth", "toothes"], "teeth", "Особая форма."),
        err("many informations", "much information", "information неисчисляемое."),
        fill("a potato — two ___", "potatoes", "+es после o."),
        order("Соберите: sheep / are / in / field / the", "The sheep are in the field.", "sheep без -s."),
        xf("this child → plural subject", "these children", "this→these, child→children."),
        fill("one life — several ___", "lives", "f → ves."),
        mc("The police ___ coming.", ["is", "are", "be"], "are", "Police — множественное."),
        fill("one quiz — two ___", "quizzes", "z → zzes."),
        err("three gooses", "three geese", "goose — geese."),
    ],
    "past-simple-verbs": [
        fill("They ___ the news. (hear, past)", "heard", "hear — heard — heard."),
        mc("She ___ a letter. (send, past)", ["sended", "sent", "send"], "sent", "send — sent."),
        err("I catched the ball.", "I caught the ball.", "catch — caught."),
        fill("He ___ the truth. (know, past)", "knew", "know — knew — known."),
        order("Соберите: when / did / leave / they", "When did they leave?", "Wh + did + S + V1."),
        xf("bring → past", "brought", "bring — brought."),
        fill("We ___ the museum. (see)", "saw", "see — saw — seen."),
        mc("I ___ my phone. (lose, past)", ["losed", "lost", "losen"], "lost", "lose — lost."),
        fill("She ___ carefully. (drive, past)", "drove", "drive — drove — driven."),
        err("He putted the bag down.", "He put the bag down.", "put — put — put."),
    ],
    "word-order-a1": [
        order("Соберите: usually / breakfast / I / eat / at 8", "I usually eat breakfast at 8.", "S + frequency + V + O + time."),
        fill("___ she work here?", "Does", "Does + he/she + V1."),
        mc("Выберите верное:", ["Where you live?", "Where do you live?", "Where live you?"], "Where do you live?", "Wh + do + S + V."),
        err("Speaks he French?", "Does he speak French?", "Do/Does в вопросе."),
        order("Слова: never / late / is / she", "She is never late.", "be + частота."),
        fill("They live ___ Moscow.", "in", "in + city."),
        xf("Переставьте: tomorrow / we / leave", "We leave tomorrow.", "Время обычно в конце."),
        match("Роли", ["Do", "you", "swim"], "Do=aux; you=S; swim=V", "Вопрос Present Simple."),
    ],
}

# Generic pads used when a module still has a thin bank (keyed by CEFR code).
GENERIC_PRACTICE_PAD: dict[str, list] = {
    "A1": [
        mc("I ___ a student.", ["am", "is", "are"], "am", "I + am."),
        fill("She ___ my sister. (be)", "is", "She + is."),
        err("He don't like tea.", "He doesn't like tea.", "He/she + doesn't."),
        order("Соберите: name / is / my / Anna", "My name is Anna.", "Притяжательное + N + be."),
        fill("They ___ from Spain. (be)", "are", "They + are."),
        mc("___ you ready?", ["Is", "Are", "Am"], "Are", "You + are."),
        xf("Сделайте вопрос: You speak English.", "Do you speak English?", "Do + S + V1."),
        fill("There ___ a book on the table.", "is", "There is + ед.ч."),
        err("She can sings.", "She can sing.", "После can — V1."),
        match("Местоимения", ["I", "he", "they"], "I=я; he=он; they=они", "Базовые forms."),
        fill("We ___ breakfast at 8. (have)", "have", "We + have."),
        order("Слова: the / park / in / play / children", "Children play in the park.", "S + V + place."),
        mc("This is ___ bag.", ["me", "my", "mine"], "my", "my + N."),
        fill("___ is cold today.", "It", "Погода — It."),
        err("I am agree.", "I agree.", "Agree без am."),
    ],
    "A2": [
        mc("She ___ TV when I called.", ["watched", "was watching", "watches"], "was watching", "Past Continuous фон."),
        fill("I ___ already finished. (have)", "have", "Present Perfect."),
        err("He go to school every day.", "He goes to school every day.", "3sg -s."),
        order("Соберите: than / bigger / is / this / that", "This is bigger than that.", "Сравнение."),
        fill("If it rains, we ___ stay home. (will)", "will", "First conditional."),
        mc("There isn't ___ milk.", ["some", "any", "many"], "any", "Отрицание + any."),
        xf("Сделайте отрицание: She can drive.", "She can't drive.", "can't + V1.", ["She cannot drive."]),
        fill("He used ___ live here.", "to", "used to + V1."),
        err("She is knowing the answer.", "She knows the answer.", "Know — Simple."),
        match("Сравните", ["good", "better", "best"], "good=base; better=comp; best=super", "Неправильные формы."),
    ],
    "B1": [
        mc("I wish I ___ taller.", ["am", "was", "were"], "were", "Wish + were."),
        fill("By 2019 they ___ left. (have)", "had", "Past Perfect."),
        err("If I will see him, I will call.", "If I see him, I will call.", "If + Present."),
        order("Соберите: been / have / waiting / I / for hours", "I have been waiting for hours.", "Perfect Continuous."),
        fill("You ___ be tired after that trip. (must)", "must", "Сильный вывод."),
        mc("She asked where I ___.", ["live", "lived", "lives"], "lived", "Sequence of tenses."),
        xf("Passive: They built the bridge.", "The bridge was built.", "Past Passive."),
        fill("I'd rather you ___ now. (leave)", "left", "Would rather + Past."),
        err("He suggested to go.", "He suggested going.", "Suggest + -ing."),
        match("Wish", ["I wish", "I knew", "the code"], "I wish=frame; I knew=Past; the code=object", "Wish + Past."),
    ],
    "B2": [
        mc("Not only ___ late, he forgot the key.", ["he was", "was he", "he is"], "was he", "Инверсия после Not only."),
        fill("I'd sooner ___ at home. (stay)", "stay", "Would sooner + V1."),
        err("Despite of the rain, we went.", "Despite the rain, we went.", "Despite без of."),
        order("Соберите: had / I / known / I / would have called", "Had I known, I would have called.", "Инверсия условия."),
        fill("She is thought ___ be abroad. (to)", "to", "Passive reporting."),
        mc("It's time we ___.", ["go", "went", "going"], "went", "It's time + Past."),
        xf("Causative: Someone cleaned my car.", "I had my car cleaned.", "Have + object + V3."),
        fill("Little ___ she know the truth. (do, past)", "did", "Little did + S."),
        err("I look forward to meet you.", "I look forward to meeting you.", "to + -ing."),
        match("Инверсия", ["Seldom", "do", "we meet"], "Seldom=front; do=aux; we meet=clause", "Negative adverb + inversion."),
    ],
    "C1": [
        mc("Were it not ___ the delay, we would start.", ["for", "to", "that"], "for", "Were it not for."),
        fill("It is essential that he ___ on time. (be)", "be", "Subjunctive."),
        err("I regret to tell you this earlier.", "I regret telling you this earlier.", "Regret + -ing о прошлом."),
        order("Соберите: so / complex / was / the / plan / that / we / paused", "So complex was the plan that we paused.", "So + adj + be + S."),
        fill("Far ___ it from me to insist. (be)", "be", "Far be it."),
        mc("On no account ___ you open that.", ["should", "you should", "should not"], "should", "On no account + should."),
        xf("Nominalise: They refused → their ___", "refusal", "refuse → refusal."),
        fill("Such ___ the noise that we left. (be)", "was", "Such was + N."),
        err("She explained me the rule.", "She explained the rule to me.", "Explain sth to sb."),
        match("Fronting", ["Into the bay", "sailed", "the yacht"], "Into the bay=front; sailed=V; the yacht=S", "Полная инверсия."),
    ],
    "C2": [
        mc("___ that as it may, we proceed.", ["Be", "Is", "Were"], "Be", "Be that as it may."),
        fill("Suffice ___ to say we disagreed.", "it", "Suffice it to say."),
        err("The data is conflicting each other.", "The data are conflicting with each other.", "Data + are; with."),
        order("Соберите: hard / as / tried / she / she / failed", "Hard as she tried, she failed.", "Adj + as + S + V."),
        fill("Come what ___, we finish tonight.", "may", "Come what may."),
        mc("He is as brilliant a writer ___ she is.", ["than", "as", "like"], "as", "as…as."),
        xf("Inversion: If she had known → ___ she known", "Had", "Had + S + V3."),
        fill("Strange ___ it seem, it worked. (as)", "as", "Adj + as + S + V."),
        err("I can't help to laugh.", "I can't help laughing.", "Can't help + -ing."),
        match("Hedges", ["It would appear", "that", "the claim holds"], "It would appear=hedge; that=linker; the claim holds=clause", "Дистанцирование."),
    ],
}

GENERIC_TEST_PAD: dict[str, list] = {
    "A1": [
        fill("___ name is Tom. (he)", "His", "His + N."),
        mc("There ___ two chairs.", ["is", "are", "be"], "are", "There are + мн."),
        err("She haven't a car.", "She hasn't a car.", "She + hasn't.", ["She doesn't have a car."]),
        order("Соберите: like / I / apples", "I like apples.", "S + V + O."),
        fill("Can you ___ me? (help)", "help", "can + V1."),
        mc("___ is your phone?", ["Who", "Where", "What"], "Where", "Место."),
        xf("Отрицание: I can swim.", "I can't swim.", "can't.", ["I cannot swim."]),
        fill("The keys are ___ the table.", "on", "on + surface."),
        err("He living in Rome.", "He lives in Rome.", "Present Simple."),
        match("Be", ["I", "she", "we"], "I=am; she=is; we=are", "Согласование be."),
        fill("___ you got a pen?", "Have", "Have you got…?"),
        order("Слова: bus / the / takes / she", "She takes the bus.", "S + V + O."),
        mc("These ___ my books.", ["is", "are", "am"], "are", "These + are."),
        fill("Please ___ the door. (close)", "close", "Imperative."),
        err("I no understand.", "I don't understand.", "don't + V1."),
    ],
    "A2": [
        fill("She ___ just left. (have)", "has", "has just + V3."),
        mc("While I ___, the phone rang.", ["cooked", "was cooking", "cook"], "was cooking", "Interrupted action."),
        err("I am going to the gym every Monday.", "I go to the gym every Monday.", "Привычка — Simple."),
        order("Соберите: will / if / you / ask / I / help", "If you ask, I will help.", "First conditional."),
        fill("This bag is ___ than that one. (light)", "lighter", "сравнительная степень."),
        mc("How ___ sugar do you need?", ["many", "much", "few"], "much", "Неисчисляемое."),
        xf("Passive: They clean the room.", "The room is cleaned.", "Present Passive."),
        fill("You ___ park here. (mustn't)", "mustn't", "Запрет.", ["must not"]),
        err("She didn't went.", "She didn't go.", "Didn't + V1."),
        match("Quantifiers", ["much", "many", "a few"], "much=uncount; many=count; a few=count+", "Исчисляемость."),
    ],
    "B1": [
        fill("She said she ___ tired. (be, past)", "was", "Sequence of tenses."),
        mc("If I ___ rich, I would travel.", ["am", "was", "were"], "were", "2nd conditional."),
        err("He has went home.", "He has gone home.", "have + V3."),
        order("Соберите: been / she / has / working / all day", "She has been working all day.", "Perfect Continuous."),
        fill("The letter ___ sent yesterday. (be)", "was", "Past Passive."),
        mc("I wish it ___ raining.", ["isn't", "wasn't", "weren't"], "weren't", "Wish + weren't.", ["wasn't"]),
        xf("'I am busy' → He said he ___ busy.", "was", "am → was."),
        fill("You look tired. You ___ have slept badly. (must)", "must", "must have + V3."),
        err("She avoid to talk.", "She avoids talking.", "avoid + -ing."),
        match("Relative", ["who", "which", "where"], "who=people; which=things; where=place", "Defining clauses."),
    ],
    "B2": [
        fill("No sooner ___ we arrived than it rained. (have)", "had", "No sooner had + S."),
        mc("I'd prefer ___ alone.", ["stay", "to stay", "staying"], "to stay", "Prefer + to."),
        err("He is used to wake up early.", "He is used to waking up early.", "be used to + -ing."),
        order("Соберите: should / under / no / circumstances / you / lie", "Under no circumstances should you lie.", "Инверсия."),
        fill("She had the report ___ . (write, causative)", "written", "have + O + V3."),
        mc("It's high time you ___.", ["leave", "left", "leaving"], "left", "High time + Past."),
        xf("Reporting: 'Don't go' → He told me ___ go.", "not to", "tell + not to."),
        fill("Hardly ___ the film started when the lights failed. (have)", "had", "Hardly had + S."),
        err("I suggested her to wait.", "I suggested that she wait.", "Suggest + that + subjunctive.", ["I suggested waiting."]),
        match("Causative", ["have", "my hair", "cut"], "have=caus; my hair=O; cut=V3", "Have sth done."),
    ],
    "C1": [
        fill("Be that as it ___, we continue.", "may", "Be that as it may."),
        mc("___ the cost, the project went ahead.", ["However", "Whatever", "Whichever"], "Whatever", "Whatever + N."),
        err("I demand that he leaves now.", "I demand that he leave now.", "Subjunctive leave."),
        order("Соберите: known / had / we / we / would have waited", "Had we known, we would have waited.", "Third conditional inversion."),
        fill("It was suggested that the plan ___ revised. (be)", "be", "Mandative subjunctive."),
        mc("Only then ___ the mistake.", ["I realised", "did I realise", "I did realise"], "did I realise", "Only then + inversion."),
        xf("Noun: decide → ___", "decision", "decide → decision."),
        fill("Such ___ his anger that he left. (be)", "was", "Such was."),
        err("She congratulated me to win.", "She congratulated me on winning.", "congratulate on."),
        match("Emphasis", ["What", "I need", "is rest"], "What=cleft; I need=clause; is rest=focus", "Wh-cleft."),
    ],
    "C2": [
        fill("Try as she ___, she couldn't open it.", "might", "Try as S might."),
        mc("___ it rain, the event moves indoors.", ["Should", "Would", "Might"], "Should", "Should it + V."),
        err("The committee have not yet reached its decision.", "The committee has not yet reached its decision.", "Committee + has (BrE often has for unit)."),
        order("Соберите: though / brilliant / the / idea / was / it / failed", "Brilliant though the idea was, it failed.", "Adj + though + S + be."),
        fill("Suffice ___ to say the talks stalled.", "it", "Suffice it to say."),
        mc("He spoke as if he ___ the owner.", ["is", "were", "was"], "were", "as if + were."),
        xf("Front: The yacht sailed into the bay. → Into the bay ___ the yacht.", "sailed", "Full inversion."),
        fill("Come what ___, keep the channel open.", "may", "Come what may."),
        err("I resent to be ignored.", "I resent being ignored.", "resent + -ing."),
        match("Concession", ["Much as", "I admire", "her work"], "Much as=front; I admire=clause; her work=O", "Much as + clause."),
    ],
}
