from app.seed.vocab import _topic, _w

EXTRA_WORDS_BY_SLUG = {
    "everyday-objects": [
        _w("sofa", "/ˈsəʊ.fə/", "диван", "noun", "The cat sleeps on the sofa.", "Кот спит на диване."),
        _w("fridge", "/frɪdʒ/", "холодильник", "noun", "Put the milk back in the fridge.", "Поставь молоко обратно в холодильник."),
        _w("spoon", "/spuːn/", "ложка", "noun", "I need a clean spoon for the soup.", "Мне нужна чистая ложка для супа."),
        _w("fork", "/fɔːk/", "вилка", "noun", "Use a fork, not your fingers.", "Возьми вилку, а не пальцы."),
        _w("glass", "/ɡlɑːs/", "стакан; стекло", "noun", "She poured juice into a tall glass.", "Она налила сок в высокий стакан."),
        _w("blanket", "/ˈblæŋ.kɪt/", "одеяло", "noun", "I pulled the blanket over my feet.", "Я натянул одеяло на ноги."),
        _w("curtain", "/ˈkɜː.tən/", "штора", "noun", "Open the curtain and let the light in.", "Открой штору и впусти свет."),
        _w("soap", "/səʊp/", "мыло", "noun", "The soap near the sink smells of lemon.", "Мыло у раковины пахнет лимоном."),
        _w("wallet", "/ˈwɒl.ɪt/", "кошелёк", "noun", "His wallet was still in the jacket.", "Кошелёк всё ещё был в куртке."),
        _w("notebook", "/ˈnəʊt.bʊk/", "тетрадь", "noun", "Write the new words in your notebook.", "Запиши новые слова в тетрадь."),
        _w("shelf", "/ʃelf/", "полка", "noun", "The photos stand on the top shelf.", "Фотографии стоят на верхней полке."),
        _w("drawer", "/drɔː/", "ящик", "noun", "The spare batteries are in the drawer.", "Запасные батарейки лежат в ящике."),
    ],
    "family-people": [
        _w("child", "/tʃaɪld/", "ребёнок", "noun", "Each child brought a small gift.", "Каждый ребёнок принёс маленький подарок."),
        _w("teenager", "/ˈtiːnˌeɪ.dʒə/", "подросток", "noun", "The teenager walks to school alone.", "Подросток ходит в школу один."),
        _w("adult", "/ˈæd.ʌlt/", "взрослый", "noun", "An adult must sign the form.", "Взрослый должен подписать бланк."),
        _w("guest", "/ɡest/", "гость", "noun", "We have a guest for dinner tonight.", "Сегодня вечером у нас гость на ужин."),
        _w("classmate", "/ˈklɑːs.meɪt/", "одноклассник", "noun", "My classmate lives on the next street.", "Мой одноклассник живёт на соседней улице."),
        _w("partner", "/ˈpɑːt.nə/", "партнёр", "noun", "Her partner cooked breakfast today.", "Её партнёр сегодня приготовил завтрак."),
        _w("relative", "/ˈrel.ə.tɪv/", "родственник", "noun", "A distant relative wrote from Canada.", "Дальний родственник написал из Канады."),
        _w("nephew", "/ˈnef.juː/", "племянник", "noun", "My nephew starts piano lessons soon.", "Мой племянник скоро начнёт уроки фортепиано."),
        _w("niece", "/niːs/", "племянница", "noun", "His niece drew a picture of the house.", "Его племянница нарисовала дом."),
        _w("roommate", "/ˈruːm.meɪt/", "сосед по комнате", "noun", "My roommate washes the dishes on Mondays.", "Сосед по комнате моет посуду по понедельникам."),
        _w("twin", "/twɪn/", "близнец", "noun", "Her twin brother has the same laugh.", "У её брата-близнеца такой же смех."),
        _w("host", "/həʊst/", "хозяин, принимающий гостей", "noun", "The host showed us the spare room.", "Хозяин показал нам свободную комнату."),
    ],
    "food-drink": [
        _w("fish", "/fɪʃ/", "рыба", "noun", "We grilled fish by the river.", "Мы пожарили рыбу у реки."),
        _w("meat", "/miːt/", "мясо", "noun", "She cooks meat with herbs and garlic.", "Она готовит мясо с травами и чесноком."),
        _w("pasta", "/ˈpæs.tə/", "паста", "noun", "The pasta needs two more minutes.", "Пасте нужно ещё две минуты."),
        _w("cake", "/keɪk/", "торт, пирог", "noun", "They shared a small chocolate cake.", "Они разделили маленький шоколадный торт."),
        _w("honey", "/ˈhʌn.i/", "мёд", "noun", "I stir honey into warm tea.", "Я размешиваю мёд в тёплом чае."),
        _w("salt", "/sɔːlt/", "соль", "noun", "Add a pinch of salt at the end.", "Добавь щепотку соли в конце."),
        _w("pepper", "/ˈpep.ə/", "перец", "noun", "Black pepper changes the taste a lot.", "Чёрный перец сильно меняет вкус."),
        _w("onion", "/ˈʌn.jən/", "лук", "noun", "Chop one onion for the stew.", "Нарежь одну луковицу для рагу."),
        _w("carrot", "/ˈkær.ət/", "морковь", "noun", "The soup has carrot and celery.", "В супе есть морковь и сельдерей."),
        _w("sandwich", "/ˈsæn.wɪdʒ/", "бутерброд", "noun", "I packed a cheese sandwich for the train.", "Я взял в поезд бутерброд с сыром."),
        _w("breakfast", "/ˈbrek.fəst/", "завтрак", "noun", "Breakfast is ready on the balcony.", "Завтрак готов на балконе."),
        _w("snack", "/snæk/", "перекус", "noun", "An apple is a better snack than crisps.", "Яблоко — лучший перекус, чем чипсы."),
    ],
    "travel-city": [
        _w("bus", "/bʌs/", "автобус", "noun", "The last bus leaves at eleven.", "Последний автобус уходит в одиннадцать."),
        _w("taxi", "/ˈtæk.si/", "такси", "noun", "We took a taxi from the station.", "Мы взяли такси от вокзала."),
        _w("bridge", "/brɪdʒ/", "мост", "noun", "The old bridge is closed to cars.", "Старый мост закрыт для машин."),
        _w("museum", "/mjuːˈziː.əm/", "музей", "noun", "The museum opens after lunch.", "Музей открывается после обеда."),
        _w("delay", "/dɪˈleɪ/", "задержка", "noun", "The delay lasted forty minutes.", "Задержка длилась сорок минут."),
        _w("gate", "/ɡeɪt/", "выход на посадку; ворота", "noun", "Go to gate twelve after security.", "После досмотра идите к выходу двенадцать."),
        _w("souvenir", "/ˌsuː.vənˈɪə/", "сувенир", "noun", "She bought a small souvenir for her sister.", "Она купила сестре маленький сувенир."),
        _w("hostel", "/ˈhɒs.təl/", "хостел", "noun", "The hostel kitchen closes at ten.", "Кухня хостела закрывается в десять."),
        _w("tram", "/træm/", "трамвай", "noun", "Take the tram to the market square.", "До рыночной площади доберись на трамвае."),
        _w("ferry", "/ˈfer.i/", "паром", "noun", "The ferry crosses the bay twice a day.", "Паром пересекает залив дважды в день."),
        _w("suitcase", "/ˈsuːt.keɪs/", "чемодан", "noun", "His suitcase was slightly over the limit.", "Его чемодан чуть превысил норму."),
        _w("tourist", "/ˈtʊə.rɪst/", "турист", "noun", "A tourist asked for the nearest bakery.", "Турист спросил, где ближайшая пекарня."),
    ],
    "work-study": [
        _w("shift", "/ʃɪft/", "смена", "noun", "Her evening shift ends at midnight.", "Её вечерняя смена заканчивается в полночь."),
        _w("contract", "/ˈkɒn.trækt/", "договор", "noun", "Read the contract before you sign it.", "Прочитай договор, прежде чем подписывать."),
        _w("grade", "/ɡreɪd/", "оценка", "noun", "He improved his grade after the rewrite.", "Он повысил оценку после переписывания."),
        _w("exam", "/ɪɡˈzæm/", "экзамен", "noun", "The exam has two written parts.", "У экзамена две письменные части."),
        _w("project", "/ˈprɒdʒ.ekt/", "проект", "noun", "Our project needs one more interview.", "Нашему проекту нужно ещё одно интервью."),
        _w("client", "/ˈklaɪ.ənt/", "клиент", "noun", "The client asked for a shorter report.", "Клиент попросил более короткий отчёт."),
        _w("tutor", "/ˈtjuː.tə/", "репетитор", "noun", "A tutor helped her with listening.", "Репетитор помог ей со аудированием."),
        _w("workshop", "/ˈwɜːk.ʃɒp/", "мастер-класс, семинар", "noun", "The workshop lasts three hours.", "Мастер-класс длится три часа."),
        _w("remote", "/rɪˈməʊt/", "удалённый", "adjective", "He works remote on Tuesdays.", "По вторникам он работает удалённо."),
        _w("inbox", "/ˈɪn.bɒks/", "входящие", "noun", "Clear your inbox before the meeting.", "Очисти входящие перед совещанием."),
        _w("essay", "/ˈes.eɪ/", "эссе", "noun", "The essay should be one page long.", "Эссе должно быть на одну страницу."),
        _w("promotion", "/prəˈməʊ.ʃən/", "повышение", "noun", "She got a promotion after the audit.", "Её повысили после проверки."),
    ],
    "health-body": [
        _w("knee", "/niː/", "колено", "noun", "He iced his knee after the run.", "Он приложил лёд к колену после пробежки."),
        _w("elbow", "/ˈel.bəʊ/", "локоть", "noun", "Don't lean on your elbow at the table.", "Не опирайся локтем на стол."),
        _w("pulse", "/pʌls/", "пульс", "noun", "The nurse checked my pulse twice.", "Медсестра дважды проверила пульс."),
        _w("diet", "/ˈdaɪ.ət/", "рацион", "noun", "A simple diet helped her energy.", "Простой рацион помог ей с энергией."),
        _w("bruise", "/bruːz/", "синяк", "noun", "A dark bruise appeared on his arm.", "На руке появился тёмный синяк."),
        _w("nurse", "/nɜːs/", "медсестра, медбрат", "noun", "The nurse explained the next steps.", "Медсестра объяснила следующие шаги."),
        _w("clinic", "/ˈklɪn.ɪk/", "клиника", "noun", "The clinic is a short walk from here.", "Клиника в нескольких минутах ходьбы."),
        _w("medicine", "/ˈmed.ɪ.sən/", "лекарство", "noun", "Take the medicine after food.", "Прими лекарство после еды."),
        _w("dentist", "/ˈden.tɪst/", "стоматолог", "noun", "The dentist asked me to bite gently.", "Стоматолог попросил слегка сомкнуть зубы."),
        _w("rest", "/rest/", "отдых", "noun", "Two days of rest reduced the pain.", "Два дня отдыха уменьшили боль."),
        _w("dizzy", "/ˈdɪz.i/", "головокружение", "adjective", "She felt dizzy after standing up fast.", "Ей стало дурно после резкого вставания."),
        _w("vaccine", "/ˈvæk.siːn/", "вакцина", "noun", "The vaccine is free at this clinic.", "В этой клинике вакцина бесплатная."),
    ],
    "feelings-personality": [
        _w("lonely", "/ˈləʊn.li/", "одинокий", "adjective", "He felt lonely in the new city.", "В новом городе он чувствовал себя одиноко."),
        _w("proud", "/praʊd/", "гордый", "adjective", "She was proud of the finished draft.", "Она гордилась готовым черновиком."),
        _w("calm", "/kɑːm/", "спокойный", "adjective", "A calm voice helped the child.", "Спокойный голос помог ребёнку."),
        _w("brave", "/breɪv/", "смелый", "adjective", "It was brave to ask for feedback.", "Было смело попросить обратную связь."),
        _w("honest", "/ˈɒn.ɪst/", "честный", "adjective", "Be honest if the task is too hard.", "Будь честен, если задача слишком сложная."),
        _w("polite", "/pəˈlaɪt/", "вежливый", "adjective", "A polite email opens more doors.", "Вежливое письмо открывает больше дверей."),
        _w("patient", "/ˈpeɪ.ʃənt/", "терпеливый", "adjective", "A patient teacher repeats the rule.", "Терпеливый учитель повторяет правило."),
        _w("curious", "/ˈkjʊə.ri.əs/", "любопытный", "adjective", "Curious students asked better questions.", "Любопытные студенты задавали лучшие вопросы."),
        _w("cheerful", "/ˈtʃɪə.fəl/", "жизнерадостный", "adjective", "Her cheerful greeting changed the mood.", "Её радостное приветствие сменило настроение."),
        _w("humble", "/ˈhʌm.bəl/", "скромный", "adjective", "He stayed humble after the award.", "После награды он остался скромным."),
        _w("tense", "/tens/", "напряжённый", "adjective", "The room felt tense before the vote.", "Перед голосованием в комнате было напряжённо."),
        _w("hopeful", "/ˈhəʊp.fəl/", "полный надежды", "adjective", "I am hopeful about next month.", "Я с надеждой смотрю на следующий месяц."),
    ],
    "nature-environment": [
        _w("river", "/ˈrɪv.ə/", "река", "noun", "The river is too cold for swimming.", "Река слишком холодная для купания."),
        _w("forest", "/ˈfɒr.ɪst/", "лес", "noun", "A narrow path cuts through the forest.", "Узкая тропа пересекает лес."),
        _w("soil", "/sɔɪl/", "почва", "noun", "Dry soil needs water before planting.", "Сухую почву нужно полить перед посадкой."),
        _w("storm", "/stɔːm/", "шторм, буря", "noun", "The storm tore a branch from the oak.", "Буря оторвала ветку у дуба."),
        _w("tide", "/taɪd/", "прилив и отлив", "noun", "Low tide left shells on the sand.", "Отлив оставил ракушки на песке."),
        _w("insect", "/ˈɪn.sekt/", "насекомое", "noun", "One insect sat on the window.", "Одно насекомое село на окно."),
        _w("meadow", "/ˈmed.əʊ/", "луг", "noun", "Wild flowers cover the meadow in June.", "В июне луг покрыт полевыми цветами."),
        _w("smoke", "/sməʊk/", "дым", "noun", "Smoke rose from the distant hillside.", "С холма вдали поднимался дым."),
        _w("harvest", "/ˈhɑː.vɪst/", "урожай", "noun", "The harvest was later than last year.", "Урожай собрали позже, чем в прошлом году."),
        _w("pollen", "/ˈpɒl.ən/", "пыльца", "noun", "Spring pollen makes her sneeze.", "Весенняя пыльца вызывает у неё чихание."),
        _w("moss", "/mɒs/", "мох", "noun", "Green moss covers the north side of the wall.", "Зелёный мох покрывает северную сторону стены."),
        _w("canyon", "/ˈkæn.jən/", "каньон", "noun", "The canyon looks deeper at sunset.", "На закате каньон кажется глубже."),
    ],
    "media-technology": [
        _w("screen", "/skriːn/", "экран", "noun", "The screen is too bright at night.", "Ночью экран слишком яркий."),
        _w("cloud", "/klaʊd/", "облако (хранилище)", "noun", "Save a copy in the cloud as well.", "Сохрани копию ещё и в облаке."),
        _w("headset", "/ˈhed.set/", "гарнитура", "noun", "The headset battery lasted all day.", "Заряда гарнитуры хватило на весь день."),
        _w("spam", "/spæm/", "спам", "noun", "Most of the inbox was spam.", "Большая часть входящих была спамом."),
        _w("pixel", "/ˈpɪk.səl/", "пиксель", "noun", "One pixel on the photo looked wrong.", "Один пиксель на фото выглядел странно."),
        _w("router", "/ˈruː.tə/", "роутер", "noun", "Restart the router if the wifi drops.", "Перезапусти роутер, если пропадёт wifi."),
        _w("hashtag", "/ˈhæʃ.tæɡ/", "хештег", "noun", "The campaign used one simple hashtag.", "В кампании использовали один простой хештег."),
        _w("offline", "/ˌɒfˈlaɪn/", "офлайн", "adjective", "The map still works offline.", "Карта работает и офлайн."),
        _w("website", "/ˈweb.saɪt/", "сайт", "noun", "The website loads slowly on the train.", "Сайт медленно открывается в поезде."),
        _w("keyboard", "/ˈkiː.bɔːd/", "клавиатура", "noun", "A quiet keyboard helps in shared rooms.", "Тихая клавиатура удобна в общей комнате."),
        _w("speaker", "/ˈspiː.kə/", "колонка; оратор", "noun", "The speaker on the desk is small but clear.", "Колонка на столе маленькая, но чёткая."),
        _w("comment", "/ˈkɒm.ent/", "комментарий", "noun", "One comment explained the missing step.", "Один комментарий объяснил пропущенный шаг."),
    ],
    "business-money": [
        _w("loan", "/ləʊn/", "кредит", "noun", "They took a small loan for the van.", "Они взяли небольшой кредит на фургон."),
        _w("tax", "/tæks/", "налог", "noun", "The tax on the invoice is listed separately.", "Налог в счёте указан отдельно."),
        _w("wage", "/weɪdʒ/", "почасовая оплата", "noun", "The hourly wage rose in April.", "Почасовая оплата выросла в апреле."),
        _w("fee", "/fiː/", "сбор, плата", "noun", "The booking fee is not refundable.", "Сбор за бронь не возвращается."),
        _w("savings", "/ˈseɪ.vɪŋz/", "сбережения", "noun", "She moved her savings to another bank.", "Она перевела сбережения в другой банк."),
        _w("debt", "/det/", "долг", "noun", "They paid the last of the debt in May.", "Остаток долга они выплатили в мае."),
        _w("currency", "/ˈkʌr.ən.si/", "валюта", "noun", "Change your currency before you leave.", "Обменяй валюту до отъезда."),
        _w("bargain", "/ˈbɑː.ɡɪn/", "выгодная покупка", "noun", "That jacket was a real bargain.", "Та куртка была настоящей находкой по цене."),
        _w("refund", "/ˈriː.fʌnd/", "возврат денег", "noun", "The shop offered a full refund.", "Магазин предложил полный возврат."),
        _w("receipt", "/rɪˈsiːt/", "чек", "noun", "Keep the receipt if you want to return it.", "Сохрани чек, если захочешь вернуть товар."),
        _w("mortgage", "/ˈmɔː.ɡɪdʒ/", "ипотека", "noun", "Their mortgage payment is due on Friday.", "Платёж по ипотеке нужно внести в пятницу."),
        _w("startup", "/ˈstɑːt.ʌp/", "стартап", "noun", "The startup hired two more designers.", "Стартап нанял ещё двух дизайнеров."),
    ],
    "society-law": [
        _w("court", "/kɔːt/", "суд", "noun", "The court opens at nine on weekdays.", "Суд открывается в девять по будням."),
        _w("judge", "/dʒʌdʒ/", "судья", "noun", "The judge asked for a short pause.", "Судья попросил короткую паузу."),
        _w("witness", "/ˈwɪt.nəs/", "свидетель", "noun", "A witness described the car clearly.", "Свидетель чётко описал машину."),
        _w("crime", "/kraɪm/", "преступление", "noun", "The report showed a drop in street crime.", "В отчёте отметили снижение уличной преступности."),
        _w("fine", "/faɪn/", "штраф", "noun", "The fine for parking there is high.", "Штраф за парковку там высокий."),
        _w("rights", "/raɪts/", "права", "noun", "The leaflet explains basic legal rights.", "Листовка объясняет базовые юридические права."),
        _w("citizen", "/ˈsɪt.ɪ.zən/", "гражданин", "noun", "Every citizen can attend the hearing.", "Каждый гражданин может прийти на слушание."),
        _w("election", "/ɪˈlek.ʃən/", "выборы", "noun", "The local election is in October.", "Местные выборы пройдут в октябре."),
        _w("campaign", "/kæmˈpeɪn/", "кампания", "noun", "The campaign focused on cheaper transport.", "Кампания говорила о более дешёвом транспорте."),
        _w("border", "/ˈbɔː.də/", "граница", "noun", "Checks at the border took an hour.", "Проверка на границе заняла час."),
        _w("justice", "/ˈdʒʌs.tɪs/", "справедливость", "noun", "They asked for justice, not revenge.", "Они просили справедливости, а не мести."),
        _w("lawyer", "/ˈlɔɪ.ə/", "юрист", "noun", "A lawyer reviewed the rental contract.", "Юрист проверил договор аренды."),
    ],
    "academic-abstract": [
        _w("evidence", "/ˈev.ɪ.dəns/", "доказательства", "noun", "The evidence does not support that claim.", "Доказательства не подтверждают это утверждение."),
        _w("analysis", "/əˈnæl.ə.sɪs/", "анализ", "noun", "The analysis compared three cities.", "Анализ сравнил три города."),
        _w("variable", "/ˈveə.ri.ə.bəl/", "переменная", "noun", "Age was the only extra variable.", "Возраст был единственной дополнительной переменной."),
        _w("sample", "/ˈsɑːm.pəl/", "выборка", "noun", "The sample included two hundred adults.", "В выборку вошли двести взрослых."),
        _w("theory", "/ˈθɪə.ri/", "теория", "noun", "The theory is simple but useful.", "Теория простая, но полезная."),
        _w("abstract", "/ˈæb.strækt/", "аннотация", "noun", "Read the abstract before the full paper.", "Прочитай аннотацию до полной статьи."),
        _w("cite", "/saɪt/", "цитировать", "verb", "Cite the source in the first paragraph.", "Укажи источник в первом абзаце."),
        _w("draft", "/drɑːft/", "черновик", "noun", "The first draft is still too long.", "Первый черновик всё ещё слишком длинный."),
        _w("peer", "/pɪə/", "коллега по статусу", "noun", "A peer reviewed the methods section.", "Коллега проверил раздел методов."),
        _w("bias", "/ˈbaɪ.əs/", "смещение, предвзятость", "noun", "The survey tried to reduce bias.", "Опрос старался снизить предвзятость."),
        _w("scope", "/skəʊp/", "охват, рамки", "noun", "The scope of the study is local.", "Рамки исследования локальные."),
        _w("outcome", "/ˈaʊt.kʌm/", "результат", "noun", "The main outcome surprised the team.", "Главный результат удивил команду."),
    ],
}

NEW_TOPICS = [
    _topic(
        "clothes-weather",
        "Одежда и погода",
        "Что надеть и как описать день: куртка, зонт, дождь, тепло и холод.",
        "A1",
        [
            _w("jacket", "/ˈdʒæk.ɪt/", "куртка", "noun", "Take a jacket; the evening is cool.", "Возьми куртку: вечером прохладно."),
            _w("coat", "/kəʊt/", "пальто", "noun", "Hang your coat by the door.", "Повесь пальто у двери."),
            _w("shirt", "/ʃɜːt/", "рубашка", "noun", "This shirt needs a better iron.", "Эту рубашку нужно лучше погладить."),
            _w("trousers", "/ˈtraʊ.zəz/", "брюки", "noun", "Dark trousers hide the dust better.", "Тёмные брюки лучше скрывают пыль."),
            _w("dress", "/dres/", "платье", "noun", "She wore a simple blue dress.", "На ней было простое синее платье."),
            _w("shoes", "/ʃuːz/", "туфли, ботинки", "noun", "These shoes are too tight.", "Эти туфли слишком тесные."),
            _w("hat", "/hæt/", "шляпа, шапка", "noun", "A hat keeps the sun off your face.", "Шляпа закрывает лицо от солнца."),
            _w("gloves", "/ɡlʌvz/", "перчатки", "noun", "Put on gloves before you cycle.", "Надень перчатки, прежде чем ехать."),
            _w("scarf", "/skɑːf/", "шарф", "noun", "The red scarf is in the bag.", "Красный шарф лежит в сумке."),
            _w("boots", "/buːts/", "сапоги", "noun", "Wear boots if the path is wet.", "Надень сапоги, если тропа мокрая."),
            _w("umbrella", "/ʌmˈbrel.ə/", "зонт", "noun", "I left my umbrella on the bus.", "Я оставил зонт в автобусе."),
            _w("rain", "/reɪn/", "дождь", "noun", "The rain started after lunch.", "Дождь начался после обеда."),
            _w("snow", "/snəʊ/", "снег", "noun", "Soft snow covered the steps.", "Мягкий снег покрыл ступеньки."),
            _w("sunny", "/ˈsʌn.i/", "солнечный", "adjective", "It is sunny, but the wind is cold.", "Солнечно, но ветер холодный."),
            _w("wind", "/wɪnd/", "ветер", "noun", "A strong wind closed the window.", "Сильный ветер захлопнул окно."),
            _w("cloud", "/klaʊd/", "облако", "noun", "One dark cloud sat over the hill.", "Над холмом висело одно тёмное облако."),
            _w("temperature", "/ˈtem.prə.tʃə/", "температура", "noun", "The temperature dropped at night.", "Ночью температура упала."),
            _w("season", "/ˈsiː.zən/", "время года", "noun", "Autumn is my favourite season.", "Осень — моё любимое время года."),
            _w("warm", "/wɔːm/", "тёплый", "adjective", "The room is warm enough without a heater.", "В комнате достаточно тепло без обогревателя."),
            _w("cold", "/kəʊld/", "холодный", "adjective", "The tap water is still cold.", "Вода из крана всё ещё холодная."),
            _w("pocket", "/ˈpɒk.ɪt/", "карман", "noun", "The ticket is in the left pocket.", "Билет в левом кармане."),
            _w("zip", "/zɪp/", "молния", "noun", "The zip on this bag is stuck.", "Молния на этой сумке заедает."),
        ],
    ),
    _topic(
        "daily-routines",
        "Распорядок дня",
        "Базовые глаголы быта: встать, умыться, уйти, приготовить, закончить.",
        "A1",
        [
            _w("wake", "/weɪk/", "просыпаться", "verb", "I wake at seven on weekdays.", "В будни я просыпаюсь в семь."),
            _w("shower", "/ˈʃaʊ.ə/", "душ", "noun", "A short shower is enough in the morning.", "Короткого душа утром достаточно."),
            _w("brush", "/brʌʃ/", "чистить (зубы, волосы)", "verb", "Brush your teeth after breakfast.", "Почисти зубы после завтрака."),
            _w("leave", "/liːv/", "уходить, оставлять", "verb", "We leave the house at eight.", "Мы выходим из дома в восемь."),
            _w("arrive", "/əˈraɪv/", "прибывать", "verb", "The bus arrives five minutes late.", "Автобус прибывает с опозданием на пять минут."),
            _w("cook", "/kʊk/", "готовить", "verb", "He cooks rice almost every evening.", "Он готовит рис почти каждый вечер."),
            _w("wash", "/wɒʃ/", "мыть", "verb", "Wash the cups before you go out.", "Вымой чашки, прежде чем выйти."),
            _w("clean", "/kliːn/", "убирать", "verb", "We clean the kitchen on Sunday.", "Мы убираем кухню в воскресенье."),
            _w("walk", "/wɔːk/", "ходить пешком", "verb", "I walk to the shop after work.", "После работы я иду в магазин пешком."),
            _w("shop", "/ʃɒp/", "делать покупки", "verb", "They shop for food on Saturday.", "Они покупают продукты в субботу."),
            _w("visit", "/ˈvɪz.ɪt/", "навещать", "verb", "We visit grandmother once a week.", "Мы навещаем бабушку раз в неделю."),
            _w("watch", "/wɒtʃ/", "смотреть", "verb", "The children watch one film on Friday.", "В пятницу дети смотрят один фильм."),
            _w("listen", "/ˈlɪs.ən/", "слушать", "verb", "Listen to the audio twice.", "Прослушай аудио дважды."),
            _w("read", "/riːd/", "читать", "verb", "She reads ten pages before bed.", "Она читает десять страниц перед сном."),
            _w("write", "/raɪt/", "писать", "verb", "Write your name at the top.", "Напиши имя сверху."),
            _w("wait", "/weɪt/", "ждать", "verb", "Wait here until I come back.", "Подожди здесь, пока я не вернусь."),
            _w("help", "/help/", "помогать", "verb", "Can you help me with this bag?", "Можешь помочь мне с этой сумкой?"),
            _w("call", "/kɔːl/", "звонить", "verb", "Call me when you reach the station.", "Позвони, когда доберёшься до вокзала."),
            _w("finish", "/ˈfɪn.ɪʃ/", "заканчивать", "verb", "Finish the exercise before the break.", "Закончи упражнение до перерыва."),
            _w("start", "/stɑːt/", "начинать", "verb", "Start the lesson with a short review.", "Начни урок с короткого повторения."),
            _w("sleep", "/sliːp/", "спать", "verb", "I sleep better with the window open.", "Мне лучше спится с открытым окном."),
            _w("rest", "/rest/", "отдыхать", "verb", "Rest for ten minutes after the walk.", "Отдохни десять минут после прогулки."),
        ],
    ),
    _topic(
        "colours-time",
        "Цвета и время",
        "Цвета, части суток и простые слова про часы, дни и недели.",
        "A1",
        [
            _w("red", "/red/", "красный", "adjective", "The red door is the side entrance.", "Красная дверь — боковой вход."),
            _w("blue", "/bluː/", "синий", "adjective", "She bought a blue notebook.", "Она купила синюю тетрадь."),
            _w("green", "/ɡriːn/", "зелёный", "adjective", "The green light lasted a few seconds.", "Зелёный сигнал горел несколько секунд."),
            _w("yellow", "/ˈjel.əʊ/", "жёлтый", "adjective", "A yellow sign marks the wet floor.", "Жёлтый знак предупреждает о мокром полу."),
            _w("black", "/blæk/", "чёрный", "adjective", "He wears a black jacket to work.", "На работу он надевает чёрную куртку."),
            _w("white", "/waɪt/", "белый", "adjective", "The white walls make the room brighter.", "Белые стены делают комнату светлее."),
            _w("grey", "/ɡreɪ/", "серый", "adjective", "Grey clouds covered the afternoon.", "Серые облака закрыли день."),
            _w("morning", "/ˈmɔː.nɪŋ/", "утро", "noun", "I drink tea every morning.", "Каждое утро я пью чай."),
            _w("afternoon", "/ˌɑːf.təˈnuːn/", "день (после полудня)", "noun", "The shop is quiet in the afternoon.", "Днём в магазине тихо."),
            _w("evening", "/ˈiːv.nɪŋ/", "вечер", "noun", "We walk in the park in the evening.", "Вечером мы гуляем в парке."),
            _w("night", "/naɪt/", "ночь", "noun", "The streets are empty at night.", "Ночью улицы пустые."),
            _w("week", "/wiːk/", "неделя", "noun", "The course lasts one week.", "Курс длится одну неделю."),
            _w("month", "/mʌnθ/", "месяц", "noun", "She pays rent on the first of the month.", "Она платит аренду первого числа."),
            _w("year", "/jɪə/", "год", "noun", "This year I want a slower pace.", "В этом году я хочу более спокойный ритм."),
            _w("hour", "/aʊə/", "час", "noun", "The museum visit takes one hour.", "Визит в музей занимает час."),
            _w("minute", "/ˈmɪn.ɪt/", "минута", "noun", "Wait a minute near the entrance.", "Подожди минуту у входа."),
            _w("early", "/ˈɜː.li/", "рано", "adverb", "The train is five minutes early.", "Поезд на пять минут раньше."),
            _w("late", "/leɪt/", "поздно", "adverb", "Sorry I am late for the call.", "Извини, я опоздал на звонок."),
            _w("today", "/təˈdeɪ/", "сегодня", "adverb", "Today the library closes at four.", "Сегодня библиотека закрывается в четыре."),
            _w("tomorrow", "/təˈmɒr.əʊ/", "завтра", "adverb", "Tomorrow we start with listening.", "Завтра начнём с аудирования."),
            _w("yesterday", "/ˈjes.tə.deɪ/", "вчера", "adverb", "Yesterday the shop was closed.", "Вчера магазин был закрыт."),
            _w("o'clock", "/əˈklɒk/", "часов ровно", "adverb", "The class starts at nine o'clock.", "Занятие начинается в девять часов."),
        ],
    ),
    _topic(
        "home-rooms",
        "Дом и комнаты",
        "Планировка жилья: кухня, спальня, лестница, балкон и двор.",
        "A1",
        [
            _w("kitchen", "/ˈkɪtʃ.ɪn/", "кухня", "noun", "The kitchen window faces the yard.", "Кухонное окно выходит во двор."),
            _w("bedroom", "/ˈbed.ruːm/", "спальня", "noun", "The small bedroom is quieter.", "Маленькая спальня тише."),
            _w("bathroom", "/ˈbɑːθ.ruːm/", "ванная", "noun", "The bathroom light is too bright.", "Свет в ванной слишком яркий."),
            _w("garden", "/ˈɡɑː.dən/", "сад", "noun", "Tomatoes grow in the back garden.", "Помидоры растут в заднем саду."),
            _w("balcony", "/ˈbæl.kə.ni/", "балкон", "noun", "We drink tea on the balcony.", "Мы пьём чай на балконе."),
            _w("stairs", "/steəz/", "лестница", "noun", "The stairs are steep and narrow.", "Лестница крутая и узкая."),
            _w("floor", "/flɔː/", "этаж; пол", "noun", "Our flat is on the third floor.", "Наша квартира на третьем этаже."),
            _w("roof", "/ruːf/", "крыша", "noun", "Rain hit the metal roof all night.", "Дождь всю ночь стучал по металлической крыше."),
            _w("wall", "/wɔːl/", "стена", "noun", "A map hangs on the kitchen wall.", "На кухонной стене висит карта."),
            _w("sink", "/sɪŋk/", "раковина", "noun", "Leave the cups by the sink.", "Оставь чашки у раковины."),
            _w("cupboard", "/ˈkʌb.əd/", "шкаф", "noun", "The cups are in the upper cupboard.", "Чашки в верхнем шкафу."),
            _w("garage", "/ˈɡær.ɑːʒ/", "гараж", "noun", "The bicycle is in the garage.", "Велосипед стоит в гараже."),
            _w("attic", "/ˈæt.ɪk/", "чердак", "noun", "Old boxes sit in the attic.", "На чердаке стоят старые коробки."),
            _w("basement", "/ˈbeɪs.mənt/", "подвал", "noun", "The washing machine is in the basement.", "Стиральная машина в подвале."),
            _w("hallway", "/ˈhɔːl.weɪ/", "коридор", "noun", "Leave your shoes in the hallway.", "Оставь обувь в коридоре."),
            _w("fence", "/fens/", "забор", "noun", "The wooden fence needs paint.", "Деревянный забор нужно покрасить."),
            _w("porch", "/pɔːtʃ/", "крыльцо", "noun", "A wet umbrella stood on the porch.", "На крыльце стоял мокрый зонт."),
            _w("yard", "/jɑːd/", "двор", "noun", "The children play in the yard.", "Дети играют во дворе."),
            _w("flat", "/flæt/", "квартира", "noun", "Their flat has two small rooms.", "В их квартире две маленькие комнаты."),
            _w("lift", "/lɪft/", "лифт", "noun", "The lift is out of order today.", "Лифт сегодня не работает."),
            _w("keyhole", "/ˈkiː.həʊl/", "замочная скважина", "noun", "The key does not fit this keyhole.", "Ключ не подходит к этой скважине."),
            _w("doorbell", "/ˈdɔː.bel/", "дверной звонок", "noun", "Ring the doorbell twice.", "Позвони в дверь дважды."),
        ],
    ),
    _topic(
        "shopping-money-basic",
        "Магазин и деньги",
        "Покупки без сложных финансов: цена, очередь, сдача, скидка.",
        "A1",
        [
            _w("shop", "/ʃɒp/", "магазин", "noun", "The shop on the corner closes early.", "Магазин на углу закрывается рано."),
            _w("price", "/praɪs/", "цена", "noun", "The price is on the back of the tag.", "Цена написана на обороте бирки."),
            _w("cheap", "/tʃiːp/", "дешёвый", "adjective", "This bread is cheap and fresh.", "Этот хлеб дешёвый и свежий."),
            _w("expensive", "/ɪkˈspen.sɪv/", "дорогой", "adjective", "The tickets were more expensive than last year.", "Билеты дороже, чем в прошлом году."),
            _w("size", "/saɪz/", "размер", "noun", "Do you have this size in black?", "Есть этот размер в чёрном?"),
            _w("colour", "/ˈkʌl.ə/", "цвет", "noun", "I prefer a darker colour.", "Мне больше нравится более тёмный цвет."),
            _w("customer", "/ˈkʌs.tə.mə/", "покупатель", "noun", "The next customer already has a number.", "У следующего покупателя уже есть номер."),
            _w("cashier", "/kæʃˈɪə/", "кассир", "noun", "The cashier asked for a smaller note.", "Кассир попросил купюру помельче."),
            _w("change", "/tʃeɪndʒ/", "сдача", "noun", "Keep the change, please.", "Сдачу оставьте себе."),
            _w("cash", "/kæʃ/", "наличные", "noun", "This stall only takes cash.", "Эта палатка принимает только наличные."),
            _w("card", "/kɑːd/", "карта", "noun", "I paid by card at the exit.", "На выходе я заплатил картой."),
            _w("queue", "/kjuː/", "очередь", "noun", "The queue moved faster after lunch.", "После обеда очередь пошла быстрее."),
            _w("sale", "/seɪl/", "распродажа", "noun", "The winter sale starts on Monday.", "Зимняя распродажа начнётся в понедельник."),
            _w("basket", "/ˈbɑː.skɪt/", "корзина", "noun", "Put heavy jars at the bottom of the basket.", "Тяжёлые банки клади на дно корзины."),
            _w("bill", "/bɪl/", "счёт", "noun", "Ask for the bill when you finish.", "Попроси счёт, когда закончишь."),
            _w("discount", "/ˈdɪs.kaʊnt/", "скидка", "noun", "Students get a small discount.", "Студентам дают небольшую скидку."),
            _w("try on", "/ˌtraɪ ˈɒn/", "примерять", "verb", "You can try on the coat over there.", "Пальто можно примерить вон там."),
            _w("open", "/ˈəʊ.pən/", "открытый", "adjective", "Is the bakery still open?", "Пекарня ещё открыта?"),
            _w("closed", "/kləʊzd/", "закрытый", "adjective", "The post office is closed on Sunday.", "Почта по воскресеньям закрыта."),
            _w("aisle", "/aɪl/", "проход между полками", "noun", "Rice is in the middle aisle.", "Рис в среднем проходе."),
            _w("label", "/ˈleɪ.bəl/", "этикетка", "noun", "Read the label before you buy spices.", "Прочитай этикетку, прежде чем брать специи."),
            _w("counter", "/ˈkaʊn.tə/", "прилавок", "noun", "Cheese is sold at the back counter.", "Сыр продают на дальнем прилавке."),
        ],
    ),
    _topic(
        "hobbies-sports",
        "Хобби и спорт",
        "Досуг A2: команда, матч, гитара, поход, фотография.",
        "A2",
        [
            _w("hobby", "/ˈhɒb.i/", "хобби", "noun", "Gardening became her main hobby.", "Садоводство стало её главным хобби."),
            _w("football", "/ˈfʊt.bɔːl/", "футбол", "noun", "They play football behind the school.", "Они играют в футбол за школой."),
            _w("tennis", "/ˈten.ɪs/", "теннис", "noun", "The tennis court is free after six.", "Корт свободен после шести."),
            _w("swimming", "/ˈswɪm.ɪŋ/", "плавание", "noun", "Swimming helps her back after work.", "Плавание помогает её спине после работы."),
            _w("cycling", "/ˈsaɪ.klɪŋ/", "езда на велосипеде", "noun", "Cycling to work saves twenty minutes.", "Поездка на работу на велосипеде экономит двадцать минут."),
            _w("guitar", "/ɡɪˈtɑː/", "гитара", "noun", "He practises the guitar after dinner.", "Он занимается на гитаре после ужина."),
            _w("chess", "/tʃes/", "шахматы", "noun", "They play chess in the library.", "Они играют в шахматы в библиотеке."),
            _w("painting", "/ˈpeɪn.tɪŋ/", "живопись", "noun", "Painting helps her slow down.", "Живопись помогает ей замедлиться."),
            _w("photography", "/fəˈtɒɡ.rə.fi/", "фотография", "noun", "Street photography needs patience.", "Уличная фотография требует терпения."),
            _w("team", "/tiːm/", "команда", "noun", "Our team meets on Thursday nights.", "Наша команда собирается в четверг вечером."),
            _w("match", "/mætʃ/", "матч", "noun", "The match was delayed by rain.", "Матч отложили из-за дождя."),
            _w("score", "/skɔː/", "счёт", "noun", "The final score was two to one.", "Итоговый счёт — два:один."),
            _w("coach", "/kəʊtʃ/", "тренер", "noun", "The coach asked for a shorter warm-up.", "Тренер попросил короче разминку."),
            _w("stadium", "/ˈsteɪ.di.əm/", "стадион", "noun", "The stadium is a twenty-minute walk.", "До стадиона двадцать минут пешком."),
            _w("camera", "/ˈkæm.rə/", "камера", "noun", "Charge the camera before the trip.", "Заряди камеру перед поездкой."),
            _w("hiking", "/ˈhaɪ.kɪŋ/", "пеший поход", "noun", "Hiking on Sunday cleared my head.", "Воскресный поход прояснил голову."),
            _w("yoga", "/ˈjəʊ.ɡə/", "йога", "noun", "Morning yoga is only twenty minutes.", "Утренняя йога занимает всего двадцать минут."),
            _w("puzzle", "/ˈpʌz.əl/", "головоломка", "noun", "This puzzle has too many similar pieces.", "В этой головоломке слишком много похожих деталей."),
            _w("club", "/klʌb/", "клуб", "noun", "The reading club meets twice a month.", "Клуб чтения собирается дважды в месяц."),
            _w("train", "/treɪn/", "тренироваться", "verb", "They train on the track before school.", "Они тренируются на дорожке до школы."),
            _w("win", "/wɪn/", "побеждать", "verb", "We did not win, but the game was fair.", "Мы не победили, но игра была честной."),
            _w("lose", "/luːz/", "проигрывать", "verb", "It is fine to lose if you learn something.", "Нормально проиграть, если чему-то научился."),
        ],
    ),
    _topic(
        "school-subjects",
        "Школа и предметы",
        "Учебные предметы и класс: учитель, оценка, опыт, словарь.",
        "A2",
        [
            _w("maths", "/mæθs/", "математика", "noun", "Maths is the first lesson on Monday.", "Математика — первый урок в понедельник."),
            _w("history", "/ˈhɪs.tər.i/", "история", "noun", "History homework is a short timeline.", "Домашнее по истории — короткая лента событий."),
            _w("biology", "/baɪˈɒl.ə.dʒi/", "биология", "noun", "Biology class meets in the lab.", "Биология проходит в лаборатории."),
            _w("chemistry", "/ˈkem.ɪ.stri/", "химия", "noun", "Chemistry needs careful notes.", "Химия требует аккуратных записей."),
            _w("physics", "/ˈfɪz.ɪks/", "физика", "noun", "Physics explained why the bridge sways.", "Физика объяснила, почему мост качается."),
            _w("geography", "/dʒiˈɒɡ.rə.fi/", "география", "noun", "Geography covers rivers and cities.", "География охватывает реки и города."),
            _w("art", "/ɑːt/", "изобразительное искусство", "noun", "Art class uses only paper and charcoal.", "На изо только бумага и уголь."),
            _w("music", "/ˈmjuː.zɪk/", "музыка", "noun", "Music starts after the break.", "Музыка начинается после перемены."),
            _w("literature", "/ˈlɪt.rə.tʃə/", "литература", "noun", "Literature this term is short stories.", "В этом семестре литература — рассказы."),
            _w("classroom", "/ˈklɑːs.ruːm/", "класс", "noun", "The classroom windows face the yard.", "Окна класса выходят во двор."),
            _w("teacher", "/ˈtiː.tʃə/", "учитель", "noun", "The teacher wrote the rule twice.", "Учитель дважды записал правило."),
            _w("pupil", "/ˈpjuː.pəl/", "ученик", "noun", "Each pupil needs a spare pencil.", "Каждому ученику нужен запасной карандаш."),
            _w("mark", "/mɑːk/", "оценка", "noun", "A higher mark needs a clearer plan.", "Для более высокой оценки нужен более ясный план."),
            _w("lesson", "/ˈles.ən/", "урок", "noun", "The lesson ends with two questions.", "Урок заканчивается двумя вопросами."),
            _w("subject", "/ˈsʌb.dʒɪkt/", "предмет", "noun", "Which subject do you enjoy most?", "Какой предмет тебе нравится больше всего?"),
            _w("blackboard", "/ˈblæk.bɔːd/", "доска", "noun", "Copy the dates from the blackboard.", "Спиши даты с доски."),
            _w("experiment", "/ɪkˈsper.ɪ.mənt/", "опыт", "noun", "The experiment needs clean glass.", "Для опыта нужно чистое стекло."),
            _w("dictionary", "/ˈdɪk.ʃən.ər.i/", "словарь", "noun", "Check the verb in a learner dictionary.", "Проверь глагол в учебном словаре."),
            _w("break", "/breɪk/", "перемена", "noun", "The break is only ten minutes.", "Перемена всего десять минут."),
            _w("uniform", "/ˈjuː.nɪ.fɔːm/", "форма", "noun", "The uniform includes a dark jumper.", "В форму входит тёмный джемпер."),
            _w("timetable", "/ˈtaɪmˌteɪ.bəl/", "расписание", "noun", "The new timetable starts next week.", "Новое расписание начнётся на следующей неделе."),
            _w("revision", "/rɪˈvɪʒ.ən/", "повторение", "noun", "Revision works better in short blocks.", "Повторение лучше идёт короткими блоками."),
        ],
    ),
    _topic(
        "restaurants-cooking",
        "Кафе и готовка",
        "Меню, счёт, вкусы и простые кухонные слова.",
        "A2",
        [
            _w("menu", "/ˈmen.juː/", "меню", "noun", "The lunch menu changes on Fridays.", "Обеденное меню меняется по пятницам."),
            _w("waiter", "/ˈweɪ.tə/", "официант", "noun", "The waiter brought water first.", "Официант сначала принёс воду."),
            _w("tip", "/tɪp/", "чаевые", "noun", "They left a small tip on the table.", "Они оставили на столе небольшие чаевые."),
            _w("starter", "/ˈstɑː.tə/", "закуска", "noun", "The starter is soup or salad.", "На закуску — суп или салат."),
            _w("dessert", "/dɪˈzɜːt/", "десерт", "noun", "Dessert is optional after a heavy meal.", "После сытного обеда десерт необязателен."),
            _w("spicy", "/ˈspaɪ.si/", "острый", "adjective", "Ask if the sauce is too spicy.", "Спроси, не слишком ли острый соус."),
            _w("boiled", "/bɔɪld/", "варёный", "adjective", "I prefer boiled potatoes with herbs.", "Я предпочитаю варёный картофель с травами."),
            _w("fried", "/fraɪd/", "жареный", "adjective", "Fried onions smell across the hall.", "Жареный лук пахнет на весь коридор."),
            _w("baked", "/beɪkt/", "запечённый", "adjective", "Baked apples need only twenty minutes.", "Запечённым яблокам нужно всего двадцать минут."),
            _w("recipe", "/ˈres.ɪ.pi/", "рецепт", "noun", "The recipe uses only five ingredients.", "В рецепте всего пять ингредиентов."),
            _w("ingredient", "/ɪnˈɡriː.di.ənt/", "ингредиент", "noun", "Salt is the last ingredient.", "Соль — последний ингредиент."),
            _w("oven", "/ˈʌv.ən/", "духовка", "noun", "Heat the oven before you mix the dough.", "Разогрей духовку, прежде чем месить тесто."),
            _w("pan", "/pæn/", "сковорода", "noun", "A heavy pan keeps the heat steady.", "Тяжёлая сковорода держит жар ровнее."),
            _w("taste", "/teɪst/", "вкус", "noun", "The taste is milder than I expected.", "Вкус мягче, чем я ждал."),
            _w("hungry", "/ˈhʌŋ.ɡri/", "голодный", "adjective", "I get hungry after a long walk.", "После долгой прогулки я проголодался."),
            _w("thirsty", "/ˈθɜː.sti/", "хочет пить", "adjective", "Take water if you feel thirsty.", "Возьми воду, если хочется пить."),
            _w("reservation", "/ˌrez.əˈveɪ.ʃən/", "бронь столика", "noun", "The reservation is under my name.", "Бронь на моё имя."),
            _w("portion", "/ˈpɔː.ʃən/", "порция", "noun", "One portion is enough for two people.", "Одной порции хватит на двоих."),
            _w("order", "/ˈɔː.də/", "заказ", "noun", "Our order arrived in ten minutes.", "Наш заказ пришёл через десять минут."),
            _w("fresh", "/freʃ/", "свежий", "adjective", "The bread is still fresh at closing time.", "Хлеб ещё свежий к закрытию."),
            _w("raw", "/rɔː/", "сырой", "adjective", "Do not eat the fish raw.", "Не ешь эту рыбу сырой."),
            _w("slice", "/slaɪs/", "ломтик", "noun", "Cut one more slice of lemon.", "Отрежь ещё один ломтик лимона."),
        ],
    ),
    _topic(
        "animals-pets",
        "Животные и питомцы",
        "Домашние и дикие животные, простые слова про уход.",
        "A2",
        [
            _w("dog", "/dɒɡ/", "собака", "noun", "The dog waits by the garden gate.", "Собака ждёт у садовой калитки."),
            _w("cat", "/kæt/", "кошка", "noun", "The cat prefers the sunny chair.", "Кошке больше нравится солнечный стул."),
            _w("bird", "/bɜːd/", "птица", "noun", "A small bird sat on the fence.", "Маленькая птица села на забор."),
            _w("horse", "/hɔːs/", "лошадь", "noun", "The horse walked slowly through the field.", "Лошадь медленно шла по полю."),
            _w("sheep", "/ʃiːp/", "овца", "noun", "The sheep stayed close to the barn.", "Овцы держались ближе к сараю."),
            _w("cow", "/kaʊ/", "корова", "noun", "One cow stood under the tree.", "Одна корова стояла под деревом."),
            _w("bee", "/biː/", "пчела", "noun", "A bee hovered over the jam.", "Пчела кружила над вареньем."),
            _w("butterfly", "/ˈbʌt.ə.flaɪ/", "бабочка", "noun", "A butterfly landed on her sleeve.", "Бабочка села ей на рукав."),
            _w("rabbit", "/ˈræb.ɪt/", "кролик", "noun", "The rabbit hid under the table.", "Кролик спрятался под столом."),
            _w("hamster", "/ˈhæm.stə/", "хомяк", "noun", "The hamster sleeps most of the day.", "Хомяк спит большую часть дня."),
            _w("feather", "/ˈfeð.ə/", "перо", "noun", "A grey feather lay on the path.", "На тропинке лежало серое перо."),
            _w("paw", "/pɔː/", "лапа", "noun", "The dog lifted one paw at the door.", "Собака подняла лапу у двери."),
            _w("nest", "/nest/", "гнездо", "noun", "There is a nest under the roof.", "Под крышей есть гнездо."),
            _w("cage", "/keɪdʒ/", "клетка", "noun", "Clean the cage twice a week.", "Чисти клетку дважды в неделю."),
            _w("wild", "/waɪld/", "дикий", "adjective", "Wild foxes sometimes cross the road.", "Дикие лисы иногда переходят дорогу."),
            _w("tame", "/teɪm/", "ручной", "adjective", "The tame bird eats from her hand.", "Ручная птица ест у неё с руки."),
            _w("pet", "/pet/", "питомец", "noun", "Their only pet is an old cat.", "Их единственный питомец — старая кошка."),
            _w("feed", "/fiːd/", "кормить", "verb", "Feed the fish once in the evening.", "Корми рыб один раз вечером."),
            _w("bark", "/bɑːk/", "лаять", "verb", "The dog does not bark at visitors.", "Собака не лает на гостей."),
            _w("fur", "/fɜː/", "шерсть", "noun", "Cat fur covers the dark sofa.", "Шерсть кошки покрывает тёмный диван."),
            _w("tail", "/teɪl/", "хвост", "noun", "The puppy wagged its tail.", "Щенок вилял хвостом."),
            _w("vet", "/vet/", "ветеринар", "noun", "The vet asked about the cat's appetite.", "Ветеринар спросил про аппетит кошки."),
        ],
    ),
    _topic(
        "transport-directions",
        "Транспорт и направление",
        "Куда повернуть и на чём ехать: светофор, тротуар, пассажир.",
        "A2",
        [
            _w("left", "/left/", "налево", "adverb", "Turn left after the bakery.", "Поверни налево после пекарни."),
            _w("right", "/raɪt/", "направо", "adverb", "The museum is on the right.", "Музей справа."),
            _w("straight", "/streɪt/", "прямо", "adverb", "Go straight until the river.", "Иди прямо до реки."),
            _w("corner", "/ˈkɔː.nə/", "угол", "noun", "Wait at the corner of Oak Street.", "Подожди на углу Оук-стрит."),
            _w("north", "/nɔːθ/", "север", "noun", "Cold air comes from the north.", "Холодный воздух приходит с севера."),
            _w("south", "/saʊθ/", "юг", "noun", "The south platform is quieter.", "Южная платформа тише."),
            _w("east", "/iːst/", "восток", "noun", "The east gate opens at dawn.", "Восточные ворота открываются на рассвете."),
            _w("west", "/west/", "запад", "noun", "The hotel faces west.", "Отель смотрит на запад."),
            _w("motorway", "/ˈməʊ.tə.weɪ/", "автострада", "noun", "Avoid the motorway at rush hour.", "Не выезжай на автостраду в час пик."),
            _w("pavement", "/ˈpeɪv.mənt/", "тротуар", "noun", "Keep the suitcase on the pavement.", "Держи чемодан на тротуаре."),
            _w("bicycle", "/ˈbaɪ.sɪ.kəl/", "велосипед", "noun", "Lock the bicycle near the entrance.", "Пристегни велосипед у входа."),
            _w("lorry", "/ˈlɒr.i/", "грузовик", "noun", "A lorry blocked the narrow street.", "Грузовик перекрыл узкую улицу."),
            _w("petrol", "/ˈpet.rəl/", "бензин", "noun", "We need petrol before the next town.", "Нужен бензин до следующего города."),
            _w("sign", "/saɪn/", "знак", "noun", "The sign points to the harbour.", "Знак указывает к гавани."),
            _w("destination", "/ˌdes.tɪˈneɪ.ʃən/", "пункт назначения", "noun", "The final destination is on the ticket.", "Конечный пункт написан на билете."),
            _w("passenger", "/ˈpæs.ən.dʒə/", "пассажир", "noun", "Each passenger needs a seatbelt.", "Каждому пассажиру нужен ремень."),
            _w("driver", "/ˈdraɪ.və/", "водитель", "noun", "The driver waited at the red light.", "Водитель ждал на красный."),
            _w("fare", "/feə/", "плата за проезд", "noun", "The bus fare is cheaper with a card.", "Проезд на автобусе дешевле по карте."),
            _w("cross", "/krɒs/", "переходить", "verb", "Cross at the lights, not here.", "Переходи на светофоре, не здесь."),
            _w("miss", "/mɪs/", "опоздать на", "verb", "Hurry or you will miss the tram.", "Поторопись, иначе опоздаешь на трамвай."),
            _w("catch", "/kætʃ/", "успеть на", "verb", "We can still catch the last ferry.", "Мы ещё можем успеть на последний паром."),
            _w("traffic lights", "/ˈtræf.ɪk laɪts/", "светофор", "noun", "Stop if the traffic lights are amber.", "Остановись, если светофор жёлтый."),
        ],
    ),
    _topic(
        "useful-nouns",
        "Полезные существительные",
        "Частые слова B1: решение, привычка, цель, ошибка, совет.",
        "B1",
        [
            _w("opportunity", "/ˌɒp.əˈtjuː.nə.ti/", "возможность", "noun", "The course is a rare opportunity.", "Курс — редкая возможность."),
            _w("challenge", "/ˈtʃæl.ɪndʒ/", "вызов", "noun", "Listening at speed is still a challenge.", "Слушать в быстром темпе всё ещё сложно."),
            _w("advantage", "/ədˈvɑːn.tɪdʒ/", "преимущество", "noun", "Living near the station is an advantage.", "Жить рядом с вокзалом — преимущество."),
            _w("disadvantage", "/ˌdɪs.ədˈvɑːn.tɪdʒ/", "недостаток", "noun", "The main disadvantage is the noise.", "Главный недостаток — шум."),
            _w("solution", "/səˈluː.ʃən/", "решение", "noun", "A shorter list was the simplest solution.", "Более короткий список оказался самым простым решением."),
            _w("decision", "/dɪˈsɪʒ.ən/", "решение (выбор)", "noun", "The decision can wait until Friday.", "Решение можно отложить до пятницы."),
            _w("advice", "/ədˈvaɪs/", "совет", "noun", "Her advice was short and practical.", "Её совет был коротким и практичным."),
            _w("experience", "/ɪkˈspɪə.ri.əns/", "опыт", "noun", "Teaching gave him useful experience.", "Преподавание дало ему полезный опыт."),
            _w("habit", "/ˈhæb.ɪt/", "привычка", "noun", "Reading at night became a habit.", "Чтение по ночам стало привычкой."),
            _w("goal", "/ɡəʊl/", "цель", "noun", "My goal is twenty minutes a day.", "Моя цель — двадцать минут в день."),
            _w("effort", "/ˈef.ət/", "усилие", "noun", "A little extra effort changed the result.", "Небольшое дополнительное усилие изменило результат."),
            _w("progress", "/ˈprəʊ.ɡres/", "прогресс", "noun", "Slow progress is still progress.", "Медленный прогресс — всё равно прогресс."),
            _w("mistake", "/mɪˈsteɪk/", "ошибка", "noun", "One mistake does not ruin the draft.", "Одна ошибка не портит черновик."),
            _w("reason", "/ˈriː.zən/", "причина", "noun", "The reason for the delay was fog.", "Причина задержки — туман."),
            _w("result", "/rɪˈzʌlt/", "результат", "noun", "The result was better than expected.", "Результат оказался лучше ожиданий."),
            _w("choice", "/tʃɔɪs/", "выбор", "noun", "You have a choice between two times.", "У тебя выбор из двух времён."),
            _w("opinion", "/əˈpɪn.jən/", "мнение", "noun", "In my opinion the ending is weak.", "На мой взгляд, концовка слабая."),
            _w("fact", "/fækt/", "факт", "noun", "Check each fact before you publish.", "Проверь каждый факт перед публикацией."),
            _w("detail", "/ˈdiː.teɪl/", "деталь", "noun", "One missing detail changed the story.", "Одна пропущенная деталь изменила историю."),
            _w("example", "/ɪɡˈzɑːm.pəl/", "пример", "noun", "Give one example from your own day.", "Приведи один пример из своего дня."),
            _w("problem", "/ˈprɒb.ləm/", "проблема", "noun", "The problem is the late start, not the task.", "Проблема в позднем старте, а не в задаче."),
            _w("idea", "/aɪˈdɪə/", "идея", "noun", "A simple idea fixed the layout.", "Простая идея исправила вёрстку."),
        ],
    ),
    _topic(
        "appearance-style",
        "Внешность и стиль",
        "Как описать человека: рост, волосы, одежда, общее впечатление.",
        "B1",
        [
            _w("tall", "/tɔːl/", "высокий", "adjective", "Her brother is taller than the doorway.", "Её брат выше дверного проёма."),
            _w("short", "/ʃɔːt/", "низкий; короткий", "adjective", "He prefers short hair in summer.", "Летом он предпочитает короткие волосы."),
            _w("slim", "/slɪm/", "стройный", "adjective", "A slim envelope fitted in the book.", "Тонкий конверт поместился в книгу."),
            _w("curly", "/ˈkɜː.li/", "кудрявый", "adjective", "Curly hair needs a different brush.", "Кудрявым волосам нужна другая щётка."),
            _w("blonde", "/blɒnd/", "светловолосый", "adjective", "The blonde child wore a red coat.", "Светловолосый ребёнок был в красном пальто."),
            _w("beard", "/bɪəd/", "борода", "noun", "He grew a short beard last winter.", "Прошлой зимой он отрастил короткую бороду."),
            _w("freckles", "/ˈfrek.əlz/", "веснушки", "noun", "Freckles show more after a week in the sun.", "Веснушки заметнее после недели на солнце."),
            _w("wrinkles", "/ˈrɪŋ.kəlz/", "морщины", "noun", "Laugh lines are just soft wrinkles.", "Морщинки смеха — просто мягкие складки."),
            _w("elegant", "/ˈel.ɪ.ɡənt/", "элегантный", "adjective", "An elegant coat changed the whole look.", "Элегантное пальто изменило весь вид."),
            _w("casual", "/ˈkæʒ.ju.əl/", "повседневный", "adjective", "The office is casual on Fridays.", "По пятницам в офисе повседневный стиль."),
            _w("neat", "/niːt/", "аккуратный", "adjective", "A neat desk helps her start faster.", "Аккуратный стол помогает ей быстрее начать."),
            _w("messy", "/ˈmes.i/", "неопрятный", "adjective", "The messy pile hid the keys.", "Неопрятная стопка спрятала ключи."),
            _w("pale", "/peɪl/", "бледный", "adjective", "He looked pale after the long flight.", "После долгого рейса он выглядел бледным."),
            _w("tanned", "/tænd/", "загорелый", "adjective", "Tanned skin made the white shirt brighter.", "На загорелой коже белая рубашка казалась ярче."),
            _w("handsome", "/ˈhæn.səm/", "красивый (о мужчине)", "adjective", "The poster showed a handsome actor.", "На постере был красивый актёр."),
            _w("pretty", "/ˈprɪt.i/", "милый, хорошенький", "adjective", "A pretty lamp sat in the window.", "На окне стояла милая лампа."),
            _w("average", "/ˈæv.ər.ɪdʒ/", "обычный, средний", "adjective", "He is of average height.", "У него средний рост."),
            _w("muscular", "/ˈmʌs.kjə.lə/", "мускулистый", "adjective", "Years of swimming made her shoulders muscular.", "Годы плавания сделали её плечи мускулистыми."),
            _w("dyed", "/daɪd/", "окрашенный", "adjective", "Dyed hair faded after the holiday.", "Окрашенные волосы выцвели после отпуска."),
            _w("fringe", "/frɪndʒ/", "чёлка", "noun", "She cut a short fringe in March.", "В марте она сделала короткую чёлку."),
            _w("outfit", "/ˈaʊt.fɪt/", "наряд, комплект", "noun", "The outfit is simple but neat.", "Наряд простой, но аккуратный."),
            _w("look", "/lʊk/", "внешний вид", "noun", "The new look is quieter than before.", "Новый вид спокойнее, чем раньше."),
        ],
    ),
    _topic(
        "holidays-culture",
        "Праздники и обычаи",
        "Слова про торжества, подарки, приглашения и традиции.",
        "B1",
        [
            _w("festival", "/ˈfes.tɪ.vəl/", "фестиваль", "noun", "The street festival lasts three days.", "Уличный фестиваль длится три дня."),
            _w("parade", "/pəˈreɪd/", "парад", "noun", "The parade starts near the river.", "Парад начинается у реки."),
            _w("gift", "/ɡɪft/", "подарок", "noun", "A handwritten note came with the gift.", "К подарку приложили записку от руки."),
            _w("tradition", "/trəˈdɪʃ.ən/", "традиция", "noun", "The tradition is to share bread first.", "По традиции сначала делят хлеб."),
            _w("firework", "/ˈfaɪə.wɜːk/", "фейерверк", "noun", "The first firework rose above the square.", "Первый фейерверк поднялся над площадью."),
            _w("carnival", "/ˈkɑː.nɪ.vəl/", "карнавал", "noun", "Carnival masks filled the market.", "Карнавальные маски заполнили рынок."),
            _w("wedding", "/ˈwed.ɪŋ/", "свадьба", "noun", "The wedding was small and quiet.", "Свадьба была маленькой и тихой."),
            _w("funeral", "/ˈfjuː.nər.əl/", "похороны", "noun", "The funeral took place on a grey morning.", "Похороны прошли серым утром."),
            _w("birthday", "/ˈbɜːθ.deɪ/", "день рождения", "noun", "Her birthday falls on a Monday this year.", "В этом году её день рождения в понедельник."),
            _w("anniversary", "/ˌæn.ɪˈvɜː.sər.i/", "годовщина", "noun", "They marked the anniversary with a walk.", "Годовщину они отметили прогулкой."),
            _w("toast", "/təʊst/", "тост", "noun", "He raised a short toast to the hosts.", "Он произнёс короткий тост за хозяев."),
            _w("costume", "/ˈkɒs.tʃuːm/", "костюм", "noun", "The costume was homemade and bright.", "Костюм был самодельным и ярким."),
            _w("decoration", "/ˌdek.əˈreɪ.ʃən/", "украшение", "noun", "Paper decorations hung from the ceiling.", "Бумажные украшения висели с потолка."),
            _w("ceremony", "/ˈser.ɪ.mə.ni/", "церемония", "noun", "The ceremony lasted less than an hour.", "Церемония длилась меньше часа."),
            _w("invitation", "/ˌɪn.vɪˈteɪ.ʃən/", "приглашение", "noun", "The invitation arrived a week late.", "Приглашение пришло на неделю позже."),
            _w("custom", "/ˈkʌs.təm/", "обычай", "noun", "A local custom is to remove shoes indoors.", "Местный обычай — снимать обувь в доме."),
            _w("holiday", "/ˈhɒl.ə.deɪ/", "праздник; отпуск", "noun", "The public holiday emptied the office.", "В государственный праздник офис опустел."),
            _w("celebration", "/ˌsel.əˈbreɪ.ʃən/", "празднование", "noun", "The celebration stayed indoors because of rain.", "Из-за дождя празднование прошло в помещении."),
            _w("gathering", "/ˈɡæð.ər.ɪŋ/", "сбор людей", "noun", "A small gathering filled the kitchen.", "Небольшой сбор заполнил кухню."),
            _w("hostess", "/ˈhəʊ.stəs/", "хозяйка", "noun", "The hostess poured tea for everyone.", "Хозяйка налила всем чай."),
            _w("firework display", "/ˈfaɪə.wɜːk dɪˌspleɪ/", "салют", "noun", "The firework display started at ten.", "Салют начался в десять."),
            _w("public holiday", "/ˌpʌb.lɪk ˈhɒl.ə.deɪ/", "выходной день", "noun", "Banks close on a public holiday.", "Банки закрыты в официальный выходной."),
        ],
    ),
    _topic(
        "science-everyday",
        "Наука вокруг нас",
        "Базовый научный словарь B1: энергия, клетка, опыт, измерение.",
        "B1",
        [
            _w("gravity", "/ˈɡræv.ə.ti/", "гравитация", "noun", "Gravity pulls the water down the pipe.", "Гравитация тянет воду вниз по трубе."),
            _w("energy", "/ˈen.ə.dʒi/", "энергия", "noun", "The lamp uses less energy than before.", "Лампа тратит меньше энергии, чем раньше."),
            _w("atom", "/ˈæt.əm/", "атом", "noun", "An atom is far smaller than a cell.", "Атом гораздо меньше клетки."),
            _w("molecule", "/ˈmɒl.ɪ.kjuːl/", "молекула", "noun", "A water molecule has three atoms.", "В молекуле воды три атома."),
            _w("microscope", "/ˈmaɪ.krə.skəʊp/", "микроскоп", "noun", "The microscope showed tiny crystals.", "Микроскоп показал крошечные кристаллы."),
            _w("laboratory", "/ləˈbɒr.ə.tər.i/", "лаборатория", "noun", "The laboratory stays locked after six.", "Лаборатория закрыта после шести."),
            _w("chemical", "/ˈkem.ɪ.kəl/", "химический", "adjective", "A chemical change is not always visible.", "Химическое изменение не всегда видно."),
            _w("magnet", "/ˈmæɡ.nət/", "магнит", "noun", "The magnet held the notes on the fridge.", "Магнит держал записки на холодильнике."),
            _w("circuit", "/ˈsɜː.kɪt/", "цепь", "noun", "A broken circuit stopped the lamp.", "Разорванная цепь погасила лампу."),
            _w("planet", "/ˈplæn.ɪt/", "планета", "noun", "The model shows each planet to scale.", "Модель показывает каждую планету в масштабе."),
            _w("orbit", "/ˈɔː.bɪt/", "орбита", "noun", "The moon's orbit is not a perfect circle.", "Орбита Луны — не идеальный круг."),
            _w("cell", "/sel/", "клетка", "noun", "Each cell needs a thin wall.", "Каждой клетке нужна тонкая стенка."),
            _w("virus", "/ˈvaɪə.rəs/", "вирус", "noun", "The virus spread faster in crowded rooms.", "Вирус быстрее распространялся в тесных комнатах."),
            _w("bacteria", "/bækˈtɪə.ri.ə/", "бактерии", "noun", "Some bacteria help us digest food.", "Некоторые бактерии помогают переваривать еду."),
            _w("evolution", "/ˌiː.vəˈluː.ʃən/", "эволюция", "noun", "The chapter on evolution is short.", "Глава про эволюцию короткая."),
            _w("formula", "/ˈfɔː.mjə.lə/", "формула", "noun", "Write the formula before the numbers.", "Сначала запиши формулу, потом числа."),
            _w("measurement", "/ˈmeʒ.ə.mənt/", "измерение", "noun", "One measurement was clearly wrong.", "Одно измерение явно ошибочное."),
            _w("scale", "/skeɪl/", "шкала; масштаб", "noun", "The map scale is one to twenty thousand.", "Масштаб карты — один к двадцати тысячам."),
            _w("solid", "/ˈsɒl.ɪd/", "твёрдое тело", "noun", "Ice is water in solid form.", "Лёд — это вода в твёрдой форме."),
            _w("liquid", "/ˈlɪk.wɪd/", "жидкость", "noun", "The liquid must stay in a closed jar.", "Жидкость должна стоять в закрытой банке."),
            _w("gas", "/ɡæs/", "газ", "noun", "The gas escaped through a tiny hole.", "Газ вышел через крошечное отверстие."),
        ],
    ),
    _topic(
        "arts-culture",
        "Искусство и культура",
        "Выставка, роман, репетиция, жанр и другие слова для разговора об искусстве.",
        "B2",
        [
            _w("exhibition", "/ˌek.sɪˈbɪʃ.ən/", "выставка", "noun", "The exhibition closes on Sunday night.", "Выставка закрывается в воскресенье вечером."),
            _w("sculpture", "/ˈskʌlp.tʃə/", "скульптура", "noun", "A bronze sculpture stands in the courtyard.", "Во дворе стоит бронзовая скульптура."),
            _w("novel", "/ˈnɒv.əl/", "роман", "noun", "The novel is short but dense.", "Роман короткий, но плотный."),
            _w("poetry", "/ˈpəʊ.ə.tri/", "поэзия", "noun", "She reads poetry on the train.", "Она читает поэзию в поезде."),
            _w("rehearsal", "/rɪˈhɜː.səl/", "репетиция", "noun", "The rehearsal ran later than planned.", "Репетиция закончилась позже, чем планировали."),
            _w("audience", "/ˈɔː.di.əns/", "публика", "noun", "The audience stayed quiet until the last note.", "Публика молчала до последней ноты."),
            _w("critic", "/ˈkrɪt.ɪk/", "критик", "noun", "One critic praised the lighting, not the plot.", "Один критик хвалил свет, а не сюжет."),
            _w("masterpiece", "/ˈmɑː.stə.piːs/", "шедевр", "noun", "The late painting is not a masterpiece.", "Поздняя картина — не шедевр."),
            _w("genre", "/ˈʒɒn.rə/", "жанр", "noun", "The film mixes two genres on purpose.", "Фильм нарочно смешивает два жанра."),
            _w("plot", "/plɒt/", "сюжет", "noun", "The plot thins after the second chapter.", "После второй главы сюжет редеет."),
            _w("metaphor", "/ˈmet.ə.fɔː/", "метафора", "noun", "The metaphor compares time to a river.", "Метафора сравнивает время с рекой."),
            _w("orchestra", "/ˈɔː.kɪ.strə/", "оркестр", "noun", "The orchestra tuned for several minutes.", "Оркестр несколько минут настраивался."),
            _w("gallery", "/ˈɡæl.ər.i/", "галерея", "noun", "The gallery is free on the first Thursday.", "В первый четверг вход в галерею бесплатный."),
            _w("premiere", "/ˈprem.ieə/", "премьера", "noun", "Tickets for the premiere sold out.", "Билеты на премьеру закончились."),
            _w("curator", "/kjʊəˈreɪ.tə/", "куратор", "noun", "The curator wrote a short wall text.", "Куратор написал короткий текст для стены."),
            _w("canvas", "/ˈkæn.vəs/", "холст", "noun", "Blue paint still covers the canvas edge.", "Край холста всё ещё в синей краске."),
            _w("stanza", "/ˈstæn.zə/", "строфа", "noun", "The last stanza changes the tone.", "Последняя строфа меняет тон."),
            _w("satire", "/ˈsæt.aɪə/", "сатира", "noun", "The play is satire, not a news report.", "Пьеса — сатира, а не новостной репортаж."),
            _w("repertoire", "/ˈrep.ə.twɑː/", "репертуар", "noun", "Their repertoire includes two modern pieces.", "В репертуаре есть два современных произведения."),
            _w("sketch", "/sketʃ/", "набросок", "noun", "A quick sketch captured the street better.", "Быстрый набросок лучше передал улицу."),
            _w("composer", "/kəmˈpəʊ.zə/", "композитор", "noun", "The composer cut the last movement.", "Композитор убрал последнюю часть."),
            _w("venue", "/ˈven.juː/", "площадка", "noun", "The venue is too small for that choir.", "Площадка слишком мала для этого хора."),
        ],
    ),
    _topic(
        "academic-verbs",
        "Академические глаголы",
        "Глаголы эссе и докладов C1: утверждать, сопоставлять, оценивать, подразумевать.",
        "C1",
        [
            _w("argue", "/ˈɑː.ɡjuː/", "утверждать, доказывать", "verb", "The authors argue that the sample is too small.", "Авторы утверждают, что выборка слишком мала."),
            _w("claim", "/kleɪm/", "заявлять", "verb", "They claim the drop is seasonal.", "Они заявляют, что спад сезонный."),
            _w("demonstrate", "/ˈdem.ən.streɪt/", "показывать, демонстрировать", "verb", "The chart demonstrates a steady decline.", "График демонстрирует устойчивое снижение."),
            _w("illustrate", "/ˈɪl.ə.streɪt/", "иллюстрировать", "verb", "One case illustrates the wider pattern.", "Один случай иллюстрирует более широкую закономерность."),
            _w("outline", "/ˈaʊt.laɪn/", "наметить в общих чертах", "verb", "Outline the method in one paragraph.", "Изложи метод в одном абзаце."),
            _w("summarise", "/ˈsʌm.ər.aɪz/", "резюмировать", "verb", "Summarise the findings without extra comment.", "Резюмируй выводы без лишних комментариев."),
            _w("evaluate", "/ɪˈvæl.ju.eɪt/", "оценивать", "verb", "Evaluate the sources before you cite them.", "Оцени источники, прежде чем на них ссылаться."),
            _w("assess", "/əˈses/", "оценивать (измерять)", "verb", "They assess risk with a simple scale.", "Они оценивают риск по простой шкале."),
            _w("interpret", "/ɪnˈtɜː.prɪt/", "толковать", "verb", "How we interpret silence depends on context.", "Как мы толкуем молчание, зависит от контекста."),
            _w("contrast", "/kənˈtrɑːst/", "противопоставлять", "verb", "Contrast the two models in the next section.", "Противопоставь две модели в следующем разделе."),
            _w("emphasise", "/ˈem.fə.saɪz/", "подчёркивать", "verb", "The report emphasises local data.", "Доклад подчёркивает локальные данные."),
            _w("imply", "/ɪmˈplaɪ/", "подразумевать", "verb", "The title implies a stronger conclusion.", "Заголовок подразумевает более сильный вывод."),
            _w("assume", "/əˈsjuːm/", "предполагать", "verb", "Do not assume the reader knows the town.", "Не предполагай, что читатель знает этот город."),
            _w("conclude", "/kənˈkluːd/", "делать вывод", "verb", "We conclude that the delay was avoidable.", "Мы заключаем, что задержки можно было избежать."),
            _w("acknowledge", "/əkˈnɒl.ɪdʒ/", "признавать", "verb", "The paper acknowledges a small sample.", "Статья признаёт небольшую выборку."),
            _w("challenge", "/ˈtʃæl.ɪndʒ/", "оспаривать", "verb", "Later studies challenge this reading.", "Более поздние работы оспаривают такое прочтение."),
            _w("undermine", "/ˌʌn.dəˈmaɪn/", "подрывать", "verb", "One missing date undermines the timeline.", "Одна пропущенная дата подрывает хронологию."),
            _w("reinforce", "/ˌriː.ɪnˈfɔːs/", "усиливать", "verb", "New interviews reinforce the first finding.", "Новые интервью усиливают первый вывод."),
            _w("constitute", "/ˈkɒn.stɪ.tʃuːt/", "составлять", "verb", "These three cases constitute the core set.", "Эти три случая составляют ядро набора."),
            _w("yield", "/jiːld/", "давать (результат)", "verb", "The second test yielded a clearer signal.", "Второй тест дал более ясный сигнал."),
            _w("omit", "/əˈmɪt/", "опускать", "verb", "Omit details that do not change the claim.", "Опусти детали, которые не меняют утверждение."),
            _w("refine", "/rɪˈfaɪn/", "уточнять", "verb", "They refined the question after the pilot.", "Они уточнили вопрос после пилотного этапа."),
        ],
    ),
    _topic(
        "formal-register",
        "Формальный стиль",
        "Лексика писем, протоколов и служебных текстов C1.",
        "C1",
        [
            _w("regarding", "/rɪˈɡɑː.dɪŋ/", "касательно", "preposition", "I am writing regarding the delayed shipment.", "Пишу касательно задержанной поставки."),
            _w("furthermore", "/ˌfɜː.ðəˈmɔː/", "кроме того", "adverb", "Furthermore, the schedule leaves no spare day.", "Кроме того, в расписании нет запасного дня."),
            _w("nevertheless", "/ˌnev.ə.ðəˈles/", "тем не менее", "adverb", "The room is small; nevertheless it works.", "Комната маленькая; тем не менее она подходит."),
            _w("whereas", "/weərˈæz/", "тогда как", "conjunction", "Weekdays are busy, whereas Sundays are quiet.", "Будни загружены, тогда как воскресенья тихие."),
            _w("albeit", "/ɔːlˈbiː.ɪt/", "хотя и", "conjunction", "The plan is clear, albeit ambitious.", "План ясный, хотя и амбициозный."),
            _w("subsequently", "/ˈsʌb.sɪ.kwənt.li/", "впоследствии", "adverb", "The draft was cut and subsequently rewritten.", "Черновик сократили и впоследствии переписали."),
            _w("accordingly", "/əˈkɔː.dɪŋ.li/", "соответственно", "adverb", "Demand rose; we increased stock accordingly.", "Спрос вырос; мы соответственно увеличили запас."),
            _w("correspondence", "/ˌkɒr.ɪˈspɒn.dəns/", "переписка", "noun", "Keep the correspondence in one folder.", "Храни переписку в одной папке."),
            _w("inquiry", "/ɪnˈkwaɪə.ri/", "запрос", "noun", "Your inquiry will receive a reply this week.", "На ваш запрос ответят на этой неделе."),
            _w("attachment", "/əˈtætʃ.mənt/", "вложение", "noun", "The attachment is a two-page summary.", "Вложение — краткое изложение на две страницы."),
            _w("clarification", "/ˌklær.ɪ.fɪˈkeɪ.ʃən/", "уточнение", "noun", "We need clarification on the start date.", "Нам нужно уточнение даты начала."),
            _w("extension", "/ɪkˈsten.ʃən/", "продление", "noun", "They granted a one-week extension.", "Они дали продление на одну неделю."),
            _w("proposal", "/prəˈpəʊ.zəl/", "предложение, заявка", "noun", "The proposal is only four pages long.", "Заявка всего на четыре страницы."),
            _w("agenda", "/əˈdʒen.də/", "повестка", "noun", "Add the budget to tomorrow's agenda.", "Добавь бюджет в завтрашнюю повестку."),
            _w("stakeholder", "/ˈsteɪkˌhəʊl.də/", "заинтересованная сторона", "noun", "Each stakeholder received the same brief.", "Каждая сторона получила одно и то же резюме."),
            _w("compliance", "/kəmˈplaɪ.əns/", "соблюдение норм", "noun", "Compliance with the new rule starts in May.", "Соблюдение нового правила начинается в мае."),
            _w("waiver", "/ˈweɪ.və/", "отказ от требования", "noun", "A waiver is needed for late submission.", "Для поздней сдачи нужен официальный отказ от срока."),
            _w("liaison", "/liˈeɪ.zɒn/", "связующее лицо", "noun", "She acts as liaison between the two teams.", "Она связующее лицо между двумя командами."),
            _w("precedent", "/ˈpres.ɪ.dənt/", "прецедент", "noun", "There is no recent precedent for this fee.", "Недавнего прецедента для этого сбора нет."),
            _w("hereby", "/ˌhɪəˈbaɪ/", "настоящим", "adverb", "I hereby confirm that the dates are correct.", "Настоящим подтверждаю, что даты верны."),
            _w("enclosed", "/ɪnˈkləʊzd/", "прилагаемый", "adjective", "Please find the enclosed copy of the form.", "Во вложении копия бланка."),
            _w("pending", "/ˈpen.dɪŋ/", "в ожидании", "adjective", "The request is still pending review.", "Запрос всё ещё ожидает проверки."),
        ],
    ),
    _topic(
        "precise-nuance",
        "Точные и нюансные слова",
        "Лексика C2 для более точной оценки: явный, зыбкий, повсеместный, двусмысленный.",
        "C2",
        [
            _w("ostensibly", "/ɒˈsten.sə.bli/", "якобы, внешне", "adverb", "The change is ostensibly minor.", "Изменение внешне кажется мелким."),
            _w("equivocal", "/ɪˈkwɪv.ə.kəl/", "двусмысленный", "adjective", "The reply was polite but equivocal.", "Ответ был вежливым, но двусмысленным."),
            _w("salient", "/ˈseɪ.li.ənt/", "существенный, бросающийся в глаза", "adjective", "The salient point is the missing date.", "Существенный момент — пропущенная дата."),
            _w("tenuous", "/ˈten.ju.əs/", "шаткий", "adjective", "The link between the two events is tenuous.", "Связь между двумя событиями шаткая."),
            _w("pervasive", "/pəˈveɪ.sɪv/", "всепроникающий", "adjective", "A pervasive smell of paint filled the hall.", "В зале стоял всепроникающий запах краски."),
            _w("idiosyncratic", "/ˌɪd.i.ə.sɪŋˈkræt.ɪk/", "своеобразный", "adjective", "His notes use an idiosyncratic shorthand.", "В его записях своя своеобразная стенография."),
            _w("ubiquitous", "/juːˈbɪk.wɪ.təs/", "повсеместный", "adjective", "Plastic bags are still ubiquitous here.", "Пластиковые пакеты здесь всё ещё повсеместны."),
            _w("ephemeral", "/ɪˈfem.ər.əl/", "мимолетный", "adjective", "The fame of the clip was ephemeral.", "Известность ролика оказалась мимолётной."),
            _w("pragmatic", "/præɡˈmæt.ɪk/", "прагматичный", "adjective", "A pragmatic fix is better than a perfect delay.", "Прагматичное решение лучше идеальной задержки."),
            _w("intrinsic", "/ɪnˈtrɪn.zɪk/", "внутренне присущий", "adjective", "Curiosity is intrinsic to good research.", "Любопытство внутренне присуще хорошему исследованию."),
            _w("extrinsic", "/ekˈstrɪn.sɪk/", "внешний", "adjective", "The delay had an extrinsic cause: a strike.", "У задержки была внешняя причина: забастовка."),
            _w("tacit", "/ˈtæs.ɪt/", "подразумеваемый", "adjective", "There was a tacit agreement not to interrupt.", "Была подразумеваемая договорённость не перебивать."),
            _w("overt", "/əʊˈvɜːt/", "явный", "adjective", "The advert makes an overt political claim.", "Реклама делает явное политическое заявление."),
            _w("covert", "/ˈkəʊ.vɜːt/", "скрытый", "adjective", "Covert pressure shaped the final vote.", "Скрытое давление повлияло на итоговое голосование."),
            _w("ambiguous", "/æmˈbɪɡ.ju.əs/", "неоднозначный", "adjective", "The last sentence is deliberately ambiguous.", "Последнее предложение намеренно неоднозначно."),
            _w("unequivocal", "/ˌʌn.ɪˈkwɪv.ə.kəl/", "однозначный", "adjective", "The board gave an unequivocal no.", "Совет дал однозначный отказ."),
            _w("concomitant", "/kənˈkɒm.ɪ.tənt/", "сопутствующий", "adjective", "Growth brought concomitant traffic problems.", "Рост принёс сопутствующие транспортные проблемы."),
            _w("vicarious", "/vɪˈkeə.ri.əs/", "через чужой опыт", "adjective", "Travel films offer only vicarious adventure.", "Фильмы о путешествиях дают лишь чужое приключение."),
            _w("paucity", "/ˈpɔː.sə.ti/", "нехватка", "noun", "A paucity of local data weakens the claim.", "Нехватка местных данных ослабляет утверждение."),
            _w("plethora", "/ˈpleθ.ər.ə/", "изобилие", "noun", "A plethora of options slowed the choice.", "Изобилие вариантов замедлило выбор."),
            _w("notwithstanding", "/ˌnɒt.wɪθˈstænd.ɪŋ/", "несмотря на", "preposition", "Notwithstanding the rain, the walk continued.", "Несмотря на дождь, прогулка продолжилась."),
            _w("sundry", "/ˈsʌn.dri/", "различный, разный", "adjective", "Sundry small costs added up quickly.", "Разные мелкие расходы быстро сложились."),
        ],
    ),
]
