"""Incremental CEFR vocab: extra words for existing topics plus new themes."""

from app.seed.vocab import _topic, _w


MORE_WORDS_BY_SLUG = {
    "everyday-objects": [
        _w("carpet", "/ˈkɑː.pɪt/", "ковёр", "noun", "The cat left hair on the carpet.", "Кот оставил шерсть на ковре."),
        _w("candle", "/ˈkæn.dəl/", "свеча", "noun", "Light a candle if the power goes out.", "Зажги свечу, если пропадёт свет."),
        _w("vase", "/vɑːz/", "ваза", "noun", "Put the tulips in a tall vase.", "Поставь тюльпаны в высокую вазу."),
        _w("charger", "/ˈtʃɑː.dʒə/", "зарядка", "noun", "I left the charger by the bed.", "Я оставил зарядку у кровати."),
        _w("mug", "/mʌɡ/", "кружка", "noun", "This mug keeps the tea warm longer.", "Эта кружка дольше держит чай тёплым."),
        _w("broom", "/bruːm/", "метла", "noun", "The broom stands behind the door.", "Метла стоит за дверью."),
        _w("envelope", "/ˈen.və.ləʊp/", "конверт", "noun", "Write the address on the envelope.", "Напиши адрес на конверте."),
        _w("tray", "/treɪ/", "поднос", "noun", "Bring the cups on a tray.", "Принеси чашки на подносе."),
        _w("hanger", "/ˈhæŋ.ə/", "вешалка", "noun", "Hang the shirt on a hanger.", "Повесь рубашку на вешалку."),
        _w("bin", "/bɪn/", "мусорное ведро", "noun", "The bin in the kitchen is already full.", "Ведро на кухне уже полное."),
    ],
    "family-people": [
        _w("sibling", "/ˈsɪb.lɪŋ/", "брат или сестра", "noun", "Each sibling chose a different city.", "Каждый из братьев и сестёр выбрал другой город."),
        _w("spouse", "/spaʊs/", "супруг, супруга", "noun", "Please write your spouse's full name.", "Укажите полное имя супруга или супруги."),
        _w("widow", "/ˈwɪd.əʊ/", "вдова", "noun", "The widow kept his letters in a box.", "Вдова хранила его письма в коробке."),
        _w("stranger", "/ˈstreɪn.dʒə/", "незнакомец", "noun", "A stranger asked for the next stop.", "Незнакомец спросил про следующую остановку."),
        _w("crowd", "/kraʊd/", "толпа", "noun", "A crowd waited outside the cinema.", "Толпа ждала у кинотеатра."),
        _w("generation", "/ˌdʒen.əˈreɪ.ʃən/", "поколение", "noun", "The younger generation prefers trains.", "Младшее поколение чаще выбирает поезда."),
        _w("ancestor", "/ˈæn.se.stə/", "предок", "noun", "One ancestor built this stone wall.", "Один из предков сложил эту каменную стену."),
        _w("fiancé", "/fiˈɒn.seɪ/", "жених", "noun", "Her fiancé arrived on the last train.", "Её жених приехал на последнем поезде."),
        _w("in-laws", "/ˈɪn.lɔːz/", "родственники супруга", "noun", "His in-laws live two streets away.", "Его родственники со стороны жены живут через две улицы."),
        _w("orphan", "/ˈɔː.fən/", "сирота", "noun", "The story follows an orphan in the city.", "История про сироту в большом городе."),
    ],
    "food-drink": [
        _w("cereal", "/ˈsɪə.ri.əl/", "хлопья", "noun", "There is no milk left for the cereal.", "Для хлопьев не осталось молока."),
        _w("yoghurt", "/ˈjɒɡ.ət/", "йогурт", "noun", "I eat yoghurt with berries at noon.", "В полдень я ем йогурт с ягодами."),
        _w("mushroom", "/ˈmʌʃ.ruːm/", "гриб", "noun", "Slice the mushroom for the omelette.", "Нарежь гриб для омлета."),
        _w("garlic", "/ˈɡɑː.lɪk/", "чеснок", "noun", "One clove of garlic is enough.", "Одного зубчика чеснока достаточно."),
        _w("lemon", "/ˈlem.ən/", "лимон", "noun", "Add a slice of lemon to the tea.", "Добавь в чай дольку лимона."),
        _w("flour", "/flaʊə/", "мука", "noun", "The flour must be dry and white.", "Мука должна быть сухой и белой."),
        _w("oil", "/ɔɪl/", "масло растительное", "noun", "Heat a little oil in the pan.", "Разогрей немного масла на сковороде."),
        _w("beans", "/biːnz/", "фасоль, бобы", "noun", "These beans need twenty minutes.", "Этой фасоли нужно двадцать минут."),
        _w("herbs", "/hɜːbz/", "зелень, травы", "noun", "Fresh herbs change the soup.", "Свежая зелень меняет вкус супа."),
        _w("vinegar", "/ˈvɪn.ɪ.ɡə/", "уксус", "noun", "A drop of vinegar brightens the salad.", "Капля уксуса делает салат ярче."),
    ],
    "travel-city": [
        _w("harbour", "/ˈhɑː.bə/", "гавань", "noun", "Fishing boats filled the harbour.", "Рыбацкие лодки заполнили гавань."),
        _w("terminal", "/ˈtɜː.mɪ.nəl/", "терминал", "noun", "Meet me in terminal two after landing.", "Встретимся в терминале два после посадки."),
        _w("visa", "/ˈviː.zə/", "виза", "noun", "The visa is valid for ninety days.", "Виза действует девяносто дней."),
        _w("customs", "/ˈkʌs.təmz/", "таможня", "noun", "Customs asked me to open the bag.", "На таможне попросили открыть сумку."),
        _w("cabin", "/ˈkæb.ɪn/", "салон; каюта", "noun", "The cabin lights dimmed after take-off.", "В салоне свет приглушили после взлёта."),
        _w("guidebook", "/ˈɡaɪd.bʊk/", "путеводитель", "noun", "The guidebook marks free walking tours.", "В путеводителе отмечены бесплатные прогулки."),
        _w("sightseeing", "/ˈsaɪtˌsiː.ɪŋ/", "осмотр достопримечательностей", "noun", "We kept sightseeing short in the heat.", "В жару мы сократили осмотр города."),
        _w("boulevard", "/ˈbuː.lə.vɑːd/", "бульвар", "noun", "Cafés line the wide boulevard.", "Кафе стоят вдоль широкого бульвара."),
        _w("embassy", "/ˈem.bə.si/", "посольство", "noun", "The embassy opens after a long weekend.", "Посольство открывается после длинных выходных."),
        _w("timetable", "/ˈtaɪmˌteɪ.bəl/", "расписание транспорта", "noun", "Check the ferry timetable on Sunday.", "В воскресенье проверь расписание парома."),
    ],
    "work-study": [
        _w("syllabus", "/ˈsɪl.ə.bəs/", "программа курса", "noun", "The syllabus lists every reading.", "В программе курса указано всё чтение."),
        _w("internship", "/ˈɪn.tɜːn.ʃɪp/", "стажировка", "noun", "Her internship lasts ten weeks.", "Её стажировка длится десять недель."),
        _w("supervisor", "/ˈsuː.pə.vaɪ.zə/", "научный руководитель; начальник", "noun", "Ask your supervisor before you change the title.", "Спроси руководителя, прежде чем менять название."),
        _w("vacancy", "/ˈveɪ.kən.si/", "вакансия", "noun", "A new vacancy appeared on Monday.", "В понедельник появилась новая вакансия."),
        _w("commute", "/kəˈmjuːt/", "дорога на работу", "noun", "The commute is shorter by bike.", "На велосипеде дорога на работу короче."),
        _w("resignation", "/ˌrez.ɪɡˈneɪ.ʃən/", "увольнение по собственному", "noun", "He handed in his resignation on Friday.", "В пятницу он подал заявление об уходе."),
        _w("workload", "/ˈwɜːk.ləʊd/", "нагрузка", "noun", "The workload doubles before exams.", "Перед экзаменами нагрузка удваивается."),
        _w("reference", "/ˈref.ər.əns/", "рекомендация", "noun", "She asked a former tutor for a reference.", "Она попросила бывшего преподавателя о рекомендации."),
        _w("enrol", "/ɪnˈrəʊl/", "записываться", "verb", "Enrol before the course fills up.", "Запишись, пока на курсе есть места."),
        _w("handout", "/ˈhænd.aʊt/", "раздаточный материал", "noun", "The handout summarises the lecture.", "Раздатка кратко повторяет лекцию."),
    ],
    "health-body": [
        _w("spine", "/spaɪn/", "позвоночник", "noun", "A soft chair is better for her spine.", "Мягкий стул лучше для её позвоночника."),
        _w("lung", "/lʌŋ/", "лёгкое", "noun", "Cold air made his lungs ache.", "От холодного воздуха у него заболели лёгкие."),
        _w("ambulance", "/ˈæm.bjə.ləns/", "скорая помощь", "noun", "An ambulance stopped outside the shop.", "Скорая остановилась у магазина."),
        _w("plaster", "/ˈplɑː.stə/", "пластырь", "noun", "Put a plaster on the small cut.", "Наклей пластырь на небольшой порез."),
        _w("nausea", "/ˈnɔː.si.ə/", "тошнота", "noun", "The motion of the bus caused nausea.", "От движения автобуса началась тошнота."),
        _w("checkup", "/ˈtʃek.ʌp/", "осмотр, проверка", "noun", "Book a checkup if the pain returns.", "Запишись на осмотр, если боль вернётся."),
        _w("swelling", "/ˈswel.ɪŋ/", "отёк", "noun", "The swelling went down overnight.", "Отёк спал за ночь."),
        _w("crutch", "/krʌtʃ/", "костыль", "noun", "He used one crutch for a week.", "Он неделю ходил с одним костылём."),
        _w("immune", "/ɪˈmjuːn/", "иммунный", "adjective", "Sleep helps the immune system.", "Сон поддерживает иммунную систему."),
        _w("scar", "/skɑː/", "шрам", "noun", "A thin scar remains on her knee.", "На колене остался тонкий шрам."),
    ],
    "feelings-personality": [
        _w("gentle", "/ˈdʒen.təl/", "мягкий, кроткий", "adjective", "A gentle answer calmed the child.", "Мягкий ответ успокоил ребёнка."),
        _w("witty", "/ˈwɪt.i/", "остроумный", "adjective", "Her witty reply ended the argument.", "Её остроумный ответ закончил спор."),
        _w("arrogant", "/ˈær.ə.ɡənt/", "высокомерный", "adjective", "The arrogant comment spoiled the meeting.", "Высокомерная реплика испортила совещание."),
        _w("shy", "/ʃaɪ/", "застенчивый", "adjective", "He is shy with large groups.", "В больших компаниях он застенчив."),
        _w("generous", "/ˈdʒen.ər.əs/", "щедрый", "adjective", "A generous neighbour shared the tools.", "Щедрый сосед поделился инструментами."),
        _w("cautious", "/ˈkɔː.ʃəs/", "осторожный", "adjective", "Be cautious on the icy steps.", "Будь осторожен на обледенелых ступеньках."),
        _w("sincere", "/sɪnˈsɪə/", "искренний", "adjective", "The apology sounded sincere.", "Извинение прозвучало искренне."),
        _w("restless", "/ˈrest.ləs/", "беспокойный", "adjective", "The restless class asked to go outside.", "Беспокойный класс просился на улицу."),
        _w("modest", "/ˈmɒd.ɪst/", "скромный", "adjective", "She gave a modest account of the win.", "Она скромно рассказала о победе."),
        _w("grumpy", "/ˈɡrʌm.pi/", "ворчливый", "adjective", "He gets grumpy before coffee.", "До кофе он становится ворчливым."),
    ],
    "nature-environment": [
        _w("cliff", "/klɪf/", "утес", "noun", "Do not stand too close to the cliff.", "Не стой слишком близко к утёсу."),
        _w("rainfall", "/ˈreɪn.fɔːl/", "осадки", "noun", "Rainfall was higher than last April.", "Осадков было больше, чем в прошлом апреле."),
        _w("wildfire", "/ˈwaɪld.faɪə/", "лесной пожар", "noun", "The wildfire jumped the dry riverbed.", "Пожар перекинулся через сухое русло."),
        _w("pesticide", "/ˈpes.tɪ.saɪd/", "пестицид", "noun", "They reduced pesticide use on the farm.", "На ферме сократили использование пестицидов."),
        _w("ozone", "/ˈəʊ.zəʊn/", "озон", "noun", "The ozone layer is thinner at the poles.", "Озоновый слой тоньше у полюсов."),
        _w("estuary", "/ˈes.tʃu.ə.ri/", "эстуарий", "noun", "Wading birds feed in the estuary.", "Кулики кормятся в эстуарии."),
        _w("fossil", "/ˈfɒs.əl/", "ископаемое", "noun", "A small fossil sat in the museum case.", "В витрине музея лежало небольшое ископаемое."),
        _w("peat", "/piːt/", "торф", "noun", "Burning peat releases stored carbon.", "Сжигание торфа выпускает накопленный углерод."),
        _w("hedge", "/hedʒ/", "живая изгородь", "noun", "Trim the hedge after nesting season.", "Подстригай изгородь после сезона гнездования."),
        _w("drought-resistant", "/ˈdraʊt rɪˌzɪs.tənt/", "засухоустойчивый", "adjective", "They planted drought-resistant grass.", "Они посадили засухоустойчивую траву."),
    ],
    "media-technology": [
        _w("firewall", "/ˈfaɪə.wɔːl/", "файрвол", "noun", "The firewall blocked the unknown file.", "Файрвол заблокировал неизвестный файл."),
        _w("malware", "/ˈmæl.weə/", "вредоносная программа", "noun", "The scan found no malware on the laptop.", "Проверка не нашла вредоносных программ."),
        _w("backup", "/ˈbæk.ʌp/", "резервная копия", "noun", "Make a backup before the update.", "Сделай резервную копию до обновления."),
        _w("bookmark", "/ˈbʊk.mɑːk/", "закладка", "noun", "Save a bookmark for the form.", "Сохрани закладку на эту форму."),
        _w("tab", "/tæb/", "вкладка", "noun", "Too many tabs slow the browser.", "Слишком много вкладок замедляют браузер."),
        _w("scroll", "/skrəʊl/", "прокручивать", "verb", "Scroll down to the second table.", "Прокрути вниз ко второй таблице."),
        _w("encryption", "/ɪnˈkrɪp.ʃən/", "шифрование", "noun", "Encryption protects the saved passwords.", "Шифрование защищает сохранённые пароли."),
        _w("cache", "/kæʃ/", "кэш", "noun", "Clear the cache if the page looks old.", "Очисти кэш, если страница выглядит устаревшей."),
        _w("thread", "/θred/", "ветка обсуждения", "noun", "The useful answer is later in the thread.", "Полезный ответ ниже в ветке."),
        _w("outage", "/ˈaʊ.tɪdʒ/", "сбой, отключение", "noun", "A short outage stopped the live stream.", "Короткий сбой остановил прямую трансляцию."),
    ],
    "business-money": [
        _w("turnover", "/ˈtɜːnˌəʊ.və/", "оборот", "noun", "Annual turnover rose after the move.", "Годовой оборот вырос после переезда."),
        _w("audit", "/ˈɔː.dɪt/", "аудит", "noun", "The audit found two missing receipts.", "Аудит нашёл два пропавших чека."),
        _w("subsidy", "/ˈsʌb.sɪ.di/", "субсидия", "noun", "A small subsidy kept the route open.", "Небольшая субсидия сохранила маршрут."),
        _w("franchise", "/ˈfræn.tʃaɪz/", "франшиза", "noun", "They bought a café franchise in Leeds.", "Они купили франшизу кафе в Лидсе."),
        _w("wholesale", "/ˈhəʊl.seɪl/", "оптовый", "adjective", "Wholesale prices fell in March.", "Оптовые цены упали в марте."),
        _w("retail", "/ˈriː.teɪl/", "розничный", "adjective", "Retail sales were quieter this week.", "Розничные продажи на этой неделе были тише."),
        _w("liquidity", "/lɪˈkwɪd.ə.ti/", "ликвидность", "noun", "Low liquidity made the sale urgent.", "Низкая ликвидность сделала продажу срочной."),
        _w("collateral", "/kəˈlæt.ər.əl/", "залог", "noun", "The van served as collateral for the loan.", "Фургон стал залогом по кредиту."),
        _w("overhead costs", "/ˈəʊ.və.hed kɒsts/", "накладные расходы", "noun", "Rent still dominates the overhead costs.", "Аренда по-прежнему главные накладные."),
        _w("break-even", "/ˌbreɪk ˈiː.vən/", "точка безубыточности", "noun", "They reached break-even in year two.", "Точки безубыточности они достигли на второй год."),
    ],
    "society-law": [
        _w("parliament", "/ˈpɑː.lə.mənt/", "парламент", "noun", "Parliament returns after the recess.", "Парламент возвращается после каникул."),
        _w("mayor", "/meə/", "мэр", "noun", "The mayor opened the new library.", "Мэр открыл новую библиотеку."),
        _w("refugee", "/ˌref.jʊˈdʒiː/", "беженец", "noun", "The city housed refugee families in spare flats.", "Город поселил семьи беженцев в свободных квартирах."),
        _w("petition", "/pəˈtɪʃ.ən/", "петиция", "noun", "The petition collected two thousand names.", "Петиция собрала две тысячи подписей."),
        _w("sanction", "/ˈsæŋk.ʃən/", "санкция", "noun", "The new sanction hit fuel imports.", "Новая санкция затронула импорт топлива."),
        _w("appeal", "/əˈpiːl/", "апелляция", "noun", "They filed an appeal within ten days.", "Они подали апелляцию за десять дней."),
        _w("hearing", "/ˈhɪə.rɪŋ/", "слушание", "noun", "The hearing was postponed until June.", "Слушание отложили до июня."),
        _w("corruption", "/kəˈrʌp.ʃən/", "коррупция", "noun", "The report described local corruption.", "В докладе описали местную коррупцию."),
        _w("ban", "/bæn/", "запрет", "noun", "A night-time ban on lorries starts in May.", "Ночной запрет на грузовики начнётся в мае."),
        _w("asylum", "/əˈsaɪ.ləm/", "убежище", "noun", "She applied for asylum after the unrest.", "Она подала на убежище после беспорядков."),
    ],
    "academic-abstract": [
        _w("footnote", "/ˈfʊt.nəʊt/", "сноска", "noun", "The key number is hidden in a footnote.", "Ключевая цифра спрятана в сноске."),
        _w("appendix", "/əˈpen.dɪks/", "приложение", "noun", "Maps are in the appendix, not the chapter.", "Карты в приложении, а не в главе."),
        _w("rationale", "/ˌræʃ.əˈnɑːl/", "обоснование", "noun", "The rationale for the cut is unclear.", "Обоснование сокращения неясно."),
        _w("synthesis", "/ˈsɪn.θə.sɪs/", "синтез", "noun", "The last chapter is a short synthesis.", "Последняя глава — короткий синтез."),
        _w("criterion", "/kraɪˈtɪə.ri.ən/", "критерий", "noun", "Clarity is the first criterion.", "Ясность — первый критерий."),
        _w("overview", "/ˈəʊ.və.vjuː/", "обзор", "noun", "Start with a one-page overview.", "Начни с обзора на одну страницу."),
        _w("construct", "/ˈkɒn.strʌkt/", "конструкт", "noun", "Trust is treated as a social construct.", "Доверие рассматривают как социальный конструкт."),
        _w("typology", "/taɪˈpɒl.ə.dʒi/", "типология", "noun", "The typology splits towns into four groups.", "Типология делит города на четыре группы."),
        _w("limitation", "/ˌlɪm.ɪˈteɪ.ʃən/", "ограничение", "noun", "A small sample is a clear limitation.", "Малая выборка — явное ограничение."),
        _w("finding", "/ˈfaɪn.dɪŋ/", "вывод исследования", "noun", "The main finding is local, not national.", "Главный вывод локальный, а не общенациональный."),
    ],
    "clothes-weather": [
        _w("jumper", "/ˈdʒʌm.pə/", "джемпер", "noun", "Take a jumper for the evening.", "Возьми джемпер на вечер."),
        _w("socks", "/sɒks/", "носки", "noun", "Dry socks matter on a long walk.", "На длинной прогулке важны сухие носки."),
        _w("belt", "/belt/", "ремень", "noun", "This belt is one hole too tight.", "Этот ремень тесен на одну дырку."),
        _w("hood", "/hʊd/", "капюшон", "noun", "Pull the hood up before the rain.", "Накинь капюшон до дождя."),
        _w("fog", "/fɒɡ/", "туман", "noun", "Thick fog hid the far bank.", "Густой туман скрыл дальний берег."),
        _w("frost", "/frɒst/", "иней, мороз", "noun", "Morning frost covered the bicycle seat.", "Утренний иней покрыл седло велосипеда."),
        _w("thunder", "/ˈθʌn.də/", "гром", "noun", "Thunder followed a few seconds later.", "Гром раздался через несколько секунд."),
        _w("lightning", "/ˈlaɪt.nɪŋ/", "молния", "noun", "Lightning lit the empty field.", "Молния осветила пустое поле."),
        _w("drizzle", "/ˈdrɪz.əl/", "морось", "noun", "A light drizzle started at noon.", "В полдень началась лёгкая морось."),
        _w("sleeve", "/sliːv/", "рукав", "noun", "The sleeve is still wet from the rain.", "Рукав ещё мокрый от дождя."),
    ],
    "daily-routines": [
        _w("stretch", "/stretʃ/", "потягиваться", "verb", "Stretch before you sit at the desk.", "Потянись, прежде чем сесть за стол."),
        _w("pack", "/pæk/", "собирать вещи", "verb", "Pack the bag the night before.", "Собери сумку накануне вечером."),
        _w("unlock", "/ʌnˈlɒk/", "отпирать", "verb", "Unlock the side door, not the front.", "Открой боковую дверь, не парадную."),
        _w("fold", "/fəʊld/", "складывать", "verb", "Fold the shirts before they crease.", "Сложи рубашки, пока они не помялись."),
        _w("yawn", "/jɔːn/", "зевать", "verb", "I yawn more on dark mornings.", "В тёмные утра я чаще зеваю."),
        _w("tidy", "/ˈtaɪ.di/", "приводить в порядок", "verb", "Tidy the desk before you leave.", "Приведи стол в порядок, прежде чем уйти."),
        _w("lock", "/lɒk/", "запирать", "verb", "Lock the bicycle even for five minutes.", "Запирай велосипед даже на пять минут."),
        _w("unpack", "/ʌnˈpæk/", "распаковывать", "verb", "Unpack the food first, then the books.", "Сначала распакуй еду, потом книги."),
        _w("commute", "/kəˈmjuːt/", "ездить на работу", "verb", "I commute across the river each day.", "Каждый день я езжу на работу через реку."),
        _w("set off", "/ˌset ˈɒf/", "отправляться", "verb", "We set off before the traffic starts.", "Мы выезжаем до начала пробок."),
    ],
    "colours-time": [
        _w("orange", "/ˈɒr.ɪndʒ/", "оранжевый", "adjective", "An orange cone marks the wet paint.", "Оранжевый конус отмечает свежую краску."),
        _w("purple", "/ˈpɜː.pəl/", "фиолетовый", "adjective", "She chose a purple notebook this time.", "На этот раз она взяла фиолетовую тетрадь."),
        _w("brown", "/braʊn/", "коричневый", "adjective", "The brown envelope is from the bank.", "Коричневый конверт — из банка."),
        _w("pink", "/pɪŋk/", "розовый", "adjective", "Pink light filled the kitchen at dawn.", "На рассвете кухню залил розовый свет."),
        _w("dawn", "/dɔːn/", "рассвет", "noun", "The street is quiet at dawn.", "На рассвете на улице тихо."),
        _w("dusk", "/dʌsk/", "сумерки", "noun", "Bats appear just after dusk.", "Летучие мыши появляются сразу после сумерек."),
        _w("midnight", "/ˈmɪd.naɪt/", "полночь", "noun", "The last tram leaves before midnight.", "Последний трамвай уходит до полуночи."),
        _w("weekend", "/ˌwiːkˈend/", "выходные", "noun", "The museum is busier at the weekend.", "В выходные в музее люднее."),
        _w("fortnight", "/ˈfɔːt.naɪt/", "две недели", "noun", "The course lasts one fortnight.", "Курс длится две недели."),
        _w("calendar", "/ˈkæl.ən.də/", "календарь", "noun", "Mark the exam on the kitchen calendar.", "Отметь экзамен на кухонном календаре."),
    ],
    "home-rooms": [
        _w("chimney", "/ˈtʃɪm.ni/", "дымоход", "noun", "Smoke rose from the brick chimney.", "Из кирпичного дымохода шёл дым."),
        _w("loft", "/lɒft/", "мансарда", "noun", "The loft is too hot in August.", "В августе на мансарде слишком жарко."),
        _w("radiator", "/ˈreɪ.di.eɪ.tə/", "батарея", "noun", "The radiator in the hall stays cold.", "Батарея в коридоре остаётся холодной."),
        _w("doormat", "/ˈdɔː.mæt/", "коврик у двери", "noun", "Wipe your shoes on the doormat.", "Вытри обувь о коврик у двери."),
        _w("landing", "/ˈlæn.dɪŋ/", "площадка на лестнице", "noun", "Leave the parcels on the landing.", "Оставь посылки на лестничной площадке."),
        _w("skylight", "/ˈskaɪ.laɪt/", "мансардное окно", "noun", "Rain tapped the skylight all night.", "Дождь всю ночь стучал по мансардному окну."),
        _w("cellar", "/ˈsel.ə/", "погреб", "noun", "Wine and tools share the cellar.", "В погребе стоят вино и инструменты."),
        _w("windowsill", "/ˈwɪn.dəʊ.sɪl/", "подоконник", "noun", "A plant sits on the kitchen windowsill.", "На кухонном подоконнике стоит растение."),
        _w("spare room", "/ˌspeə ˈruːm/", "гостевая комната", "noun", "Guests sleep in the spare room.", "Гости спят в запасной комнате."),
        _w("driveway", "/ˈdraɪv.weɪ/", "подъезд к дому", "noun", "Do not block the narrow driveway.", "Не перекрывай узкий подъезд к дому."),
    ],
    "shopping-money-basic": [
        _w("trolley", "/ˈtrɒl.i/", "тележка", "noun", "Return the trolley to the shelter.", "Верни тележку под навес."),
        _w("till", "/tɪl/", "касса", "noun", "The till closed for a short count.", "Кассу закрыли на короткую сверку."),
        _w("barcode", "/ˈbɑː.kəʊd/", "штрихкод", "noun", "The barcode on the jar would not scan.", "Штрихкод на банке не считывался."),
        _w("voucher", "/ˈvaʊ.tʃə/", "ваучер, купон", "noun", "This voucher is valid until Friday.", "Этот купон действует до пятницы."),
        _w("loyalty", "/ˈlɔɪ.əl.ti/", "программа лояльности", "noun", "The loyalty card saves a little each week.", "Карта лояльности чуть экономит каждую неделю."),
        _w("wrapping", "/ˈræp.ɪŋ/", "упаковка", "noun", "Ask for plain wrapping, not a gift box.", "Попроси простую упаковку, не подарочную."),
        _w("stock", "/stɒk/", "товарный запас", "noun", "That size is out of stock today.", "Этого размера сегодня нет в наличии."),
        _w("fitting room", "/ˈfɪt.ɪŋ ruːm/", "примерочная", "noun", "The fitting room is behind the mirrors.", "Примерочная за зеркалами."),
        _w("refundable", "/rɪˈfʌn.də.bəl/", "с возвратом", "adjective", "The deposit is not refundable.", "Залог не возвращается."),
        _w("bargain bin", "/ˈbɑː.ɡɪn bɪn/", "корзина уценки", "noun", "Mugs in the bargain bin cost one pound.", "Кружки в корзине уценки стоят фунт."),
    ],
    "hobbies-sports": [
        _w("knitting", "/ˈnɪt.ɪŋ/", "вязание", "noun", "Knitting keeps her hands busy on the train.", "Вязание занимает ей руки в поезде."),
        _w("jogging", "/ˈdʒɒɡ.ɪŋ/", "лёгкий бег", "noun", "Jogging before breakfast is enough for him.", "Ему хватает лёгкого бега до завтрака."),
        _w("camping", "/ˈkæm.pɪŋ/", "кемпинг", "noun", "Camping by the lake needs a permit.", "Для кемпинга у озера нужно разрешение."),
        _w("fishing", "/ˈfɪʃ.ɪŋ/", "рыбалка", "noun", "Fishing here is better after rain.", "Здесь лучше ловить после дождя."),
        _w("pottery", "/ˈpɒt.ər.i/", "гончарное дело", "noun", "The pottery class uses local clay.", "На гончарном кружке берут местную глину."),
        _w("choir", "/kwaɪə/", "хор", "noun", "The choir practises on Wednesday nights.", "Хор репетирует по средам вечером."),
        _w("skate", "/skeɪt/", "кататься на коньках", "verb", "Children skate on the frozen pond.", "Дети катаются на замёрзшем пруду."),
        _w("collect", "/kəˈlekt/", "коллекционировать", "verb", "He collects old tram tickets.", "Он коллекционирует старые трамвайные билеты."),
        _w("board game", "/ˈbɔːd ɡeɪm/", "настольная игра", "noun", "We play one board game on Sundays.", "По воскресеньям мы играем в одну настольную игру."),
        _w("warm-up", "/ˈwɔːm.ʌp/", "разминка", "noun", "A short warm-up prevents sore knees.", "Короткая разминка бережёт колени."),
    ],
    "school-subjects": [
        _w("pencil", "/ˈpen.səl/", "карандаш", "noun", "A sharp pencil is better for maps.", "Для карт лучше остро заточенный карандаш."),
        _w("ruler", "/ˈruː.lə/", "линейка", "noun", "Use a ruler for the timeline.", "Для ленты времени возьми линейку."),
        _w("glue", "/ɡluː/", "клей", "noun", "The glue needs two minutes to set.", "Клею нужно две минуты, чтобы схватиться."),
        _w("canteen", "/kænˈtiːn/", "столовая", "noun", "The canteen closes after the second sitting.", "Столовая закрывается после второй смены."),
        _w("playground", "/ˈpleɪ.ɡraʊnd/", "площадка", "noun", "The playground is wet after the shower.", "Площадка мокрая после ливня."),
        _w("headteacher", "/ˌhedˈtiː.tʃə/", "директор школы", "noun", "The headteacher signed the trip letter.", "Директор подписал письмо о поездке."),
        _w("coursework", "/ˈkɔːs.wɜːk/", "курсовая работа", "noun", "Coursework is due the week after half-term.", "Курсовую нужно сдать на неделе после каникул."),
        _w("lab", "/læb/", "лаборатория", "noun", "Keep bags off the lab benches.", "Не кладите сумки на лабораторные столы."),
        _w("eraser", "/ɪˈreɪ.zə/", "ластик", "noun", "The eraser left a grey smudge.", "Ластик оставил серое пятно."),
        _w("detention", "/dɪˈten.ʃən/", "оставление после уроков", "noun", "Detention is in room four today.", "Оставление сегодня в четвёртом кабинете."),
    ],
    "restaurants-cooking": [
        _w("grill", "/ɡrɪl/", "гриль", "noun", "The grill needs a minute to heat.", "Грилю нужна минута, чтобы разогреться."),
        _w("dough", "/dəʊ/", "тесто", "noun", "Leave the dough to rise in a warm place.", "Оставь тесто подходить в тёплом месте."),
        _w("knead", "/niːd/", "месить", "verb", "Knead the dough until it feels smooth.", "Меси тесто, пока оно не станет гладким."),
        _w("napkin", "/ˈnæp.kɪn/", "салфетка", "noun", "A clean napkin sat beside each plate.", "Рядом с каждой тарелкой лежала чистая салфетка."),
        _w("leftover", "/ˈleftˌəʊ.və/", "остатки еды", "noun", "Leftover rice becomes tomorrow's lunch.", "Остатки риса станут завтрашним обедом."),
        _w("buffet", "/ˈbʊf.eɪ/", "шведский стол", "noun", "The hotel buffet opens at seven.", "Шведский стол в отеле открывается в семь."),
        _w("steam", "/stiːm/", "готовить на пару", "verb", "Steam the greens for four minutes.", "Готовь зелень на пару четыре минуты."),
        _w("corkscrew", "/ˈkɔːk.skruː/", "штопор", "noun", "The corkscrew is in the top drawer.", "Штопор в верхнем ящике."),
        _w("course", "/kɔːs/", "перемена блюд", "noun", "The second course is fish.", "Вторая перемена — рыба."),
        _w("takeaway", "/ˈteɪk.ə.weɪ/", "еда на вынос", "noun", "We ordered takeaway after the late train.", "После позднего поезда мы взяли еду на вынос."),
    ],
    "animals-pets": [
        _w("wolf", "/wʊlf/", "волк", "noun", "A wolf was seen on the far ridge.", "Волка видели на дальнем гребне."),
        _w("fox", "/fɒks/", "лиса", "noun", "The fox crossed the empty car park.", "Лиса перешла пустую парковку."),
        _w("owl", "/aʊl/", "сова", "noun", "An owl called from the church tower.", "Сова крикнула с церковной башни."),
        _w("deer", "/dɪə/", "олень", "noun", "Two deer stood at the forest edge.", "Два оленя стояли на опушке."),
        _w("goat", "/ɡəʊt/", "коза", "noun", "The goat ate the lower leaves.", "Коза съела нижние листья."),
        _w("duck", "/dʌk/", "утка", "noun", "A duck led her ducklings to the pond.", "Утка повела утят к пруду."),
        _w("whale", "/weɪl/", "кит", "noun", "The whale surfaced near the boat.", "Кит всплыл рядом с лодкой."),
        _w("turtle", "/ˈtɜː.təl/", "черепаха", "noun", "The turtle hid under the water plant.", "Черепаха спряталась под водным растением."),
        _w("leash", "/liːʃ/", "поводок", "noun", "Keep the dog on a short leash here.", "Держи собаку здесь на коротком поводке."),
        _w("kennel", "/ˈken.əl/", "конура", "noun", "The kennel stayed dry under the roof.", "Конура оставалась сухой под крышей."),
    ],
    "transport-directions": [
        _w("junction", "/ˈdʒʌŋk.ʃən/", "перекрёсток, развилка", "noun", "Slow down before the next junction.", "Сбавь скорость перед следующей развилкой."),
        _w("tunnel", "/ˈtʌn.əl/", "тоннель", "noun", "The tunnel is closed to bicycles.", "Тоннель закрыт для велосипедов."),
        _w("lane", "/leɪn/", "полоса; переулок", "noun", "Stay in the left lane until the bridge.", "Оставайся в левой полосе до моста."),
        _w("overtake", "/ˌəʊ.vəˈteɪk/", "обгонять", "verb", "Do not overtake on this bend.", "Не обгоняй на этом повороте."),
        _w("coach", "/kəʊtʃ/", "междугородний автобус", "noun", "The coach to Bristol leaves at nine.", "Автобус до Бристоля уходит в девять."),
        _w("harbour wall", "/ˈhɑː.bə wɔːl/", "мол, стенка гавани", "noun", "Walk along the harbour wall at dusk.", "Прогуляйся по стенке гавани в сумерках."),
        _w("round trip", "/ˈraʊnd trɪp/", "поездка туда и обратно", "noun", "A round trip costs less than two singles.", "Билет туда-обратно дешевле двух простых."),
        _w("shortcut", "/ˈʃɔːt.kʌt/", "короткий путь", "noun", "The shortcut floods after heavy rain.", "Короткий путь затапливает после сильного дождя."),
        _w("detour", "/ˈdiː.tʊə/", "объезд", "noun", "Follow the detour past the school.", "Объезд идёт мимо школы."),
        _w("kerb", "/kɜːb/", "бордюр", "noun", "Do not park with two wheels on the kerb.", "Не паркуйся двумя колёсами на бордюре."),
    ],
    "useful-nouns": [
        _w("benefit", "/ˈben.ɪ.fɪt/", "польза", "noun", "The main benefit is a quieter street.", "Главная польза — более тихая улица."),
        _w("risk", "/rɪsk/", "риск", "noun", "There is little risk if you leave early.", "Риска почти нет, если выйти рано."),
        _w("pressure", "/ˈpreʃ.ə/", "давление", "noun", "Work pressure rose before the deadline.", "Давление на работе выросло перед сроком."),
        _w("standard", "/ˈstæn.dəd/", "норма, стандарт", "noun", "The room is below the usual standard.", "Комната ниже обычного стандарта."),
        _w("condition", "/kənˈdɪʃ.ən/", "условие; состояние", "noun", "The bike is in good condition.", "Велосипед в хорошем состоянии."),
        _w("method", "/ˈmeθ.əd/", "метод", "noun", "A slower method gave a cleaner result.", "Более медленный метод дал более чистый результат."),
        _w("purpose", "/ˈpɜː.pəs/", "цель, назначение", "noun", "The purpose of the note is to warn guests.", "Назначение записки — предупредить гостей."),
        _w("issue", "/ˈɪʃ.uː/", "вопрос, проблема", "noun", "Parking is still the main issue.", "Парковка по-прежнему главный вопрос."),
        _w("impact", "/ˈɪm.pækt/", "влияние", "noun", "The new hours had little impact.", "Новые часы почти не повлияли."),
        _w("approach", "/əˈprəʊtʃ/", "подход", "noun", "A calmer approach worked better.", "Более спокойный подход сработал лучше."),
    ],
    "appearance-style": [
        _w("bald", "/bɔːld/", "лысый", "adjective", "He has been bald since his thirties.", "Он лысый с тридцати лет."),
        _w("wavy", "/ˈweɪ.vi/", "волнистый", "adjective", "Wavy hair needs less heat.", "Волнистым волосам нужно меньше нагрева."),
        _w("stubble", "/ˈstʌb.əl/", "щетина", "noun", "Dark stubble showed after two days.", "Тёмная щетина проступила через два дня."),
        _w("dimple", "/ˈdɪm.pəl/", "ямочка", "noun", "A dimple appeared when she smiled.", "Когда она улыбнулась, появилась ямочка."),
        _w("posture", "/ˈpɒs.tʃə/", "осанка", "noun", "Better posture reduced the neck pain.", "Лучшая осанка уменьшила боль в шее."),
        _w("complexion", "/kəmˈplek.ʃən/", "цвет лица", "noun", "A cold wind roughened her complexion.", "Холодный ветер загрубил цвет лица."),
        _w("stylish", "/ˈstaɪ.lɪʃ/", "стильный", "adjective", "The coat is simple but stylish.", "Пальто простое, но стильное."),
        _w("plump", "/plʌmp/", "полноватый", "adjective", "A plump cushion filled the corner chair.", "Полная подушка заняла угловое кресло."),
        _w("gaunt", "/ɡɔːnt/", "измождённый", "adjective", "He looked gaunt after the night shift.", "После ночной смены он выглядел измождённым."),
        _w("well-dressed", "/ˌwel ˈdrest/", "хорошо одетый", "adjective", "The well-dressed man still missed the train.", "Хорошо одетый мужчина всё равно опоздал на поезд."),
    ],
    "holidays-culture": [
        _w("feast", "/fiːst/", "пир", "noun", "The feast began after the short speech.", "Пир начался после короткой речи."),
        _w("lantern", "/ˈlæn.tən/", "фонарь", "noun", "Paper lanterns hung above the stalls.", "Бумажные фонари висели над прилавками."),
        _w("carol", "/ˈkær.əl/", "рождественский гимн", "noun", "Children sang one carol at the door.", "Дети спели у двери один гимн."),
        _w("banquet", "/ˈbæŋ.kwɪt/", "банкет", "noun", "The banquet was smaller than last year.", "Банкет был меньше, чем в прошлом году."),
        _w("ritual", "/ˈrɪtʃ.u.əl/", "ритуал", "noun", "A short ritual opened the market.", "Короткий ритуал открыл рынок."),
        _w("farewell", "/ˌfeəˈwel/", "прощание", "noun", "The farewell was quiet at the station.", "Прощание на вокзале было тихим."),
        _w("reunion", "/ˌriːˈjuː.ni.ən/", "встреча выпускников, воссоединение", "noun", "The family reunion filled the kitchen.", "Семейная встреча заполнила кухню."),
        _w("toastmaster", "/ˈtəʊstˌmɑː.stə/", "тамада", "noun", "The toastmaster kept speeches short.", "Тамада не давал речам затягиваться."),
        _w("procession", "/prəˈseʃ.ən/", "шествие", "noun", "The procession moved toward the river.", "Шествие двигалось к реке."),
        _w("costume party", "/ˈkɒs.tjuːm ˌpɑː.ti/", "костюмированная вечеринка", "noun", "The costume party starts after nine.", "Костюмированная вечеринка начинается после девяти."),
    ],
    "science-everyday": [
        _w("acid", "/ˈæs.ɪd/", "кислота", "noun", "The acid must stay in a labelled bottle.", "Кислота должна стоять в подписанной бутылке."),
        _w("friction", "/ˈfrɪk.ʃən/", "трение", "noun", "Friction heats the bicycle brakes.", "Трение нагревает тормоза велосипеда."),
        _w("lens", "/lenz/", "линза", "noun", "Wipe the lens before you take the photo.", "Протри линзу, прежде чем снимать."),
        _w("nucleus", "/ˈnjuː.kli.əs/", "ядро", "noun", "The nucleus sits near the centre of the cell.", "Ядро находится ближе к центру клетки."),
        _w("enzyme", "/ˈen.zaɪm/", "фермент", "noun", "One enzyme speeds up the reaction.", "Один фермент ускоряет реакцию."),
        _w("vacuum", "/ˈvæk.juːm/", "вакуум", "noun", "Sound does not travel in a vacuum.", "Звук не распространяется в вакууме."),
        _w("crystal", "/ˈkrɪs.təl/", "кристалл", "noun", "A salt crystal grew on the string.", "На нитке вырос кристалл соли."),
        _w("current", "/ˈkʌr.ənt/", "ток; течение", "noun", "A weak current still moved the leaves.", "Слабое течение всё ещё двигало листья."),
        _w("evaporate", "/ɪˈvæp.ər.eɪt/", "испаряться", "verb", "Puddles evaporate faster on windy days.", "Лужи быстрее испаряются в ветреные дни."),
        _w("condense", "/kənˈdens/", "конденсироваться", "verb", "Steam will condense on the cold glass.", "Пар сконденсируется на холодном стекле."),
    ],
    "arts-culture": [
        _w("mural", "/ˈmjʊə.rəl/", "настенная роспись", "noun", "A new mural covers the station wall.", "Новая роспись закрывает стену вокзала."),
        _w("sonnet", "/ˈsɒn.ɪt/", "сонет", "noun", "The last sonnet is only fourteen lines.", "Последний сонет — всего четырнадцать строк."),
        _w("encore", "/ˈɒŋ.kɔː/", "бис", "noun", "The encore was quieter than the set.", "На бис сыграли тише, чем основной сет."),
        _w("interval", "/ˈɪn.tə.vəl/", "антракт", "noun", "The interval is twenty minutes.", "Антракт длится двадцать минут."),
        _w("collage", "/ˈkɒl.ɑːʒ/", "коллаж", "noun", "The collage uses tickets and maps.", "В коллаже билеты и карты."),
        _w("motif", "/məʊˈtiːf/", "мотив", "noun", "A water motif returns in every chapter.", "Мотив воды возвращается в каждой главе."),
        _w("libretto", "/lɪˈbret.əʊ/", "либретто", "noun", "The libretto is clearer than the surtitles.", "Либретто понятнее титров."),
        _w("still life", "/ˌstɪl ˈlaɪf/", "натюрморт", "noun", "The still life uses only three objects.", "В натюрморте всего три предмета."),
        _w("overture", "/ˈəʊ.və.tʃʊə/", "увертюра", "noun", "The overture is longer than the first scene.", "Увертюра длиннее первой сцены."),
        _w("retrospective", "/ˌret.rəʊˈspek.tɪv/", "ретроспектива", "noun", "The retrospective fills two floors.", "Ретроспектива занимает два этажа."),
    ],
    "academic-verbs": [
        _w("posit", "/ˈpɒz.ɪt/", "выдвигать (тезис)", "verb", "They posit a second, quieter cause.", "Они выдвигают вторую, более тихую причину."),
        _w("substantiate", "/səbˈstæn.ʃi.eɪt/", "подтверждать фактами", "verb", "One chart does not substantiate the claim.", "Один график не подтверждает утверждение."),
        _w("delineate", "/dɪˈlɪn.i.eɪt/", "очерчивать", "verb", "Delineate the limits of the sample.", "Очерти границы выборки."),
        _w("corroborate", "/kəˈrɒb.ə.reɪt/", "подкреплять", "verb", "Later interviews corroborate the first report.", "Поздние интервью подкрепляют первый отчёт."),
        _w("postulate", "/ˈpɒs.tʃə.leɪt/", "постулировать", "verb", "The model postulates constant demand.", "Модель постулирует постоянный спрос."),
        _w("encapsulate", "/ɪnˈkæp.sjə.leɪt/", "сжимать до сути", "verb", "One sentence encapsulates the finding.", "Одно предложение сжимает вывод до сути."),
        _w("interrogate", "/ɪnˈter.ə.ɡeɪt/", "критически разбирать", "verb", "Interrogate the source, not only the number.", "Разбери источник, а не только цифру."),
        _w("contextualise", "/kənˈtek.stʃu.ə.laɪz/", "помещать в контекст", "verb", "Contextualise the quote before you judge it.", "Помести цитату в контекст, прежде чем судить."),
        _w("qualify", "/ˈkwɒl.ɪ.faɪ/", "оговаривать, уточнять", "verb", "Qualify the claim if the town is unusual.", "Оговори утверждение, если город нетипичный."),
        _w("foreground", "/ˈfɔː.ɡraʊnd/", "выдвигать на первый план", "verb", "The chapter foregrounds local voices.", "Глава выдвигает на первый план местные голоса."),
    ],
    "formal-register": [
        _w("pursuant", "/pəˈsjuː.ənt/", "в соответствии", "preposition", "Pursuant to clause four, payment is due now.", "В соответствии с пунктом четыре оплата нужна сейчас."),
        _w("aforementioned", "/əˈfɔː.men.ʃənd/", "вышеупомянутый", "adjective", "The aforementioned dates remain unchanged.", "Вышеупомянутые даты не меняются."),
        _w("hereafter", "/ˌhɪəˈrɑːf.tə/", "в дальнейшем (в тексте)", "adverb", "The company is hereafter called the Supplier.", "Компания в дальнейшем именуется Поставщиком."),
        _w("kindly", "/ˈkaɪnd.li/", "пожалуйста (офиц.)", "adverb", "Kindly confirm receipt of this letter.", "Пожалуйста, подтвердите получение письма."),
        _w("advise", "/ədˈvaɪz/", "сообщать (офиц.)", "verb", "Please advise us of any delay.", "Просим сообщить о любой задержке."),
        _w("remain", "/rɪˈmeɪn/", "оставаться в силе", "verb", "The earlier terms remain in force.", "Прежние условия остаются в силе."),
        _w("confirm", "/kənˈfɜːm/", "подтверждать", "verb", "Confirm the room number before you travel.", "Подтвердите номер комнаты до поездки."),
        _w("herewith", "/ˌhɪəˈwɪð/", "при сём", "adverb", "I herewith enclose a copy of the form.", "При сём прилагаю копию бланка."),
        _w("thereafter", "/ˌðeəˈrɑːf.tə/", "после этого", "adverb", "Sign the form; thereafter send it by post.", "Подпиши бланк; после этого отправь его почтой."),
        _w("undersigned", "/ˌʌn.dəˈsaɪnd/", "нижеподписавшийся", "noun", "The undersigned accepts the new date.", "Нижеподписавшийся принимает новую дату."),
    ],
    "precise-nuance": [
        _w("inchoate", "/ɪnˈkəʊ.ət/", "ещё не оформившийся", "adjective", "The plan is still inchoate after one meeting.", "После одной встречи план ещё не оформился."),
        _w("pellucid", "/pəˈluː.sɪd/", "кристально ясный", "adjective", "The pellucid note left no room for doubt.", "Кристально ясная записка не оставляла сомнений."),
        _w("recondite", "/ˈrek.ən.daɪt/", "малодоступный, тёмный", "adjective", "The joke relies on a recondite reference.", "Шутка держится на малодоступной отсылке."),
        _w("liminal", "/ˈlɪm.ɪ.nəl/", "пороговый", "adjective", "Dusk is a liminal hour in the novel.", "Сумерки в романе — пороговый час."),
        _w("trenchant", "/ˈtren.tʃənt/", "резкий, проницательный", "adjective", "A trenchant review named the weak act.", "Резкая рецензия указала на слабый акт."),
        _w("anodyne", "/ˈæn.ə.daɪn/", "безобидный, сглаженный", "adjective", "The statement was anodyne and empty.", "Заявление было сглаженным и пустым."),
        _w("sui generis", "/ˌsuː.i ˈdʒen.ər.ɪs/", "уникальный в своём роде", "adjective", "The building is sui generis, not a copy.", "Здание уникально в своём роде, это не копия."),
        _w("factitious", "/fækˈtɪʃ.əs/", "напускной", "adjective", "The excitement felt factitious after the leak.", "Возбуждение после утечки казалось напускным."),
        _w("perspicuous", "/pəˈspɪk.ju.əs/", "прозрачный по смыслу", "adjective", "A perspicuous chart replaced the long note.", "Прозрачный график заменил длинную записку."),
        _w("rebarbative", "/rɪˈbɑː.bə.tɪv/", "отталкивающий", "adjective", "The rebarbative tone lost the room.", "Отталкивающий тон потерял зал."),
    ],
}


MORE_TOPICS = [
    _topic(
        "body-basics",
        "Тело: базовые слова",
        "Части тела, с которых начинают описывать себя и простых людей.",
        "A1",
        [
            _w("head", "/hed/", "голова", "noun", "He hit his head on the low door.", "Он ударился головой о низкую дверь."),
            _w("arm", "/ɑːm/", "рука (от плеча)", "noun", "She carried the bag on one arm.", "Она несла сумку на одной руке."),
            _w("leg", "/leɡ/", "нога", "noun", "My left leg is tired after the hill.", "Левая нога устала после подъёма."),
            _w("hand", "/hænd/", "кисть руки", "noun", "Wash your hands before you cook.", "Вымой руки, прежде чем готовить."),
            _w("foot", "/fʊt/", "ступня", "noun", "There is sand on my left foot.", "На левой ступне песок."),
            _w("eye", "/aɪ/", "глаз", "noun", "Something is in my right eye.", "Что-то попало в правый глаз."),
            _w("ear", "/ɪə/", "ухо", "noun", "The wind is loud in this ear.", "В этом ухе ветер звучит громко."),
            _w("nose", "/nəʊz/", "нос", "noun", "Her nose is red from the cold.", "Нос покраснел от холода."),
            _w("mouth", "/maʊθ/", "рот", "noun", "Do not talk with food in your mouth.", "Не говори с едой во рту."),
            _w("hair", "/heə/", "волосы", "noun", "Wet hair dripped on the floor.", "Мокрые волосы капали на пол."),
            _w("face", "/feɪs/", "лицо", "noun", "He washed his face in cold water.", "Он умыл лицо холодной водой."),
            _w("neck", "/nek/", "шея", "noun", "A scarf covered her neck.", "Шарф закрывал ей шею."),
            _w("back", "/bæk/", "спина", "noun", "My back hurts after the long sit.", "Спина болит после долгого сидения."),
            _w("stomach", "/ˈstʌm.ək/", "живот", "noun", "His stomach growled before lunch.", "Живот заурчал до обеда."),
            _w("finger", "/ˈfɪŋ.ɡə/", "палец руки", "noun", "I cut my finger on the paper.", "Я порезал палец бумагой."),
            _w("tooth", "/tuːθ/", "зуб", "noun", "One tooth feels loose.", "Один зуб шатается."),
            _w("skin", "/skɪn/", "кожа", "noun", "Dry skin needs a little cream.", "Сухой коже нужен немного крема."),
            _w("bone", "/bəʊn/", "кость", "noun", "The dog found a bone in the yard.", "Собака нашла во дворе кость."),
            _w("blood", "/blʌd/", "кровь", "noun", "A little blood came from the cut.", "Из пореза вышло немного крови."),
            _w("chest", "/tʃest/", "грудь", "noun", "The cold air hurt his chest.", "Холодный воздух саднил грудь."),
        ],
    ),
    _topic(
        "town-places",
        "Городские места",
        "Куда пойти в городе: парк, банк, библиотека, рынок, площадь.",
        "A1",
        [
            _w("park", "/pɑːk/", "парк", "noun", "We sit in the park after lunch.", "После обеда мы сидим в парке."),
            _w("bank", "/bæŋk/", "банк", "noun", "The bank closes at four on Friday.", "В пятницу банк закрывается в четыре."),
            _w("library", "/ˈlaɪ.brər.i/", "библиотека", "noun", "The library is quiet after school.", "После школы в библиотеке тихо."),
            _w("cinema", "/ˈsɪn.ə.mə/", "кинотеатр", "noun", "The cinema has two small screens.", "В кинотеатре два маленьких зала."),
            _w("hospital", "/ˈhɒs.pɪ.təl/", "больница", "noun", "The hospital is behind the bus stop.", "Больница за автобусной остановкой."),
            _w("school", "/skuːl/", "школа", "noun", "The school gate opens at eight.", "Школьные ворота открываются в восемь."),
            _w("market", "/ˈmɑː.kɪt/", "рынок", "noun", "Fresh cheese is cheaper at the market.", "Свежий сыр дешевле на рынке."),
            _w("square", "/skweə/", "площадь", "noun", "Meet me in the main square.", "Встретимся на главной площади."),
            _w("street", "/striːt/", "улица", "noun", "This street has no cars after six.", "На этой улице после шести нет машин."),
            _w("cafe", "/ˈkæf.eɪ/", "кафе", "noun", "The cafe on the corner opens early.", "Кафе на углу открывается рано."),
            _w("bakery", "/ˈbeɪ.kər.i/", "пекарня", "noun", "The bakery sells bread until noon.", "Пекарня продаёт хлеб до полудня."),
            _w("church", "/tʃɜːtʃ/", "церковь", "noun", "The church clock is two minutes fast.", "Часы на церкви спешат на две минуты."),
            _w("police", "/pəˈliːs/", "полиция", "noun", "Ask the police for the lost bag.", "Спроси в полиции про потерянную сумку."),
            _w("zoo", "/zuː/", "зоопарк", "noun", "The zoo is closed on Mondays.", "Зоопарк по понедельникам закрыт."),
            _w("beach", "/biːtʃ/", "пляж", "noun", "The beach is empty after five.", "После пяти пляж пустой."),
            _w("farm", "/fɑːm/", "ферма", "noun", "The farm sells eggs on Saturday.", "Ферма продаёт яйца в субботу."),
            _w("theatre", "/ˈθɪə.tə/", "театр", "noun", "The theatre is a short walk from here.", "Театр в нескольких минутах ходьбы."),
            _w("post office", "/ˈpəʊst ˌɒf.ɪs/", "почта", "noun", "The post office is next to the bank.", "Почта рядом с банком."),
            _w("playground", "/ˈpleɪ.ɡraʊnd/", "детская площадка", "noun", "The playground is behind the school.", "Площадка за школой."),
            _w("bridge", "/brɪdʒ/", "мост", "noun", "Cross the bridge and turn left.", "Перейди мост и поверни налево."),
        ],
    ),
    _topic(
        "everyday-verbs",
        "Частые глаголы",
        "Глаголы, без которых трудно собрать простое предложение.",
        "A1",
        [
            _w("go", "/ɡəʊ/", "идти, ехать", "verb", "I go to the shop after work.", "После работы я иду в магазин."),
            _w("come", "/kʌm/", "приходить", "verb", "Come here for a minute.", "Подойди сюда на минуту."),
            _w("take", "/teɪk/", "брать", "verb", "Take the blue bag, not the black one.", "Возьми синюю сумку, не чёрную."),
            _w("give", "/ɡɪv/", "давать", "verb", "Give her the key, please.", "Дай ей ключ, пожалуйста."),
            _w("buy", "/baɪ/", "покупать", "verb", "Buy milk if you see a shop.", "Купи молоко, если увидишь магазин."),
            _w("sell", "/sel/", "продавать", "verb", "They sell maps at the station.", "На вокзале продают карты."),
            _w("sit", "/sɪt/", "сидеть", "verb", "Sit near the window if you can.", "Сядь у окна, если получится."),
            _w("stand", "/stænd/", "стоять", "verb", "Stand behind the yellow line.", "Стой за жёлтой линией."),
            _w("eat", "/iːt/", "есть", "verb", "We eat dinner at seven.", "Мы ужинаем в семь."),
            _w("drink", "/drɪŋk/", "пить", "verb", "Drink water before the walk.", "Выпей воды перед прогулкой."),
            _w("like", "/laɪk/", "нравиться", "verb", "I like this quiet street.", "Мне нравится эта тихая улица."),
            _w("need", "/niːd/", "нуждаться", "verb", "I need a smaller bag.", "Мне нужна сумка поменьше."),
            _w("want", "/wɒnt/", "хотеть", "verb", "They want a table by the window.", "Они хотят столик у окна."),
            _w("know", "/nəʊ/", "знать", "verb", "I know a shorter way.", "Я знаю более короткий путь."),
            _w("think", "/θɪŋk/", "думать", "verb", "I think the shop is still open.", "Думаю, магазин ещё открыт."),
            _w("say", "/seɪ/", "сказать", "verb", "Say the number again, please.", "Скажи номер ещё раз, пожалуйста."),
            _w("tell", "/tel/", "рассказывать", "verb", "Tell me when the bus comes.", "Скажи, когда подойдёт автобус."),
            _w("ask", "/ɑːsk/", "спрашивать", "verb", "Ask him for the next stop.", "Спроси у него следующую остановку."),
            _w("find", "/faɪnd/", "находить", "verb", "I cannot find my other glove.", "Не могу найти вторую перчатку."),
            _w("lose", "/luːz/", "терять", "verb", "Do not lose the ticket.", "Не потеряй билет."),
        ],
    ),
    _topic(
        "countryside",
        "Деревня и пейзаж",
        "Холмы, берег, тропа и то, что видишь за городом.",
        "A2",
        [
            _w("hill", "/hɪl/", "холм", "noun", "The path climbs the last hill slowly.", "Тропа медленно поднимается на последний холм."),
            _w("valley", "/ˈvæl.i/", "долина", "noun", "Fog stays in the valley until noon.", "Туман держится в долине до полудня."),
            _w("island", "/ˈaɪ.lənd/", "остров", "noun", "The island has one small shop.", "На острове один маленький магазин."),
            _w("coast", "/kəʊst/", "побережье", "noun", "Wind is stronger on the coast.", "На побережье ветер сильнее."),
            _w("desert", "/ˈdez.ət/", "пустыня", "noun", "The desert road has almost no shade.", "На пустынной дороге почти нет тени."),
            _w("village", "/ˈvɪl.ɪdʒ/", "деревня", "noun", "The village shop closes at lunch.", "Деревенский магазин закрывается в обед."),
            _w("countryside", "/ˈkʌn.tri.saɪd/", "сельская местность", "noun", "They moved to the countryside last year.", "В прошлом году они переехали за город."),
            _w("path", "/pɑːθ/", "тропа", "noun", "The path is muddy after rain.", "После дождя тропа грязная."),
            _w("lake", "/leɪk/", "озеро", "noun", "The lake freezes in hard winters.", "В суровые зимы озеро замерзает."),
            _w("mountain", "/ˈmaʊn.tɪn/", "гора", "noun", "The mountain path is closed in snow.", "Горная тропа закрыта в снег."),
            _w("field", "/fiːld/", "поле", "noun", "Cows stand in the next field.", "Коровы стоят на соседнем поле."),
            _w("barn", "/bɑːn/", "сарай", "noun", "Hay is stored in the old barn.", "Сено хранят в старом сарае."),
            _w("stream", "/striːm/", "ручей", "noun", "A cold stream crosses the path.", "Холодный ручей пересекает тропу."),
            _w("cave", "/keɪv/", "пещера", "noun", "The cave stays cool in summer.", "Пещера летом остаётся прохладной."),
            _w("shore", "/ʃɔː/", "берег", "noun", "We walked along the rocky shore.", "Мы шли по каменистому берегу."),
            _w("wood", "/wʊd/", "лесок", "noun", "The wood is darker after four.", "После четырёх в леске темнее."),
            _w("hedgerow", "/ˈhedʒ.rəʊ/", "изгородь вдоль поля", "noun", "Birds nest in the thick hedgerow.", "Птицы гнездятся в густой изгороди."),
            _w("farmhouse", "/ˈfɑːm.haʊs/", "фермерский дом", "noun", "The farmhouse has a red door.", "У фермерского дома красная дверь."),
            _w("orchard", "/ˈɔː.tʃəd/", "фруктовый сад", "noun", "Apples drop in the orchard in October.", "В октябре в саду падают яблоки."),
            _w("ridge", "/rɪdʒ/", "гребень холма", "noun", "From the ridge you see two villages.", "С гребня видны две деревни."),
        ],
    ),
    _topic(
        "communication",
        "Общение и сообщения",
        "Письмо, звонок, спор и то, как передают новость.",
        "A2",
        [
            _w("message", "/ˈmes.ɪdʒ/", "сообщение", "noun", "I left a short message on the door.", "Я оставил короткое сообщение на двери."),
            _w("email", "/ˈiː.meɪl/", "письмо по почте", "noun", "The email has the new time.", "В письме указано новое время."),
            _w("letter", "/ˈlet.ə/", "письмо", "noun", "Her letter arrived a week late.", "Её письмо пришло на неделю позже."),
            _w("stamp", "/stæmp/", "марка", "noun", "This stamp is not enough for abroad.", "Этой марки не хватает для заграницы."),
            _w("reply", "/rɪˈplaɪ/", "ответ", "noun", "A reply came after two days.", "Ответ пришёл через два дня."),
            _w("chat", "/tʃæt/", "переписка, болтовня", "noun", "A short chat solved the mix-up.", "Короткая переписка сняла путаницу."),
            _w("conversation", "/ˌkɒn.vəˈseɪ.ʃən/", "разговор", "noun", "The conversation moved to the kitchen.", "Разговор перешёл на кухню."),
            _w("whisper", "/ˈwɪs.pə/", "шептать", "verb", "Whisper if the baby is asleep.", "Шепчи, если малыш спит."),
            _w("shout", "/ʃaʊt/", "кричать", "verb", "Do not shout across the hall.", "Не кричи через весь коридор."),
            _w("explain", "/ɪkˈspleɪn/", "объяснять", "verb", "Explain the rule in one sentence.", "Объясни правило одним предложением."),
            _w("describe", "/dɪˈskraɪb/", "описывать", "verb", "Describe the bag, not only the colour.", "Опиши сумку, а не только цвет."),
            _w("mention", "/ˈmen.ʃən/", "упоминать", "verb", "Mention the delay in your note.", "Упомяни задержку в записке."),
            _w("announce", "/əˈnaʊns/", "объявлять", "verb", "They will announce the gate soon.", "Скоро объявят выход на посадку."),
            _w("argue", "/ˈɑː.ɡjuː/", "спорить", "verb", "They argue about the bill, not the food.", "Они спорят о счёте, а не о еде."),
            _w("agree", "/əˈɡriː/", "соглашаться", "verb", "I agree with the shorter plan.", "Я согласен с более коротким планом."),
            _w("promise", "/ˈprɒm.ɪs/", "обещать", "verb", "Promise you will call from the station.", "Пообещай, что позвонишь с вокзала."),
            _w("remind", "/rɪˈmaɪnd/", "напоминать", "verb", "Remind me about the form tomorrow.", "Напомни мне завтра про бланк."),
            _w("apologise", "/əˈpɒl.ə.dʒaɪz/", "извиняться", "verb", "Apologise if you are late again.", "Извинись, если снова опоздаешь."),
            _w("interrupt", "/ˌɪn.təˈrʌpt/", "перебивать", "verb", "Do not interrupt during the talk.", "Не перебивай во время выступления."),
            _w("translate", "/trænzˈleɪt/", "переводить", "verb", "Translate the sign before you enter.", "Переведи надпись, прежде чем входить."),
        ],
    ),
    _topic(
        "house-chores",
        "Дом и хозяйство",
        "Уборка, стирка, мелкий ремонт — слова быта A2.",
        "A2",
        [
            _w("sweep", "/swiːp/", "подметать", "verb", "Sweep the kitchen before guests arrive.", "Подмети кухню, прежде чем придут гости."),
            _w("mop", "/mɒp/", "мыть пол шваброй", "verb", "Mop the hall after the rain.", "Вымой шваброй прихожую после дождя."),
            _w("iron", "/ˈaɪən/", "гладить", "verb", "Iron the shirt while it is still slightly damp.", "Гладь рубашку, пока она ещё чуть влажная."),
            _w("dust", "/dʌst/", "вытирать пыль", "verb", "Dust the shelves once a week.", "Вытирай пыль с полок раз в неделю."),
            _w("vacuum", "/ˈvæk.juːm/", "пылесосить", "verb", "Vacuum the stairs on Sunday morning.", "Пылесось лестницу в воскресенье утром."),
            _w("laundry", "/ˈlɔːn.dri/", "стирка", "noun", "The laundry dries slowly in wet weather.", "В сырую погоду стирка сохнет медленно."),
            _w("rubbish", "/ˈrʌb.ɪʃ/", "мусор", "noun", "Take the rubbish out before dinner.", "Вынеси мусор до ужина."),
            _w("chore", "/tʃɔː/", "домашнее дело", "noun", "Washing cups is my evening chore.", "Мытьё чашек — моё вечернее дело."),
            _w("mess", "/mes/", "беспорядок", "noun", "The mess in the hall is from the wet boots.", "Беспорядок в прихожей — от мокрых сапог."),
            _w("repair", "/rɪˈpeə/", "чинить", "verb", "Can you repair the loose handle?", "Можешь починить расшатанную ручку?"),
            _w("leak", "/liːk/", "протечка", "noun", "A slow leak stained the ceiling.", "Медленная протечка оставила пятно на потолке."),
            _w("tap", "/tæp/", "кран", "noun", "The kitchen tap drips at night.", "Кухонный кран капает ночью."),
            _w("bulb", "/bʌlb/", "лампочка", "noun", "Change the bulb in the landing first.", "Сначала смени лампочку на площадке."),
            _w("bleach", "/bliːtʃ/", "отбеливатель", "noun", "Do not mix bleach with other cleaners.", "Не смешивай отбеливатель с другими средствами."),
            _w("soak", "/səʊk/", "замачивать", "verb", "Soak the pan before you scrub it.", "Замочи сковороду, прежде чем скрести."),
            _w("rinse", "/rɪns/", "полоскать", "verb", "Rinse the soap off the plates.", "Смой мыло с тарелок."),
            _w("peg", "/peɡ/", "прищепка", "noun", "The last peg fell into the grass.", "Последняя прищепка упала в траву."),
            _w("drain", "/dreɪn/", "сток", "noun", "Hair blocked the bathroom drain.", "Волосы забили сток в ванной."),
            _w("polish", "/ˈpɒl.ɪʃ/", "полировать", "verb", "Polish the table after you dust it.", "Натри стол после пыли."),
            _w("unclog", "/ʌnˈklɒɡ/", "прочищать", "verb", "Unclog the sink with hot water first.", "Сначала прочисти раковину горячей водой."),
        ],
    ),
    _topic(
        "relationships",
        "Отношения и люди рядом",
        "Дружба, доверие, ссора и слова про близкий круг B1.",
        "B1",
        [
            _w("trust", "/trʌst/", "доверять", "verb", "I trust her with the spare key.", "Я доверяю ей запасной ключ."),
            _w("forgive", "/fəˈɡɪv/", "прощать", "verb", "Forgive the late reply; the train stalled.", "Прости поздний ответ: поезд встал."),
            _w("support", "/səˈpɔːt/", "поддерживать", "verb", "Friends support him during the move.", "Друзья поддерживают его во время переезда."),
            _w("date", "/deɪt/", "свидание", "noun", "Their first date was a short walk.", "Их первое свидание было короткой прогулкой."),
            _w("break-up", "/ˈbreɪk.ʌp/", "разрыв отношений", "noun", "The break-up was quiet and final.", "Разрыв был тихим и окончательным."),
            _w("acquaintance", "/əˈkweɪn.təns/", "знакомый", "noun", "He is only an acquaintance from the gym.", "Он всего лишь знакомый из зала."),
            _w("friendship", "/ˈfrend.ʃɪp/", "дружба", "noun", "Their friendship survived two cities.", "Их дружба пережила два города."),
            _w("loyal", "/ˈlɔɪ.əl/", "верный", "adjective", "A loyal friend keeps a secret.", "Верный друг хранит секрет."),
            _w("close", "/kləʊs/", "близкий", "adjective", "We are close, but we do not meet often.", "Мы близки, хотя видимся редко."),
            _w("distant", "/ˈdɪs.tənt/", "отстранённый", "adjective", "He sounded distant on the call.", "В разговоре он звучал отстранённо."),
            _w("quarrel", "/ˈkwɒr.əl/", "ссора", "noun", "The quarrel started over a small bill.", "Ссора началась из-за мелкого счёта."),
            _w("reconcile", "/ˈrek.ən.saɪl/", "мириться", "verb", "They reconciled after a week of silence.", "Они помирились после недели молчания."),
            _w("jealousy", "/ˈdʒel.ə.si/", "ревность", "noun", "Jealousy ruined an otherwise good evening.", "Ревность испортила в целом хороший вечер."),
            _w("companion", "/kəmˈpæn.jən/", "спутник, компаньон", "noun", "A quiet companion is better on long trains.", "В долгих поездах лучше тихий спутник."),
            _w("bond", "/bɒnd/", "связь", "noun", "A shared joke became their bond.", "Общая шутка стала их связью."),
            _w("neglect", "/nɪˈɡlekt/", "пренебрегать", "verb", "Do not neglect old friends in a new city.", "Не забывай старых друзей в новом городе."),
            _w("affection", "/əˈfek.ʃən/", "привязанность", "noun", "He shows affection in small practical ways.", "Он проявляет привязанность мелкими практическими жестами."),
            _w("conflict", "/ˈkɒn.flɪkt/", "конфликт", "noun", "The conflict faded after one honest talk.", "Конфликт сошёл на нет после честного разговора."),
            _w("rely", "/rɪˈlaɪ/", "полагаться", "verb", "I rely on her to lock the side door.", "Я полагаюсь на неё: она запирает боковую дверь."),
            _w("misunderstand", "/ˌmɪs.ʌn.dəˈstænd/", "неправильно понять", "verb", "I misunderstood the time, not the place.", "Я неправильно понял время, а не место."),
        ],
    ),
    _topic(
        "work-skills",
        "Навыки и карьера",
        "То, о чём говорят на собеседовании и в команде: отзыв, найм, смена роли.",
        "B1",
        [
            _w("skill", "/skɪl/", "навык", "noun", "Listening is still my weakest skill.", "Слух по-прежнему мой самый слабый навык."),
            _w("feedback", "/ˈfiːd.bæk/", "обратная связь", "noun", "The feedback was short and useful.", "Обратная связь была короткой и полезной."),
            _w("teamwork", "/ˈtiːm.wɜːk/", "командная работа", "noun", "The task needs teamwork, not a hero.", "Задаче нужна командная работа, а не герой."),
            _w("leadership", "/ˈliː.də.ʃɪp/", "лидерство", "noun", "Quiet leadership kept the shift calm.", "Спокойное лидерство удержало смену."),
            _w("negotiate", "/nɪˈɡəʊ.ʃi.eɪt/", "договариваться", "verb", "They negotiated a later start date.", "Они договорились о более поздней дате начала."),
            _w("delegate", "/ˈdel.ɪ.ɡeɪt/", "поручать", "verb", "Delegate the bookings, not the budget.", "Поручи брони, но не бюджет."),
            _w("resign", "/rɪˈzaɪn/", "увольняться", "verb", "She resigned after the third restructure.", "Она уволилась после третьей реорганизации."),
            _w("hire", "/haɪə/", "нанимать", "verb", "They will hire two more tutors in May.", "В мае они наймут ещё двух преподавателей."),
            _w("apply", "/əˈplaɪ/", "подавать заявку", "verb", "Apply before Friday if you want a place.", "Подай заявку до пятницы, если хочешь место."),
            _w("multitask", "/ˌmʌl.tiˈtɑːsk/", "делать несколько дел сразу", "verb", "I cannot multitask during a call.", "Во время звонка я не могу делать несколько дел."),
            _w("mentor", "/ˈmen.tɔː/", "наставник", "noun", "A mentor reviewed her first draft.", "Наставник посмотрел её первый черновик."),
            _w("workload", "/ˈwɜːk.ləʊd/", "нагрузка", "noun", "The workload is lighter after the launch.", "После запуска нагрузка легче."),
            _w("promotion", "/prəˈməʊ.ʃən/", "повышение", "noun", "The promotion came with later hours.", "Повышение принесло более поздние часы."),
            _w("redundant", "/rɪˈdʌn.dənt/", "сокращённый", "adjective", "He was made redundant when the shop closed.", "Его сократили, когда магазин закрылся."),
            _w("probation", "/prəˈbeɪ.ʃən/", "испытательный срок", "noun", "Probation lasts three months here.", "Испытательный срок здесь три месяца."),
            _w("appraisal", "/əˈpreɪ.zəl/", "аттестация", "noun", "The appraisal is a short conversation.", "Аттестация — короткий разговор."),
            _w("shift work", "/ˈʃɪft wɜːk/", "сменная работа", "noun", "Shift work made weekends irregular.", "Сменная работа сделала выходные неровными."),
            _w("notice", "/ˈnəʊ.tɪs/", "срок уведомления", "noun", "Give two weeks' notice before you leave.", "Предупреди за две недели до ухода."),
            _w("shortlist", "/ˈʃɔːt.lɪst/", "короткий список", "noun", "Three names are on the shortlist.", "В коротком списке три имени."),
            _w("cover letter", "/ˈkʌv.ə ˌlet.ə/", "сопроводительное письмо", "noun", "Keep the cover letter under one page.", "Держи сопроводительное письмо короче страницы."),
        ],
    ),
    _topic(
        "news-opinion",
        "Новости и мнение",
        "Как говорить о репортаже, слухе, источнике и предвзятости.",
        "B2",
        [
            _w("journalist", "/ˈdʒɜː.nə.lɪst/", "журналист", "noun", "The journalist asked for one extra hour.", "Журналист попросил ещё час."),
            _w("rumour", "/ˈruː.mə/", "слух", "noun", "The rumour started in a group chat.", "Слух начался в групповом чате."),
            _w("source", "/sɔːs/", "источник", "noun", "Name the source or drop the claim.", "Назови источник или убери утверждение."),
            _w("coverage", "/ˈkʌv.ər.ɪdʒ/", "освещение", "noun", "Local coverage ignored the night shift.", "Местное освещение обошло ночную смену."),
            _w("editor", "/ˈed.ɪ.tə/", "редактор", "noun", "The editor cut the last paragraph.", "Редактор убрал последний абзац."),
            _w("broadcast", "/ˈbrɔːd.kɑːst/", "трансляция", "noun", "The broadcast started five minutes late.", "Трансляция началась на пять минут позже."),
            _w("scandal", "/ˈskæn.dəl/", "скандал", "noun", "The scandal faded after a week.", "Скандал угас через неделю."),
            _w("censorship", "/ˈsen.sə.ʃɪp/", "цензура", "noun", "Censorship hid the original headline.", "Цензура скрыла исходный заголовок."),
            _w("column", "/ˈkɒl.əm/", "колонка", "noun", "Her column is shorter on Fridays.", "По пятницам её колонка короче."),
            _w("op-ed", "/ˈɒp.ed/", "авторская колонка", "noun", "The op-ed argued for cheaper night buses.", "В колонке говорили о более дешёвых ночных автобусах."),
            _w("leak", "/liːk/", "утечка", "noun", "A leak of the draft changed the vote.", "Утечка черновика изменила голосование."),
            _w("fact-check", "/ˈfækt tʃek/", "проверка фактов", "noun", "A fact-check found two wrong dates.", "Проверка фактов нашла две неверные даты."),
            _w("byline", "/ˈbaɪ.laɪn/", "строка с автором", "noun", "There is no byline on the night piece.", "У ночного материала нет строки с автором."),
            _w("tabloid", "/ˈtæb.lɔɪd/", "бульварная газета", "noun", "The tabloid used a sharper photo.", "Бульварная газета взяла более резкое фото."),
            _w("broadsheet", "/ˈbrɔːd.ʃiːt/", "серьёзная газета", "noun", "The broadsheet ran a longer investigation.", "Серьёзная газета дала более длинное расследование."),
            _w("spin", "/spɪn/", "подача, спин", "noun", "The spin made a delay sound like a gift.", "Подача превратила задержку в подарок."),
            _w("credibility", "/ˌkred.əˈbɪl.ə.ti/", "достоверность", "noun", "One error hurt the paper's credibility.", "Одна ошибка ударила по достоверности газеты."),
            _w("press release", "/ˈpres rɪˌliːs/", "пресс-релиз", "noun", "The press release is thinner than the report.", "Пресс-релиз тоньше самого отчёта."),
        ],
    ),
    _topic(
        "wellbeing",
        "Самочувствие и стресс",
        "Слова B2 про нагрузку, отдых, терапию и устойчивость.",
        "B2",
        [
            _w("stress", "/stres/", "стресс", "noun", "Deadline stress faded after the send.", "Стресс из-за срока спал после отправки."),
            _w("burnout", "/ˈbɜːn.aʊt/", "выгорание", "noun", "Burnout showed first as missed breakfasts.", "Выгорание сначала проявилось пропущенными завтраками."),
            _w("mindfulness", "/ˈmaɪnd.fəl.nəs/", "осознанность", "noun", "Ten minutes of mindfulness is enough.", "Десяти минут осознанности достаточно."),
            _w("therapy", "/ˈθer.ə.pi/", "терапия", "noun", "Therapy is on Thursday after work.", "Терапия в четверг после работы."),
            _w("counsellor", "/ˈkaʊn.səl.ə/", "консультант", "noun", "The counsellor asked one careful question.", "Консультант задал один осторожный вопрос."),
            _w("insomnia", "/ɪnˈsɒm.ni.ə/", "бессонница", "noun", "Insomnia got worse after the night shifts.", "Бессонница усилилась после ночных смен."),
            _w("cope", "/kəʊp/", "справляться", "verb", "She copes by walking before dinner.", "Она справляется: гуляет до ужина."),
            _w("overwhelm", "/ˌəʊ.vəˈwelm/", "перегружать", "verb", "Too many tabs overwhelm him.", "Слишком много вкладок его перегружает."),
            _w("resilience", "/rɪˈzɪl.i.əns/", "устойчивость", "noun", "Resilience here means a slower restart.", "Устойчивость здесь — это более медленный перезапуск."),
            _w("wellbeing", "/ˌwelˈbiː.ɪŋ/", "благополучие", "noun", "Staff wellbeing is more than free fruit.", "Благополучие сотрудников — это не только бесплатные фрукты."),
            _w("anxiety", "/æŋˈzaɪ.ə.ti/", "тревога", "noun", "Travel anxiety fades after the first hour.", "Тревога в дороге спадает после первого часа."),
            _w("fatigue", "/fəˈtiːɡ/", "усталость", "noun", "Screen fatigue is worse in the afternoon.", "Усталость от экрана сильнее после обеда."),
            _w("self-care", "/ˌself ˈkeə/", "забота о себе", "noun", "Self-care can be a short walk, not a spa.", "Забота о себе может быть короткой прогулкой, а не спа."),
            _w("boundary", "/ˈbaʊn.dər.i/", "граница", "noun", "A clear boundary is no mail after eight.", "Ясная граница — никаких писем после восьми."),
            _w("restorative", "/rɪˈstɒr.ə.tɪv/", "восстанавливающий", "adjective", "A restorative weekend has almost no plans.", "Восстанавливающие выходные почти без планов."),
            _w("grounded", "/ˈɡraʊn.dɪd/", "устойчивый, собранный", "adjective", "She felt more grounded after the walk.", "После прогулки она чувствовала себя собраннее."),
        ],
    ),
    _topic(
        "argument-rhetoric",
        "Довод и риторика",
        "Глаголы и имена C1 для спора: опровергнуть, уступить, аналогия, позиция.",
        "C1",
        [
            _w("refute", "/rɪˈfjuːt/", "опровергать", "verb", "One date is enough to refute the timeline.", "Одной даты достаточно, чтобы опровергнуть хронологию."),
            _w("concede", "/kənˈsiːd/", "признавать (в споре)", "verb", "I concede the sample is small.", "Признаю: выборка маленькая."),
            _w("assert", "/əˈsɜːt/", "утверждать", "verb", "They assert more than the chart can carry.", "Они утверждают больше, чем выдерживает график."),
            _w("rhetoric", "/ˈret.ər.ɪk/", "риторика", "noun", "The rhetoric is warmer than the policy.", "Риторика теплее самой политики."),
            _w("fallacy", "/ˈfæl.ə.si/", "логическая ошибка", "noun", "That is a fallacy, not a parallel case.", "Это логическая ошибка, а не параллельный случай."),
            _w("analogy", "/əˈnæl.ə.dʒi/", "аналогия", "noun", "The analogy with weather is too neat.", "Аналогия с погодой слишком аккуратная."),
            _w("rebuttal", "/rɪˈbʌt.əl/", "возражение", "noun", "The rebuttal is shorter than the claim.", "Возражение короче самого утверждения."),
            _w("stance", "/stɑːns/", "позиция", "noun", "Her stance on night buses did not shift.", "Её позиция по ночным автобусам не сдвинулась."),
            _w("warrant", "/ˈwɒr.ənt/", "основание вывода", "noun", "The warrant between fact and claim is thin.", "Основание между фактом и выводом тонкое."),
            _w("premise", "/ˈprem.ɪs/", "посылка", "noun", "If the premise fails, the rest falls.", "Если посылка неверна, падает и остальное."),
            _w("counterargument", "/ˈkaʊn.tərˌɑː.ɡjə.mənt/", "контраргумент", "noun", "A fair paper states the counterargument.", "Честная статья называет контраргумент."),
            _w("equivocate", "/ɪˈkwɪv.ə.keɪt/", "говорить двусмысленно", "verb", "Do not equivocate about the missing page.", "Не говори двусмысленно о пропавшей странице."),
            _w("bolster", "/ˈbəʊl.stə/", "укреплять (довод)", "verb", "Two interviews bolster the first finding.", "Два интервью укрепляют первый вывод."),
            _w("undercut", "/ˌʌn.dəˈkʌt/", "подрывать снизу", "verb", "The late figure undercuts the whole chart.", "Поздняя цифра подрывает весь график."),
            _w("caveat", "/ˈkæv.i.æt/", "оговорка", "noun", "Add a caveat about the weather that week.", "Добавь оговорку про погоду той недели."),
            _w("overstate", "/ˌəʊ.vəˈsteɪt/", "преувеличивать", "verb", "Do not overstate a local drop as a trend.", "Не выдавай местный спад за тенденцию."),
        ],
    ),
    _topic(
        "fine-shades",
        "Тонкие оттенки смысла",
        "Ещё слой C2: сдержанный, колкий, туманный, немногословный.",
        "C2",
        [
            _w("laconic", "/ləˈkɒn.ɪk/", "немногословный", "adjective", "His laconic note said only 'later'.", "Его немногословная записка гласила лишь «позже»."),
            _w("florid", "/ˈflɒr.ɪd/", "витиеватый", "adjective", "The florid speech hid a thin plan.", "Витиеватая речь прятала тонкий план."),
            _w("pithy", "/ˈpɪθ.i/", "ёмкий", "adjective", "A pithy line replaced the long slogan.", "Ёмкая строка заменила длинный слоган."),
            _w("sardonic", "/sɑːˈdɒn.ɪk/", "язвительный", "adjective", "A sardonic smile ended the exchange.", "Язвительная улыбка закончила обмен репликами."),
            _w("wistful", "/ˈwɪst.fəl/", "задумчиво-грустный", "adjective", "She sounded wistful about the old route.", "Она говорила о старом маршруте с тихой грустью."),
            _w("bleak", "/bliːk/", "мрачный", "adjective", "The forecast for the coastal road is bleak.", "Прогноз для прибрежной дороги мрачный."),
            _w("understated", "/ˌʌn.dəˈsteɪ.tɪd/", "сдержанный", "adjective", "The praise was understated and therefore sharper.", "Похвала была сдержанной и оттого острее."),
            _w("opaque", "/əʊˈpeɪk/", "непрозрачный", "adjective", "The last clause is deliberately opaque.", "Последний пункт намеренно непрозрачен."),
            _w("lucid", "/ˈluː.sɪd/", "ясный", "adjective", "A lucid paragraph saved the chapter.", "Ясный абзац спас главу."),
            _w("barbed", "/bɑːbd/", "колкий", "adjective", "One barbed remark stayed in the room.", "Одна колкая реплика осталась в зале."),
            _w("muted", "/ˈmjuː.tɪd/", "приглушённый", "adjective", "The reaction was muted, not hostile.", "Реакция была приглушённой, не враждебной."),
            _w("elliptical", "/ɪˈlɪp.tɪ.kəl/", "с пропусками, недоговорённый", "adjective", "The ending is elliptical on purpose.", "Концовка нарочно недоговорена."),
            _w("sententious", "/senˈten.ʃəs/", "нравоучительный", "adjective", "A sententious last line weakened the piece.", "Нравоучительная последняя строка ослабила текст."),
            _w("lapidary", "/ˈlæp.ɪ.dər.i/", "чеканный", "adjective", "The lapidary style fits a short plaque.", "Чеканный стиль подходит короткой табличке."),
            _w("turgid", "/ˈtɜː.dʒɪd/", "напыщенный", "adjective", "The turgid introduction hid a simple point.", "Напыщенное вступление прятало простую мысль."),
            _w("limpid", "/ˈlɪm.pɪd/", "прозрачный", "adjective", "Limpid prose is harder than it looks.", "Прозрачная проза труднее, чем кажется."),
        ],
    ),
]
