"""New CEFR topics for the third incremental vocab pack."""

from app.seed.vocab import _topic, _w

MORE_PLUS_TOPICS = [
    _topic(
        "hotels-staying",
        "Отель и ночёвка",
        "Ресепшен, бронь, багаж, этаж — слова для ночи в чужом городе.",
        "A2",
        [
            _w("reception", "/rɪˈsep.ʃən/", "ресепшен", "noun", "Ask at reception for a later checkout.", "Спроси на ресепшене про более поздний выезд."),
            _w("booking", "/ˈbʊk.ɪŋ/", "бронь", "noun", "The booking is under my family name.", "Бронь на мою фамилию."),
            _w("check-in", "/ˈtʃek ɪn/", "заселение", "noun", "Check-in starts at three, not before.", "Заселение с трёх, не раньше."),
            _w("checkout", "/ˈtʃek.aʊt/", "выезд", "noun", "Checkout is eleven; bags can stay till two.", "Выезд в одиннадцать; сумки можно оставить до двух."),
            _w("luggage", "/ˈlʌɡ.ɪdʒ/", "багаж", "noun", "Leave the luggage by the lift.", "Оставь багаж у лифта."),
            _w("lift", "/lɪft/", "лифт", "noun", "The lift is slow after breakfast.", "После завтрака лифт медленный."),
            _w("floor", "/flɔː/", "этаж", "noun", "Our room is on the fourth floor.", "Наш номер на четвёртом этаже."),
            _w("double room", "/ˌdʌb.əl ˈruːm/", "двухместный номер", "noun", "A double room is cheaper than two singles.", "Двухместный дешевле двух одноместных."),
            _w("single room", "/ˌsɪŋ.ɡəl ˈruːm/", "одноместный номер", "noun", "I booked a single room near the stairs.", "Я взял одноместный у лестницы."),
            _w("balcony", "/ˈbæl.kə.ni/", "балкон", "noun", "The balcony faces a quiet yard.", "Балкон выходит в тихий двор."),
            _w("reservation", "/ˌrez.əˈveɪ.ʃən/", "бронирование", "noun", "The reservation number is on the email.", "Номер бронирования в письме."),
            _w("cancel", "/ˈkæn.səl/", "отменять", "verb", "Cancel before six or you still pay.", "Отмени до шести, иначе всё равно заплатишь."),
            _w("key card", "/ˈkiː kɑːd/", "карта-ключ", "noun", "The key card stops working near the lift.", "Карта-ключ сбоит у лифта."),
            _w("wifi", "/ˈwaɪ.faɪ/", "вайфай", "noun", "The wifi password is on the door.", "Пароль вайфая на двери."),
            _w("housekeeping", "/ˈhaʊsˌkiː.pɪŋ/", "горничная служба", "noun", "Housekeeping comes after nine if you ask.", "Горничная приходит после девяти, если попросить."),
            _w("minibar", "/ˈmɪn.i.bɑː/", "мини-бар", "noun", "The minibar prices are on a card inside.", "Цены мини-бара на карточке внутри."),
            _w("late checkout", "/ˌleɪt ˈtʃek.aʊt/", "поздний выезд", "noun", "Late checkout costs extra on Sundays.", "Поздний выезд в воскресенье стоит дороже."),
            _w("twin room", "/ˌtwɪn ˈruːm/", "номер с двумя кроватями", "noun", "A twin room is better if you need two beds.", "Номер с двумя кроватями лучше, если нужны две."),
            _w("view", "/vjuː/", "вид из окна", "noun", "The view is a brick wall, not the river.", "Вид — кирпичная стена, не река."),
        ],
    ),
    _topic(
        "shops-errands",
        "Магазины и поручения",
        "Куда сходить в городе: аптека, очередь, чек, размер, часы работы.",
        "A2",
        [
            _w("chemist", "/ˈkem.ɪst/", "аптека", "noun", "The chemist on the corner closes at six.", "Аптека на углу закрывается в шесть."),
            _w("butcher", "/ˈbʊtʃ.ə/", "мясная лавка", "noun", "The butcher saves bones for soup on Fridays.", "В мясной по пятницам оставляют кости на суп."),
            _w("florist", "/ˈflɒr.ɪst/", "цветочный", "noun", "The florist opens before the first tram.", "Цветочный открывается до первого трамвая."),
            _w("hardware shop", "/ˈhɑːd.weə ʃɒp/", "хозяйственный", "noun", "The hardware shop has the right screws.", "В хозяйственном есть нужные шурупы."),
            _w("dry cleaner", "/ˈdraɪ ˌkliː.nə/", "химчистка", "noun", "The dry cleaner needs two days for the coat.", "Химчистке нужно два дня на пальто."),
            _w("newsagent", "/ˈnjuːzˌeɪ.dʒənt/", "газетный киоск", "noun", "The newsagent still sells paper maps.", "В газетном киоске всё ещё продают карты."),
            _w("opening hours", "/ˈəʊ.pən.ɪŋ ˌaʊəz/", "часы работы", "noun", "Opening hours change after a bank holiday.", "После праздника часы работы меняются."),
            _w("errand", "/ˈer.ənd/", "поручение", "noun", "The only errand left is the post office.", "Осталось одно поручение — почта."),
            _w("return", "/rɪˈtɜːn/", "возвращать товар", "verb", "You can return the kettle within fourteen days.", "Чайник можно вернуть в течение четырнадцати дней."),
            _w("sold out", "/ˌsəʊld ˈaʊt/", "распродано", "adjective", "The brown bread is sold out already.", "Коричневый хлеб уже распродали."),
            _w("carrier bag", "/ˈkær.i.ə bæɡ/", "пакет", "noun", "I forgot a carrier bag again.", "Я снова забыл пакет."),
            _w("greengrocer", "/ˈɡriːnˌɡrəʊ.sə/", "зеленной", "noun", "The greengrocer wraps apples in paper.", "В зеленном яблоки заворачивают в бумагу."),
            _w("size", "/saɪz/", "размер", "noun", "This size is too tight at the shoulders.", "Этот размер тесен в плечах."),
            _w("try on", "/ˌtraɪ ˈɒn/", "примерять", "verb", "Try on the coat before you buy it.", "Примерь пальто, прежде чем покупать."),
            _w("label", "/ˈleɪ.bəl/", "этикетка", "noun", "The label says wash at thirty.", "На этикетке написано стирать при тридцати."),
            _w("scale", "/skeɪl/", "весы", "noun", "Put the apples on the scale first.", "Сначала положи яблоки на весы."),
            _w("special offer", "/ˌspeʃ.əl ˈɒf.ə/", "акция", "noun", "The special offer ends on Sunday.", "Акция заканчивается в воскресенье."),
            _w("checkout", "/ˈtʃek.aʊt/", "касса самообслуживания", "noun", "The self checkout is faster after eight.", "Касса самообслуживания быстрее после восьми."),
        ],
    ),
    _topic(
        "phones-digital",
        "Телефон и сообщения",
        "Звонок, сигнал, без звука, пропущенный вызов — бытовой цифровой словарь.",
        "A2",
        [
            _w("call", "/kɔːl/", "звонить", "verb", "Call me when you reach the platform.", "Позвони, когда будешь на платформе."),
            _w("text", "/tekst/", "писать сообщение", "verb", "Text the gate number, not the whole plan.", "Напиши номер выхода, не весь план."),
            _w("signal", "/ˈsɪɡ.nəl/", "связь, сигнал", "noun", "There is no signal in the underpass.", "В переходе нет связи."),
            _w("ringtone", "/ˈrɪŋ.təʊn/", "рингтон", "noun", "The ringtone is too loud for the library.", "Рингтон слишком громкий для библиотеки."),
            _w("contact", "/ˈkɒn.tækt/", "контакт", "noun", "Save the new contact before you lose the card.", "Сохрани контакт, пока не потерял карточку."),
            _w("hang up", "/ˌhæŋ ˈʌp/", "класть трубку", "verb", "Hang up if the line stays silent.", "Положи трубку, если линия молчит."),
            _w("pick up", "/ˌpɪk ˈʌp/", "брать трубку", "verb", "Pick up if you see the school number.", "Бери трубку, если видишь номер школы."),
            _w("missed call", "/ˌmɪst ˈkɔːl/", "пропущенный вызов", "noun", "A missed call from the clinic came at noon.", "Пропущенный вызов из клиники пришёл в полдень."),
            _w("notification", "/ˌnəʊ.tɪ.fɪˈkeɪ.ʃən/", "уведомление", "noun", "Turn off notifications after nine.", "Выключи уведомления после девяти."),
            _w("mute", "/mjuːt/", "без звука", "verb", "Mute the group chat during the meeting.", "Поставь чат на без звука во время встречи."),
            _w("speaker", "/ˈspiː.kə/", "громкая связь", "noun", "Do not use speaker on the bus.", "Не включай громкую связь в автобусе."),
            _w("battery", "/ˈbæt.ər.i/", "батарея", "noun", "The battery dies before the last stop.", "Батарея садится до последней остановки."),
            _w("update", "/ˈʌp.deɪt/", "обновление", "noun", "The update can wait until you are on wifi.", "Обновление подождёт, пока будет вайфай."),
            _w("airplane mode", "/ˈeə.pleɪn məʊd/", "режим полёта", "noun", "Airplane mode stops the night pings.", "Режим полёта глушит ночные сигналы."),
            _w("blocked", "/blɒkt/", "заблокированный", "adjective", "The unknown number is now blocked.", "Неизвестный номер теперь заблокирован."),
            _w("swipe", "/swaɪp/", "свайпнуть", "verb", "Swipe up to close the last app.", "Свайпни вверх, чтобы закрыть последнее приложение."),
            _w("hotspot", "/ˈhɒt.spɒt/", "точка доступа", "noun", "The hotspot lasts until the train tunnel.", "Точка доступа живёт до тоннеля."),
            _w("unread", "/ʌnˈred/", "непрочитанный", "adjective", "Twelve unread messages can wait until lunch.", "Двенадцать непрочитанных подождут до обеда."),
        ],
    ),
    _topic(
        "housing-rent",
        "Аренда и жильё",
        "Хозяин, залог, договор, сырость, котёл — слова про квартиру.",
        "B1",
        [
            _w("landlord", "/ˈlænd.lɔːd/", "арендодатель", "noun", "The landlord painted the hall last May.", "Хозяин покрасил подъезд в прошлом мае."),
            _w("tenant", "/ˈten.ənt/", "арендатор", "noun", "Each tenant has a key to the side door.", "У каждого арендатора есть ключ от боковой двери."),
            _w("rent", "/rent/", "арендная плата", "noun", "Rent is due on the first working day.", "Аренду нужно платить в первый рабочий день."),
            _w("deposit", "/dɪˈpɒz.ɪt/", "залог", "noun", "The deposit comes back if the walls stay clean.", "Залог вернут, если стены останутся чистыми."),
            _w("lease", "/liːs/", "договор аренды", "noun", "The lease ends in September, not July.", "Договор заканчивается в сентябре, не в июле."),
            _w("furnished", "/ˈfɜː.nɪʃt/", "меблированный", "adjective", "The furnished flat already has a table.", "В меблированной квартире стол уже есть."),
            _w("utility", "/juːˈtɪl.ə.ti/", "коммунальный платёж", "noun", "One utility bill covers water and heat.", "Один коммунальный счёт закрывает воду и тепло."),
            _w("flatmate", "/ˈflæt.meɪt/", "сосед по квартире", "noun", "A new flatmate arrives on Sunday.", "Новый сосед приезжает в воскресенье."),
            _w("mortgage", "/ˈmɔː.ɡɪdʒ/", "ипотека", "noun", "The mortgage rate dropped after the review.", "Ставка по ипотеке упала после пересмотра."),
            _w("estate agent", "/ɪˈsteɪt ˌeɪ.dʒənt/", "риелтор", "noun", "The estate agent was late to the viewing.", "Риелтор опоздал на просмотр."),
            _w("viewing", "/ˈvjuː.ɪŋ/", "просмотр квартиры", "noun", "The viewing is only fifteen minutes.", "Просмотр всего пятнадцать минут."),
            _w("damp", "/dæmp/", "сырость", "noun", "Damp showed first behind the wardrobe.", "Сырость сначала проявилась за шкафом."),
            _w("mould", "/məʊld/", "плесень", "noun", "Mould returned after the wet autumn.", "Плесень вернулась после сырой осени."),
            _w("boiler", "/ˈbɔɪ.lə/", "котёл", "noun", "The boiler clicks twice before it starts.", "Котёл дважды щёлкает, прежде чем запуститься."),
            _w("notice period", "/ˈnəʊ.tɪs ˌpɪə.ri.əd/", "срок уведомления", "noun", "The notice period is one calendar month.", "Срок уведомления — один календарный месяц."),
            _w("inventory", "/ˈɪn.vən.tər.i/", "опись имущества", "noun", "Check the inventory before you sign.", "Проверь опись, прежде чем подписывать."),
            _w("sublet", "/ˌsʌbˈlet/", "сдавать в субаренду", "verb", "You cannot sublet without written consent.", "Сдавать в субаренду нельзя без письменного согласия."),
            _w("guarantor", "/ˌɡær.ənˈtɔː/", "поручитель", "noun", "A guarantor is required for the first year.", "На первый год нужен поручитель."),
            _w("service charge", "/ˈsɜː.vɪs tʃɑːdʒ/", "плата за содержание", "noun", "The service charge rose after the lift repair.", "Плата за содержание выросла после ремонта лифта."),
            _w("move-in", "/ˈmuːv ɪn/", "заезд", "noun", "Move-in is after midday on the first.", "Заезд после полудня первого числа."),
        ],
    ),
    _topic(
        "crime-safety",
        "Безопасность и право",
        "Кража, свидетель, штраф, сигнал тревоги — практический бытовой слой.",
        "B1",
        [
            _w("theft", "/θeft/", "кража", "noun", "The theft happened during the short gap.", "Кража случилась в короткий промежуток."),
            _w("steal", "/stiːl/", "красть", "verb", "Someone tried to steal a bike by the shop.", "Кто-то пытался украсть велосипед у магазина."),
            _w("witness", "/ˈwɪt.nəs/", "свидетель", "noun", "A witness saw the van leave after nine.", "Свидетель видел, как фургон уехал после девяти."),
            _w("suspect", "/ˈsʌs.pekt/", "подозреваемый", "noun", "The suspect was still on the platform.", "Подозреваемый всё ещё был на платформе."),
            _w("arrest", "/əˈrest/", "арестовывать", "verb", "Police did not arrest anyone at the scene.", "На месте никого не арестовали."),
            _w("report", "/rɪˈpɔːt/", "заявлять", "verb", "Report the missing bag before you leave town.", "Заяви о пропаже сумки, прежде чем уехать."),
            _w("burglary", "/ˈbɜː.ɡlər.i/", "кража со взломом", "noun", "The burglary left only a broken latch.", "После взлома сломалась только защёлка."),
            _w("pickpocket", "/ˈpɪkˌpɒk.ɪt/", "карманник", "noun", "A pickpocket works the busy tram.", "Карманник работает в час пик в трамвае."),
            _w("alarm", "/əˈlɑːm/", "сигнализация", "noun", "The alarm went off when the door stuck.", "Сигнализация сработала, когда дверь заело."),
            _w("evidence", "/ˈev.ɪ.dəns/", "улика", "noun", "The only evidence is a wet footprint.", "Единственная улика — мокрый след."),
            _w("charge", "/tʃɑːdʒ/", "обвинение", "noun", "The charge was dropped after the second statement.", "Обвинение сняли после второго показания."),
            _w("victim", "/ˈvɪk.tɪm/", "потерпевший", "noun", "The victim waited in a quiet room.", "Потерпевший ждал в тихой комнате."),
            _w("patrol", "/pəˈtrəʊl/", "патруль", "noun", "A night patrol walks the harbour wall.", "Ночной патруль идёт по стенке гавани."),
            _w("lock up", "/ˌlɒk ˈʌp/", "запирать на ночь", "verb", "Lock up the shed even for an hour.", "Запирай сарай даже на час."),
            _w("fraud", "/frɔːd/", "мошенничество", "noun", "The fraud used a copied payment page.", "Мошенничество шло через копию страницы оплаты."),
            _w("statement", "/ˈsteɪt.mənt/", "показания", "noun", "Write the statement while the details are fresh.", "Пиши показания, пока детали свежие."),
            _w("safe", "/seɪf/", "безопасный", "adjective", "This street is safe after ten now.", "Эта улица после десяти теперь безопасна."),
            _w("password reset", "/ˈpɑːs.wɜːd ˌriː.set/", "сброс пароля", "noun", "A fake password reset is still fraud.", "Липовый сброс пароля — всё равно мошенничество."),
            _w("lost property", "/ˌlɒst ˈprɒp.ə.ti/", "бюро находок", "noun", "Ask lost property before you buy a new pass.", "Спроси в бюро находок, прежде чем покупать новый проездной."),
            _w("emergency", "/ɪˈmɜː.dʒən.si/", "чрезвычайная ситуация", "noun", "The emergency exit is behind the stairs.", "Аварийный выход за лестницей."),
        ],
    ),
    _topic(
        "office-meetings",
        "Совещания и офис",
        "Повестка, протокол, перенос, слайды — слова для рабочих встреч.",
        "B2",
        [
            _w("agenda", "/əˈdʒen.də/", "повестка", "noun", "The agenda forgot the night-shift item.", "В повестке забыли пункт про ночную смену."),
            _w("minutes", "/ˈmɪn.ɪts/", "протокол", "noun", "The minutes missed who owns the leak.", "В протоколе не сказано, кто отвечает за протечку."),
            _w("brainstorm", "/ˈbreɪn.stɔːm/", "мозговой штурм", "verb", "Brainstorm titles after you have the data.", "Штурмуйте названия, когда уже есть данные."),
            _w("postpone", "/pəʊstˈpəʊn/", "откладывать", "verb", "Postpone if two people are still on a train.", "Отложите, если двое всё ещё в поезде."),
            _w("adjourn", "/əˈdʒɜːn/", "объявлять перерыв", "verb", "They adjourned until the figure arrived.", "Они объявили перерыв, пока не пришла цифра."),
            _w("quorum", "/ˈkwɔː.rəm/", "кворум", "noun", "There is no quorum before ten.", "До десяти кворума нет."),
            _w("action item", "/ˈæk.ʃən ˌaɪ.təm/", "пункт к исполнению", "noun", "One action item is enough if it is owned.", "Одного пункта хватит, если за ним есть ответственный."),
            _w("briefing", "/ˈbriː.fɪŋ/", "брифинг", "noun", "The briefing lasted twelve minutes.", "Брифинг длился двенадцать минут."),
            _w("slide", "/slaɪd/", "слайд", "noun", "Cut the last slide; it repeats the chart.", "Убери последний слайд: он повторяет график."),
            _w("timeslot", "/ˈtaɪm.slɒt/", "слот времени", "noun", "The only free timeslot is after four.", "Свободный слот только после четырёх."),
            _w("recap", "/ˈriː.kæp/", "краткое резюме", "noun", "A three-line recap is enough for the group.", "Трёхстрочного резюме группе хватит."),
            _w("unblock", "/ʌnˈblɒk/", "снимать блокер", "verb", "Unblock the form before you add more fields.", "Сними блокер с формы, прежде чем добавлять поля."),
            _w("owner", "/ˈəʊ.nə/", "ответственный", "noun", "Name an owner or the task will drift.", "Назови ответственного, иначе задача поплывёт."),
            _w("cadence", "/ˈkeɪ.dəns/", "ритм встреч", "noun", "A weekly cadence is too often for this group.", "Еженедельный ритм для этой группы слишком частый."),
            _w("pre-read", "/ˈpriː riːd/", "материалы заранее", "noun", "The pre-read is two pages, not a deck.", "Материалы заранее — две страницы, не колода слайдов."),
            _w("dial-in", "/ˈdaɪəl ɪn/", "подключение по телефону", "noun", "The dial-in number is on the calendar invite.", "Номер для звонка в приглашении календаря."),
            _w("parking lot", "/ˈpɑː.kɪŋ lɒt/", "отложенные вопросы", "noun", "Put the logo debate in the parking lot.", "Спор про логотип отложите в список на потом."),
            _w("takeaway", "/ˈteɪk.ə.weɪ/", "вывод совещания", "noun", "The takeaway is a later start, not more staff.", "Вывод — более поздний старт, не больше людей."),
        ],
    ),
    _topic(
        "climate-action",
        "Климат и действие",
        "Выбросы, свалка, возобновляемое, след — слова про среду без чужих слоганов.",
        "B2",
        [
            _w("recycle", "/ˌriːˈsaɪ.kəl/", "сдавать на переработку", "verb", "Recycle the glass after the last jar.", "Сдай стекло после последней банки."),
            _w("landfill", "/ˈlænd.fɪl/", "свалка", "noun", "The landfill is full after the storm clean-up.", "Свалка заполнилась после уборки после бури."),
            _w("compost", "/ˈkɒm.pɒst/", "компост", "noun", "Food scraps go in the compost, not the bin.", "Остатки еды — в компост, не в ведро."),
            _w("renewable", "/rɪˈnjuː.ə.bəl/", "возобновляемый", "adjective", "The new roof uses renewable power at noon.", "Новая крыша в полдень берёт возобновляемую энергию."),
            _w("emission", "/ɪˈmɪʃ.ən/", "выброс", "noun", "The emission cut is local, not national.", "Сокращение выброса местное, не общенациональное."),
            _w("footprint", "/ˈfʊt.prɪnt/", "след", "noun", "A shorter commute cuts the weekly footprint.", "Более короткая дорога на работу снижает недельный след."),
            _w("conservation", "/ˌkɒn.səˈveɪ.ʃən/", "охрана природы", "noun", "Conservation here means leaving the hedge alone.", "Охрана здесь — не трогать изгородь."),
            _w("habitat", "/ˈhæb.ɪ.tæt/", "среда обитания", "noun", "The new path cuts through a quiet habitat.", "Новая тропа режет тихую среду обитания."),
            _w("pollute", "/pəˈluːt/", "загрязнять", "verb", "Paint runoff can pollute the small stream.", "Стоки краски могут загрязнить ручей."),
            _w("biodegradable", "/ˌbaɪ.əʊ.dɪˈɡreɪ.də.bəl/", "биоразлагаемый", "adjective", "The bag is biodegradable, but slowly.", "Пакет биоразлагаемый, но медленно."),
            _w("drought", "/draʊt/", "засуха", "noun", "The drought left the reservoir low.", "Засуха опустила уровень водохранилища."),
            _w("floodplain", "/ˈflʌd.pleɪn/", "пойма", "noun", "Do not build on the floodplain after last year.", "Не строй на пойме после прошлого года."),
            _w("offset", "/ˈɒf.set/", "компенсация выбросов", "noun", "The offset is a tree scheme, not a free pass.", "Компенсация — схема с деревьями, не индульгенция."),
            _w("retrofit", "/ˈret.rəʊ.fɪt/", "модернизировать здание", "verb", "They will retrofit the hall before winter.", "Зал модернизируют до зимы."),
            _w("heatwave", "/ˈhiːt.weɪv/", "волна жары", "noun", "The heatwave closed the school at noon.", "Волна жары закрыла школу в полдень."),
            _w("divest", "/daɪˈvest/", "выводить деньги", "verb", "The town voted to divest from the old plant.", "Город проголосовал вывести деньги из старого завода."),
            _w("greenwash", "/ˈɡriːn.wɒʃ/", "притворяться зелёным", "verb", "Do not greenwash a later train as climate policy.", "Не выдавай поздний поезд за климатическую политику."),
            _w("mitigate", "/ˈmɪt.ɪ.ɡeɪt/", "смягчать ущерб", "verb", "Planting will not mitigate a blocked drain.", "Посадка не смягчит забитый сток."),
            _w("adaptation", "/ˌæd.əpˈteɪ.ʃən/", "адаптация", "noun", "Adaptation here is a higher doorstep, not a slogan.", "Адаптация здесь — более высокий порог, не слоган."),
            _w("reuse", "/ˌriːˈjuːz/", "использовать повторно", "verb", "Reuse the jars for dry rice.", "Используй банки повторно для сухого риса."),
        ],
    ),
    _topic(
        "research-writing",
        "Исследование и текст",
        "Метод, цитата, черновик, выборка — слова для учёбы и отчёта.",
        "C1",
        [
            _w("abstract", "/ˈæb.strækt/", "аннотация", "noun", "The abstract hides the small sample.", "Аннотация прячет маленькую выборку."),
            _w("methodology", "/ˌmeθ.əˈdɒl.ə.dʒi/", "методология", "noun", "The methodology is a walk-along, not a survey.", "Методология — прогулка рядом, не опрос."),
            _w("citation", "/saɪˈteɪ.ʃən/", "цитирование", "noun", "One citation is from a blog, not a paper.", "Одна ссылка из блога, не из статьи."),
            _w("peer review", "/ˌpɪə rɪˈvjuː/", "рецензирование", "noun", "Peer review asked for a later year of data.", "Рецензенты попросили данные за более поздний год."),
            _w("bias", "/ˈbaɪ.əs/", "смещение", "noun", "Selection bias sits in who answered at night.", "Смещение в том, кто отвечал ночью."),
            _w("sample", "/ˈsɑːm.pəl/", "выборка", "noun", "The sample is one street, not a city.", "Выборка — одна улица, не город."),
            _w("draft", "/drɑːft/", "черновик", "noun", "The third draft is shorter and clearer.", "Третий черновик короче и яснее."),
            _w("revise", "/rɪˈvaɪz/", "перерабатывать", "verb", "Revise the claim after the new figure.", "Переработай утверждение после новой цифры."),
            _w("plagiarism", "/ˈpleɪ.dʒər.ɪ.zəm/", "плагиат", "noun", "Close paraphrase without a source is still plagiarism.", "Близкий пересказ без источника — всё равно плагиат."),
            _w("literature review", "/ˈlɪt.rə.tʃə rɪˌvjuː/", "обзор литературы", "noun", "The literature review stops in 2019.", "Обзор литературы обрывается на 2019-м."),
            _w("dataset", "/ˈdeɪ.tə.set/", "набор данных", "noun", "The dataset excludes weekends on purpose.", "Набор данных нарочно без выходных."),
            _w("significance", "/sɪɡˈnɪf.ɪ.kəns/", "значимость", "noun", "Statistical significance is not the same as a useful gap.", "Статистическая значимость — не то же, что полезный разрыв."),
            _w("redraft", "/ˌriːˈdrɑːft/", "переписывать заново", "verb", "Redraft the opening; the rest can stay.", "Перепиши вступление, остальное можно оставить."),
            _w("triangulate", "/traɪˈæŋ.ɡjə.leɪt/", "сверять три источника", "verb", "Triangulate the count with the night log.", "Сверь подсчёт с ночным журналом."),
            _w("working paper", "/ˈwɜː.kɪŋ ˌpeɪ.pə/", "рабочий доклад", "noun", "The working paper is clearer than the talk.", "Рабочий доклад яснее устного выступления."),
            _w("replicability", "/ˌrep.lɪ.kəˈbɪl.ə.ti/", "воспроизводимость", "noun", "Replicability fails if the route is not named.", "Воспроизводимость падает, если маршрут не назван."),
            _w("preprint", "/ˈpriː.prɪnt/", "препринт", "noun", "The preprint still has the old chart title.", "В препринте всё ещё старое название графика."),
            _w("field notes", "/ˈfiːld nəʊts/", "полевые записи", "noun", "Field notes are messier than the final table.", "Полевые записи грязнее итоговой таблицы."),
        ],
    ),
    _topic(
        "public-discourse",
        "Публичная речь",
        "Консенсус, рамка спора, подотчётность — слой для общественной речи.",
        "C1",
        [
            _w("consensus", "/kənˈsen.səs/", "согласие большинства", "noun", "There is no consensus on the later opening.", "Согласия по более позднему открытию нет."),
            _w("dissent", "/dɪˈsent/", "особое мнение", "noun", "A short dissent is in the annex.", "Краткое особое мнение — в приложении."),
            _w("mandate", "/ˈmæn.deɪt/", "мандат", "noun", "The mandate is a quieter street, not a ban.", "Мандат — более тихая улица, не запрет."),
            _w("framing", "/ˈfreɪ.mɪŋ/", "рамка подачи", "noun", "The framing turns a delay into a gift.", "Рамка подачи превращает задержку в подарок."),
            _w("legitimacy", "/ləˈdʒɪt.ɪ.mə.si/", "легитимность", "noun", "Legitimacy fell after the closed meeting.", "Легитимность упала после закрытого заседания."),
            _w("accountability", "/əˌkaʊn.təˈbɪl.ə.ti/", "подотчётность", "noun", "Accountability needs a named owner, not a slogan.", "Подотчётности нужен именной ответственный, не слоган."),
            _w("backlash", "/ˈbæk.læʃ/", "обратная реакция", "noun", "The backlash came from the last two streets.", "Обратная реакция пришла с двух последних улиц."),
            _w("talking point", "/ˈtɔː.kɪŋ pɔɪnt/", "заготовленный тезис", "noun", "That talking point ignores the night figure.", "Этот тезис обходит ночную цифру."),
            _w("grassroots", "/ˈɡrɑːs.ruːts/", "низовой", "adjective", "A grassroots list filled the hall.", "Низовой список заполнил зал."),
            _w("oversight", "/ˈəʊ.və.saɪt/", "надзор", "noun", "Oversight failed when the log went missing.", "Надзор не сработал, когда пропал журнал."),
            _w("whistleblower", "/ˈwɪs.əlˌbləʊ.ə/", "разоблачитель", "noun", "The whistleblower used the internal channel first.", "Разоблачитель сначала пошёл по внутреннему каналу."),
            _w("public interest", "/ˌpʌb.lɪk ˈɪn.trəst/", "общественный интерес", "noun", "Public interest is the night route, not the slogan.", "Общественный интерес — ночной маршрут, не слоган."),
            _w("deliberation", "/dɪˌlɪb.əˈreɪ.ʃən/", "обсуждение", "noun", "Deliberation was shorter than the press note.", "Обсуждение было короче пресс-заметки."),
            _w("opt-out", "/ˈɒpt aʊt/", "отказ от участия", "noun", "An opt-out is still a decision.", "Отказ от участия — тоже решение."),
            _w("safeguard", "/ˈseɪf.ɡɑːd/", "гарантия", "noun", "The only safeguard is a named review date.", "Единственная гарантия — названная дата пересмотра."),
            _w("sunset clause", "/ˈsʌn.set ˌklɔːz/", "срок действия нормы", "noun", "A sunset clause ends the trial in June.", "Срок действия нормы заканчивает эксперимент в июне."),
            _w("silence", "/ˈsaɪ.ləns/", "умолчание", "noun", "The silence on night buses is the story.", "Умолчание про ночные автобусы и есть история."),
            _w("stake", "/steɪk/", "интерес, ставка", "noun", "Each street has a different stake in the hours.", "У каждой улицы свой интерес к часам работы."),
        ],
    ),
    _topic(
        "money-everyday",
        "Деньги каждый день",
        "Наличные, сдача, одолжить, накопить, чаевые — без банковского жаргона.",
        "A2",
        [
            _w("cash", "/kæʃ/", "наличные", "noun", "The stall still prefers cash after six.", "После шести ларёк всё ещё предпочитает наличные."),
            _w("borrow", "/ˈbɒr.əʊ/", "занимать", "verb", "Borrow a pound if you are short for the ticket.", "Займи фунт, если на билет не хватает."),
            _w("lend", "/lend/", "давать в долг", "verb", "I can lend you the fare until Friday.", "Могу одолжить на проезд до пятницы."),
            _w("save", "/seɪv/", "копить", "verb", "Save the coins in the jar by the sink.", "Копи монеты в банке у раковины."),
            _w("spend", "/spend/", "тратить", "verb", "Do not spend the last note on a snack.", "Не трать последнюю купюру на перекус."),
            _w("waste", "/weɪst/", "транжирить", "verb", "Do not waste money on a second map.", "Не трать деньги на вторую карту."),
            _w("fare", "/feə/", "плата за проезд", "noun", "The fare rose after the new year.", "Плата за проезд выросла после Нового года."),
            _w("owe", "/əʊ/", "быть должным", "verb", "I still owe you for the shared taxi.", "Я всё ещё должен тебе за общее такси."),
            _w("pay back", "/ˌpeɪ ˈbæk/", "отдавать долг", "verb", "I will pay back the fare on Monday.", "Отдам за проезд в понедельник."),
            _w("broke", "/brəʊk/", "без денег", "adjective", "I am broke until the Friday transfer.", "Я без денег до пятничного перевода."),
            _w("purse", "/pɜːs/", "кошелёк", "noun", "The purse is still on the kitchen chair.", "Кошелёк всё ещё на кухонном стуле."),
            _w("ATM", "/ˌeɪ.tiːˈem/", "банкомат", "noun", "The ATM on the corner is out of cash.", "Банкомат на углу без наличных."),
            _w("PIN", "/pɪn/", "пин-код", "noun", "Cover the PIN even on an empty street.", "Закрой пин даже на пустой улице."),
            _w("refund", "/ˈriː.fʌnd/", "возврат денег", "noun", "The refund takes five working days.", "Возврат идёт пять рабочих дней."),
            _w("split", "/splɪt/", "делить счёт", "verb", "We can split the bill if the machine works.", "Можем разделить счёт, если автомат работает."),
            _w("cheaply", "/ˈtʃiːp.li/", "дёшево", "adverb", "You can eat cheaply if you skip the station café.", "Можно поесть дёшево, если обойти вокзальное кафе."),
            _w("in debt", "/ɪn ˈdet/", "в долгу", "adjective", "He is in debt after the broken boiler.", "Он в долгу после сломанного котла."),
            _w("savings", "/ˈseɪ.vɪŋz/", "накопления", "noun", "The savings cover one month of rent.", "Накоплений хватает на месяц аренды."),
        ],
    ),
    _topic(
        "kitchen-actions",
        "Кухня: действия",
        "Кипятить, жарить, мешать, остужать — глаголы для простой готовки.",
        "A2",
        [
            _w("boil", "/bɔɪl/", "кипятить", "verb", "Boil the potatoes for twelve minutes.", "Кипяти картошку двенадцать минут."),
            _w("fry", "/fraɪ/", "жарить", "verb", "Fry the onions until they look soft.", "Жарь лук, пока он не станет мягким."),
            _w("bake", "/beɪk/", "печь", "verb", "Bake the tray on the middle shelf.", "Пеки противень на средней полке."),
            _w("roast", "/rəʊst/", "запекать", "verb", "Roast the roots with a little oil.", "Запеки корнеплоды с небольшим количеством масла."),
            _w("stir", "/stɜː/", "мешать", "verb", "Stir the rice so it does not stick.", "Мешай рис, чтобы не прилип."),
            _w("pour", "/pɔː/", "наливать", "verb", "Pour the sauce at the table, not in the pan.", "Налей соус за столом, не на сковороде."),
            _w("peel", "/piːl/", "чистить кожуру", "verb", "Peel the apple over the sink.", "Чисти яблоко над раковиной."),
            _w("grate", "/ɡreɪt/", "тереть", "verb", "Grate a little cheese over the top.", "Натри немного сыра сверху."),
            _w("taste", "/teɪst/", "пробовать", "verb", "Taste the soup before you add salt.", "Попробуй суп, прежде чем сыпать соль."),
            _w("cool", "/kuːl/", "остужать", "verb", "Cool the pie before you cut it.", "Остуди пирог, прежде чем резать."),
            _w("drain", "/dreɪn/", "откидывать", "verb", "Drain the pasta, but keep a cup of water.", "Откинь пасту, но оставь чашку воды."),
            _w("serve", "/sɜːv/", "подавать", "verb", "Serve the stew in the wide bowls.", "Подай рагу в широких мисках."),
            _w("preheat", "/ˌpriːˈhiːt/", "разогревать духовку", "verb", "Preheat the oven while you chop.", "Разогрей духовку, пока режешь."),
            _w("season", "/ˈsiː.zən/", "приправлять", "verb", "Season at the end if the stock is salty.", "Приправляй в конце, если бульон солёный."),
            _w("cover", "/ˈkʌv.ə/", "накрывать", "verb", "Cover the pan or the sauce will dry.", "Накрой сковороду, иначе соус высохнет."),
            _w("saucepan", "/ˈsɔːs.pən/", "кастрюля", "noun", "Use the smaller saucepan for the sauce.", "Для соуса возьми кастрюлю поменьше."),
            _w("chopping board", "/ˈtʃɒp.ɪŋ bɔːd/", "доска для резки", "noun", "Wash the chopping board after the onion.", "Вымой доску после лука."),
            _w("leftovers", "/ˈleftˌəʊ.vəz/", "остатки", "noun", "Leftovers become tomorrow's lunch.", "Остатки станут завтрашним обедом."),
        ],
    ),
    _topic(
        "time-calendar",
        "Календарь и сроки",
        "Вчера, срок, выходной, вовремя — слова про время в быту.",
        "A1",
        [
            _w("today", "/təˈdeɪ/", "сегодня", "adverb", "The shop is quieter today.", "Сегодня в магазине тише."),
            _w("yesterday", "/ˈjes.tə.deɪ/", "вчера", "adverb", "Yesterday the last bus left early.", "Вчера последний автобус ушёл рано."),
            _w("tomorrow", "/təˈmɒr.əʊ/", "завтра", "adverb", "Tomorrow the market opens at eight.", "Завтра рынок откроется в восемь."),
            _w("tonight", "/təˈnaɪt/", "сегодня вечером", "adverb", "Tonight we eat late after the train.", "Сегодня вечером едим поздно после поезда."),
            _w("morning", "/ˈmɔː.nɪŋ/", "утро", "noun", "The morning is colder by the river.", "Утром у реки холоднее."),
            _w("afternoon", "/ˌɑːf.təˈnuːn/", "день", "noun", "The office is quieter in the afternoon.", "После полудня в офисе тише."),
            _w("evening", "/ˈiːv.nɪŋ/", "вечер", "noun", "The evening walk is short in winter.", "Вечерняя прогулка зимой короткая."),
            _w("late", "/leɪt/", "поздний", "adjective", "The late tram is still better than a taxi.", "Поздний трамвай всё равно лучше такси."),
            _w("early", "/ˈɜː.li/", "ранний", "adjective", "An early start beats the school traffic.", "Ранний выход обходит школьные пробки."),
            _w("hour", "/aʊə/", "час", "noun", "The walk takes one hour if it is dry.", "Прогулка занимает час, если сухо."),
            _w("minute", "/ˈmɪn.ɪt/", "минута", "noun", "Wait one minute under the clock.", "Подожди минуту под часами."),
            _w("week", "/wiːk/", "неделя", "noun", "The course lasts one week.", "Курс длится одну неделю."),
            _w("month", "/mʌnθ/", "месяц", "noun", "The ticket is valid for one month.", "Билет действует один месяц."),
            _w("year", "/jɪə/", "год", "noun", "She has lived here for a year.", "Она живёт здесь уже год."),
            _w("holiday", "/ˈhɒl.ə.deɪ/", "праздник", "noun", "The next holiday is a short Monday.", "Следующий праздник — короткий понедельник."),
            _w("appointment", "/əˈpɔɪnt.mənt/", "запись", "noun", "The appointment is at a quarter to three.", "Запись без четверти три."),
            _w("on time", "/ˌɒn ˈtaɪm/", "вовремя", "adverb", "The ferry is on time if the wind drops.", "Паром вовремя, если ветер спадёт."),
            _w("schedule", "/ˈʃed.juːl/", "график", "noun", "The new schedule starts next Monday.", "Новый график начинается в следующий понедельник."),
        ],
    ),
    _topic(
        "rare-register",
        "Редкий регистр",
        "Слова C2 для точной оценки тона, не коллекция редких прилагательных ради списка.",
        "C2",
        [
            _w("captious", "/ˈkæp.ʃəs/", "придирчивый", "adjective", "A captious note delayed a simple fix.", "Придирчивая записка задержала простой ремонт."),
            _w("nugatory", "/ˈnjuː.ɡə.tər.i/", "ничтожный по силе", "adjective", "The promise is nugatory without a date.", "Обещание ничтожно без даты."),
            _w("peremptory", "/pəˈremp.tər.i/", "безапелляционный", "adjective", "The peremptory last line closed the door.", "Безапелляционная последняя строка закрыла дверь."),
            _w("supercilious", "/ˌsuː.pəˈsɪl.i.əs/", "надменный", "adjective", "A supercilious smile ended the exchange.", "Надменная улыбка закончила обмен."),
            _w("punctilious", "/pʌŋkˈtɪl.i.əs/", "педантичный", "adjective", "Punctilious timing saved the last ferry.", "Педантичное время спасло последний паром."),
            _w("sesquipedalian", "/ˌses.kwɪ.pɪˈdeɪ.li.ən/", "длиннословный", "adjective", "The sesquipedalian opening hid a short point.", "Длиннословное вступление прятало короткую мысль."),
            _w("oleaginous", "/ˌəʊ.liˈædʒ.ɪ.nəs/", "масляно-угодливый", "adjective", "The oleaginous thanks felt like a delay tactic.", "Масляная благодарность была похожа на тактику оттяжки."),
            _w("perspicacious", "/ˌpɜː.spɪˈkeɪ.ʃəs/", "проницательный", "adjective", "A perspicacious reader named the missing hour.", "Проницательный читатель назвал пропавший час."),
            _w("lucubrations", "/ˌluː.kjʊˈbreɪ.ʃənz/", "ночные штудии", "noun", "The lucubrations added a footnote, not a fact.", "Ночные штудии добавили сноску, не факт."),
            _w("obiter", "/ˈɒb.ɪ.tə/", "мимоходом", "adverb", "The date appears only obiter in the annex.", "Дата появляется лишь мимоходом в приложении."),
            _w("captiousness", "/ˈkæp.ʃəs.nəs/", "придирчивость", "noun", "Captiousness delayed a one-line fix.", "Придирчивость задержала правку на одну строку."),
            _w("orotundity", "/ˌɒr.əˈtʌn.də.ti/", "пышность речи", "noun", "The orotundity hid a missing date.", "Пышность речи спрятала пропавшую дату."),
            _w("lapidary style", "/ˈlæp.ɪ.dər.i staɪl/", "чеканный стиль", "noun", "A lapidary style fits a short plaque.", "Чеканный стиль подходит короткой табличке."),
            _w("minatory note", "/ˈmɪn.ə.tər.i nəʊt/", "угрожающая записка", "noun", "The minatory note named no owner.", "Угрожающая записка не назвала ответственного."),
            _w("jejune recap", "/dʒɪˈdʒuːn ˈriː.kæp/", "тощее резюме", "noun", "The jejune recap skipped the night figure.", "Тощее резюме обошло ночную цифру."),
            _w("sibylline clause", "/ˈsɪb.ɪ.laɪn klɔːz/", "тёмный пункт", "noun", "The sibylline clause hid the real date.", "Тёмный пункт спрятал настоящую дату."),
        ],
    ),
]
