"""Third incremental CEFR pack: extra words on existing slugs plus new themes."""

from app.seed.vocab import _topic, _w
from app.seed.plus_topics_more import MORE_PLUS_TOPICS


PLUS_WORDS_BY_SLUG = {
    "everyday-objects": [
        _w("stool", "/stuːl/", "табурет", "noun", "The kitchen stool wobbles on one leg.", "Кухонный табурет шатается на одной ножке."),
        _w("plug", "/plʌɡ/", "вилка, штекер", "noun", "The plug does not fit this socket.", "Вилка не подходит к этой розетке."),
        _w("sponge", "/spʌndʒ/", "губка", "noun", "Rinse the sponge after the dishes.", "Прополощи губку после посуды."),
        _w("ladder", "/ˈlæd.ə/", "лестница-стремянка", "noun", "Use a ladder for the top shelf.", "Для верхней полки возьми стремянку."),
        _w("bucket", "/ˈbʌk.ɪt/", "ведро", "noun", "Fill the bucket from the garden tap.", "Наполни ведро из садового крана."),
        _w("kettle", "/ˈket.əl/", "чайник", "noun", "The kettle clicks off when the water boils.", "Чайник щёлкает, когда вода закипает."),
        _w("thermos", "/ˈθɜː.məs/", "термос", "noun", "Tea stays hot in this thermos until noon.", "В этом термосе чай остаётся горячим до полудня."),
        _w("remote", "/rɪˈməʊt/", "пульт", "noun", "The remote is under the sofa cushion.", "Пульт лежит под диванной подушкой."),
        _w("doorknob", "/ˈdɔː.nɒb/", "дверная ручка", "noun", "The doorknob is loose again.", "Дверная ручка снова разболталась."),
        _w("coaster", "/ˈkəʊ.stə/", "подставка под стакан", "noun", "Put a coaster under the wet glass.", "Поставь подставку под мокрый стакан."),
    ],
    "family-people": [
        _w("newborn", "/ˈnjuː.bɔːn/", "новорождённый", "noun", "The newborn slept through the visit.", "Новорождённый проспал весь визит."),
        _w("godparent", "/ˈɡɒdˌpeə.rənt/", "крёстный, крёстная", "noun", "Her godparent sent a small book.", "Крёстная прислала небольшую книгу."),
        _w("household", "/ˈhaʊs.həʊld/", "семья, домохозяйство", "noun", "The household shares one laundry day.", "В доме стирают в один общий день."),
        _w("caretaker", "/ˈkeəˌteɪ.kə/", "смотритель", "noun", "The caretaker locked the side gate.", "Смотритель закрыл боковые ворота."),
        _w("passer-by", "/ˌpɑː.sə ˈbaɪ/", "прохожий", "noun", "A passer-by pointed to the right street.", "Прохожий показал нужную улицу."),
        _w("folk", "/fəʊk/", "люди, народ", "noun", "Local folk still use the old ferry.", "Местные люди всё ещё ходят на старом пароме."),
        _w("nanny", "/ˈnæn.i/", "няня", "noun", "The nanny leaves at six on Fridays.", "По пятницам няня уходит в шесть."),
        _w("widower", "/ˈwɪd.əʊ.ə/", "вдовец", "noun", "The widower kept her garden going.", "Вдовец продолжал ухаживать за её садом."),
        _w("stepbrother", "/ˈstepˌbrʌð.ə/", "сводный брат", "noun", "My stepbrother lives two towns away.", "Мой сводный брат живёт в двух городах отсюда."),
        _w("in-law", "/ˈɪn.lɔː/", "родственник со стороны супруга", "noun", "One in-law always brings extra bread.", "Один из родственников всегда приносит лишний хлеб."),
    ],
    "food-drink": [
        _w("oats", "/əʊts/", "овсянка", "noun", "I cook oats with a pinch of salt.", "Я варю овсянку с щепоткой соли."),
        _w("spinach", "/ˈspɪn.ɪtʃ/", "шпинат", "noun", "Add the spinach at the very end.", "Добавь шпинат в самом конце."),
        _w("beetroot", "/ˈbiːt.ruːt/", "свёкла", "noun", "The soup turns pink from the beetroot.", "Суп розовеет от свёклы."),
        _w("cucumber", "/ˈkjuː.kʌm.bə/", "огурец", "noun", "Slice the cucumber thin for the salad.", "Нарежь огурец тонко для салата."),
        _w("walnut", "/ˈwɔːl.nʌt/", "грецкий орех", "noun", "A few walnuts change the cake.", "Несколько грецких орехов меняют торт."),
        _w("mustard", "/ˈmʌs.təd/", "горчица", "noun", "A little mustard is enough for this ham.", "Этой ветчине хватит немного горчицы."),
        _w("cocoa", "/ˈkəʊ.kəʊ/", "какао", "noun", "Hot cocoa helped after the walk.", "Горячее какао помогло после прогулки."),
        _w("pastry", "/ˈpeɪ.stri/", "выпечка", "noun", "The pastry is better before ten.", "Выпечка вкуснее до десяти."),
        _w("broth", "/brɒθ/", "бульон", "noun", "The broth needs another twenty minutes.", "Бульону нужно ещё двадцать минут."),
        _w("radish", "/ˈræd.ɪʃ/", "редис", "noun", "The radish is sharper than last week.", "Редис острее, чем на прошлой неделе."),
    ],
    "travel-city": [
        _w("platform", "/ˈplæt.fɔːm/", "платформа", "noun", "Wait on platform four, not five.", "Жди на платформе четыре, не на пятой."),
        _w("ticket office", "/ˈtɪk.ɪt ˌɒf.ɪs/", "билетная касса", "noun", "The ticket office closes at nine.", "Касса закрывается в девять."),
        _w("roundabout", "/ˈraʊnd.ə.baʊt/", "кольцевая развязка", "noun", "Take the second exit at the roundabout.", "На кольце бери второй съезд."),
        _w("pavement", "/ˈpeɪv.mənt/", "тротуар", "noun", "The pavement is icy near the school.", "Тротуар у школы скользкий."),
        _w("crossing", "/ˈkrɒs.ɪŋ/", "переход", "noun", "Use the crossing, not the middle of the road.", "Иди через переход, не по середине дороги."),
        _w("kiosk", "/ˈkiː.ɒsk/", "киоск", "noun", "The kiosk still sells paper maps.", "В киоске всё ещё продают бумажные карты."),
        _w("suburb", "/ˈsʌb.ɜːb/", "пригород", "noun", "The last tram ends in the suburb.", "Последний трамвай заканчивается в пригороде."),
        _w("alley", "/ˈæl.i/", "переулок", "noun", "The café hides in a narrow alley.", "Кафе прячется в узком переулке."),
        _w("skyline", "/ˈskaɪ.laɪn/", "силуэт города", "noun", "The skyline looks clearer after rain.", "После дождя силуэт города чётче."),
        _w("layover", "/ˈleɪˌəʊ.və/", "пересадка, стыковка", "noun", "The layover in Vienna is only forty minutes.", "Пересадка в Вене всего сорок минут."),
    ],
    "work-study": [
        _w("deadline", "/ˈded.laɪn/", "срок сдачи", "noun", "The deadline moved to Thursday night.", "Срок сдвинули на четверг вечером."),
        _w("assignment", "/əˈsaɪn.mənt/", "задание", "noun", "This assignment is only two pages.", "Это задание всего на две страницы."),
        _w("lecture", "/ˈlek.tʃə/", "лекция", "noun", "The lecture starts ten minutes late.", "Лекция начинается на десять минут позже."),
        _w("seminar", "/ˈsem.ɪ.nɑː/", "семинар", "noun", "Speak once in the seminar, even briefly.", "Скажи хоть раз на семинаре, пусть коротко."),
        _w("overtime", "/ˈəʊ.və.taɪm/", "сверхурочные", "noun", "Overtime is paid after eight hours.", "Сверхурочные платят после восьми часов."),
        _w("colleague", "/ˈkɒl.iːɡ/", "коллега", "noun", "A colleague saved me a seat.", "Коллега занял мне место."),
        _w("campus", "/ˈkæm.pəs/", "кампус", "noun", "The campus shop closes at dusk.", "Магазин на кампусе закрывается в сумерках."),
        _w("revision", "/rɪˈvɪʒ.ən/", "повторение", "noun", "Revision is quieter in the morning.", "Повторять спокойнее утром."),
        _w("scholarship", "/ˈskɒl.ə.ʃɪp/", "стипендия", "noun", "The scholarship covers the train pass.", "Стипендия покрывает проездной."),
        _w("timetable", "/ˈtaɪmˌteɪ.bəl/", "расписание занятий", "noun", "Check the new timetable on the door.", "Проверь новое расписание на двери."),
    ],
    "health-body": [
        _w("ankle", "/ˈæŋ.kəl/", "лодыжка", "noun", "She twisted her ankle on the wet step.", "Она подвернула лодыжку на мокрой ступеньке."),
        _w("wrist", "/rɪst/", "запястье", "noun", "The watch left a mark on his wrist.", "Часы оставили след на запястье."),
        _w("forehead", "/ˈfɒr.ɪd/", "лоб", "noun", "A cool cloth on the forehead helped.", "Прохладная ткань на лбу помогла."),
        _w("throat", "/θrəʊt/", "горло", "noun", "My throat is sore after the cold wind.", "Горло болит после холодного ветра."),
        _w("allergy", "/ˈæl.ə.dʒi/", "аллергия", "noun", "The allergy is worse near cut grass.", "Аллергия сильнее у свежескошенной травы."),
        _w("prescription", "/prɪˈskrɪp.ʃən/", "рецепт", "noun", "The pharmacy needs a new prescription.", "Аптеке нужен новый рецепт."),
        _w("bandage", "/ˈbæn.dɪdʒ/", "бинт", "noun", "Change the bandage if it gets wet.", "Смени бинт, если он намокнет."),
        _w("dizzy", "/ˈdɪz.i/", "головокружение", "adjective", "She felt dizzy after standing up fast.", "Ей стало дурно после резкого подъёма."),
        _w("fever", "/ˈfiː.və/", "температура, жар", "noun", "The fever broke during the night.", "Жар спал ночью."),
        _w("stitches", "/ˈstɪtʃ.ɪz/", "швы", "noun", "The stitches come out next Tuesday.", "Швы снимут в следующий вторник."),
    ],
    "feelings-personality": [
        _w("cheerful", "/ˈtʃɪə.fəl/", "жизнерадостный", "adjective", "A cheerful note was taped to the fridge.", "На холодильнике висела жизнерадостная записка."),
        _w("patient", "/ˈpeɪ.ʃənt/", "терпеливый", "adjective", "Be patient: the kettle is slow today.", "Потерпи: чайник сегодня медленный."),
        _w("stubborn", "/ˈstʌb.ən/", "упрямый", "adjective", "He is stubborn about the short route.", "Он упрям насчёт короткого маршрута."),
        _w("curious", "/ˈkjʊə.ri.əs/", "любопытный", "adjective", "The curious child asked one more question.", "Любопытный ребёнок задал ещё один вопрос."),
        _w("proud", "/praʊd/", "гордый", "adjective", "She was proud of the quiet fix.", "Она гордилась тихим исправлением."),
        _w("lonely", "/ˈləʊn.li/", "одинокий", "adjective", "The house felt lonely after they left.", "После их ухода дом казался одиноким."),
        _w("grateful", "/ˈɡreɪt.fəl/", "благодарный", "adjective", "I am grateful for the spare key.", "Я благодарен за запасной ключ."),
        _w("anxious", "/ˈæŋk.ʃəs/", "тревожный", "adjective", "He gets anxious before long flights.", "Перед долгими рейсами он тревожится."),
        _w("calm", "/kɑːm/", "спокойный", "adjective", "Her calm voice slowed the queue.", "Её спокойный голос замедлил очередь."),
        _w("moody", "/ˈmuː.di/", "переменчивый в настроении", "adjective", "He is moody on dark Monday mornings.", "В тёмные понедельники он переменчив."),
    ],
    "nature-environment": [
        _w("meadow", "/ˈmed.əʊ/", "луг", "noun", "Butterflies filled the wet meadow.", "Бабочки заполнили сырой луг."),
        _w("marsh", "/mɑːʃ/", "болото", "noun", "Boots sank in the marsh after rain.", "После дождя сапоги тонули в болоте."),
        _w("glacier", "/ˈɡlæs.i.ə/", "ледник", "noun", "The glacier has pulled back from the hut.", "Ледник отошёл от хижины."),
        _w("canopy", "/ˈkæn.ə.pi/", "полог леса", "noun", "Little light reaches through the canopy.", "Сквозь полог леса почти не проходит свет."),
        _w("pollen", "/ˈpɒl.ən/", "пыльца", "noun", "Yellow pollen covered the car roof.", "Жёлтая пыльца покрыла крышу машины."),
        _w("tide", "/taɪd/", "прилив, отлив", "noun", "The tide hid the last row of stones.", "Прилив скрыл последний ряд камней."),
        _w("dew", "/djuː/", "роса", "noun", "Dew stayed on the grass until nine.", "Роса держалась на траве до девяти."),
        _w("moss", "/mɒs/", "мох", "noun", "Moss makes the path slippery.", "Мох делает тропу скользкой."),
        _w("thicket", "/ˈθɪk.ɪt/", "чаща", "noun", "A bird vanished into the thicket.", "Птица исчезла в чаще."),
        _w("runoff", "/ˈrʌn.ɒf/", "стоки", "noun", "Street runoff reached the small stream.", "Уличные стоки дошли до ручья."),
    ],
    "media-technology": [
        _w("upload", "/ˈʌp.ləʊd/", "загружать", "verb", "Upload the file before the meeting starts.", "Загрузи файл до начала встречи."),
        _w("download", "/ˈdaʊn.ləʊd/", "скачивать", "verb", "Download the map while you still have signal.", "Скачай карту, пока есть связь."),
        _w("username", "/ˈjuː.zə.neɪm/", "имя пользователя", "noun", "The username is case-sensitive here.", "Имя пользователя здесь чувствительно к регистру."),
        _w("password", "/ˈpɑːs.wɜːd/", "пароль", "noun", "Do not reuse this password on other sites.", "Не используй этот пароль на других сайтах."),
        _w("inbox", "/ˈɪn.bɒks/", "входящие", "noun", "The inbox filled with the same reminder.", "Во входящих снова то же напоминание."),
        _w("offline", "/ˌɒfˈlaɪn/", "офлайн", "adjective", "The form works offline after the first load.", "Форма работает офлайн после первой загрузки."),
        _w("widget", "/ˈwɪdʒ.ɪt/", "виджет", "noun", "Remove the weather widget from the home screen.", "Убери виджет погоды с главного экрана."),
        _w("lag", "/læɡ/", "задержка", "noun", "The lag made the call hard to follow.", "Из-за задержки разговор было трудно вести."),
        _w("screenshot", "/ˈskriːn.ʃɒt/", "снимок экрана", "noun", "Send a screenshot of the error, not a photo.", "Пришли снимок ошибки, не фото экрана."),
        _w("unsubscribe", "/ˌʌn.səbˈskraɪb/", "отписаться", "verb", "Unsubscribe if the weekly mail is useless.", "Отпишись, если еженедельная рассылка бесполезна."),
    ],
    "business-money": [
        _w("invoice", "/ˈɪn.vɔɪs/", "счёт", "noun", "The invoice is due on the fifteenth.", "Счёт нужно оплатить пятнадцатого."),
        _w("receipt", "/rɪˈsiːt/", "чек", "noun", "Keep the receipt if you might return it.", "Сохрани чек, если вдруг будешь возвращать."),
        _w("interest", "/ˈɪn.trəst/", "процент", "noun", "The interest on the loan is lower this year.", "Процент по кредиту в этом году ниже."),
        _w("budget", "/ˈbʌdʒ.ɪt/", "бюджет", "noun", "The travel budget is already gone.", "Командировочный бюджет уже закончился."),
        _w("profit", "/ˈprɒf.ɪt/", "прибыль", "noun", "A small profit is still a profit.", "Маленькая прибыль — всё равно прибыль."),
        _w("loss", "/lɒs/", "убыток", "noun", "January showed a loss after the repairs.", "В январе после ремонта вышел убыток."),
        _w("shareholder", "/ˈʃeəˌhəʊl.də/", "акционер", "noun", "One shareholder asked for a shorter report.", "Один акционер попросил более короткий отчёт."),
        _w("dividend", "/ˈdɪv.ɪ.dend/", "дивиденд", "noun", "The dividend is paid once a year.", "Дивиденд выплачивают раз в год."),
        _w("forecast", "/ˈfɔː.kɑːst/", "прогноз", "noun", "The forecast for spring sales is cautious.", "Прогноз весенних продаж осторожный."),
        _w("markup", "/ˈmɑːk.ʌp/", "наценка", "noun", "The markup on the late tickets is steep.", "Наценка на поздние билеты высокая."),
    ],
    "society-law": [
        _w("jury", "/ˈdʒʊə.ri/", "присяжные", "noun", "The jury left the room for an hour.", "Присяжные вышли на час."),
        _w("verdict", "/ˈvɜː.dɪkt/", "вердикт", "noun", "The verdict came after a short pause.", "Вердикт вынесли после короткой паузы."),
        _w("lawsuit", "/ˈlɔː.suːt/", "иск", "noun", "The lawsuit is about a leaking roof.", "Иск касается протекающей крыши."),
        _w("fine", "/faɪn/", "штраф", "noun", "The parking fine arrived a week later.", "Штраф за парковку пришёл через неделю."),
        _w("ballot", "/ˈbæl.ət/", "бюллетень", "noun", "Fold the ballot before you leave the booth.", "Сложи бюллетень, прежде чем выйти из кабины."),
        _w("treaty", "/ˈtriː.ti/", "договор", "noun", "The treaty is still waiting for one signature.", "Договору не хватает одной подписи."),
        _w("ministry", "/ˈmɪn.ɪ.stri/", "министерство", "noun", "The ministry published the new hours.", "Министерство опубликовало новые часы."),
        _w("civic", "/ˈsɪv.ɪk/", "гражданский", "adjective", "A civic group cleaned the riverbank.", "Гражданская группа убрала берег."),
        _w("statute", "/ˈstætʃ.uːt/", "статут, закон", "noun", "The statute changed the night-bus rules.", "Закон изменил правила ночных автобусов."),
        _w("ombudsman", "/ˈɒm.bʊdz.mən/", "омбудсмен", "noun", "Write to the ombudsman if the reply never comes.", "Пиши омбудсмену, если ответа так и нет."),
    ],
    "academic-abstract": [
        _w("hypothesis", "/haɪˈpɒθ.ə.sɪs/", "гипотеза", "noun", "The first hypothesis did not survive the data.", "Первая гипотеза не выдержала данных."),
        _w("framework", "/ˈfreɪm.wɜːk/", "рамка, каркас", "noun", "Use a simple framework, then add detail.", "Возьми простую рамку, потом добавляй детали."),
        _w("assumption", "/əˈsʌmp.ʃən/", "допущение", "noun", "The assumption about traffic is too neat.", "Допущение про пробки слишком аккуратное."),
        _w("implication", "/ˌɪm.plɪˈkeɪ.ʃən/", "следствие", "noun", "The implication is local, not national.", "Следствие локальное, не общенациональное."),
        _w("variable", "/ˈveə.ri.ə.bəl/", "переменная", "noun", "Weather is the noisy variable here.", "Погода здесь — шумная переменная."),
        _w("validity", "/vəˈlɪd.ə.ti/", "валидность", "noun", "The validity of the test is still debated.", "Валидность теста всё ещё спорят."),
        _w("discourse", "/ˈdɪs.kɔːs/", "дискурс", "noun", "Public discourse ignored the night shift.", "Публичный дискурс обошёл ночную смену."),
        _w("paradigm", "/ˈpær.ə.daɪm/", "парадигма", "noun", "The old paradigm still shapes the form.", "Старая парадигма всё ещё задаёт форму."),
        _w("nuance", "/ˈnjuː.ɑːns/", "нюанс", "noun", "The nuance is in the timing, not the word.", "Нюанс в моменте, а не в самом слове."),
        _w("scope", "/skəʊp/", "охват", "noun", "Keep the scope to one street, not the city.", "Держи охват на одной улице, не на всём городе."),
    ],
    "clothes-weather": [
        _w("raincoat", "/ˈreɪn.kəʊt/", "дождевик", "noun", "The raincoat is still wet from last night.", "Дождевик ещё мокрый со вчера."),
        _w("sandals", "/ˈsæn.dəlz/", "сандалии", "noun", "Sandals are a bad idea on this path.", "На этой тропе сандалии — плохая идея."),
        _w("mittens", "/ˈmɪt.ɪnz/", "варежки", "noun", "The child lost one mitten at the gate.", "Ребёнок потерял одну варежку у калитки."),
        _w("overcoat", "/ˈəʊ.və.kəʊt/", "пальто", "noun", "The overcoat is too warm for April.", "Это пальто слишком тёплое для апреля."),
        _w("hail", "/heɪl/", "град", "noun", "Hail bounced off the bicycle seat.", "Град отскакивал от велосипедного седла."),
        _w("breeze", "/briːz/", "ветерок", "noun", "A light breeze dried the washing.", "Лёгкий ветерок высушил бельё."),
        _w("humid", "/ˈhjuː.mɪd/", "влажный", "adjective", "The room feels humid after the shower.", "После душа в комнате влажно."),
        _w("overcast", "/ˈəʊ.və.kɑːst/", "пасмурный", "adjective", "An overcast sky hid the far hill.", "Пасмурное небо скрыло дальний холм."),
        _w("sleet", "/sliːt/", "мокрый снег", "noun", "Sleet made the steps shine.", "Мокрый снег сделал ступеньки блестящими."),
        _w("cardigan", "/ˈkɑː.dɪ.ɡən/", "кардиган", "noun", "A thin cardigan is enough in this room.", "В этой комнате хватит тонкого кардигана."),
    ],
    "daily-routines": [
        _w("wake up", "/ˌweɪk ˈʌp/", "просыпаться", "verb", "I wake up before the first tram.", "Я просыпаюсь до первого трамвая."),
        _w("get dressed", "/ˌɡet ˈdrest/", "одеваться", "verb", "Get dressed before the kettle boils.", "Оденься, пока чайник не закипел."),
        _w("brush", "/brʌʃ/", "чистить (зубы, волосы)", "verb", "Brush your teeth after the sweet tea.", "Почисти зубы после сладкого чая."),
        _w("shave", "/ʃeɪv/", "бриться", "verb", "He forgot to shave before the meeting.", "Он забыл побриться перед встречей."),
        _w("do the dishes", "/ˌduː ðə ˈdɪʃ.ɪz/", "мыть посуду", "verb", "I do the dishes while the rice rests.", "Я мою посуду, пока рис настаивается."),
        _w("take out", "/ˌteɪk ˈaʊt/", "выносить (мусор)", "verb", "Take out the food waste before dinner.", "Вынеси пищевые отходы до ужина."),
        _w("set the table", "/ˌset ðə ˈteɪ.bəl/", "накрывать на стол", "verb", "Set the table for four, not three.", "Накрой на четверых, не на троих."),
        _w("turn off", "/ˌtɜːn ˈɒf/", "выключать", "verb", "Turn off the hall light when you leave.", "Выключи свет в коридоре, когда уходишь."),
        _w("wind down", "/ˌwaɪnd ˈdaʊn/", "расслабляться", "verb", "I wind down with a short walk.", "Я расслабляюсь короткой прогулкой."),
    ],
    "colours-time": [
        _w("grey", "/ɡreɪ/", "серый", "adjective", "The grey coat hides the dust better.", "Серое пальто лучше скрывает пыль."),
        _w("beige", "/beɪʒ/", "бежевый", "adjective", "A beige wall makes the room warmer.", "Бежевая стена делает комнату теплее."),
        _w("navy", "/ˈneɪ.vi/", "тёмно-синий", "adjective", "Navy trousers work for the interview.", "Тёмно-синие брюки подойдут на собеседование."),
        _w("turquoise", "/ˈtɜː.kwɔɪz/", "бирюзовый", "adjective", "The turquoise door is easy to find.", "Бирюзовую дверь легко найти."),
        _w("noon", "/nuːn/", "полдень", "noun", "The market is loudest at noon.", "Рынок громче всего в полдень."),
        _w("sunrise", "/ˈsʌn.raɪz/", "восход", "noun", "Sunrise is later after the clocks change.", "После перевода часов восход позже."),
        _w("sunset", "/ˈsʌn.set/", "закат", "noun", "We reached the ridge just after sunset.", "Мы вышли на гребень сразу после заката."),
        _w("quarter", "/ˈkwɔː.tə/", "четверть часа", "noun", "The bus leaves at a quarter to eight.", "Автобус уходит без четверти восемь."),
        _w("decade", "/ˈdek.eɪd/", "десятилетие", "noun", "The shop has stood here for a decade.", "Магазин стоит здесь уже десять лет."),
        _w("leap year", "/ˈliːp jɪə/", "високосный год", "noun", "February is longer in a leap year.", "В високосный год февраль длиннее."),
    ],
    "home-rooms": [
        _w("attic", "/ˈæt.ɪk/", "чердак", "noun", "Old maps are in a box in the attic.", "Старые карты лежат в коробке на чердаке."),
        _w("porch", "/pɔːtʃ/", "крыльцо", "noun", "Leave wet boots on the porch.", "Мокрые сапоги оставь на крыльце."),
        _w("banister", "/ˈbæn.ɪ.stə/", "перила", "noun", "Hold the banister; the steps are worn.", "Держись за перила: ступени стёртые."),
        _w("threshold", "/ˈθreʃ.həʊld/", "порог", "noun", "The cat sat on the sunny threshold.", "Кот сидел на солнечном пороге."),
        _w("pantry", "/ˈpæn.tri/", "кладовая", "noun", "Spare jars go in the pantry, not the fridge.", "Запасные банки — в кладовую, не в холодильник."),
        _w("airing cupboard", "/ˈeə.rɪŋ ˌkʌb.əd/", "шкаф для сушки", "noun", "Sheets dry faster in the airing cupboard.", "Простыни быстрее сохнут в сушильном шкафу."),
        _w("skirting", "/ˈskɜː.tɪŋ/", "плинтус", "noun", "Paint the skirting after the walls.", "Плинтус крась после стен."),
        _w("trapdoor", "/ˈtræp.dɔː/", "люк", "noun", "The trapdoor to the cellar sticks in winter.", "Люк в погреб зимой заедает."),
        _w("utility room", "/juːˈtɪl.ə.ti ruːm/", "подсобка", "noun", "The vacuum lives in the utility room.", "Пылесос стоит в подсобке."),
        _w("bay window", "/ˌbeɪ ˈwɪn.dəʊ/", "эркер", "noun", "A chair fits in the bay window.", "В эркере помещается стул."),
    ],
    "shopping-money-basic": [
        _w("aisle", "/aɪl/", "проход между полками", "noun", "Rice is in the third aisle on the left.", "Рис в третьем проходе слева."),
        _w("counter", "/ˈkaʊn.tə/", "прилавок", "noun", "Ask at the cheese counter for a taste.", "Попроси кусочек на сырном прилавке."),
        _w("change", "/tʃeɪndʒ/", "сдача", "noun", "I have no change for the locker.", "У меня нет сдачи для шкафчика."),
        _w("coin", "/kɔɪn/", "монета", "noun", "A single coin is missing from the pile.", "В стопке не хватает одной монеты."),
        _w("note", "/nəʊt/", "купюра", "noun", "The machine will not take a torn note.", "Автомат не берёт порванную купюру."),
        _w("afford", "/əˈfɔːd/", "мочь себе позволить", "verb", "We can afford the later train, not the taxi.", "Поздний поезд нам по карману, такси — нет."),
        _w("bargain", "/ˈbɑː.ɡɪn/", "выгодная покупка", "noun", "This kettle was a bargain after the sale.", "Этот чайник после распродажи — выгодная покупка."),
        _w("queue", "/kjuː/", "очередь", "noun", "The queue moved after a second till opened.", "Очередь сдвинулась, когда открыли вторую кассу."),
        _w("price tag", "/ˈpraɪs tæɡ/", "ценник", "noun", "The price tag is still on the sleeve.", "Ценник всё ещё на рукаве."),
        _w("exchange", "/ɪksˈtʃeɪndʒ/", "обменивать", "verb", "You can exchange the jumper within a week.", "Джемпер можно обменять в течение недели."),
    ],
    "hobbies-sports": [
        _w("hike", "/haɪk/", "пеший поход", "noun", "The hike is short but steep.", "Поход короткий, но крутой."),
        _w("yoga", "/ˈjəʊ.ɡə/", "йога", "noun", "Yoga is in the hall on Tuesday nights.", "Йога в зале по вторникам вечером."),
        _w("sketch", "/sketʃ/", "набросок", "noun", "A quick sketch is enough for the idea.", "Для идеи хватит быстрого наброска."),
        _w("puzzle", "/ˈpʌz.əl/", "головоломка", "noun", "The puzzle is missing one edge piece.", "В головоломке не хватает одного крайнего куска."),
        _w("racket", "/ˈræk.ɪt/", "ракетка", "noun", "Borrow a racket if yours is still wet.", "Возьми ракетку, если твоя ещё мокрая."),
        _w("goal", "/ɡəʊl/", "гол; ворота", "noun", "The only goal came after a corner.", "Единственный гол случился после углового."),
        _w("referee", "/ˌref.əˈriː/", "судья", "noun", "The referee stopped play for a minute.", "Судья остановил игру на минуту."),
        _w("stretching", "/ˈstretʃ.ɪŋ/", "растяжка", "noun", "Do stretching after, not only before.", "Растяжку делай после, не только до."),
        _w("allotment", "/əˈlɒt.mənt/", "огород", "noun", "Tomatoes on the allotment ripen late.", "Помидоры на огороде зреют поздно."),
        _w("scrapbook", "/ˈskræp.bʊk/", "альбом вырезок", "noun", "The scrapbook has tickets from every ferry.", "В альбоме билеты со всех паромов."),
    ],
    "school-subjects": [
        _w("timetable", "/ˈtaɪmˌteɪ.bəl/", "расписание", "noun", "The timetable changed after half-term.", "После каникул расписание изменилось."),
        _w("blackboard", "/ˈblæk.bɔːd/", "доска", "noun", "The last example is still on the blackboard.", "Последний пример всё ещё на доске."),
        _w("homework", "/ˈhəʊm.wɜːk/", "домашняя работа", "noun", "Homework is shorter on Fridays.", "По пятницам домашка короче."),
        _w("break", "/breɪk/", "перемена", "noun", "The first break is only ten minutes.", "Первая перемена всего десять минут."),
        _w("geography", "/dʒiˈɒɡ.rə.fi/", "география", "noun", "Geography is in room twelve today.", "География сегодня в двенадцатом кабинете."),
        _w("history", "/ˈhɪs.tər.i/", "история", "noun", "History homework is a short timeline.", "По истории нужно сделать короткую ленту времени."),
        _w("biology", "/baɪˈɒl.ə.dʒi/", "биология", "noun", "Biology needs a clean lab coat.", "На биологию нужен чистый халат."),
        _w("assembly", "/əˈsem.bli/", "линейка", "noun", "Assembly is cancelled because of the storm.", "Линейку отменили из-за бури."),
        _w("mark", "/mɑːk/", "оценка", "noun", "The mark is fair if you read the comment.", "Оценка справедливая, если прочесть комментарий."),
        _w("uniform", "/ˈjuː.nɪ.fɔːm/", "форма", "noun", "The winter uniform includes a dark jumper.", "Зимняя форма включает тёмный джемпер."),
    ],
    "restaurants-cooking": [
        _w("simmer", "/ˈsɪm.ə/", "томить на малом огне", "verb", "Simmer the sauce; do not let it boil hard.", "Томи соус, не давай ему бурно кипеть."),
        _w("chop", "/tʃɒp/", "крупно резать", "verb", "Chop the onion, do not mince it.", "Порежь лук крупно, не мельчи."),
        _w("whisk", "/wɪsk/", "взбивать", "verb", "Whisk the eggs until they look pale.", "Взбивай яйца, пока они не посветлеют."),
        _w("starter", "/ˈstɑː.tə/", "закуска", "noun", "The starter is soup, not salad.", "На закуску суп, не салат."),
        _w("dessert", "/dɪˈzɜːt/", "десерт", "noun", "Skip dessert if the main course is late.", "Пропусти десерт, если основное блюдо задерживается."),
        _w("bill", "/bɪl/", "счёт", "noun", "Ask for the bill when you are ready.", "Попроси счёт, когда будете готовы."),
        _w("tip", "/tɪp/", "чаевые", "noun", "A small tip is enough for counter service.", "За обслуживание у стойки хватит небольших чаевых."),
        _w("recipe", "/ˈres.ɪ.pi/", "рецепт", "noun", "The recipe forgets the pinch of salt.", "В рецепте забыли щепотку соли."),
        _w("seasoning", "/ˈsiː.zən.ɪŋ/", "приправа", "noun", "Taste before you add more seasoning.", "Попробуй, прежде чем сыпать ещё приправу."),
        _w("portion", "/ˈpɔː.ʃən/", "порция", "noun", "Ask for a smaller portion if you are full.", "Попроси порцию поменьше, если уже сыт."),
    ],
    "animals-pets": [
        _w("sparrow", "/ˈspær.əʊ/", "воробей", "noun", "A sparrow stole crumbs from the table.", "Воробей стащил крошки со стола."),
        _w("hedgehog", "/ˈhedʒ.hɒɡ/", "ёж", "noun", "A hedgehog crossed the quiet lane.", "Ёж перешёл тихий переулок."),
        _w("squirrel", "/ˈskwɪr.əl/", "белка", "noun", "The squirrel hid a nut under the bench.", "Белка спрятала орех под скамейкой."),
        _w("swan", "/swɒn/", "лебедь", "noun", "The swan nested far from the path.", "Лебедь свил гнездо далеко от тропы."),
        _w("calf", "/kɑːf/", "телёнок", "noun", "The calf stayed close to the fence.", "Телёнок держался у забора."),
        _w("puppy", "/ˈpʌp.i/", "щенок", "noun", "The puppy slept through the storm.", "Щенок проспал всю бурю."),
        _w("kitten", "/ˈkɪt.ən/", "котёнок", "noun", "The kitten prefers the sunny chair.", "Котёнок выбирает солнечный стул."),
        _w("beak", "/biːk/", "клюв", "noun", "The bird tapped the window with its beak.", "Птица стучала клювом в окно."),
        _w("paw", "/pɔː/", "лапа", "noun", "A muddy paw print sat on the step.", "На ступеньке остался след грязной лапы."),
        _w("stable", "/ˈsteɪ.bəl/", "конюшня", "noun", "The stable door was left half open.", "Дверь конюшни оставили полуоткрытой."),
    ],
    "transport-directions": [
        _w("traffic lights", "/ˈtræf.ɪk laɪts/", "светофор", "noun", "Turn right after the traffic lights.", "Поверни направо после светофора."),
        _w("zebra crossing", "/ˈzeb.rə ˌkrɒs.ɪŋ/", "пешеходный переход", "noun", "Cars must stop at the zebra crossing.", "Машины должны остановиться на переходе."),
        _w("cycle lane", "/ˈsaɪ.kəl leɪn/", "велополоса", "noun", "Stay in the cycle lane until the bridge.", "Оставайся в велополосе до моста."),
        _w("hard shoulder", "/ˌhɑːd ˈʃəʊl.də/", "обочина", "noun", "Do not walk on the hard shoulder.", "Не ходи по обочине."),
        _w("level crossing", "/ˈlev.əl ˌkrɒs.ɪŋ/", "железнодорожный переезд", "noun", "The level crossing bells started early.", "На переезде звонки начались заранее."),
        _w("flyover", "/ˈflaɪˌəʊ.və/", "эстакада", "noun", "The flyover hides the old station roof.", "Эстакада закрывает крышу старого вокзала."),
        _w("slip road", "/ˈslɪp rəʊd/", "съезд с трассы", "noun", "Miss the first slip road; take the next.", "Первый съезд пропусти, бери следующий."),
        _w("one-way", "/ˌwʌn ˈweɪ/", "односторонний", "adjective", "This street is one-way after six.", "После шести улица односторонняя."),
        _w("diversion", "/daɪˈvɜː.ʃən/", "объезд", "noun", "Follow the diversion past the school.", "Объезд идёт мимо школы."),
        _w("milestone", "/ˈmaɪl.stəʊn/", "верстовой столб; веха", "noun", "An old milestone still marks the fork.", "Старый столб всё ещё отмечает развилку."),
    ],
    "useful-nouns": [
        _w("reason", "/ˈriː.zən/", "причина", "noun", "The reason for the delay is a fallen tree.", "Причина задержки — упавшее дерево."),
        _w("choice", "/tʃɔɪs/", "выбор", "noun", "The late train is the safer choice.", "Поздний поезд — более безопасный выбор."),
        _w("chance", "/tʃɑːns/", "шанс", "noun", "There is a chance of fog after midnight.", "После полуночи есть шанс тумана."),
        _w("habit", "/ˈhæb.ɪt/", "привычка", "noun", "The habit of leaving early saved us.", "Привычка выходить рано нас спасла."),
        _w("effort", "/ˈef.ət/", "усилие", "noun", "A little effort now saves a later rewrite.", "Небольшое усилие сейчас сэкономит переписывание."),
        _w("result", "/rɪˈzʌlt/", "результат", "noun", "The result is quieter streets, not empty ones.", "Результат — более тихие улицы, не пустые."),
        _w("example", "/ɪɡˈzɑːm.pəl/", "пример", "noun", "One example is enough if it is local.", "Одного примера хватит, если он местный."),
        _w("detail", "/ˈdiː.teɪl/", "деталь", "noun", "The missing detail is the time, not the place.", "Не хватает детали про время, не про место."),
        _w("difference", "/ˈdɪf.ər.əns/", "разница", "noun", "The difference is ten minutes, not an hour.", "Разница десять минут, не час."),
        _w("solution", "/səˈluː.ʃən/", "решение", "noun", "A later start is a better solution than a taxi.", "Более поздний старт лучше, чем такси."),
    ],
    "body-basics": [
        _w("shoulder", "/ˈʃəʊl.də/", "плечо", "noun", "The bag strap cut into her shoulder.", "Ремень сумки врезался в плечо."),
        _w("knee", "/niː/", "колено", "noun", "My knee complains on long stairs.", "Колено ноет на длинных лестницах."),
        _w("thumb", "/θʌm/", "большой палец", "noun", "I hit my thumb with the cupboard door.", "Я ударил большой палец дверцей шкафа."),
        _w("chin", "/tʃɪn/", "подбородок", "noun", "A drop of rain sat on his chin.", "На подбородке осталась капля дождя."),
        _w("cheek", "/tʃiːk/", "щека", "noun", "Cold wind burned her cheek.", "Холодный ветер обжёг щёку."),
        _w("lip", "/lɪp/", "губа", "noun", "The dry air cracked his lip.", "Сухой воздух потрескал губу."),
        _w("heel", "/hiːl/", "пятка", "noun", "A stone in the shoe hurt her heel.", "Камень в ботинке натёр пятку."),
        _w("palm", "/pɑːm/", "ладонь", "noun", "The key left a mark on my palm.", "Ключ оставил след на ладони."),
        _w("waist", "/weɪst/", "талия", "noun", "The belt sits too high on the waist.", "Ремень сидит слишком высоко на талии."),
        _w("hip", "/hɪp/", "бедро", "noun", "She leaned on one hip at the counter.", "Она опёрлась бедром о прилавок."),
    ],
    "town-places": [
        _w("pharmacy", "/ˈfɑː.mə.si/", "аптека", "noun", "The pharmacy is open until eight.", "Аптека работает до восьми."),
        _w("stadium", "/ˈsteɪ.di.əm/", "стадион", "noun", "The stadium lights stay on after the match.", "Огни стадиона горят после матча."),
        _w("harbour", "/ˈhɑː.bə/", "гавань", "noun", "Walk to the harbour if the wind drops.", "Иди к гавани, если ветер спадёт."),
        _w("fountain", "/ˈfaʊn.tɪn/", "фонтан", "noun", "Meet by the fountain, not the steps.", "Встретимся у фонтана, не у ступеней."),
        _w("gallery", "/ˈɡæl.ər.i/", "галерея", "noun", "The gallery is free on the first Sunday.", "В первое воскресенье галерея бесплатная."),
        _w("town hall", "/ˌtaʊn ˈhɔːl/", "ратуша", "noun", "The town hall posts new hours on the door.", "Ратуша вешает новые часы на дверь."),
        _w("car park", "/ˈkɑː pɑːk/", "парковка", "noun", "The car park fills before nine.", "Парковка заполняется до девяти."),
        _w("roundabout", "/ˈraʊnd.ə.baʊt/", "кольцо", "noun", "The bakery is after the second roundabout.", "Пекарня после второго кольца."),
        _w("suburb", "/ˈsʌb.ɜːb/", "пригород", "noun", "Trams run later in this suburb now.", "В этом пригороде трамваи ходят позже."),
        _w("quay", "/kiː/", "причал", "noun", "Fish boxes sat on the wet quay.", "Ящики с рыбой стояли на мокром причале."),
    ],
    "everyday-verbs": [
        _w("open", "/ˈəʊ.pən/", "открывать", "verb", "Open the window before you cook.", "Открой окно, прежде чем готовить."),
        _w("close", "/kləʊz/", "закрывать", "verb", "Close the gate or the dog will leave.", "Закрой калитку, иначе собака уйдёт."),
        _w("wait", "/weɪt/", "ждать", "verb", "Wait under the clock, not by the road.", "Жди под часами, не у дороги."),
        _w("help", "/help/", "помогать", "verb", "Help her with the heavy bag.", "Помоги ей с тяжёлой сумкой."),
        _w("start", "/stɑːt/", "начинать", "verb", "Start the letter with the date.", "Начни письмо с даты."),
        _w("finish", "/ˈfɪn.ɪʃ/", "заканчивать", "verb", "Finish the soup before it cools.", "Доешь суп, пока не остыл."),
        _w("bring", "/brɪŋ/", "приносить", "verb", "Bring a spare pen for the form.", "Принеси запасную ручку для бланка."),
        _w("leave", "/liːv/", "уходить; оставлять", "verb", "Leave the key under the pot.", "Оставь ключ под горшком."),
        _w("meet", "/miːt/", "встречать", "verb", "Meet me after the last lesson.", "Встретимся после последнего урока."),
        _w("remember", "/rɪˈmem.bə/", "помнить", "verb", "Remember the side door sticks.", "Помни: боковая дверь заедает."),
    ],
    "countryside": [
        _w("meadow", "/ˈmed.əʊ/", "луг", "noun", "Cows move to the upper meadow in May.", "В мае коров переводят на верхний луг."),
        _w("footpath", "/ˈfʊt.pɑːθ/", "пешеходная тропа", "noun", "The footpath is closed after the landslide.", "Тропу закрыли после оползня."),
        _w("stile", "/staɪl/", "перелаз", "noun", "Climb the stile, then keep the hedge on your left.", "Перелезь через перелаз и держи изгородь слева."),
        _w("brook", "/brʊk/", "ручей", "noun", "The brook is loud after last night's rain.", "После вчерашнего дождя ручей шумит."),
        _w("pasture", "/ˈpɑːs.tʃə/", "пастбище", "noun", "The pasture gate must stay shut.", "Калитку пастбища нужно держать закрытой."),
        _w("copse", "/kɒps/", "рощица", "noun", "Deer rest in the copse at noon.", "Олени в полдень отдыхают в рощице."),
        _w("moor", "/mʊə/", "пустошь", "noun", "Fog sits on the moor until late morning.", "Туман держится на пустоши до позднего утра."),
        _w("croft", "/krɒft/", "небольшой надел", "noun", "The croft still has one stone barn.", "На наделе всё ещё стоит один каменный сарай."),
        _w("ford", "/fɔːd/", "брод", "noun", "Do not use the ford after heavy rain.", "Не ходи вброд после сильного дождя."),
        _w("haystack", "/ˈheɪ.stæk/", "стог сена", "noun", "A haystack hid the far fence.", "Стог закрыл дальний забор."),
    ],
    "communication": [
        _w("voicemail", "/ˈvɔɪs.meɪl/", "голосовая почта", "noun", "Leave a voicemail if I miss the call.", "Оставь голосовое, если я не возьму трубку."),
        _w("subject", "/ˈsʌb.dʒɪkt/", "тема письма", "noun", "Put the date in the subject line.", "Поставь дату в тему письма."),
        _w("cc", "/ˌsiːˈsiː/", "копия", "noun", "Add her in cc, not as the main receiver.", "Добавь её в копию, не как основного получателя."),
        _w("forward", "/ˈfɔː.wəd/", "пересылать", "verb", "Forward the note to the whole group.", "Перешли записку всей группе."),
        _w("clarify", "/ˈklær.ɪ.faɪ/", "уточнять", "verb", "Clarify the time before you leave home.", "Уточни время, прежде чем выходить."),
        _w("summarise", "/ˈsʌm.ər.aɪz/", "кратко излагать", "verb", "Summarise the call in four lines.", "Изложи звонок в четырёх строках."),
        _w("tone", "/təʊn/", "тон", "noun", "The tone of the last mail was too sharp.", "Тон последнего письма был слишком резким."),
        _w("misread", "/ˌmɪsˈriːd/", "неверно прочитать", "verb", "I misread 'Tuesday' as 'Thursday'.", "Я прочитал «вторник» как «четверг»."),
        _w("follow-up", "/ˈfɒl.əʊ ʌp/", "повторное письмо", "noun", "A short follow-up is enough after two days.", "Короткого повторного письма хватит через два дня."),
        _w("small talk", "/ˈsmɔːl tɔːk/", "светская беседа", "noun", "Skip the small talk if the train is leaving.", "Пропусти светскую беседу, если поезд уходит."),
    ],
    "house-chores": [
        _w("wipe", "/waɪp/", "протирать", "verb", "Wipe the hob before it cools.", "Протри плиту, пока она не остыла."),
        _w("scrub", "/skrʌb/", "скрести", "verb", "Scrub the sink after the coffee grounds.", "Поскреби раковину после кофейной гущи."),
        _w("air", "/eə/", "проветривать", "verb", "Air the bedroom for ten minutes.", "Проветри спальню десять минут."),
        _w("sort", "/sɔːt/", "сортировать", "verb", "Sort the recycling before collection day.", "Разбери вторсырьё до дня вывоза."),
        _w("defrost", "/ˌdiːˈfrɒst/", "размораживать", "verb", "Defrost the freezer once a year.", "Размораживай морозилку раз в год."),
        _w("unplug", "/ʌnˈplʌɡ/", "вынимать из розетки", "verb", "Unplug the iron before you leave.", "Вынь утюг из розетки, прежде чем уйти."),
        _w("hang out", "/ˌhæŋ ˈaʊt/", "развешивать бельё", "verb", "Hang out the shirts while the wind lasts.", "Развесь рубашки, пока есть ветер."),
        _w("clog", "/klɒɡ/", "забиваться", "verb", "Hair will clog the drain if you ignore it.", "Волосы забьют сток, если их не убирать."),
        _w("spare", "/speə/", "запасной", "adjective", "A spare bulb is in the top drawer.", "Запасная лампочка в верхнем ящике."),
        _w("chores", "/tʃɔːz/", "домашние дела", "noun", "Sunday chores are shorter if we start early.", "Воскресные дела короче, если начать рано."),
    ],
    "relationships": [
        _w("confide", "/kənˈfaɪd/", "доверять секрет", "verb", "I can confide in her about the move.", "Я могу доверить ей секрет о переезде."),
        _w("drift apart", "/ˌdrɪft əˈpɑːt/", "отдаляться", "verb", "They drifted apart after different cities.", "Они отдалились после разных городов."),
        _w("make up", "/ˌmeɪk ˈʌp/", "мириться", "verb", "They made up before the weekend.", "Они помирились до выходных."),
        _w("keep in touch", "/ˌkiːp ɪn ˈtʌtʃ/", "поддерживать связь", "verb", "Keep in touch even if the hours change.", "Поддерживай связь, даже если часы сдвинутся."),
        _w("trustworthy", "/ˈtrʌstˌwɜː.ði/", "надёжный", "adjective", "A trustworthy neighbour still has the spare key.", "Надёжный сосед всё ещё хранит запасной ключ."),
        _w("awkward", "/ˈɔː.kwəd/", "неловкий", "adjective", "The dinner was awkward after the argument.", "Ужин был неловким после ссоры."),
        _w("supportive", "/səˈpɔː.tɪv/", "поддерживающий", "adjective", "A supportive message arrived at midnight.", "Поддерживающее сообщение пришло в полночь."),
        _w("resentment", "/rɪˈzent.mənt/", "обида", "noun", "Resentment faded after one honest list.", "Обида спала после честного списка."),
        _w("intimacy", "/ˈɪn.tɪ.mə.si/", "близость", "noun", "Intimacy here is shared silence, not talk.", "Близость здесь — общее молчание, не разговор."),
        _w("falling-out", "/ˌfɔː.lɪŋ ˈaʊt/", "ссора, разлад", "noun", "The falling-out lasted only a fortnight.", "Разлад длился всего две недели."),
    ],
    "work-skills": [
        _w("brief", "/briːf/", "бриф, краткое ТЗ", "noun", "The brief forgot the night-time constraint.", "В брифе забыли ночное ограничение."),
        _w("handover", "/ˈhændˌəʊ.və/", "передача дел", "noun", "A one-page handover is enough.", "Одной страницы передачи дел хватит."),
        _w("onboarding", "/ˈɒnˌbɔː.dɪŋ/", "ввод в должность", "noun", "Onboarding is two quiet mornings, not a tour.", "Ввод — два тихих утра, не экскурсия."),
        _w("stakeholder", "/ˈsteɪkˌhəʊl.də/", "заинтересованная сторона", "noun", "One stakeholder still wants the old date.", "Одна сторона всё ещё хочет старую дату."),
        _w("deliverable", "/dɪˈlɪv.ər.ə.bəl/", "результат работы", "noun", "The only deliverable this week is the map.", "Единственный результат на этой неделе — карта."),
        _w("escalate", "/ˈes.kə.leɪt/", "эскалировать", "verb", "Escalate if the reply is still missing Friday.", "Эскалируй, если к пятнице ответа всё ещё нет."),
        _w("prioritise", "/praɪˈɒr.ɪ.taɪz/", "расставлять приоритеты", "verb", "Prioritise the leak before the paint.", "Сначала протечка, потом краска."),
        _w("capacity", "/kəˈpæs.ə.ti/", "ёмкость, запас сил", "noun", "There is no capacity for a new project.", "На новый проект нет запаса сил."),
        _w("secondment", "/sɪˈkɒnd.mənt/", "временный перевод", "noun", "The secondment lasts four months.", "Временный перевод длится четыре месяца."),
        _w("headcount", "/ˈhed.kaʊnt/", "численность штата", "noun", "Headcount stays the same after the merger.", "После слияния численность не меняется."),
    ],
    "news-opinion": [
        _w("headline", "/ˈhed.laɪn/", "заголовок", "noun", "The headline promised more than the piece.", "Заголовок обещал больше, чем сам текст."),
        _w("dateline", "/ˈdeɪt.laɪn/", "строка с местом и датой", "noun", "The dateline is Leeds, not London.", "В строке — Лидс, не Лондон."),
        _w("paywall", "/ˈpeɪ.wɔːl/", "платный доступ", "noun", "The paywall hid the last three paragraphs.", "Платный доступ скрыл последние три абзаца."),
        _w("syndication", "/ˌsɪn.dɪˈkeɪ.ʃən/", "синдикация", "noun", "Syndication copied the error into six papers.", "Синдикация разнесла ошибку по шести газетам."),
        _w("correction", "/kəˈrek.ʃən/", "опровержение, правка", "noun", "A correction ran two days later.", "Правку дали через два дня."),
        _w("angle", "/ˈæŋ.ɡəl/", "угол подачи", "noun", "The night-shift angle is still missing.", "Угол про ночную смену всё ещё отсутствует."),
        _w("stringer", "/ˈstrɪŋ.ə/", "внештатный корреспондент", "noun", "A stringer filed from the harbour at dawn.", "Внештатник передал материал из гавани на рассвете."),
        _w("embargo", "/ɪmˈbɑː.ɡəʊ/", "эмбарго на публикацию", "noun", "The embargo lifts at six tomorrow.", "Эмбарго снимается завтра в шесть."),
        _w("pundit", "/ˈpʌn.dɪt/", "комментатор", "noun", "The pundit had not read the annex.", "Комментатор не читал приложение."),
        _w("soundbite", "/ˈsaʊnd.baɪt/", "короткая цитата", "noun", "One soundbite replaced the whole interview.", "Одна короткая цитата заменила всё интервью."),
    ],
    "wellbeing": [
        _w("paced", "/peɪst/", "размеренный", "adjective", "A paced morning leaves fewer mistakes.", "Размеренное утро даёт меньше ошибок."),
        _w("overwork", "/ˌəʊ.vəˈwɜːk/", "переработка", "noun", "Overwork showed first as skipped lunches.", "Переработка сначала проявилась пропущенными обедами."),
        _w("decompress", "/ˌdiː.kəmˈpres/", "сбрасывать напряжение", "verb", "I decompress on the last two stops.", "Я сбрасываю напряжение на последних двух остановках."),
        _w("headspace", "/ˈhed.speɪs/", "ясность в голове", "noun", "There is no headspace for a new chat.", "На новый чат нет ясности в голове."),
        _w("rest day", "/ˈrest deɪ/", "день отдыха", "noun", "Tuesday is a rest day after the night shift.", "Вторник — день отдыха после ночной смены."),
        _w("screen time", "/ˈskriːn taɪm/", "время у экрана", "noun", "Screen time after nine ruins her sleep.", "Экран после девяти портит ей сон."),
        _w("grounding", "/ˈɡraʊn.dɪŋ/", "заземление, сбор", "noun", "A short walk is her grounding, not an app.", "Её сбор — короткая прогулка, не приложение."),
        _w("compassion", "/kəmˈpæʃ.ən/", "сострадание", "noun", "Compassion here is a later deadline, not a slogan.", "Сострадание здесь — более поздний срок, не слоган."),
        _w("withdrawn", "/wɪðˈdrɔːn/", "замкнутый", "adjective", "He grew withdrawn during the long winter.", "За долгую зиму он стал замкнутее."),
        _w("replenish", "/rɪˈplen.ɪʃ/", "восполнять", "verb", "Sleep will replenish more than another coffee.", "Сон восполнит больше, чем ещё один кофе."),
    ],
    "argument-rhetoric": [
        _w("concede", "/kənˈsiːd/", "уступать в споре", "verb", "I concede the chart is older than I said.", "Уступаю: график старше, чем я сказал."),
        _w("hedge", "/hedʒ/", "смягчать формулировку", "verb", "Hedge the claim if the town is unusual.", "Смягчи утверждение, если город нетипичный."),
        _w("steelman", "/ˈstiːl.mæn/", "усилить чужой довод", "verb", "Steelman the other side before you cut it.", "Усиль чужой довод, прежде чем его резать."),
        _w("straw man", "/ˈstrɔː mæn/", "подмена тезиса", "noun", "That is a straw man, not her actual claim.", "Это подмена тезиса, не её настоящее утверждение."),
        _w("burden of proof", "/ˌbɜː.dən əv ˈpruːf/", "бремя доказательства", "noun", "The burden of proof sits with the late figure.", "Бремя доказательства лежит на поздней цифре."),
        _w("non sequitur", "/ˌnɒn ˈsek.wɪ.tə/", "не следует из сказанного", "noun", "The last sentence is a non sequitur.", "Последнее предложение не следует из сказанного."),
        _w("tautology", "/tɔːˈtɒl.ə.dʒi/", "тавтология", "noun", "Calling it 'true because it is true' is a tautology.", "«Верно, потому что верно» — тавтология."),
        _w("equivocation", "/ɪˌkwɪv.əˈkeɪ.ʃən/", "двусмысленность", "noun", "The equivocation hides in the word 'soon'.", "Двусмысленность спрятана в слове «скоро»."),
        _w("concession", "/kənˈseʃ.ən/", "уступка", "noun", "A small concession opened the rest of the talk.", "Небольшая уступка открыла остальной разговор."),
        _w("warranted", "/ˈwɒr.ən.tɪd/", "обоснованный", "adjective", "A delay is warranted if the fog stays.", "Задержка обоснованна, если туман не спадёт."),
    ],
    "fine-shades": [
        _w("oblique", "/əˈbliːk/", "косвенный", "adjective", "The praise was oblique and therefore sharper.", "Похвала была косвенной и оттого острее."),
        _w("gnomic", "/ˈnəʊ.mɪk/", "афористичный", "adjective", "A gnomic last line closed the chapter.", "Афористичная последняя строка закрыла главу."),
        _w("orotund", "/ˈɒr.ə.tʌnd/", "гулкий, пышный", "adjective", "The orotund opening hid a thin point.", "Пышное вступление прятало тонкую мысль."),
        _w("mealy-mouthed", "/ˈmiː.li maʊðd/", "уклончивый", "adjective", "The mealy-mouthed reply named no date.", "Уклончивый ответ не назвал даты."),
        _w("lapidary", "/ˈlæp.ɪ.dər.i/", "чеканный", "adjective", "The plaque uses a lapidary two-line form.", "На табличке чеканная форма из двух строк."),
        _w("querulous", "/ˈkwer.jə.ləs/", "плаксиво-ворчливый", "adjective", "A querulous note asked for a later slot.", "Плаксивая записка просила более поздний слот."),
        _w("sotto voce", "/ˌsɒt.əʊ ˈvəʊ.tʃeɪ/", "вполголоса", "adverb", "The warning was sotto voce and still reached the row.", "Предупреждение было вполголоса и всё равно дошло до ряда."),
        _w("sibylline", "/ˈsɪb.ɪ.laɪn/", "тёмный, прорицательный", "adjective", "The sibylline footnote explained nothing.", "Тёмная сноска ничего не объяснила."),
        _w("minatory", "/ˈmɪn.ə.tər.i/", "угрожающий", "adjective", "A minatory last sentence closed the letter.", "Угрожающее последнее предложение закрыло письмо."),
        _w("jejune", "/dʒɪˈdʒuːn/", "плоский, тощий по мысли", "adjective", "The jejune summary skipped the night shift.", "Плоское резюме обошло ночную смену."),
    ],
}

PLUS_TOPICS = [
    _topic(
        "numbers-quantity",
        "Числа и количество",
        "Сколько, хватает ли, пара, половина — слова, без которых трудно купить и посчитать.",
        "A1",
        [
            _w("number", "/ˈnʌm.bə/", "число, номер", "noun", "Write the house number on the form.", "Напиши номер дома в бланке."),
            _w("half", "/hɑːf/", "половина", "noun", "Half of the cake is still on the plate.", "Половина торта всё ещё на тарелке."),
            _w("pair", "/peə/", "пара", "noun", "I need a new pair of socks.", "Мне нужна новая пара носков."),
            _w("dozen", "/ˈdʌz.ən/", "дюжина", "noun", "Buy a dozen eggs if they look fresh.", "Купи дюжину яиц, если они свежие."),
            _w("enough", "/ɪˈnʌf/", "достаточно", "determiner", "There is enough bread for breakfast.", "Хлеба хватит на завтрак."),
            _w("empty", "/ˈemp.ti/", "пустой", "adjective", "The bottle is empty; take another.", "Бутылка пустая, возьми другую."),
            _w("full", "/fʊl/", "полный", "adjective", "The bin is full already.", "Ведро уже полное."),
            _w("many", "/ˈmen.i/", "много (исчисл.)", "determiner", "Too many bags will not fit.", "Слишком много сумок не влезет."),
            _w("few", "/fjuː/", "мало", "determiner", "Few seats are left on the late bus.", "На позднем автобусе осталось мало мест."),
            _w("extra", "/ˈek.strə/", "лишний, дополнительный", "adjective", "Bring an extra pen for the test.", "Возьми лишнюю ручку на тест."),
            _w("piece", "/piːs/", "кусок", "noun", "One piece of cheese is enough.", "Одного куска сыра достаточно."),
            _w("slice", "/slaɪs/", "ломтик", "noun", "Cut a thin slice of lemon.", "Отрежь тонкий ломтик лимона."),
            _w("whole", "/həʊl/", "целый", "adjective", "I ate the whole apple on the walk.", "Я съел целое яблоко на прогулке."),
            _w("total", "/ˈtəʊ.təl/", "итого", "noun", "The total is less than I expected.", "Итого меньше, чем я думал."),
            _w("count", "/kaʊnt/", "считать", "verb", "Count the chairs before guests arrive.", "Посчитай стулья, прежде чем придут гости."),
            _w("minus", "/ˈmaɪ.nəs/", "минус", "preposition", "Ten minus three is seven.", "Десять минус три — семь."),
            _w("plus", "/plʌs/", "плюс", "preposition", "Two plus two is still four.", "Два плюс два по-прежнему четыре."),
            _w("twice", "/twaɪs/", "дважды", "adverb", "The ferry crosses twice a day.", "Паром ходит дважды в день."),
            _w("once", "/wʌns/", "один раз", "adverb", "I have been there only once.", "Я был там только один раз."),
            _w("both", "/bəʊθ/", "оба", "determiner", "Both keys are in the same drawer.", "Оба ключа в одном ящике."),
        ],
    ),
    _topic(
        "describing-things",
        "Как описать вещь",
        "Большой, дешёвый, чистый, тяжёлый — короткие прилагательные для быта.",
        "A1",
        [
            _w("big", "/bɪɡ/", "большой", "adjective", "The big bag will not fit under the seat.", "Большая сумка не влезет под сиденье."),
            _w("small", "/smɔːl/", "маленький", "adjective", "A small table is enough for tea.", "Для чая хватит маленького стола."),
            _w("new", "/njuː/", "новый", "adjective", "The new lock is quieter.", "Новый замок тише."),
            _w("old", "/əʊld/", "старый", "adjective", "The old map still shows the ferry.", "На старой карте всё ещё есть паром."),
            _w("cheap", "/tʃiːp/", "дешёвый", "adjective", "Cheap bread goes stale faster.", "Дешёвый хлеб быстрее черствеет."),
            _w("expensive", "/ɪkˈspen.sɪv/", "дорогой", "adjective", "The later train is more expensive.", "Поздний поезд дороже."),
            _w("clean", "/kliːn/", "чистый", "adjective", "Leave a clean cup for the morning.", "Оставь чистую чашку на утро."),
            _w("dirty", "/ˈdɜː.ti/", "грязный", "adjective", "Dirty boots stay on the porch.", "Грязные сапоги остаются на крыльце."),
            _w("easy", "/ˈiː.zi/", "лёгкий, простой", "adjective", "This form is easy if you have the date.", "Бланк простой, если есть дата."),
            _w("hard", "/hɑːd/", "трудный; жёсткий", "adjective", "The last hill is hard on a bike.", "Последний холм на велосипеде трудный."),
            _w("fast", "/fɑːst/", "быстрый", "adjective", "A fast walk is enough before dinner.", "Быстрой прогулки до ужина хватит."),
            _w("slow", "/sləʊ/", "медленный", "adjective", "The slow lift stops on every floor.", "Медленный лифт останавливается на каждом этаже."),
            _w("heavy", "/ˈhev.i/", "тяжёлый", "adjective", "The box is too heavy for one person.", "Коробка слишком тяжёлая для одного."),
            _w("light", "/laɪt/", "лёгкий", "adjective", "A light bag is better on the stairs.", "На лестнице лучше лёгкая сумка."),
            _w("open", "/ˈəʊ.pən/", "открытый", "adjective", "The shop is open until nine.", "Магазин открыт до девяти."),
            _w("closed", "/kləʊzd/", "закрытый", "adjective", "The museum is closed on Mondays.", "Музей по понедельникам закрыт."),
            _w("long", "/lɒŋ/", "длинный", "adjective", "The queue is long after five.", "После пяти очередь длинная."),
            _w("short", "/ʃɔːt/", "короткий", "adjective", "Take the short path if it is dry.", "Иди короткой тропой, если сухо."),
            _w("quiet", "/ˈkwaɪ.ət/", "тихий", "adjective", "This street is quiet after eight.", "После восьми на этой улице тихо."),
            _w("loud", "/laʊd/", "громкий", "adjective", "A loud train passes at midnight.", "В полночь проходит громкий поезд."),
        ],
    ),
    _topic(
        "prepositions-place",
        "Предлоги места",
        "Где лежит вещь и куда идти: in, on, under, next to, between.",
        "A1",
        [
            _w("in", "/ɪn/", "в", "preposition", "The keys are in the bowl.", "Ключи в миске."),
            _w("on", "/ɒn/", "на", "preposition", "Leave the map on the table.", "Оставь карту на столе."),
            _w("under", "/ˈʌn.də/", "под", "preposition", "The cat is under the chair.", "Кот под стулом."),
            _w("next to", "/ˈnekst tuː/", "рядом с", "preposition", "Sit next to the window.", "Сядь рядом с окном."),
            _w("between", "/bɪˈtwiːn/", "между", "preposition", "The bakery is between the bank and the park.", "Пекарня между банком и парком."),
            _w("behind", "/bɪˈhaɪnd/", "позади", "preposition", "The bins are behind the house.", "Баки стоят позади дома."),
            _w("in front of", "/ɪn ˈfrʌnt əv/", "перед", "preposition", "Wait in front of the station clock.", "Жди перед вокзальными часами."),
            _w("above", "/əˈbʌv/", "над", "preposition", "The lamp hangs above the table.", "Лампа висит над столом."),
            _w("below", "/bɪˈləʊ/", "ниже", "preposition", "The cellar is below the kitchen.", "Погреб ниже кухни."),
            _w("near", "/nɪə/", "близко к", "preposition", "There is a stop near the school.", "Остановка есть рядом со школой."),
            _w("far from", "/ˈfɑː frəm/", "далеко от", "preposition", "The farm is far from the last shop.", "Ферма далеко от последнего магазина."),
            _w("inside", "/ɪnˈsaɪd/", "внутри", "preposition", "It is warmer inside the porch.", "Внутри крыльца теплее."),
            _w("outside", "/ˌaʊtˈsaɪd/", "снаружи", "preposition", "Leave wet coats outside the kitchen.", "Мокрые пальто оставь снаружи кухни."),
            _w("through", "/θruː/", "через, сквозь", "preposition", "Walk through the market, then turn left.", "Пройди через рынок и поверни налево."),
            _w("across", "/əˈkrɒs/", "через (на другую сторону)", "preposition", "Go across the bridge and wait.", "Перейди мост и подожди."),
            _w("along", "/əˈlɒŋ/", "вдоль", "preposition", "Walk along the river until the second bench.", "Иди вдоль реки до второй скамейки."),
            _w("around", "/əˈraʊnd/", "вокруг", "preposition", "There is a path around the lake.", "Вокруг озера есть тропа."),
            _w("opposite", "/ˈɒp.ə.zɪt/", "напротив", "preposition", "The café is opposite the library.", "Кафе напротив библиотеки."),
            _w("at", "/æt/", "у, в (точке)", "preposition", "Meet me at the bus stop.", "Встретимся на автобусной остановке."),
            _w("into", "/ˈɪn.tuː/", "внутрь", "preposition", "Come into the hall and close the door.", "Заходи в прихожую и закрой дверь."),
        ],
    ),
] + MORE_PLUS_TOPICS

_UNUSED_DOC = r'''
    _topic(
        "hotels-staying",
        "Отель и ночёвка",
        "Ресепшен, бронь, багаж, этаж — слова для ночи в чужом городе.",
        "A2",
        [
            _w("reception", "/rɪˈsep.ʃən/", "ресепшен", "noun", "Ask at reception for a later checkout.", "Спроси на ресепшене про более поздний выезд."),
            _w("booking", "/ˈbʊk.ɪŋ/", "бронь", "noun", "The booking is under my family name.", "Бронь на мою фамилию."),
            _w("check-in", "/ˈtʃek ɪn/", "заселение", "noun", "Check-in starts at three, not before.", "Заселение с трёх, не раньше."),
            _w("checkout", "/ˈtʃek.aʊt/", "выезд", "noun", "Checkout is eleven; bags can stay till two.", "Выезд в одиннадцать; сумки можно оставить до двух."),
            _w("luggage", "/ˈlʌɡ.ɪdʒ/", "багаж", "noun", "Leave the luggage by the lift.", "Оставь багаж у лифта."),
            _w("lift", "/lɪft/", "лифт", "noun", "The lift is slow after breakfast.", "После завтрака лифт медленный."),
            _w("floor", "/flɔː/", "этаж", "noun", "Our room is on the fourth floor.", "Наш номер на четвёртом этаже."),
            _w("double room", "/ˌdʌb.əl ˈruːm/", "двухместный номер", "noun", "A double room is cheaper than two singles.", "Двухместный дешевле двух одноместных."),
            _w("single room", "/ˌsɪŋ.ɡəl ˈruːm/", "одноместный номер", "noun", "I booked a single room near the stairs.", "Я взял одноместный у лестницы."),
            _w("balcony", "/ˈbæl.kə.ni/", "балкон", "noun", "The balcony faces a quiet yard.", "Балкон выходит в тихий двор."),
            _w("reservation", "/ˌrez.əˈveɪ.ʃən/", "бронирование", "noun", "The reservation number is on the email.", "Номер бронирования в письме."),
            _w("cancel", "/ˈkæn.səl/", "отменять", "verb", "Cancel before six or you still pay.", "Отмени до шести, иначе всё равно заплатишь."),
            _w("key card", "/ˈkiː kɑːd/", "карта-ключ", "noun", "The key card stops working near the lift.", "Карта-ключ сбоит у лифта."),
            _w("wifi", "/ˈwaɪ.faɪ/", "вайфай", "noun", "The wifi password is on the door.", "Пароль вайфая на двери."),
            _w("housekeeping", "/ˈhaʊsˌkiː.pɪŋ/", "горничная служба", "noun", "Housekeeping comes after nine if you ask.", "Горничная приходит после девяти, если попросить."),
            _w("minibar", "/ˈmɪn.i.bɑː/", "мини-бар", "noun", "The minibar prices are on a card inside.", "Цены мини-бара на карточке внутри."),
            _w("late checkout", "/ˌleɪt ˈtʃek.aʊt/", "поздний выезд", "noun", "Late checkout costs extra on Sundays.", "Поздний выезд в воскресенье стоит дороже."),
            _w("twin room", "/ˌtwɪn ˈruːm/", "номер с двумя кроватями", "noun", "A twin room is better if you need two beds.", "Номер с двумя кроватями лучше, если нужны две."),
            _w("view", "/vjuː/", "вид из окна", "noun", "The view is a brick wall, not the river.", "Вид — кирпичная стена, не река."),
        ],
    ),
'''
