"""Expanded dialogue scripts (8–14 turns). Preserve phrases used by existing gaps/choices."""

from __future__ import annotations

DIALOGUE_LINES: dict[str, list[dict]] = {
    "dialogue-a1-coffee-order": [
        {"speaker": "Clerk", "text": "Hi! What would you like?", "ru": "Здравствуйте! Что будете?"},
        {"speaker": "Customer", "text": "A large coffee, please.", "ru": "Большой кофе, пожалуйста."},
        {"speaker": "Clerk", "text": "To stay or to go?", "ru": "Здесь или с собой?"},
        {"speaker": "Customer", "text": "To go, thanks.", "ru": "С собой, спасибо."},
        {"speaker": "Clerk", "text": "Would you like milk or sugar?", "ru": "Молоко или сахар?"},
        {"speaker": "Customer", "text": "A little milk, no sugar.", "ru": "Немного молока, без сахара."},
        {"speaker": "Clerk", "text": "That will be three euros.", "ru": "Три евро."},
        {"speaker": "Customer", "text": "Here you are. Keep the change.", "ru": "Вот, сдачу оставьте."},
        {"speaker": "Clerk", "text": "Thank you. Enjoy your coffee!", "ru": "Спасибо. Приятного кофе!"},
        {"speaker": "Customer", "text": "Thanks. Have a nice day.", "ru": "Спасибо. Хорошего дня."},
    ],
    "dialogue-a1-asking-time": [
        {"speaker": "A", "text": "Excuse me, what time is it?", "ru": "Извините, который час?"},
        {"speaker": "B", "text": "It's half past three.", "ru": "Половина четвёртого."},
        {"speaker": "A", "text": "Thank you!", "ru": "Спасибо!"},
        {"speaker": "B", "text": "You're welcome.", "ru": "Пожалуйста."},
        {"speaker": "A", "text": "Is the museum still open?", "ru": "Музей ещё открыт?"},
        {"speaker": "B", "text": "Yes, until six o'clock.", "ru": "Да, до шести."},
        {"speaker": "A", "text": "Great. How do I get there?", "ru": "Отлично. Как туда пройти?"},
        {"speaker": "B", "text": "Go straight, then turn right at the lights.", "ru": "Прямо, потом направо на светофоре."},
        {"speaker": "A", "text": "Thanks again for your help.", "ru": "Ещё раз спасибо за помощь."},
        {"speaker": "B", "text": "No problem. Enjoy your visit.", "ru": "Не за что. Хорошей прогулки."},
    ],
    "dialogue-a1-bus-stop": [
        {"speaker": "Tourist", "text": "Does this bus go to the museum?", "ru": "Этот автобус идёт к музею?"},
        {"speaker": "Local", "text": "No, you need bus seven.", "ru": "Нет, вам нужен седьмой."},
        {"speaker": "Tourist", "text": "Where can I catch it?", "ru": "Где его поймать?"},
        {"speaker": "Local", "text": "At the next stop, two minutes from here.", "ru": "На следующей остановке, в двух минутах."},
        {"speaker": "Tourist", "text": "How often does bus seven come?", "ru": "Как часто ходит седьмой?"},
        {"speaker": "Local", "text": "About every ten minutes.", "ru": "Примерно каждые десять минут."},
        {"speaker": "Tourist", "text": "Do I need exact coins?", "ru": "Нужны точные монеты?"},
        {"speaker": "Local", "text": "No, you can pay by card on the bus.", "ru": "Нет, можно картой в автобусе."},
        {"speaker": "Tourist", "text": "Perfect. Thanks for your help.", "ru": "Отлично. Спасибо за помощь."},
        {"speaker": "Local", "text": "You're welcome. Have a good visit.", "ru": "Пожалуйста. Хорошего визита."},
    ],
    "dialogue-a1-hotel-checkin": [
        {"speaker": "Guest", "text": "Hello. I have a reservation under Kim.", "ru": "Здравствуйте. Бронь на имя Ким."},
        {"speaker": "Reception", "text": "One moment. A single room for two nights?", "ru": "Минутку. Одноместный на две ночи?"},
        {"speaker": "Guest", "text": "Yes, that's right.", "ru": "Да, всё верно."},
        {"speaker": "Reception", "text": "Your key is for room twelve. Breakfast starts at seven.", "ru": "Ключ от комнаты двенадцать. Завтрак с семи."},
        {"speaker": "Guest", "text": "Is Wi‑Fi included?", "ru": "Wi‑Fi включён?"},
        {"speaker": "Reception", "text": "Yes. The password is on the key card.", "ru": "Да. Пароль на карте-ключе."},
        {"speaker": "Guest", "text": "Where can I leave my suitcase for a minute?", "ru": "Куда на минуту поставить чемодан?"},
        {"speaker": "Reception", "text": "Next to the sofa is fine.", "ru": "Можно у дивана."},
        {"speaker": "Guest", "text": "Thank you very much.", "ru": "Большое спасибо."},
        {"speaker": "Reception", "text": "Enjoy your stay.", "ru": "Приятного пребывания."},
    ],
    "dialogue-a1-buying-stamps": [
        {"speaker": "Customer", "text": "I need stamps for a postcard to Italy.", "ru": "Нужны марки на открытку в Италию."},
        {"speaker": "Clerk", "text": "International stamps are on the left shelf.", "ru": "Международные — на левой полке."},
        {"speaker": "Customer", "text": "How much is one stamp?", "ru": "Сколько стоит одна марка?"},
        {"speaker": "Clerk", "text": "Two euros each.", "ru": "По два евро."},
        {"speaker": "Customer", "text": "I'll take three, please.", "ru": "Три, пожалуйста."},
        {"speaker": "Clerk", "text": "That will be six euros.", "ru": "Шесть евро."},
        {"speaker": "Customer", "text": "Can I post the card here as well?", "ru": "Можно здесь же отправить открытку?"},
        {"speaker": "Clerk", "text": "Yes. Drop it in the blue box by the door.", "ru": "Да. Бросьте в синий ящик у двери."},
        {"speaker": "Customer", "text": "Great, thank you.", "ru": "Отлично, спасибо."},
        {"speaker": "Clerk", "text": "Have a nice day.", "ru": "Хорошего дня."},
    ],
    "dialogue-a1-finding-toilet": [
        {"speaker": "Visitor", "text": "Excuse me, where is the toilet?", "ru": "Извините, где туалет?"},
        {"speaker": "Guard", "text": "Go straight and turn left after the café.", "ru": "Прямо и налево после кафе."},
        {"speaker": "Visitor", "text": "Is it free?", "ru": "Он бесплатный?"},
        {"speaker": "Guard", "text": "Yes. The code is on the receipt if you buy something.", "ru": "Да. Код на чеке, если что-то купите."},
        {"speaker": "Visitor", "text": "I already bought tea. Is that enough?", "ru": "Я уже купил чай. Этого хватит?"},
        {"speaker": "Guard", "text": "Yes. Show the receipt at the door.", "ru": "Да. Покажите чек у двери."},
        {"speaker": "Visitor", "text": "How far is it from here?", "ru": "Как далеко отсюда?"},
        {"speaker": "Guard", "text": "About one minute on foot.", "ru": "Минуты пешком."},
        {"speaker": "Visitor", "text": "Thanks for the clear directions.", "ru": "Спасибо за понятные указания."},
        {"speaker": "Guard", "text": "You're welcome.", "ru": "Пожалуйста."},
    ],
    "dialogue-a2-doctor-appointment": [
        {"speaker": "Reception", "text": "Good morning, City Clinic.", "ru": "Доброе утро, городская клиника."},
        {"speaker": "Patient", "text": "I'd like to book an appointment with Dr. Fox.", "ru": "Хочу записаться к доктору Фоксу."},
        {"speaker": "Reception", "text": "We have a slot on Tuesday at eleven.", "ru": "Есть окно во вторник в 11."},
        {"speaker": "Patient", "text": "Perfect. My name is Elena Volkova.", "ru": "Отлично. Меня зовут Елена Волкова."},
        {"speaker": "Reception", "text": "Is this your first visit with us?", "ru": "Это ваш первый визит к нам?"},
        {"speaker": "Patient", "text": "Yes. Do I need to bring anything?", "ru": "Да. Нужно что-то взять с собой?"},
        {"speaker": "Reception", "text": "Your ID and a list of any medicines you take.", "ru": "Документ и список лекарств, если принимаете."},
        {"speaker": "Patient", "text": "Understood. Can I get an SMS reminder?", "ru": "Поняла. Можно SMS-напоминание?"},
        {"speaker": "Reception", "text": "Of course. I'll add your number now.", "ru": "Конечно. Сейчас добавлю номер."},
        {"speaker": "Patient", "text": "Thank you. See you on Tuesday.", "ru": "Спасибо. До вторника."},
    ],
    "dialogue-a2-returning-item": [
        {"speaker": "Customer", "text": "I'd like to return this sweater. It's too small.", "ru": "Хочу вернуть свитер. Он мал."},
        {"speaker": "Staff", "text": "Do you have the receipt?", "ru": "Чек есть?"},
        {"speaker": "Customer", "text": "Yes, here it is.", "ru": "Да, вот."},
        {"speaker": "Staff", "text": "Would you like a refund or an exchange?", "ru": "Вернуть деньги или обменять?"},
        {"speaker": "Customer", "text": "An exchange for a larger size, please.", "ru": "Обмен на больший размер, пожалуйста."},
        {"speaker": "Staff", "text": "We have a large in the same colour.", "ru": "Есть большой того же цвета."},
        {"speaker": "Customer", "text": "Can I try it on quickly?", "ru": "Можно быстро примерить?"},
        {"speaker": "Staff", "text": "Sure. The fitting rooms are on the left.", "ru": "Конечно. Примерочные слева."},
        {"speaker": "Customer", "text": "This one fits. Let's exchange it.", "ru": "Этот подходит. Давайте обменяем."},
        {"speaker": "Staff", "text": "Done. Here's your new receipt.", "ru": "Готово. Вот новый чек."},
    ],
    "dialogue-a2-group-project": [
        {"speaker": "Sam", "text": "Can you prepare the slides?", "ru": "Можешь сделать слайды?"},
        {"speaker": "Nina", "text": "Sure. Who will write the short report?", "ru": "Конечно. Кто напишет короткий отчёт?"},
        {"speaker": "Sam", "text": "I will. Let's meet on Thursday to practise.", "ru": "Я. Встретимся в четверг порепетировать."},
        {"speaker": "Nina", "text": "Good idea. I'll send my draft by Wednesday.", "ru": "Хорошая идея. Пришлю черновик к среде."},
        {"speaker": "Sam", "text": "Should we practise in the library?", "ru": "Потренируемся в библиотеке?"},
        {"speaker": "Nina", "text": "Yes. I'll book a quiet room for twenty minutes.", "ru": "Да. Забронирую тихую комнату на двадцать минут."},
        {"speaker": "Sam", "text": "I'll bring printed notes for the report.", "ru": "Принесу распечатки к отчёту."},
        {"speaker": "Nina", "text": "If anything changes, write in the group chat.", "ru": "Если что изменится — напиши в чат."},
        {"speaker": "Sam", "text": "Will do. Thanks for taking the slides.", "ru": "Сделаю. Спасибо, что берёшь слайды."},
        {"speaker": "Nina", "text": "No problem. We can finish this together.", "ru": "Не за что. Справимся вместе."},
    ],
    "dialogue-a2-allergy-order": [
        {"speaker": "Guest", "text": "Does this soup contain nuts?", "ru": "В этом супе есть орехи?"},
        {"speaker": "Waiter", "text": "No nuts, but it has cream. Are you allergic to dairy?", "ru": "Орехов нет, но есть сливки. У вас аллергия на молочное?"},
        {"speaker": "Guest", "text": "Yes. Could I have the salad without cheese instead?", "ru": "Да. Можно салат без сыра?"},
        {"speaker": "Waiter", "text": "Of course. I'll note it for the kitchen.", "ru": "Конечно. Отмечу для кухни."},
        {"speaker": "Guest", "text": "Thank you. What dressing is safe?", "ru": "Спасибо. Какая заправка безопасна?"},
        {"speaker": "Waiter", "text": "The lemon oil dressing has no dairy.", "ru": "Заправка с лимонным маслом без молочного."},
        {"speaker": "Guest", "text": "That sounds good. And still water, please.", "ru": "Отлично. И негазированную воду, пожалуйста."},
        {"speaker": "Waiter", "text": "Coming right up.", "ru": "Сейчас принесу."},
        {"speaker": "Guest", "text": "One more thing — no croutons either.", "ru": "Ещё — без сухариков."},
        {"speaker": "Waiter", "text": "Understood. Salad without cheese or croutons.", "ru": "Понял. Салат без сыра и сухариков."},
    ],
    "dialogue-a2-library-fine": [
        {"speaker": "Librarian", "text": "This book is five days overdue.", "ru": "Книга просрочена на пять дней."},
        {"speaker": "Student", "text": "Oh no. How much is the fine?", "ru": "Ой. Какой штраф?"},
        {"speaker": "Librarian", "text": "Two pounds in total. You can pay by card.", "ru": "Всего два фунта. Можно картой."},
        {"speaker": "Student", "text": "I'll pay now and renew it for another week.", "ru": "Заплачу сейчас и продлю ещё на неделю."},
        {"speaker": "Librarian", "text": "Done. Please return it on time next time.", "ru": "Готово. В следующий раз верните вовремя."},
        {"speaker": "Student", "text": "Can I set an email reminder?", "ru": "Можно почтовое напоминание?"},
        {"speaker": "Librarian", "text": "Yes. I'll tick that in your account.", "ru": "Да. Отмечу в вашем аккаунте."},
        {"speaker": "Student", "text": "Is there a limit on renewals?", "ru": "Есть лимит продлений?"},
        {"speaker": "Librarian", "text": "Two renewals if nobody else requests the book.", "ru": "Два, если никто не ждёт книгу."},
        {"speaker": "Student", "text": "Perfect. Thanks for explaining.", "ru": "Отлично. Спасибо за объяснение."},
    ],
    "dialogue-a2-gym-membership": [
        {"speaker": "Client", "text": "How much is a monthly membership?", "ru": "Сколько стоит месячный абонемент?"},
        {"speaker": "Staff", "text": "Thirty-five if you pay monthly, or three hundred for a year.", "ru": "Тридцать пять помесячно или триста за год."},
        {"speaker": "Client", "text": "Does it include group classes?", "ru": "Групповые занятия включены?"},
        {"speaker": "Staff", "text": "Yes, except the weekend yoga sessions.", "ru": "Да, кроме йоги по выходным."},
        {"speaker": "Client", "text": "Can I freeze the membership for holidays?", "ru": "Можно заморозить на отпуск?"},
        {"speaker": "Staff", "text": "Once a year for up to four weeks.", "ru": "Раз в год до четырёх недель."},
        {"speaker": "Client", "text": "I'll start with the monthly plan.", "ru": "Начну с помесячного."},
        {"speaker": "Staff", "text": "Great. I need a photo ID and a bank card.", "ru": "Отлично. Нужны документ и карта."},
        {"speaker": "Client", "text": "Here they are. When can I train?", "ru": "Вот. Когда можно заниматься?"},
        {"speaker": "Staff", "text": "Your pass works from this evening.", "ru": "Абонемент действует с сегодняшнего вечера."},
    ],
    "dialogue-b1-job-interview": [
        {"speaker": "Interviewer", "text": "Tell me about a problem you solved at work.", "ru": "Расскажите о проблеме, которую вы решили на работе."},
        {
            "speaker": "Candidate",
            "text": "Our delivery was late, so I contacted the supplier and updated the clients the same day.",
            "ru": "Доставка опоздала, я связался с поставщиком и в тот же день сообщил клиентам.",
        },
        {"speaker": "Interviewer", "text": "What was the result?", "ru": "Какой был результат?"},
        {
            "speaker": "Candidate",
            "text": "We kept the clients and improved our checklist for future delays.",
            "ru": "Клиентов сохранили и улучшили чек-лист на будущее.",
        },
        {"speaker": "Interviewer", "text": "How did you prioritise under pressure?", "ru": "Как вы расставляли приоритеты под давлением?"},
        {
            "speaker": "Candidate",
            "text": "I fixed the client updates first, then logged the supplier issue for the team.",
            "ru": "Сначала обновил клиентов, потом зафиксировал проблему поставщика для команды.",
        },
        {"speaker": "Interviewer", "text": "Would you do anything differently now?", "ru": "Сделали бы что-то иначе сейчас?"},
        {
            "speaker": "Candidate",
            "text": "I would add earlier warning emails when a shipment looks risky.",
            "ru": "Добавил бы ранние предупреждения, если поставка выглядит рискованной.",
        },
        {"speaker": "Interviewer", "text": "That sounds practical. Any questions for us?", "ru": "Звучит практично. Есть вопросы к нам?"},
        {
            "speaker": "Candidate",
            "text": "How does the team share incident notes after a delay?",
            "ru": "Как команда делится заметками после задержки?",
        },
    ],
    "dialogue-b1-flatmate-chores": [
        {"speaker": "Alex", "text": "The kitchen is a mess again. Can we set a cleaning schedule?", "ru": "Кухня снова в беспорядке. Составим график уборки?"},
        {"speaker": "Jordan", "text": "Sure. I'll wash the dishes on weekdays if you take the weekend floors.", "ru": "Ок. Я мою посуду в будни, ты — полы на выходных."},
        {"speaker": "Alex", "text": "Deal. Let's also buy more bin bags tomorrow.", "ru": "Договорились. Завтра купим ещё мешки для мусора."},
        {"speaker": "Jordan", "text": "I'll add it to the shared list.", "ru": "Добавлю в общий список."},
        {"speaker": "Alex", "text": "What about the bathroom on Wednesdays?", "ru": "А ванная по средам?"},
        {"speaker": "Jordan", "text": "I can do odd weeks; you take even weeks.", "ru": "Я — нечётные недели, ты — чётные."},
        {"speaker": "Alex", "text": "Works for me. Should we put a reminder on the fridge?", "ru": "Мне ок. Напомним на холодильнике?"},
        {"speaker": "Jordan", "text": "Yes. A simple checklist will help guests too.", "ru": "Да. Простой чек-лист поможет и гостям."},
        {"speaker": "Alex", "text": "Great. Thanks for being flexible.", "ru": "Супер. Спасибо, что гибко."},
        {"speaker": "Jordan", "text": "Same. Cleaner flat, calmer mornings.", "ru": "Взаимно. Чище квартира — спокойнее утра."},
    ],
    "dialogue-b1-deadline-push": [
        {"speaker": "Priya", "text": "Can we move the report deadline to Wednesday?", "ru": "Можем сдвинуть дедлайн отчёта на среду?"},
        {"speaker": "Marcus", "text": "What's blocking you?", "ru": "Что мешает?"},
        {
            "speaker": "Priya",
            "text": "The sales numbers arrived late, and I still need to check two charts.",
            "ru": "Цифры продаж пришли поздно, ещё нужно проверить два графика.",
        },
        {"speaker": "Marcus", "text": "Wednesday works if you send a short status update today.", "ru": "Среда ок, если сегодня короткий статус."},
        {"speaker": "Priya", "text": "Deal. I'll post it in the channel by five.", "ru": "Договорились. Выложу в канал до пяти."},
        {"speaker": "Marcus", "text": "Please flag any chart that still looks uncertain.", "ru": "Отметь любой график, который ещё сомнителен."},
        {"speaker": "Priya", "text": "I will. The second chart may need a footnote.", "ru": "Сделаю. Ко второму, возможно, нужна сноска."},
        {"speaker": "Marcus", "text": "Fine. Add the footnote rather than delaying further.", "ru": "Ок. Лучше сноска, чем ещё одна задержка."},
        {"speaker": "Priya", "text": "Thanks for the flexibility.", "ru": "Спасибо за гибкость."},
        {"speaker": "Marcus", "text": "Anytime. Clear updates keep the whole team calm.", "ru": "Всегда. Понятные апдейты успокаивают команду."},
    ],
    "dialogue-b1-lost-tourist": [
        {"speaker": "Tourist", "text": "Sorry, is the train station far from here?", "ru": "Извините, вокзал далеко?"},
        {
            "speaker": "Local",
            "text": "About twelve minutes on foot. Cross the bridge, then follow the tram tracks.",
            "ru": "Минут двенадцать пешком. Перейдите мост и идите вдоль трамвайных путей.",
        },
        {"speaker": "Tourist", "text": "Should I take a tram instead?", "ru": "Может, лучше на трамвае?"},
        {
            "speaker": "Local",
            "text": "Only if it starts raining. Walking is usually faster at this hour.",
            "ru": "Только если начнётся дождь. В этот час пешком обычно быстрее.",
        },
        {"speaker": "Tourist", "text": "Is there a café near the bridge?", "ru": "Есть кафе у моста?"},
        {"speaker": "Local", "text": "Yes, the one with green chairs if you need a map signal.", "ru": "Да, с зелёными стульями — там лучше ловит карта."},
        {"speaker": "Tourist", "text": "Perfect. Thanks for the clear directions.", "ru": "Отлично. Спасибо за понятные указания."},
        {"speaker": "Local", "text": "Anytime. Watch the bike lane on the corner.", "ru": "Всегда пожалуйста. На углу смотрите велодорожку."},
        {"speaker": "Tourist", "text": "Got it. Have a nice afternoon.", "ru": "Понял. Хорошего дня."},
        {"speaker": "Local", "text": "You too. The station entrance is under the big clock.", "ru": "И вам. Вход на вокзал под большими часами."},
    ],
    "dialogue-b1-phone-plan": [
        {"speaker": "Customer", "text": "I need more mobile data for travel next month.", "ru": "Нужно больше мобильного интернета для поездки."},
        {
            "speaker": "Advisor",
            "text": "We can add a roaming pack or switch you to a higher local plan.",
            "ru": "Можем добавить роуминг-пакет или перевести на больший местный тариф.",
        },
        {"speaker": "Customer", "text": "Which option is cheaper for two weeks abroad?", "ru": "Что дешевле на две недели за границей?"},
        {
            "speaker": "Advisor",
            "text": "The roaming pack. It pauses automatically when you return.",
            "ru": "Роуминг-пакет. Он сам останавливается по возвращении.",
        },
        {"speaker": "Customer", "text": "Does it cover EU countries only?", "ru": "Только страны ЕС?"},
        {"speaker": "Advisor", "text": "EU plus a short list you can open in the app.", "ru": "ЕС плюс короткий список в приложении."},
        {"speaker": "Customer", "text": "Can I keep my number if I add the pack?", "ru": "Номер сохранится, если добавлю пакет?"},
        {"speaker": "Advisor", "text": "Yes. Nothing changes except the data allowance.", "ru": "Да. Меняется только объём интернета."},
        {"speaker": "Customer", "text": "Please add the roaming pack then.", "ru": "Тогда добавьте роуминг-пакет."},
        {"speaker": "Advisor", "text": "Done. You'll get a confirmation SMS shortly.", "ru": "Готово. Скоро придёт SMS-подтверждение."},
    ],
    "dialogue-b2-customer-complaint": [
        {"speaker": "Client", "text": "I ordered a lamp last week, but the package arrived damaged.", "ru": "Заказывал лампу на прошлой неделе, посылка пришла повреждённой."},
        {"speaker": "Agent", "text": "I'm sorry about that. Could you send a photo of the damage?", "ru": "Извините. Можете прислать фото повреждения?"},
        {"speaker": "Client", "text": "Already done. I attached it to ticket 4821.", "ru": "Уже. Прикрепил к тикету 4821."},
        {
            "speaker": "Agent",
            "text": "Thank you. We'll ship a replacement tomorrow and arrange a pickup for the broken one.",
            "ru": "Спасибо. Завтра отправим замену и организуем забор сломанной.",
        },
        {"speaker": "Client", "text": "Will I need to be home for the pickup?", "ru": "Нужно ли быть дома для забора?"},
        {"speaker": "Agent", "text": "Someone over eighteen should be there between ten and two.", "ru": "Кто-то старше 18 должен быть дома с 10 до 14."},
        {"speaker": "Client", "text": "That works. Please keep the same colour.", "ru": "Подходит. Цвет оставьте тот же."},
        {"speaker": "Agent", "text": "Confirmed. I'll email the tracking link tonight.", "ru": "Подтверждаю. Сегодня вечером пришлю трек."},
        {"speaker": "Client", "text": "Appreciate the clear plan.", "ru": "Спасибо за понятный план."},
        {"speaker": "Agent", "text": "Of course. Message the ticket if anything changes.", "ru": "Конечно. Пишите в тикет, если что изменится."},
    ],
    "dialogue-b2-travel-plan": [
        {"speaker": "Mira", "text": "If we take the early train, we'll have a full day in the old town.", "ru": "Если сядем на ранний поезд, будет целый день в старом городе."},
        {"speaker": "Leo", "text": "True, but the evening tickets are cheaper. We could explore less and save money.", "ru": "Да, но вечерние билеты дешевле. Можно меньше гулять и сэкономить."},
        {"speaker": "Mira", "text": "I'd rather pay a bit more and avoid rushing.", "ru": "Лучше чуть доплатить и не торопиться."},
        {"speaker": "Leo", "text": "Fair enough. Let's book the morning seats tonight.", "ru": "Справедливо. Забронируем утренние места сегодня вечером."},
        {"speaker": "Mira", "text": "Should we reserve a museum slot as well?", "ru": "Забронируем ещё слот в музей?"},
        {"speaker": "Leo", "text": "Yes — midday, after coffee near the square.", "ru": "Да — в полдень, после кофе у площади."},
        {"speaker": "Mira", "text": "I'll pack light so we can walk more.", "ru": "Возьму лёгкий рюкзак, чтобы больше ходить."},
        {"speaker": "Leo", "text": "Good idea. I'll download the offline map.", "ru": "Хорошая мысль. Скачаю офлайн-карту."},
        {"speaker": "Mira", "text": "If the train is delayed, we'll message in the chat.", "ru": "Если поезд задержится — напишем в чат."},
        {"speaker": "Leo", "text": "Deal. This plan feels balanced.", "ru": "Договорились. План выглядит сбалансированным."},
    ],
    "dialogue-b2-salary-talk": [
        {
            "speaker": "Employee",
            "text": "I'd like to discuss adjusting my salary based on the new responsibilities.",
            "ru": "Хочу обсудить пересмотр зарплаты с учётом новых обязанностей.",
        },
        {"speaker": "Manager", "text": "I've noticed the extra load. What range are you aiming for?", "ru": "Вижу допнагрузку. На какой диапазон ориентируетесь?"},
        {
            "speaker": "Employee",
            "text": "Around eight percent, or a clear path to that within two quarters.",
            "ru": "Около восьми процентов или понятный путь к этому за два квартала.",
        },
        {
            "speaker": "Manager",
            "text": "Let me check the budget this week and book a follow-up on Friday.",
            "ru": "Проверю бюджет на этой неделе и назначу продолжение в пятницу.",
        },
        {"speaker": "Employee", "text": "Please include the review criteria in that note.", "ru": "Пожалуйста, укажите критерии пересмотра в заметке."},
        {"speaker": "Manager", "text": "I will. Bring examples of impact from both projects.", "ru": "Сделаю. Принесите примеры эффекта по обоим проектам."},
        {"speaker": "Employee", "text": "I already drafted a one-page summary.", "ru": "У меня уже есть одностраничное резюме."},
        {"speaker": "Manager", "text": "Perfect. Evidence makes the conversation fairer.", "ru": "Отлично. Факты делают разговор честнее."},
        {"speaker": "Employee", "text": "I want a decision that also fits the team budget.", "ru": "Хочу решение, которое вписывается и в бюджет команды."},
        {"speaker": "Manager", "text": "That attitude helps. See you Friday.", "ru": "Такой подход помогает. До пятницы."},
    ],
    "dialogue-b2-landlord-repair": [
        {"speaker": "Tenant", "text": "The kitchen tap has been dripping for three days.", "ru": "Кухонный кран капает уже три дня."},
        {"speaker": "Landlord", "text": "Have you tried tightening it? Sometimes that helps.", "ru": "Пробовали подтянуть? Иногда помогает."},
        {
            "speaker": "Tenant",
            "text": "I did. There's also a small puddle under the sink now.",
            "ru": "Пробовал. Под раковиной уже маленькая лужа.",
        },
        {
            "speaker": "Landlord",
            "text": "Understood. I'll send a plumber tomorrow morning between nine and eleven.",
            "ru": "Понял. Завтра утром пришлю сантехника с девяти до одиннадцати.",
        },
        {"speaker": "Tenant", "text": "Great. I'll be home then.", "ru": "Отлично. Я буду дома."},
        {"speaker": "Landlord", "text": "Please clear space under the sink before they arrive.", "ru": "Пожалуйста, освободите место под раковиной."},
        {"speaker": "Tenant", "text": "Will do. Should I turn off the water overnight?", "ru": "Сделаю. Перекрыть воду на ночь?"},
        {"speaker": "Landlord", "text": "Only if the puddle grows. Message me photos either way.", "ru": "Только если лужа растёт. В любом случае пришлите фото."},
        {"speaker": "Tenant", "text": "I'll send two photos now.", "ru": "Сейчас пришлю два фото."},
        {"speaker": "Landlord", "text": "Thanks. Sorry for the hassle — we'll sort it quickly.", "ru": "Спасибо. Извините за хлопоты — быстро разберёмся."},
    ],
    "dialogue-b2p-mentor-feedback": [
        {
            "speaker": "Mentee",
            "text": "Could you look at my draft slides before Thursday's pitch?",
            "ru": "Можете глянуть черновик слайдов до четвергового питча?",
        },
        {
            "speaker": "Mentor",
            "text": "Sure. The story is clear, but the third slide buries the key number.",
            "ru": "Конечно. История ясная, но на третьем слайде ключевая цифра теряется.",
        },
        {
            "speaker": "Mentee",
            "text": "Should I move it to the opening or add a callout box?",
            "ru": "Перенести в начало или добавить выноску?",
        },
        {
            "speaker": "Mentor",
            "text": "Open with it, then keep one simple chart. Cut two decorative animations.",
            "ru": "Начните с неё, оставьте один простой график. Уберите две декоративные анимации.",
        },
        {"speaker": "Mentee", "text": "Got it. I'll send a revised version tonight.", "ru": "Понял. Пришлю правку сегодня вечером."},
        {
            "speaker": "Mentor",
            "text": "Also shorten the closing ask to one sentence.",
            "ru": "И сократите финальную просьбу до одного предложения.",
        },
        {"speaker": "Mentee", "text": "Something like 'Approve the pilot by Friday'?", "ru": "Вроде «Одобрите пилот к пятнице»?"},
        {"speaker": "Mentor", "text": "Exactly. Specific beats poetic.", "ru": "Именно. Конкретика лучше поэзии."},
        {"speaker": "Mentee", "text": "Thanks — this saves me from overbuilding the deck.", "ru": "Спасибо — это спасает от перегруза колоды."},
        {
            "speaker": "Mentor",
            "text": "Glad to help. Ping me if the numbers still feel hidden.",
            "ru": "Рад помочь. Напиши, если цифры всё ещё прячутся.",
        },
    ],
}
