"""Seed decks: irregular verbs, idioms/proverbs, curated exceptions."""

STUDY_DECKS = [
    {
        "slug": "irregular-verbs-core",
        "title": "Неправильные глаголы",
        "description": "Частые V1 / V2 / V3 с переводом и коротким примером. Учите партиями, как словарь.",
        "kind": "verbs",
        "cards": [
            {"primary_text": "be", "secondary_text": "was/were", "tertiary_text": "been", "translation": "быть", "example": "She has been here.", "example_translation": "Она здесь была.", "category": "core"},
            {"primary_text": "have", "secondary_text": "had", "tertiary_text": "had", "translation": "иметь", "example": "We had lunch.", "example_translation": "Мы пообедали.", "category": "core"},
            {"primary_text": "do", "secondary_text": "did", "tertiary_text": "done", "translation": "делать", "example": "I did my homework.", "example_translation": "Я сделал домашку.", "category": "core"},
            {"primary_text": "go", "secondary_text": "went", "tertiary_text": "gone", "translation": "идти, ехать", "example": "They went home.", "example_translation": "Они поехали домой.", "category": "motion"},
            {"primary_text": "come", "secondary_text": "came", "tertiary_text": "come", "translation": "приходить", "example": "He came late.", "example_translation": "Он пришёл поздно.", "category": "motion"},
            {"primary_text": "see", "secondary_text": "saw", "tertiary_text": "seen", "translation": "видеть", "example": "I saw a fox.", "example_translation": "Я видел лису.", "category": "senses"},
            {"primary_text": "take", "secondary_text": "took", "tertiary_text": "taken", "translation": "брать", "example": "She took the key.", "example_translation": "Она взяла ключ.", "category": "core"},
            {"primary_text": "get", "secondary_text": "got", "tertiary_text": "got/gotten", "translation": "получать, добираться", "example": "I got your message.", "example_translation": "Я получил сообщение.", "category": "core"},
            {"primary_text": "make", "secondary_text": "made", "tertiary_text": "made", "translation": "делать, создавать", "example": "He made tea.", "example_translation": "Он заварил чай.", "category": "core"},
            {"primary_text": "know", "secondary_text": "knew", "tertiary_text": "known", "translation": "знать", "example": "I knew the answer.", "example_translation": "Я знал ответ.", "category": "mind"},
            {"primary_text": "think", "secondary_text": "thought", "tertiary_text": "thought", "translation": "думать", "example": "She thought hard.", "example_translation": "Она напряжённо думала.", "category": "mind"},
            {"primary_text": "give", "secondary_text": "gave", "tertiary_text": "given", "translation": "давать", "example": "Give me a minute.", "example_translation": "Дай мне минуту.", "category": "core"},
            {"primary_text": "find", "secondary_text": "found", "tertiary_text": "found", "translation": "находить", "example": "I found my pass.", "example_translation": "Я нашёл пропуск.", "category": "core"},
            {"primary_text": "tell", "secondary_text": "told", "tertiary_text": "told", "translation": "говорить (кому-то)", "example": "He told us the plan.", "example_translation": "Он рассказал нам план.", "category": "speech"},
            {"primary_text": "say", "secondary_text": "said", "tertiary_text": "said", "translation": "сказать", "example": "She said hello.", "example_translation": "Она сказала «привет».", "category": "speech"},
            {"primary_text": "become", "secondary_text": "became", "tertiary_text": "become", "translation": "становиться", "example": "It became cold.", "example_translation": "Стало холодно.", "category": "change"},
            {"primary_text": "leave", "secondary_text": "left", "tertiary_text": "left", "translation": "уходить, оставлять", "example": "We left at six.", "example_translation": "Мы ушли в шесть.", "category": "motion"},
            {"primary_text": "feel", "secondary_text": "felt", "tertiary_text": "felt", "translation": "чувствовать", "example": "I felt tired.", "example_translation": "Я чувствовал усталость.", "category": "senses"},
            {"primary_text": "bring", "secondary_text": "brought", "tertiary_text": "brought", "translation": "приносить", "example": "Bring a jacket.", "example_translation": "Принеси куртку.", "category": "core"},
            {"primary_text": "begin", "secondary_text": "began", "tertiary_text": "begun", "translation": "начинать", "example": "The film began.", "example_translation": "Фильм начался.", "category": "change"},
            {"primary_text": "keep", "secondary_text": "kept", "tertiary_text": "kept", "translation": "хранить, продолжать", "example": "Keep the receipt.", "example_translation": "Сохрани чек.", "category": "core"},
            {"primary_text": "hold", "secondary_text": "held", "tertiary_text": "held", "translation": "держать", "example": "Hold the rope.", "example_translation": "Держи верёвку.", "category": "core"},
            {"primary_text": "write", "secondary_text": "wrote", "tertiary_text": "written", "translation": "писать", "example": "She wrote a note.", "example_translation": "Она написала записку.", "category": "speech"},
            {"primary_text": "stand", "secondary_text": "stood", "tertiary_text": "stood", "translation": "стоять", "example": "He stood still.", "example_translation": "Он стоял неподвижно.", "category": "motion"},
            {"primary_text": "hear", "secondary_text": "heard", "tertiary_text": "heard", "translation": "слышать", "example": "I heard a noise.", "example_translation": "Я услышал шум.", "category": "senses"},
            {"primary_text": "let", "secondary_text": "let", "tertiary_text": "let", "translation": "позволять", "example": "Let me help.", "example_translation": "Позволь мне помочь.", "category": "core"},
            {"primary_text": "mean", "secondary_text": "meant", "tertiary_text": "meant", "translation": "значить, иметь в виду", "example": "What did you mean?", "example_translation": "Что ты имел в виду?", "category": "mind"},
            {"primary_text": "set", "secondary_text": "set", "tertiary_text": "set", "translation": "ставить, устанавливать", "example": "Set the timer.", "example_translation": "Поставь таймер.", "category": "core"},
            {"primary_text": "meet", "secondary_text": "met", "tertiary_text": "met", "translation": "встречать", "example": "We met at noon.", "example_translation": "Мы встретились в полдень.", "category": "social"},
            {"primary_text": "run", "secondary_text": "ran", "tertiary_text": "run", "translation": "бежать", "example": "She ran fast.", "example_translation": "Она бежала быстро.", "category": "motion"},
            {"primary_text": "pay", "secondary_text": "paid", "tertiary_text": "paid", "translation": "платить", "example": "I paid the bill.", "example_translation": "Я оплатил счёт.", "category": "core"},
            {"primary_text": "sit", "secondary_text": "sat", "tertiary_text": "sat", "translation": "сидеть", "example": "Sit here, please.", "example_translation": "Сядьте здесь, пожалуйста.", "category": "motion"},
            {"primary_text": "speak", "secondary_text": "spoke", "tertiary_text": "spoken", "translation": "говорить (на языке)", "example": "He spoke clearly.", "example_translation": "Он говорил ясно.", "category": "speech"},
            {"primary_text": "lie", "secondary_text": "lay", "tertiary_text": "lain", "translation": "лежать", "example": "The cat lay on the mat.", "example_translation": "Кот лежал на коврике.", "category": "motion"},
            {"primary_text": "lead", "secondary_text": "led", "tertiary_text": "led", "translation": "вести", "example": "She led the team.", "example_translation": "Она вела команду.", "category": "social"},
            {"primary_text": "read", "secondary_text": "read", "tertiary_text": "read", "translation": "читать", "example": "I read the note.", "example_translation": "Я прочитал записку.", "category": "speech"},
            {"primary_text": "grow", "secondary_text": "grew", "tertiary_text": "grown", "translation": "расти", "example": "Plants grow fast.", "example_translation": "Растения быстро растут.", "category": "change"},
            {"primary_text": "lose", "secondary_text": "lost", "tertiary_text": "lost", "translation": "терять", "example": "Don't lose the key.", "example_translation": "Не потеряй ключ.", "category": "core"},
            {"primary_text": "fall", "secondary_text": "fell", "tertiary_text": "fallen", "translation": "падать", "example": "The cup fell.", "example_translation": "Чашка упала.", "category": "motion"},
            {"primary_text": "send", "secondary_text": "sent", "tertiary_text": "sent", "translation": "отправлять", "example": "Send the file.", "example_translation": "Отправь файл.", "category": "speech"},
            {"primary_text": "build", "secondary_text": "built", "tertiary_text": "built", "translation": "строить", "example": "They built a shed.", "example_translation": "Они построили сарай.", "category": "core"},
            {"primary_text": "understand", "secondary_text": "understood", "tertiary_text": "understood", "translation": "понимать", "example": "I understood you.", "example_translation": "Я вас понял.", "category": "mind"},
            {"primary_text": "draw", "secondary_text": "drew", "tertiary_text": "drawn", "translation": "рисовать, тянуть", "example": "She drew a map.", "example_translation": "Она нарисовала карту.", "category": "core"},
            {"primary_text": "break", "secondary_text": "broke", "tertiary_text": "broken", "translation": "ломать", "example": "He broke the seal.", "example_translation": "Он сорвал пломбу.", "category": "core"},
            {"primary_text": "spend", "secondary_text": "spent", "tertiary_text": "spent", "translation": "тратить", "example": "We spent an hour.", "example_translation": "Мы потратили час.", "category": "core"},
            {"primary_text": "cut", "secondary_text": "cut", "tertiary_text": "cut", "translation": "резать", "example": "Cut the rope.", "example_translation": "Перережь верёвку.", "category": "core"},
            {"primary_text": "choose", "secondary_text": "chose", "tertiary_text": "chosen", "translation": "выбирать", "example": "Choose a seat.", "example_translation": "Выбери место.", "category": "mind"},
            {"primary_text": "drive", "secondary_text": "drove", "tertiary_text": "driven", "translation": "водить", "example": "She drove carefully.", "example_translation": "Она вела осторожно.", "category": "motion"},
            {"primary_text": "buy", "secondary_text": "bought", "tertiary_text": "bought", "translation": "покупать", "example": "I bought bread.", "example_translation": "Я купил хлеб.", "category": "core"},
            {"primary_text": "wear", "secondary_text": "wore", "tertiary_text": "worn", "translation": "носить (одежду)", "example": "He wore a coat.", "example_translation": "Он был в пальто.", "category": "core"},
            {"primary_text": "catch", "secondary_text": "caught", "tertiary_text": "caught", "translation": "ловить", "example": "Catch the ball.", "example_translation": "Поймай мяч.", "category": "motion"},
            {"primary_text": "fight", "secondary_text": "fought", "tertiary_text": "fought", "translation": "драться, бороться", "example": "They fought hard.", "example_translation": "Они боролись упорно.", "category": "social"},
            {"primary_text": "throw", "secondary_text": "threw", "tertiary_text": "thrown", "translation": "бросать", "example": "Throw it here.", "example_translation": "Брось сюда.", "category": "motion"},
            {"primary_text": "forget", "secondary_text": "forgot", "tertiary_text": "forgotten", "translation": "забывать", "example": "Don't forget the code.", "example_translation": "Не забудь код.", "category": "mind"},
            {"primary_text": "win", "secondary_text": "won", "tertiary_text": "won", "translation": "побеждать", "example": "Our team won.", "example_translation": "Наша команда победила.", "category": "social"},
            {"primary_text": "teach", "secondary_text": "taught", "tertiary_text": "taught", "translation": "учить (кого-то)", "example": "She taught maths.", "example_translation": "Она преподавала математику.", "category": "speech"},
            {"primary_text": "sleep", "secondary_text": "slept", "tertiary_text": "slept", "translation": "спать", "example": "I slept well.", "example_translation": "Я хорошо спал.", "category": "core"},
            {"primary_text": "eat", "secondary_text": "ate", "tertiary_text": "eaten", "translation": "есть", "example": "We ate early.", "example_translation": "Мы поели рано.", "category": "core"},
            {"primary_text": "drink", "secondary_text": "drank", "tertiary_text": "drunk", "translation": "пить", "example": "He drank water.", "example_translation": "Он выпил воды.", "category": "core"},
            {"primary_text": "swim", "secondary_text": "swam", "tertiary_text": "swum", "translation": "плавать", "example": "They swam across.", "example_translation": "Они переплыли.", "category": "motion"},
        ],
    },
    {
        "slug": "idioms-everyday",
        "title": "Идиомы и устойчивые выражения",
        "description": "Короткие бытовые идиомы и пословицы с русским смыслом и своим примером.",
        "kind": "idioms",
        "cards": [
            {"primary_text": "break the ice", "translation": "разрядить обстановку", "example": "A joke helped break the ice.", "example_translation": "Шутка помогла разрядить обстановку.", "category": "social"},
            {"primary_text": "piece of cake", "translation": "очень легко", "example": "The quiz was a piece of cake.", "example_translation": "Тест был лёгким.", "category": "everyday"},
            {"primary_text": "under the weather", "translation": "нездоровится", "example": "I'm a bit under the weather today.", "example_translation": "Мне сегодня немного нездоровится.", "category": "health"},
            {"primary_text": "hit the books", "translation": "сесть за учёбу", "example": "Exams are near — time to hit the books.", "example_translation": "Скоро экзамены — пора за учебники.", "category": "study"},
            {"primary_text": "call it a day", "translation": "закончить работу на сегодня", "example": "It's late; let's call it a day.", "example_translation": "Уже поздно — давайте на сегодня всё.", "category": "work"},
            {"primary_text": "on the same page", "translation": "понимать друг друга одинаково", "example": "Before we start, are we on the same page?", "example_translation": "Перед стартом — мы всё одинаково понимаем?", "category": "work"},
            {"primary_text": "better late than never", "translation": "лучше поздно, чем никогда", "example": "You finally sent the report — better late than never.", "example_translation": "Ты всё-таки прислал отчёт — лучше поздно, чем никогда.", "category": "proverb"},
            {"primary_text": "actions speak louder than words", "translation": "дела важнее слов", "example": "Fix the bug; actions speak louder than words.", "example_translation": "Исправь баг — дела важнее слов.", "category": "proverb"},
            {"primary_text": "keep an eye on", "translation": "присматривать", "example": "Keep an eye on the gate.", "example_translation": "Присматривай за калиткой.", "category": "everyday"},
            {"primary_text": "once in a blue moon", "translation": "очень редко", "example": "We meet once in a blue moon.", "example_translation": "Мы видимся крайне редко.", "category": "time"},
            {"primary_text": "cost an arm and a leg", "translation": "очень дорого", "example": "That ticket costs an arm and a leg.", "example_translation": "Тот билет стоит бешеных денег.", "category": "money"},
            {"primary_text": "hit the nail on the head", "translation": "попасть в точку", "example": "Your note hit the nail on the head.", "example_translation": "Твоя ремарка попала в точку.", "category": "speech"},
            {"primary_text": "spill the beans", "translation": "выдать секрет", "example": "Don't spill the beans yet.", "example_translation": "Пока не выдавай секрет.", "category": "speech"},
            {"primary_text": "the ball is in your court", "translation": "очередь за тобой решать", "example": "I sent the draft — the ball is in your court.", "example_translation": "Черновик отправил — теперь ход за тобой.", "category": "work"},
            {"primary_text": "burn the midnight oil", "translation": "сидеть допоздна за работой", "example": "She burned the midnight oil before the launch.", "example_translation": "Перед запуском она сидела допоздна.", "category": "work"},
            {"primary_text": "a blessing in disguise", "translation": "скрытое благо", "example": "Missing the train was a blessing in disguise.", "example_translation": "Опоздание на поезд оказалось к лучшему.", "category": "proverb"},
            {"primary_text": "get cold feet", "translation": "струсить перед важным шагом", "example": "He got cold feet before the talk.", "example_translation": "Перед выступлением он струсил.", "category": "feelings"},
            {"primary_text": "let the cat out of the bag", "translation": "случайно выдать тайну", "example": "The photo let the cat out of the bag.", "example_translation": "Фото случайно выдало тайну.", "category": "speech"},
            {"primary_text": "practice makes perfect", "translation": "повторение — мать учения", "example": "Keep drilling — practice makes perfect.", "example_translation": "Продолжай тренировать — практика делает мастером.", "category": "proverb"},
            {"primary_text": "when in Rome", "translation": "в чужой монастырь со своим уставом не ходят", "example": "They dine late here — when in Rome, do as the Romans do.", "example_translation": "Здесь ужинают поздно — в чужой монастырь со своим уставом не ходят.", "category": "proverb"},
            {"primary_text": "bite the bullet", "translation": "стиснуть зубы и сделать", "example": "Just bite the bullet and call.", "example_translation": "Стисни зубы и позвони.", "category": "courage"},
            {"primary_text": "cut corners", "translation": "срезать путь / экономить в ущерб качеству", "example": "Don't cut corners on safety.", "example_translation": "Не экономь на безопасности.", "category": "work"},
            {"primary_text": "in hot water", "translation": "в беде / под огнём критики", "example": "He is in hot water with the boss after the missed deadline.", "example_translation": "После сорванного срока у него крупные неприятности с боссом.", "category": "trouble"},
            {"primary_text": "learn the ropes", "translation": "освоить азы", "example": "It takes a week to learn the ropes.", "example_translation": "Неделя нужна, чтобы освоить азы.", "category": "work"},
            {"primary_text": "on thin ice", "translation": "на тонком льду", "example": "You're on thin ice with that tone.", "example_translation": "С таким тоном ты на тонком льду.", "category": "trouble"},
            {"primary_text": "see eye to eye", "translation": "сходиться во мнениях", "example": "We don't see eye to eye on this.", "example_translation": "Мы тут не сходимся.", "category": "social"},
            {"primary_text": "take it with a grain of salt", "translation": "относиться скептически", "example": "Take that rumour with a grain of salt.", "example_translation": "Относись к слуху скептически.", "category": "mind"},
            {"primary_text": "the early bird", "translation": "кто рано встаёт, тому Бог подаёт", "example": "The early bird gets the quiet desk — arrive before nine.", "example_translation": "Кто раньше — тому тихий стол: приходи до девяти.", "category": "proverb"},
            {"primary_text": "go the extra mile", "translation": "сделать больше обычного", "example": "She went the extra mile for the guest.", "example_translation": "Она сделала для гостя больше обычного.", "category": "work"},
            {"primary_text": "keep your chin up", "translation": "не вешать нос", "example": "Keep your chin up — results will come.", "example_translation": "Не вешай нос — результат придёт.", "category": "feelings"},
            {"primary_text": "Mickey Mouse company", "translation": "несерьёзная контора; «шарашкина контора»", "example": "Don't join that Mickey Mouse company — payroll is always late.", "example_translation": "Не устраивайся в эту шарашкину контору — зарплату вечно задерживают.", "category": "work"},
            {"primary_text": "a Mickey Mouse job", "translation": "халтура; работа спустя рукава", "example": "Fixing the leak with tape was a Mickey Mouse job.", "example_translation": "Заткнуть течь скотчем — чистая халтура.", "category": "work"},
            {"primary_text": "Mickey Mouse degree", "translation": "пустой диплом / «корочки ни о чём»", "example": "HR ignored his Mickey Mouse degree and asked for real projects.", "example_translation": "HR проигнорировал его «корочки ни о чём» и попросил реальные проекты.", "category": "study"},
            {"primary_text": "hit the sack", "translation": "ложиться спать", "example": "I'm exhausted — time to hit the sack.", "example_translation": "Я вымотан — пора ложиться.", "category": "everyday"},
            {"primary_text": "pull someone's leg", "translation": "разыгрывать кого-то", "example": "Relax — I was only pulling your leg.", "example_translation": "Расслабься — я просто разыгрывал тебя.", "category": "social"},
            {"primary_text": "rain cats and dogs", "translation": "лить как из ведра", "example": "It was raining cats and dogs, so we stayed in.", "example_translation": "Лило как из ведра, поэтому мы остались дома.", "category": "everyday"},
            {"primary_text": "a dime a dozen", "translation": "хоть пруд пруди; на каждом шагу", "example": "Cheap gadgets like that are a dime a dozen.", "example_translation": "Таких дешёвых гаджетов — хоть пруд пруди.", "category": "everyday"},
            {"primary_text": "bark up the wrong tree", "translation": "ошибиться адресом; винить не того", "example": "If you blame me for the bug, you're barking up the wrong tree.", "example_translation": "Если винишь меня за баг — ты ошибся адресом.", "category": "speech"},
            {"primary_text": "beat around the bush", "translation": "ходить вокруг да около", "example": "Stop beating around the bush and say what you want.", "example_translation": "Хватит ходить вокруг да около — скажи, чего хочешь.", "category": "speech"},
            {"primary_text": "burn bridges", "translation": "сжигать мосты", "example": "Leave politely — don't burn bridges with that team.", "example_translation": "Уходи вежливо — не сжигай мосты с этой командой.", "category": "work"},
            {"primary_text": "catch someone red-handed", "translation": "поймать с поличным", "example": "Security caught him red-handed copying files.", "example_translation": "Охрана поймала его с поличным при копировании файлов.", "category": "trouble"},
            {"primary_text": "cross that bridge when you come to it", "translation": "решать проблемы по мере поступления", "example": "We'll worry about visas later — cross that bridge when you come to it.", "example_translation": "О визах подумаем потом — решать проблемы по мере поступления.", "category": "mind"},
            {"primary_text": "don't cry over spilled milk", "translation": "о сделанном не жалеют", "example": "The deal fell through — don't cry over spilled milk.", "example_translation": "Сделка сорвалась — о сделанном не жалеют.", "category": "feelings"},
            {"primary_text": "every cloud has a silver lining", "translation": "нет худа без добра", "example": "Lost the job, found a better one — every cloud has a silver lining.", "example_translation": "Потерял работу, нашёл лучше — нет худа без добра.", "category": "proverb"},
            {"primary_text": "get the hang of", "translation": "набить руку; втянуться", "example": "After a week you'll get the hang of the shortcuts.", "example_translation": "Через неделю набьёшь руку на горячих клавишах.", "category": "study"},
            {"primary_text": "give someone the benefit of the doubt", "translation": "давать аванс доверия", "example": "She was late once — give her the benefit of the doubt.", "example_translation": "Она опоздала один раз — дай ей аванс доверия.", "category": "social"},
            {"primary_text": "jump on the bandwagon", "translation": "примкнуть к модному тренду", "example": "Every brand jumped on the bandwagon after the viral clip.", "example_translation": "После вирусного ролика все бренды примкнули к тренду.", "category": "social"},
            {"primary_text": "kill two birds with one stone", "translation": "убить двух зайцев", "example": "Walking to work kills two birds with one stone: exercise and commute.", "example_translation": "Пешком на работу — убить двух зайцев: спорт и дорога.", "category": "everyday"},
            {"primary_text": "make ends meet", "translation": "сводить концы с концами", "example": "With rent this high, it's hard to make ends meet.", "example_translation": "При такой аренде трудно сводить концы с концами.", "category": "money"},
            {"primary_text": "miss the boat", "translation": "упустить шанс", "example": "Apply today or you'll miss the boat on early pricing.", "example_translation": "Подавай сегодня, иначе упустишь раннюю цену.", "category": "trouble"},
            {"primary_text": "out of the blue", "translation": "внезапно; как снег на голову", "example": "An old classmate called out of the blue.", "example_translation": "Одноклассник позвонил как снег на голову.", "category": "time"},
            {"primary_text": "play it by ear", "translation": "действовать по ситуации", "example": "No fixed agenda — we'll play it by ear.", "example_translation": "Жёсткого плана нет — будем действовать по ситуации.", "category": "work"},
            {"primary_text": "put all your eggs in one basket", "translation": "ставить всё на одну карту", "example": "Don't put all your eggs in one basket — diversify clients.", "example_translation": "Не ставь всё на одну карту — диверсифицируй клиентов.", "category": "money"},
            {"primary_text": "rub someone the wrong way", "translation": "раздражать кого-то", "example": "His jokes rub the new hire the wrong way.", "example_translation": "Его шутки раздражают нового сотрудника.", "category": "social"},
            {"primary_text": "speak of the devil", "translation": "лёгок на помине", "example": "Speak of the devil — here comes Alex now.", "example_translation": "Лёгок на помине — вот и Алекс идёт.", "category": "speech"},
            {"primary_text": "the last straw", "translation": "последняя капля", "example": "The third delay was the last straw, so she quit.", "example_translation": "Третья задержка стала последней каплей — она уволилась.", "category": "feelings"},
            {"primary_text": "throw in the towel", "translation": "сдаться; бросить полотенце", "example": "After five failed builds he almost threw in the towel.", "example_translation": "После пяти провальных сборок он едва не сдался.", "category": "courage"},
            {"primary_text": "up in the air", "translation": "в подвешенном состоянии", "example": "Travel plans are still up in the air.", "example_translation": "Планы на поездку всё ещё в воздухе.", "category": "time"},
            {"primary_text": "water under the bridge", "translation": "было и прошло", "example": "That argument is water under the bridge now.", "example_translation": "Тот спор — уже вода под мостом, было и прошло.", "category": "feelings"},
            {"primary_text": "wrap one's head around", "translation": "осознать; «въехать»", "example": "I still can't wrap my head around the new tax rules.", "example_translation": "Я всё ещё не могу въехать в новые налоговые правила.", "category": "mind"},
            {"primary_text": "by the book", "translation": "строго по правилам", "example": "Auditors expect everything done by the book.", "example_translation": "Аудиторы ждут, что всё сделано строго по правилам.", "category": "work"},
            {"primary_text": "cut to the chase", "translation": "переходить к делу", "example": "Cut to the chase — what's the deadline?", "example_translation": "Ближе к делу — какой дедлайн?", "category": "speech"},
            {"primary_text": "face the music", "translation": "отвечать за последствия", "example": "He skipped the review and had to face the music.", "example_translation": "Он пропустил ревью и пришлось отвечать за последствия.", "category": "courage"},
            {"primary_text": "hang in there", "translation": "держись; не сдавайся", "example": "Hang in there — the hardest week is almost over.", "example_translation": "Держись — самая тяжёлая неделя почти позади.", "category": "feelings"},
            {"primary_text": "leave no stone unturned", "translation": "перевернуть всё вверх дном в поисках", "example": "We'll leave no stone unturned until we find the leak.", "example_translation": "Перевернём всё вверх дном, пока не найдём утечку.", "category": "work"},
            {"primary_text": "on the fence", "translation": "не определиться; сидеть на двух стульях", "example": "I'm still on the fence about moving abroad.", "example_translation": "Я всё ещё не определился насчёт переезда.", "category": "mind"},
            {"primary_text": "rule of thumb", "translation": "примерное правило; эмпирическое правило", "example": "As a rule of thumb, reply within one day.", "example_translation": "Как правило на глаз — отвечай в течение дня.", "category": "work"},
            {"primary_text": "the tip of the iceberg", "translation": "верхушка айсберга", "example": "These bugs are just the tip of the iceberg.", "example_translation": "Эти баги — лишь верхушка айсберга.", "category": "trouble"},
            {"primary_text": "add fuel to the fire", "translation": "подливать масло в огонь", "example": "A sarcastic reply only added fuel to the fire.", "example_translation": "Саркастичный ответ только подлил масла в огонь.", "category": "trouble"},
            {"primary_text": "back to square one", "translation": "вернуться на исходную", "example": "The vendor backed out, so we're back to square one.", "example_translation": "Вендор отказался — мы снова на исходной.", "category": "work"},
            {"primary_text": "bite off more than you can chew", "translation": "взять на себя непосильное", "example": "Three side projects at once — you've bitten off more than you can chew.", "example_translation": "Три сайд-проекта сразу — ты взял на себя непосильное.", "category": "work"},
            {"primary_text": "break a leg", "translation": "ни пуха ни пера; удачи", "example": "Break a leg at the interview tomorrow!", "example_translation": "Ни пуха ни пера на завтрашнем собеседовании!", "category": "social"},
            {"primary_text": "get out of hand", "translation": "выйти из-под контроля", "example": "The group chat got out of hand after midnight.", "example_translation": "После полуночи чат вышел из-под контроля.", "category": "trouble"},
            {"primary_text": "keep something under wraps", "translation": "держать в секрете", "example": "Keep the launch date under wraps until Friday.", "example_translation": "Держи дату запуска в секрете до пятницы.", "category": "speech"},
            {"primary_text": "read between the lines", "translation": "читать между строк", "example": "Read between the lines — they're not hiring yet.", "example_translation": "Читай между строк — они пока не нанимают.", "category": "mind"},
            {"primary_text": "steal someone's thunder", "translation": "перехватить чужой успех / внимание", "example": "Don't steal her thunder — let her announce the win.", "example_translation": "Не перехватывай её момент — пусть сама объявит о победе.", "category": "social"},
        ],
    },
    {
        "slug": "exceptions-spelling-plurals",
        "title": "Исключения: написание и plural",
        "description": "Курируемый набор частых исключений: plural, орфография, артикли.",
        "kind": "exceptions",
        "cards": [
            {"primary_text": "child → children", "translation": "не childs", "example": "Three children waved.", "example_translation": "Трое детей помахали.", "category": "plural"},
            {"primary_text": "person → people", "translation": "не persons (в быту)", "example": "People are waiting.", "example_translation": "Люди ждут.", "category": "plural"},
            {"primary_text": "mouse → mice", "translation": "не mouses", "example": "Two mice ran out.", "example_translation": "Две мыши выбежали.", "category": "plural"},
            {"primary_text": "sheep → sheep", "translation": "форма не меняется", "example": "Five sheep grazed.", "example_translation": "Пять овец паслись.", "category": "plural"},
            {"primary_text": "fish → fish / fishes", "translation": "часто без -es; fishes — о видах", "example": "We caught three fish.", "example_translation": "Мы поймали трёх рыб.", "category": "plural"},
            {"primary_text": "news is", "translation": "news — ед.ч.", "example": "The news is good.", "example_translation": "Новости хорошие.", "category": "agreement"},
            {"primary_text": "a university", "translation": "звук /j/ — a, не an", "example": "She is a university student.", "example_translation": "Она студентка университета.", "category": "articles"},
            {"primary_text": "an hour", "translation": "немой h — an", "example": "Wait an hour.", "example_translation": "Подожди час.", "category": "articles"},
            {"primary_text": "the Hague", "translation": "город с the", "example": "They met in The Hague.", "example_translation": "Они встретились в Гааге.", "category": "articles"},
            {"primary_text": "i before e", "translation": "кроме after c: receive", "example": "I received the mail.", "example_translation": "Я получил письмо.", "category": "spelling"},
            {"primary_text": "occur → occurred", "translation": "удвоение r", "example": "It occurred to me.", "example_translation": "Мне пришло в голову.", "category": "spelling"},
            {"primary_text": "prefer → preferred", "translation": "удвоение r", "example": "She preferred tea.", "example_translation": "Она предпочла чай.", "category": "spelling"},
            {"primary_text": "travel → travelling (BrE)", "translation": "l удваивается в BrE", "example": "We are travelling light.", "example_translation": "Мы едем налегке.", "category": "spelling"},
            {"primary_text": "good → better → best", "translation": "не gooder", "example": "This is better.", "example_translation": "Это лучше.", "category": "comparison"},
            {"primary_text": "bad → worse → worst", "translation": "не badder", "example": "That was the worst day.", "example_translation": "Это был худший день.", "category": "comparison"},
            {"primary_text": "far → farther/further", "translation": "further также «далее по смыслу»", "example": "Further details follow.", "example_translation": "Дальнейшие детали ниже.", "category": "comparison"},
            {"primary_text": "advice (uncountable)", "translation": "не an advice → a piece of advice", "example": "A piece of advice helped.", "example_translation": "Один совет помог.", "category": "uncountable"},
            {"primary_text": "information", "translation": "без plural informations", "example": "Useful information is here.", "example_translation": "Полезная информация здесь.", "category": "uncountable"},
            {"primary_text": "furniture", "translation": "не furnitures", "example": "The furniture looks new.", "example_translation": "Мебель выглядит новой.", "category": "uncountable"},
            {"primary_text": "police are", "translation": "police — мн. согласование", "example": "The police are here.", "example_translation": "Полиция уже здесь.", "category": "agreement"},
            {"primary_text": "criteria / criterion", "translation": "criterion ед., criteria мн.", "example": "One criterion matters.", "example_translation": "Важен один критерий.", "category": "plural"},
            {"primary_text": "data", "translation": "часто мн. в формальном стиле", "example": "The data are incomplete.", "example_translation": "Данные неполные.", "category": "agreement"},
            {"primary_text": "lie / lay", "translation": "lie=лежать (lay/lain); lay=класть (laid)", "example": "Lay the map flat.", "example_translation": "Положи карту ровно.", "category": "verbs"},
            {"primary_text": "raise / rise", "translation": "raise + object; rise без объекта", "example": "Prices rose overnight.", "example_translation": "Цены выросли за ночь.", "category": "verbs"},
            {"primary_text": "affect / effect", "translation": "affect=влиять (V); effect=следствие (N)", "example": "The delay affected us.", "example_translation": "Задержка на нас повлияла.", "category": "usage"},
        ],
    },
]
