"""Seed decks: irregular verbs, idioms/proverbs, curated exceptions."""

STUDY_DECKS = [
    {
        "slug": "irregular-verbs-core",
        "title": "Неправильные глаголы",
        "description": "Частые V1 / V2 / V3 с переводом и коротким примером. Учите партиями, как словарь.",
        "kind": "verbs",
        "cards": [
            {"primary_text": "be", "secondary_text": "was/were", "tertiary_text": "been", "translation": "быть", "example": "She has been here.", "example_translation": "Она здесь была.", "category": "core"},
            {"primary_text": "have", "secondary_text": "had", "tertiary_text": "had", "translation": "иметь", "example": "We had lunch.", "example_translation": "Мы пообедали.", "category": "core"},
            {"primary_text": "do", "secondary_text": "did", "tertiary_text": "done", "translation": "делать", "example": "I did my homework.", "example_translation": "Я сделал домашку.", "category": "core"},
            {"primary_text": "go", "secondary_text": "went", "tertiary_text": "gone", "translation": "идти, ехать", "example": "They went home.", "example_translation": "Они поехали домой.", "category": "motion"},
            {"primary_text": "come", "secondary_text": "came", "tertiary_text": "come", "translation": "приходить", "example": "He came late.", "example_translation": "Он пришёл поздно.", "category": "motion"},
            {"primary_text": "see", "secondary_text": "saw", "tertiary_text": "seen", "translation": "видеть", "example": "I saw a fox.", "example_translation": "Я видел лису.", "category": "senses"},
            {"primary_text": "take", "secondary_text": "took", "tertiary_text": "taken", "translation": "брать", "example": "She took the key.", "example_translation": "Она взяла ключ.", "category": "core"},
            {"primary_text": "get", "secondary_text": "got", "tertiary_text": "got/gotten", "translation": "получать, добираться", "example": "I got your message.", "example_translation": "Я получил сообщение.", "category": "core"},
            {"primary_text": "make", "secondary_text": "made", "tertiary_text": "made", "translation": "делать, создавать", "example": "He made tea.", "example_translation": "Он заварил чай.", "category": "core"},
            {"primary_text": "know", "secondary_text": "knew", "tertiary_text": "known", "translation": "знать", "example": "I knew the answer.", "example_translation": "Я знал ответ.", "category": "mind"},
            {"primary_text": "think", "secondary_text": "thought", "tertiary_text": "thought", "translation": "думать", "example": "She thought hard.", "example_translation": "Она напряжённо думала.", "category": "mind"},
            {"primary_text": "give", "secondary_text": "gave", "tertiary_text": "given", "translation": "давать", "example": "Give me a minute.", "example_translation": "Дай мне минуту.", "category": "core"},
            {"primary_text": "find", "secondary_text": "found", "tertiary_text": "found", "translation": "находить", "example": "I found my pass.", "example_translation": "Я нашёл пропуск.", "category": "core"},
            {"primary_text": "tell", "secondary_text": "told", "tertiary_text": "told", "translation": "говорить (кому-то)", "example": "He told us the plan.", "example_translation": "Он рассказал нам план.", "category": "speech"},
            {"primary_text": "say", "secondary_text": "said", "tertiary_text": "said", "translation": "сказать", "example": "She said hello.", "example_translation": "Она сказала «привет».", "category": "speech"},
            {"primary_text": "become", "secondary_text": "became", "tertiary_text": "become", "translation": "становиться", "example": "It became cold.", "example_translation": "Стало холодно.", "category": "change"},
            {"primary_text": "leave", "secondary_text": "left", "tertiary_text": "left", "translation": "уходить, оставлять", "example": "We left at six.", "example_translation": "Мы ушли в шесть.", "category": "motion"},
            {"primary_text": "feel", "secondary_text": "felt", "tertiary_text": "felt", "translation": "чувствовать", "example": "I felt tired.", "example_translation": "Я чувствовал усталость.", "category": "senses"},
            {"primary_text": "bring", "secondary_text": "brought", "tertiary_text": "brought", "translation": "приносить", "example": "Bring a jacket.", "example_translation": "Принеси куртку.", "category": "core"},
            {"primary_text": "begin", "secondary_text": "began", "tertiary_text": "begun", "translation": "начинать", "example": "The film began.", "example_translation": "Фильм начался.", "category": "change"},
            {"primary_text": "keep", "secondary_text": "kept", "tertiary_text": "kept", "translation": "хранить, продолжать", "example": "Keep the receipt.", "example_translation": "Сохрани чек.", "category": "core"},
            {"primary_text": "hold", "secondary_text": "held", "tertiary_text": "held", "translation": "держать", "example": "Hold the rope.", "example_translation": "Держи верёвку.", "category": "core"},
            {"primary_text": "write", "secondary_text": "wrote", "tertiary_text": "written", "translation": "писать", "example": "She wrote a note.", "example_translation": "Она написала записку.", "category": "speech"},
            {"primary_text": "stand", "secondary_text": "stood", "tertiary_text": "stood", "translation": "стоять", "example": "He stood still.", "example_translation": "Он стоял неподвижно.", "category": "motion"},
            {"primary_text": "hear", "secondary_text": "heard", "tertiary_text": "heard", "translation": "слышать", "example": "I heard a noise.", "example_translation": "Я услышал шум.", "category": "senses"},
            {"primary_text": "let", "secondary_text": "let", "tertiary_text": "let", "translation": "позволять", "example": "Let me help.", "example_translation": "Позволь мне помочь.", "category": "core"},
            {"primary_text": "mean", "secondary_text": "meant", "tertiary_text": "meant", "translation": "значить, иметь в виду", "example": "What did you mean?", "example_translation": "Что ты имел в виду?", "category": "mind"},
            {"primary_text": "set", "secondary_text": "set", "tertiary_text": "set", "translation": "ставить, устанавливать", "example": "Set the timer.", "example_translation": "Поставь таймер.", "category": "core"},
            {"primary_text": "meet", "secondary_text": "met", "tertiary_text": "met", "translation": "встречать", "example": "We met at noon.", "example_translation": "Мы встретились в полдень.", "category": "social"},
            {"primary_text": "run", "secondary_text": "ran", "tertiary_text": "run", "translation": "бежать", "example": "She ran fast.", "example_translation": "Она бежала быстро.", "category": "motion"},
            {"primary_text": "pay", "secondary_text": "paid", "tertiary_text": "paid", "translation": "платить", "example": "I paid the bill.", "example_translation": "Я оплатил счёт.", "category": "core"},
            {"primary_text": "sit", "secondary_text": "sat", "tertiary_text": "sat", "translation": "сидеть", "example": "Sit here, please.", "example_translation": "Сядьте здесь, пожалуйста.", "category": "motion"},
            {"primary_text": "speak", "secondary_text": "spoke", "tertiary_text": "spoken", "translation": "говорить (на языке)", "example": "He spoke clearly.", "example_translation": "Он говорил ясно.", "category": "speech"},
            {"primary_text": "lie", "secondary_text": "lay", "tertiary_text": "lain", "translation": "лежать", "example": "The cat lay on the mat.", "example_translation": "Кот лежал на коврике.", "category": "motion"},
            {"primary_text": "lead", "secondary_text": "led", "tertiary_text": "led", "translation": "вести", "example": "She led the team.", "example_translation": "Она вела команду.", "category": "social"},
            {"primary_text": "read", "secondary_text": "read", "tertiary_text": "read", "translation": "читать", "example": "I read the note.", "example_translation": "Я прочитал записку.", "category": "speech"},
            {"primary_text": "grow", "secondary_text": "grew", "tertiary_text": "grown", "translation": "расти", "example": "Plants grow fast.", "example_translation": "Растения быстро растут.", "category": "change"},
            {"primary_text": "lose", "secondary_text": "lost", "tertiary_text": "lost", "translation": "терять", "example": "Don't lose the key.", "example_translation": "Не потеряй ключ.", "category": "core"},
            {"primary_text": "fall", "secondary_text": "fell", "tertiary_text": "fallen", "translation": "падать", "example": "The cup fell.", "example_translation": "Чашка упала.", "category": "motion"},
            {"primary_text": "send", "secondary_text": "sent", "tertiary_text": "sent", "translation": "отправлять", "example": "Send the file.", "example_translation": "Отправь файл.", "category": "speech"},
            {"primary_text": "build", "secondary_text": "built", "tertiary_text": "built", "translation": "строить", "example": "They built a shed.", "example_translation": "Они построили сарай.", "category": "core"},
            {"primary_text": "understand", "secondary_text": "understood", "tertiary_text": "understood", "translation": "понимать", "example": "I understood you.", "example_translation": "Я вас понял.", "category": "mind"},
            {"primary_text": "draw", "secondary_text": "drew", "tertiary_text": "drawn", "translation": "рисовать, тянуть", "example": "She drew a map.", "example_translation": "Она нарисовала карту.", "category": "core"},
            {"primary_text": "break", "secondary_text": "broke", "tertiary_text": "broken", "translation": "ломать", "example": "He broke the seal.", "example_translation": "Он сорвал пломбу.", "category": "core"},
            {"primary_text": "spend", "secondary_text": "spent", "tertiary_text": "spent", "translation": "тратить", "example": "We spent an hour.", "example_translation": "Мы потратили час.", "category": "core"},
            {"primary_text": "cut", "secondary_text": "cut", "tertiary_text": "cut", "translation": "резать", "example": "Cut the rope.", "example_translation": "Перережь верёвку.", "category": "core"},
            {"primary_text": "choose", "secondary_text": "chose", "tertiary_text": "chosen", "translation": "выбирать", "example": "Choose a seat.", "example_translation": "Выбери место.", "category": "mind"},
            {"primary_text": "drive", "secondary_text": "drove", "tertiary_text": "driven", "translation": "водить", "example": "She drove carefully.", "example_translation": "Она вела осторожно.", "category": "motion"},
            {"primary_text": "buy", "secondary_text": "bought", "tertiary_text": "bought", "translation": "покупать", "example": "I bought bread.", "example_translation": "Я купил хлеб.", "category": "core"},
            {"primary_text": "wear", "secondary_text": "wore", "tertiary_text": "worn", "translation": "носить (одежду)", "example": "He wore a coat.", "example_translation": "Он был в пальто.", "category": "core"},
            {"primary_text": "catch", "secondary_text": "caught", "tertiary_text": "caught", "translation": "ловить", "example": "Catch the ball.", "example_translation": "Поймай мяч.", "category": "motion"},
            {"primary_text": "fight", "secondary_text": "fought", "tertiary_text": "fought", "translation": "драться, бороться", "example": "They fought hard.", "example_translation": "Они боролись упорно.", "category": "social"},
            {"primary_text": "throw", "secondary_text": "threw", "tertiary_text": "thrown", "translation": "бросать", "example": "Throw it here.", "example_translation": "Брось сюда.", "category": "motion"},
            {"primary_text": "forget", "secondary_text": "forgot", "tertiary_text": "forgotten", "translation": "забывать", "example": "Don't forget the code.", "example_translation": "Не забудь код.", "category": "mind"},
            {"primary_text": "win", "secondary_text": "won", "tertiary_text": "won", "translation": "побеждать", "example": "Our team won.", "example_translation": "Наша команда победила.", "category": "social"},
            {"primary_text": "teach", "secondary_text": "taught", "tertiary_text": "taught", "translation": "учить (кого-то)", "example": "She taught maths.", "example_translation": "Она преподавала математику.", "category": "speech"},
            {"primary_text": "sleep", "secondary_text": "slept", "tertiary_text": "slept", "translation": "спать", "example": "I slept well.", "example_translation": "Я хорошо спал.", "category": "core"},
            {"primary_text": "eat", "secondary_text": "ate", "tertiary_text": "eaten", "translation": "есть", "example": "We ate early.", "example_translation": "Мы поели рано.", "category": "core"},
            {"primary_text": "drink", "secondary_text": "drank", "tertiary_text": "drunk", "translation": "пить", "example": "He drank water.", "example_translation": "Он выпил воды.", "category": "core"},
            {"primary_text": "swim", "secondary_text": "swam", "tertiary_text": "swum", "translation": "плавать", "example": "They swam across.", "example_translation": "Они переплыли.", "category": "motion"},
        ],
    },
    {
        "slug": "idioms-everyday",
        "title": "Идиомы и устойчивые выражения",
        "description": "Короткие бытовые идиомы и пословицы с русским смыслом и своим примером.",
        "kind": "idioms",
        "cards": [
            {"primary_text": "break the ice", "translation": "разрядить обстановку", "example": "A joke helped break the ice.", "example_translation": "Шутка помогла разрядить обстановку.", "category": "social"},
            {"primary_text": "piece of cake", "translation": "очень легко", "example": "The quiz was a piece of cake.", "example_translation": "Тест был лёгким.", "category": "everyday"},
            {"primary_text": "under the weather", "translation": "нездоровится", "example": "I'm a bit under the weather today.", "example_translation": "Мне сегодня немного нездоровится.", "category": "health"},
            {"primary_text": "hit the books", "translation": "сесть за учёбу", "example": "Exams are near — time to hit the books.", "example_translation": "Скоро экзамены — пора за учебники.", "category": "study"},
            {"primary_text": "call it a day", "translation": "закончить работу на сегодня", "example": "It's late; let's call it a day.", "example_translation": "Уже поздно — давайте на сегодня всё.", "category": "work"},
            {"primary_text": "on the same page", "translation": "понимать друг друга одинаково", "example": "Before we start, are we on the same page?", "example_translation": "Перед стартом — мы всё одинаково понимаем?", "category": "work"},
            {"primary_text": "better late than never", "translation": "лучше поздно, чем никогда", "example": "You came — better late than never.", "example_translation": "Ты пришёл — лучше поздно, чем никогда.", "category": "proverb"},
            {"primary_text": "actions speak louder than words", "translation": "дела важнее слов", "example": "Fix the bug; actions speak louder than words.", "example_translation": "Исправь баг — дела важнее слов.", "category": "proverb"},
            {"primary_text": "keep an eye on", "translation": "присматривать", "example": "Keep an eye on the gate.", "example_translation": "Присматривай за калиткой.", "category": "everyday"},
            {"primary_text": "once in a blue moon", "translation": "очень редко", "example": "We meet once in a blue moon.", "example_translation": "Мы видимся крайне редко.", "category": "time"},
            {"primary_text": "cost an arm and a leg", "translation": "очень дорого", "example": "That ticket costs an arm and a leg.", "example_translation": "Тот билет стоит бешеных денег.", "category": "money"},
            {"primary_text": "hit the nail on the head", "translation": "попасть в точку", "example": "Your note hit the nail on the head.", "example_translation": "Твоя ремарка попала в точку.", "category": "speech"},
            {"primary_text": "spill the beans", "translation": "выдать секрет", "example": "Don't spill the beans yet.", "example_translation": "Пока не выдавай секрет.", "category": "speech"},
            {"primary_text": "the ball is in your court", "translation": "очередь за тобой решать", "example": "I sent the draft — the ball is in your court.", "example_translation": "Черновик отправил — теперь ход за тобой.", "category": "work"},
            {"primary_text": "burn the midnight oil", "translation": "сидеть допоздна за работой", "example": "She burned the midnight oil before the launch.", "example_translation": "Перед запуском она сидела допоздна.", "category": "work"},
            {"primary_text": "a blessing in disguise", "translation": "скрытое благо", "example": "Missing the train was a blessing in disguise.", "example_translation": "Опоздание на поезд оказалось к лучшему.", "category": "proverb"},
            {"primary_text": "get cold feet", "translation": "струсить перед важным шагом", "example": "He got cold feet before the talk.", "example_translation": "Перед выступлением он струсил.", "category": "feelings"},
            {"primary_text": "let the cat out of the bag", "translation": "случайно выдать тайну", "example": "The photo let the cat out of the bag.", "example_translation": "Фото случайно выдало тайну.", "category": "speech"},
            {"primary_text": "practice makes perfect", "translation": "повторение — мать учения", "example": "Keep drilling — practice makes perfect.", "example_translation": "Продолжай тренировать — практика делает мастером.", "category": "proverb"},
            {"primary_text": "when in Rome", "translation": "в чужой монастырь… (подстраивайся)", "example": "Try local food — when in Rome.", "example_translation": "Попробуй местную еду — когда в Риме…", "category": "proverb"},
            {"primary_text": "bite the bullet", "translation": "стиснуть зубы и сделать", "example": "Just bite the bullet and call.", "example_translation": "Стисни зубы и позвони.", "category": "courage"},
            {"primary_text": "cut corners", "translation": "срезать путь / экономить в ущерб качеству", "example": "Don't cut corners on safety.", "example_translation": "Не экономь на безопасности.", "category": "work"},
            {"primary_text": "in hot water", "translation": "в беде / под огнём критики", "example": "He is in hot water with the boss.", "example_translation": "Он в беде у босса.", "category": "trouble"},
            {"primary_text": "learn the ropes", "translation": "освоить азы", "example": "It takes a week to learn the ropes.", "example_translation": "Неделя нужна, чтобы освоить азы.", "category": "work"},
            {"primary_text": "on thin ice", "translation": "на тонком льду", "example": "You're on thin ice with that tone.", "example_translation": "С таким тоном ты на тонком льду.", "category": "trouble"},
            {"primary_text": "see eye to eye", "translation": "сходиться во мнениях", "example": "We don't see eye to eye on this.", "example_translation": "Мы тут не сходимся.", "category": "social"},
            {"primary_text": "take it with a grain of salt", "translation": "относиться скептически", "example": "Take that rumour with a grain of salt.", "example_translation": "Относись к слуху скептически.", "category": "mind"},
            {"primary_text": "the early bird", "translation": "кто рано встаёт…", "example": "The early bird gets the quiet desk.", "example_translation": "Кто раньше — тому тихий стол.", "category": "proverb"},
            {"primary_text": "go the extra mile", "translation": "сделать больше обычного", "example": "She went the extra mile for the guest.", "example_translation": "Она сделала для гостя больше обычного.", "category": "work"},
            {"primary_text": "keep your chin up", "translation": "не вешать нос", "example": "Keep your chin up — results will come.", "example_translation": "Не вешай нос — результат придёт.", "category": "feelings"},
        ],
    },
    {
        "slug": "exceptions-spelling-plurals",
        "title": "Исключения: написание и plural",
        "description": "Курируемый набор частых исключений: plural, орфография, артикли.",
        "kind": "exceptions",
        "cards": [
            {"primary_text": "child → children", "translation": "не childs", "example": "Three children waved.", "example_translation": "Трое детей помахали.", "category": "plural"},
            {"primary_text": "person → people", "translation": "не persons (в быту)", "example": "People are waiting.", "example_translation": "Люди ждут.", "category": "plural"},
            {"primary_text": "mouse → mice", "translation": "не mouses", "example": "Two mice ran out.", "example_translation": "Две мыши выбежали.", "category": "plural"},
            {"primary_text": "sheep → sheep", "translation": "форма не меняется", "example": "Five sheep grazed.", "example_translation": "Пять овец паслись.", "category": "plural"},
            {"primary_text": "fish → fish / fishes", "translation": "часто без -es; fishes — о видах", "example": "We caught three fish.", "example_translation": "Мы поймали трёх рыб.", "category": "plural"},
            {"primary_text": "news is", "translation": "news — ед.ч.", "example": "The news is good.", "example_translation": "Новости хорошие.", "category": "agreement"},
            {"primary_text": "a university", "translation": "звук /j/ — a, не an", "example": "She is a university student.", "example_translation": "Она студентка университета.", "category": "articles"},
            {"primary_text": "an hour", "translation": "немой h — an", "example": "Wait an hour.", "example_translation": "Подожди час.", "category": "articles"},
            {"primary_text": "the Hague", "translation": "город с the", "example": "They met in The Hague.", "example_translation": "Они встретились в Гааге.", "category": "articles"},
            {"primary_text": "i before e", "translation": "кроме after c: receive", "example": "I received the mail.", "example_translation": "Я получил письмо.", "category": "spelling"},
            {"primary_text": "occur → occurred", "translation": "удвоение r", "example": "It occurred to me.", "example_translation": "Мне пришло в голову.", "category": "spelling"},
            {"primary_text": "prefer → preferred", "translation": "удвоение r", "example": "She preferred tea.", "example_translation": "Она предпочла чай.", "category": "spelling"},
            {"primary_text": "travel → travelling (BrE)", "translation": "l удваивается в BrE", "example": "We are travelling light.", "example_translation": "Мы едем налегке.", "category": "spelling"},
            {"primary_text": "good → better → best", "translation": "не gooder", "example": "This is better.", "example_translation": "Это лучше.", "category": "comparison"},
            {"primary_text": "bad → worse → worst", "translation": "не badder", "example": "That was the worst day.", "example_translation": "Это был худший день.", "category": "comparison"},
            {"primary_text": "far → farther/further", "translation": "further также «далее по смыслу»", "example": "Further details follow.", "example_translation": "Дальнейшие детали ниже.", "category": "comparison"},
            {"primary_text": "advice (uncountable)", "translation": "не an advice → a piece of advice", "example": "A piece of advice helped.", "example_translation": "Один совет помог.", "category": "uncountable"},
            {"primary_text": "information", "translation": "без plural informations", "example": "Useful information is here.", "example_translation": "Полезная информация здесь.", "category": "uncountable"},
            {"primary_text": "furniture", "translation": "не furnitures", "example": "The furniture looks new.", "example_translation": "Мебель выглядит новой.", "category": "uncountable"},
            {"primary_text": "police are", "translation": "police — мн. согласование", "example": "The police are here.", "example_translation": "Полиция уже здесь.", "category": "agreement"},
            {"primary_text": "criteria / criterion", "translation": "criterion ед., criteria мн.", "example": "One criterion matters.", "example_translation": "Важен один критерий.", "category": "plural"},
            {"primary_text": "data", "translation": "часто мн. в формальном стиле", "example": "The data are incomplete.", "example_translation": "Данные неполные.", "category": "agreement"},
            {"primary_text": "lie / lay", "translation": "lie=лежать (lay/lain); lay=класть (laid)", "example": "Lay the map flat.", "example_translation": "Положи карту ровно.", "category": "verbs"},
            {"primary_text": "raise / rise", "translation": "raise + object; rise без объекта", "example": "Prices rose overnight.", "example_translation": "Цены выросли за ночь.", "category": "verbs"},
            {"primary_text": "affect / effect", "translation": "affect=влиять (V); effect=следствие (N)", "example": "The delay affected us.", "example_translation": "Задержка на нас повлияла.", "category": "usage"},
        ],
    },
]
