"""B1–C2 on-topic practice/test pads keyed by module slug."""

from app.seed.helpers import err, fill, match, mc, order, xf

TOPIC_PRACTICE_ADV: dict[str, list] = {
    # --- B1 ---
    "present-perfect-vs-past-simple": [
        fill("I ___ her yesterday. (see)", "saw", "Конкретное прошлое — Past Simple."),
        mc("She ___ in London since 2019.", ["lived", "has lived", "lives"], "has lived", "since → Perfect."),
        err("I have seen him yesterday.", "I saw him yesterday.", "yesterday → Past Simple."),
        xf("Вставьте Present Perfect (только что закончили): I ___ the report. (finish)", "have finished", "just/already → Perfect."),
        fill("They ___ to Paris last summer. (go)", "went", "last summer → Past."),
        match("Соедините маркер и время", ["yesterday", "since 2020", "already"], "yesterday=Past; since 2020=Perfect; already=Perfect", "Маркеры."),
        mc("___ you ever try sushi?", ["Did", "Have", "Has"], "Have", "ever → Perfect."),
        fill("He ___ his keys — he can't find them. (lose)", "has lost", "Результат сейчас — Perfect."),
        order("Соберите: ago / two / days / arrived / she", "She arrived two days ago.", "ago → Past."),
        err("I lived here since May.", "I have lived here since May.", "since → Perfect."),
    ],
    "present-perfect-continuous": [
        order("Соберите: been / have / waiting / I / for hours", "I have been waiting for hours.", "Perfect Continuous."),
        fill("She ___ been working all day.", "has", "has been + V-ing."),
        err("I have waiting for you.", "I have been waiting for you.", "have been + V-ing."),
        xf("Вопрос: They have been studying.", "Have they been studying?", "Have + S + been + V-ing."),
        fill("We have ___ practising since noon.", "been", "been + V-ing."),
        match("PPC", ["have", "been", "running"], "have=aux; been=perfect; running=V-ing", "have been + V-ing."),
        mc("It ___ been raining all morning.", ["have", "has", "is"], "has", "It + has."),
        fill("How long ___ you been learning English?", "have", "How long + have been."),
        order("Слова: been / she / has / cooking", "She has been cooking.", "has been + V-ing."),
        err("They has been travelling.", "They have been travelling.", "They + have."),
    ],
    "past-perfect": [
        fill("By 2019 they ___ left. (have)", "had", "Past Perfect."),
        mc("She ___ already eaten when we arrived.", ["has", "had", "have"], "had", "had + V3."),
        err("After he has left, I called.", "After he had left, I called.", "Раньше прошлого — had."),
        xf("Вставьте Past Perfect (к моему приходу уже): When I arrived, the train ___ . (leave)", "had left", "had + V3."),
        fill("They had never ___ sushi before that day. (try)", "tried", "Past Perfect: had + never + V3."),
        match("Past Perfect", ["had", "finished", "before"], "had=aux; finished=V3; before=маркер", "had + V3."),
        mc("I realised I ___ my wallet.", ["forgot", "had forgotten", "have forgotten"], "had forgotten", "Раньше момента в прошлом."),
        fill("By the time we got there, the film ___ started.", "had", "had + V3."),
        order("Соберите: had / she / left / already", "She had already left.", "had + already + V3."),
        err("He had went home.", "He had gone home.", "go — gone."),
    ],
    "future-continuous": [
        fill("This time tomorrow I ___ flying to Rome. (be)", "will be", "will be + V-ing."),
        mc("At 8 she ___ still ___.", ["will / work", "will be / working", "is / working"], "will be / working", "will be + V-ing."),
        err("I will working at noon.", "I will be working at noon.", "will be + V-ing."),
        xf("Вопрос: They will be waiting.", "Will they be waiting?", "Will + S + be + V-ing."),
        fill("Don't call at 6 — we ___ be having dinner.", "will", "will be + V-ing."),
        match("Future Continuous", ["will", "be", "sleeping"], "will=aux; be=continuous; sleeping=V-ing", "will be + V-ing."),
        mc("___ you be using the car tonight?", ["Do", "Will", "Are"], "Will", "Will + S + be."),
        fill("He won't ___ attending the meeting.", "be", "won't be + V-ing."),
        order("Соберите: be / will / raining / it", "It will be raining.", "will be + V-ing."),
        err("She will be cook.", "She will be cooking.", "V-ing."),
    ],
    "second-conditional": [
        mc("If I ___ rich, I would travel.", ["am", "was", "were"], "were", "2nd conditional."),
        fill("If she studied more, she ___ pass. (would)", "would", "would + V1."),
        err("If I would have time, I would help.", "If I had time, I would help.", "If + Past, would."),
        xf("Second Conditional: вставьте would: If we lived nearer → we ___ meet more often.", "would", "would + V."),
        fill("If I ___ you, I'd apologise. (be)", "were", "were после if.", ["was"]),
        match("Second", ["If", "Past", "would + V"], "If=рамка; Past=условие; would=результат", "Нереальное настоящее."),
        mc("What ___ you do if you won?", ["will", "would", "do"], "would", "would + V."),
        fill("If it ___ warmer, we'd go out. (be)", "were", "were.", ["was"]),
        order("Соберите: would / buy / I / a car / if / I / had / money", "I would buy a car if I had money.", "would + if Past."),
        err("If he knows, he would tell us.", "If he knew, he would tell us.", "If + Past."),
    ],
    "third-conditional": [
        fill("If I had left earlier, I ___ have caught the train.", "would", "would have + V3."),
        mc("If she ___ harder, she would have passed.", ["studied", "had studied", "has studied"], "had studied", "If + Past Perfect."),
        err("If I would have known, I would have called.", "If I had known, I would have called.", "If + had + V3."),
        xf("Third Conditional: вставьте would: If they had invited me → I ___ have gone.", "would", "would have + V3."),
        fill("He wouldn't have crashed if he ___ been careful.", "had", "had + V3."),
        match("Third", ["If", "had + V3", "would have + V3"], "If=рамка; had+V3=условие; would have=результат", "Нереальное прошлое."),
        mc("If we ___ the map, we wouldn't have got lost.", ["took", "had taken", "have taken"], "had taken", "Past Perfect в if."),
        fill("She ___ have come if you'd asked. (would)", "would", "would have."),
        order("Соберите: had / if / known / I / I / would have waited", "If I had known, I would have waited.", "3rd structure."),
        err("If you would have told me, I had helped.", "If you had told me, I would have helped.", "Классическая 3rd."),
    ],
    "modals-possibility": [
        fill("You ___ be tired after that trip. (must)", "must", "Сильный вывод."),
        mc("She ___ be at home — the lights are off.", ["must", "can't", "should"], "can't", "Невозможность."),
        err("He musts be joking.", "He must be joking.", "must без -s."),
        xf("Возможно: They ___ be late. (might)", "might", "might + V.", ["may", "could"]),
        fill("You look tired. You ___ have slept badly. (must)", "must", "must have + V3."),
        match("Вывод", ["must", "might", "can't"], "must=уверен; might=возможно; can't=невозможно", "Модальные вывода."),
        mc("It ___ rain later — take an umbrella.", ["must", "might", "can't"], "might", "Возможность."),
        fill("They can't ___ forgotten — I reminded them. (have)", "have", "can't have + V3."),
        order("Соберите: be / must / she / busy", "She must be busy.", "must + be."),
        err("He can be in Spain — I saw him here a minute ago.", "He can't be in Spain — I saw him here a minute ago.", "can't для невозможности."),
    ],
    "reported-statements": [
        fill("She said she ___ tired. (be, past)", "was", "Sequence of tenses."),
        xf("Косвенная речь: вставьте сдвиг времени: 'I am busy' → He said he ___ busy.", "was", "am → was."),
        err("He said he will come yesterday's report.", "He said he would come.", "will → would."),
        mc("They told me they ___ the keys.", ["lose", "had lost", "have lost"], "had lost", "Past Perfect в косвенной."),
        fill("She said she ___ me later. (call → would)", "would call", "will → would."),
        match("Сдвиг", ["am→was", "will→would", "have→had"], "am→was=to be; will→would=future; have→had=perfect", "Sequence."),
        mc("'I can help' → She said she ___ help.", ["can", "could", "will"], "could", "can → could."),
        fill("He told us he ___ finished. (have)", "had", "have → had."),
        order("Соберите: said / she / was / hungry / she", "She said she was hungry.", "said + clause."),
        err("She said me she was late.", "She told me she was late.", "tell + person.", ["She said she was late."]),
    ],
    "reported-questions": [
        mc("She asked where I ___.", ["live", "lived", "lives"], "lived", "Sequence of tenses."),
        fill("He asked if I ___ ready. (be)", "was", "if + Past."),
        err("She asked where do I live.", "She asked where I lived.", "Без do; прямой порядок."),
        xf("Косвенный вопрос: вставьте форму: 'Are you OK?' → He asked if I ___ OK.", "was", "be → was."),
        fill("They asked what time the train ___. (leave)", "left", "Past в косвенном."),
        match("Reported Q", ["asked", "if/whether", "S + V"], "asked=глагол; if=да/нет; S+V=порядок", "Косвенный вопрос."),
        mc("I asked how long she ___ there.", ["works", "worked", "had worked"], "had worked", "Perfect возможен.", ["worked"]),
        fill("She wondered whether we ___ come. (can → could)", "could", "can → could."),
        order("Соберите: asked / he / I / was / if / free", "He asked if I was free.", "asked if + clause."),
        err("He asked me where was the station.", "He asked me where the station was.", "Прямой порядок."),
    ],
    "passive-all-simple": [
        xf("Перепишите в Passive: They built the bridge.", "The bridge was built.", "Past Passive."),
        fill("The documents ___ signed yesterday.", "were", "were + V3."),
        err("The room cleaned every day.", "The room is cleaned every day.", "Нужен be."),
        mc("A new law ___ last month.", ["passes", "was passed", "passed"], "was passed", "Past Passive."),
        fill("English ___ in many countries. (speak, present)", "is spoken", "is + V3."),
        match("Passive", ["is/was/were", "V3", "by + agent"], "be=время; V3=действие; by=агент опц.", "be + V3."),
        order("Соберите: was / the / cancelled / flight", "The flight was cancelled.", "S + was + V3."),
        mc("These emails ___ daily.", ["send", "are sent", "sent"], "are sent", "Present Passive."),
        fill("The thief ___ caught by the police. (be)", "was", "was + V3."),
        err("The cakes was eaten.", "The cakes were eaten.", "Мн. — were."),
    ],
    "defining-nondefining": [
        fill("My brother ___ lives in Oslo is a doctor. (non-defining — who)", "who", "who в non-defining.", [", who"]),
        mc("The book ___ I lent you is due back.", ["which", "who", "where"], "which", "Defining — which/that.", ["that"]),
        err("My father that is 60 loves hiking. (non-defining)", "My father, who is 60, loves hiking.", "Non-defining — who + запятые."),
        xf("Составьте defining relative clause: students + study hard → ?", "students who study hard", "who без запятых."),
        fill("Paris, ___ is the capital of France, is beautiful.", "which", "Non-defining which."),
        match("Типы", ["defining", "non-defining", "commas"], "defining=без запятых; non-defining=с запятыми; commas=ключ", "Относительные."),
        mc("This is the café ___ we met.", ["which", "where", "who"], "where", "место."),
        fill("People ___ arrive early get seats.", "who", "Defining who."),
        order("Соберите: which / the / film / won / award / an", "the film which won an award", "Defining which."),
        err("The man, that called, left. (non-defining)", "The man, who called, left.", "that не в non-defining."),
    ],
    "gerund-vs-infinitive": [
        err("He suggested to go.", "He suggested going.", "Suggest + -ing."),
        fill("I look forward to ___ you. (meet)", "meeting", "to + -ing."),
        mc("She decided ___ early.", ["leaving", "to leave", "leave"], "to leave", "decide + to."),
        xf("Какая форма после enjoy: enjoy + ? (-ing / to)", "enjoy + -ing", "enjoy + gerund.", ["enjoying / -ing"]),
        fill("It's hard ___ hear you. (to)", "to", "adj + to + V."),
        match("Паттерны", ["enjoy", "decide", "look forward to"], "enjoy=-ing; decide=to; look forward to=-ing", "После глагола."),
        mc("He avoided ___ the topic.", ["to discuss", "discussing", "discuss"], "discussing", "avoid + -ing."),
        fill("They promised ___ help.", "to", "promise + to."),
        order("Соберите: smoking / stopped / he", "He stopped smoking.", "stop + -ing."),
        err("I want going home.", "I want to go home.", "want + to."),
    ],
    "wish-past-simple": [
        mc("I wish we ___ closer to the station.", ["are", "were", "will be"], "were", "Wish + were."),
        fill("I wish it ___ raining.", "weren't", "Wish + weren't.", ["wasn't"]),
        err("I wish I have more time.", "I wish I had more time.", "Wish + Past."),
        xf("Жалоба на настоящее с wish: I don't know → I wish I ___.", "knew", "Wish + Past."),
        fill("She wishes she ___ speak French. (can → could)", "could", "can → could."),
        match("Wish", ["I wish", "I knew", "the code"], "I wish=frame; I knew=Past; the code=object", "Wish + Past."),
        mc("I wish he ___ here now.", ["is", "was", "were"], "were", "were предпочтительно.", ["was"]),
        fill("I wish they ___ so noisy. (not be)", "weren't", "weren't.", ["weren't so noisy", "were not"]),
        order("Соберите: wish / I / lived / nearer", "I wish I lived nearer.", "wish + Past."),
        err("I wish I am on holiday.", "I wish I were on holiday.", "were/was после wish."),
    ],
    "question-tags": [
        fill("You're tired, ___ you?", "aren't", "Positive → negative tag."),
        mc("She can't swim, ___ she?", ["can", "can't", "does"], "can", "Negative → positive tag."),
        err("He likes tea, like he?", "He likes tea, doesn't he?", "does/doesn't tag."),
        xf("Добавьте question tag: They were late, ___ they?", "weren't", "were → weren't."),
        fill("Let's go, ___ we?", "shall", "Let's → shall we."),
        match("Tags", ["isn't it", "don't you", "haven't they"], "isn't it=be; don't you=Present; haven't they=Perfect", "Согласование."),
        mc("I'm right, ___ I?", ["am not", "aren't", "don't"], "aren't", "I am → aren't I."),
        fill("He hasn't called, ___ he?", "has", "Negative → positive."),
        order("Соберите: she / isn't / is / late", "She is late, isn't she?", "statement + tag."),
        err("You won't tell, will not you?", "You won't tell, will you?", "won't → will."),
    ],
    "word-order-b1": [
        order("Соберите: been / she / has / working / all day", "She has been working all day.", "Perfect Continuous."),
        fill("He asked where I ___.", "lived", "Косвенный вопрос — прямой порядок."),
        mc("Выберите верное:", ["If I would know, I told you.", "If I knew, I would tell you.", "If I know, I would tell you."], "If I knew, I would tell you.", "2nd conditional."),
        err("She said me the truth.", "She told me the truth.", "tell + person."),
        xf("Перепишите в Passive: Someone has stolen my bike.", "My bike has been stolen.", "Perfect Passive."),
        fill("Вставьте пропущенное слово: I wish I ___ the answer.", "knew", "Wish + Past."),
        match("B1 порядок", ["Had", "I known", "I would have called"], "Had=инверсия опц.; I known=условие; I would have called=результат", "3rd/инверсия."),
        order("Слова: yet / finished / hasn't / he", "He hasn't finished yet.", "yet в конце."),
        fill("By then they ___ already left.", "had", "Past Perfect."),
        err("Do you can help me?", "Can you help me?", "Модальный сам в вопросе."),
    ],
    # --- B2 ---
    "mixed-conditionals": [
        fill("If I had taken the job, I ___ be in London now.", "would", "Mixed: past condition → present result."),
        mc("If she ___ taller, she would have joined the team then.", ["is", "was", "were"], "were", "Present unreal → past result.", ["was"]),
        err("If I would have studied, I would be a doctor now.", "If I had studied, I would be a doctor now.", "If + Past Perfect."),
        xf("Mixed Conditional (прошлое → настоящее): вставьте would: If we had left earlier, we ___ be there now.", "would", "would + V."),
        fill("If he weren't so stubborn, he ___ have apologised.", "would", "Present unreal → past result."),
        match("Mixed", ["had + V3", "would + V", "now"], "had+V3=прошлое условие; would+V=настоящий результат; now=маркер", "Смешанный тип."),
        mc("If I ___ your number, I would have called yesterday.", ["have", "had", "would have"], "had", "had + N."),
        fill("She would still work here if they ___ offered her more.", "had", "had + V3."),
        order("Соберите: would / be / richer / if / he / had / invested", "He would be richer if he had invested.", "mixed."),
        err("If I knew her then, I would have said hello.", "If I had known her then, I would have said hello.", "Прошлое условие — had known."),
    ],
    "wish-if-only": [
        fill("If only I ___ listened!", "had", "If only + Past Perfect."),
        mc("I wish you ___ make so much noise.", ["don't", "wouldn't", "won't"], "wouldn't", "Wish + would — раздражение."),
        err("I wish I would be taller.", "I wish I were taller.", "Состояние — were, не would."),
        xf("Жалоба на привычку: I wish he ___ stop interrupting.", "would", "wish + would."),
        fill("If only we ___ more time. (have — настоящее)", "had", "If only + Past."),
        match("Wish/If only", ["were", "had + V3", "would + V"], "were=настоящее; had+V3=прошлое; would=желание изменить поведение", "Нюансы."),
        mc("I wish I ___ gone to the party.", ["have", "had", "would"], "had", "Сожаление о прошлом."),
        fill("If only it ___ rain tomorrow. (would)", "wouldn't", "wouldn't + V."),
        order("Соберите: wish / I / hadn't / said / that", "I wish I hadn't said that.", "wish + Past Perfect."),
        err("If only I can speak Japanese.", "If only I could speak Japanese.", "Past форма."),
    ],
    "modals-deduction": [
        fill("She ___ have forgotten — she never forgets. (can't)", "can't", "can't have + V3."),
        mc("He ___ be the manager — he has the keys.", ["might", "must", "can't"], "must", "Сильный вывод."),
        err("It must to be a mistake.", "It must be a mistake.", "must + V1."),
        xf("Возможно в прошлом: She ___ have missed the bus. (might)", "might", "might have + V3."),
        fill("They must ___ left already. (have)", "have", "must have + V3."),
        match("Deduction", ["must", "might", "can't"], "must=уверен; might=возможно; can't=исключено", "Выводы."),
        mc("You ___ be serious!", ["must", "can't", "should"], "can't", "Неверие."),
        fill("He may ___ been delayed. (have)", "have", "may have + V3."),
        order("Соберите: have / must / she / heard", "She must have heard.", "must have + V3."),
        err("He can have arrived — the door is locked from inside and he's outside.", "He can't have arrived — …", "can't have для невозможности."),
    ],
    "past-modals": [
        fill("You ___ have told me earlier. (should)", "should", "should have + V3 — упрёк."),
        mc("We ___ have taken a taxi.", ["should", "must to", "ought"], "should", "should have.", ["ought to"]),
        err("You should to have called.", "You should have called.", "should have + V3."),
        xf("Не нужно было: You ___ have bought so much. (needn't)", "needn't", "needn't have + V3."),
        fill("They can't ___ known about it. (have)", "have", "can't have + V3."),
        match("Past modals", ["should have", "needn't have", "might have"], "should have=упрёк; needn't have=зря; might have=возможно", "have + V3."),
        mc("I ___ have left the keys at home.", ["must", "must to", "should to"], "must", "must have."),
        fill("She needn't ___ worried. (have)", "have", "needn't have + V3."),
        order("Соберите: have / should / you / asked", "You should have asked.", "should have + V3."),
        err("He must has forgotten.", "He must have forgotten.", "have, не has."),
    ],
    "passive-perfect-infinitive": [
        fill("She is thought ___ be abroad. (to)", "to", "Passive reporting."),
        mc("The file seems ___ have been deleted.", ["to", "for", "that"], "to", "to have been + V3."),
        err("He is said that he is rich.", "He is said to be rich.", "be said to + V."),
        xf("Перепишите reporting passive: People believe she left → She is believed ___ left.", "to have", "to have + V3."),
        fill("The bridge is reported to ___ been damaged.", "have", "to have been + V3."),
        match("Perfect infinitive", ["to have", "been", "stolen"], "to have=perfect; been=passive; stolen=V3", "to have been + V3."),
        mc("They are expected ___ arrive soon.", ["to", "for", "that"], "to", "be expected to."),
        fill("Вставьте вспомогательный глагол: He was alleged to ___ taken bribes.", "have", "to have + V3."),
        order("Соберите: to / said / is / she / be / ill", "She is said to be ill.", "Passive reporting."),
        err("It is thought him to be lying.", "He is thought to be lying.", "S + be thought to."),
    ],
    "causative-have-get": [
        xf("Перепишите в causative (have/get something done): Someone cleaned my car.", "I had my car cleaned.", "Have + object + V3."),
        fill("She had the report ___ . (write, causative)", "written", "have + O + V3."),
        err("I made my hair cut yesterday.", "I had my hair cut yesterday.", "have/get + O + V3."),
        mc("We ___ the lock changed.", ["had", "did", "made"], "had", "had + O + V3."),
        fill("I'm getting my phone ___ . (repair)", "repaired", "get + O + V3."),
        match("Causative", ["have", "my hair", "cut"], "have=caus; my hair=O; cut=V3", "Have sth done."),
        order("Соберите: had / cleaned / we / the / windows", "We had the windows cleaned.", "had + O + V3."),
        mc("He got his essay ___ by a tutor.", ["check", "checked", "checking"], "checked", "get + O + V3."),
        fill("They had someone ___ the piano. (tune — active causative)", "tune", "have + someone + V1."),
        err("I have cut my hair at the salon. (услуга)", "I had my hair cut at the salon.", "causative have."),
    ],
    "participle-clauses": [
        fill("___ the door, she turned on the light. (open — participle)", "Opening", "V-ing clause."),
        mc("___ by the news, he sat down.", ["Shocking", "Shocked", "Shock"], "Shocked", "V3 для пассивного смысла."),
        err("Walked down the street, I saw her.", "Walking down the street, I saw her.", "V-ing для одновременности."),
        xf("Замените на participle clause: After she finished → ___ finished, she left.", "Having", "Having + V3."),
        fill("Not ___ what to say, I stayed quiet. (know)", "knowing", "Not + V-ing."),
        match("Participles", ["Opening", "Shocked", "Having finished"], "Opening=active; Shocked=passive sense; Having finished=perfect", "Типы."),
        mc("___ the email, he called me.", ["Reading", "Read", "Having read"], "Having read", "Perfect participle.", ["Reading"]),
        fill("The man ___ in the corner is my boss. (sit)", "sitting", "Reduced relative — V-ing."),
        order("Соберите: the / letter / reading / she / smiled", "Reading the letter, she smiled.", "Participle clause."),
        err("Been tired, he went to bed.", "Being tired, he went to bed.", "Being + adj."),
    ],
    "inversion-intro": [
        mc("Not only ___ late, he forgot the key.", ["he was", "was he", "he is"], "was he", "Инверсия после Not only."),
        fill("Little ___ she know the truth. (do, past)", "did", "Little did + S."),
        err("Never I have agreed to such a clause.", "Never have I agreed to such a clause.", "Have перед I."),
        order("Соберите: had / I / known / I / would have called", "Had I known, I would have called.", "Инверсия условия."),
        fill("Seldom ___ we see such courage. (do)", "do", "Seldom do + S."),
        match("Инверсия", ["Seldom", "do", "we meet"], "Seldom=front; do=aux; we meet=clause", "Negative adverb + inversion."),
        mc("Under no circumstances ___ you lie.", ["you should", "should you", "you shouldn't"], "should you", "Инверсия."),
        fill("No sooner ___ we arrived than it rained. (have)", "had", "No sooner had + S."),
        order("Слова: never / I / have / felt / worse", "Never have I felt worse.", "Never + aux + S."),
        err("Only then I realised the mistake.", "Only then did I realise the mistake.", "Only then + did."),
    ],
    "cleft-sentences": [
        fill("___ I need is rest.", "What", "Wh-cleft."),
        mc("It was John ___ called you.", ["which", "who", "what"], "who", "It-cleft."),
        err("What I want are a break.", "What I want is a break.", "What-clause + is."),
        xf("Сделайте it-cleft на время: I met her in 2019 → It was in 2019 ___ I met her.", "that", "It was … that."),
        fill("The one ___ helped me was Ana.", "who", "the one who."),
        match("Emphasis", ["What", "I need", "is rest"], "What=cleft; I need=clause; is rest=focus", "Wh-cleft."),
        mc("It was the noise ___ woke me.", ["who", "that", "what"], "that", "It-cleft that."),
        fill("___ bothers me is the delay.", "What", "What + clause + is."),
        order("Соберите: was / it / Maria / who / replied", "It was Maria who replied.", "It-cleft."),
        err("All what I want is peace.", "All I want is peace.", "All (that) I want."),
    ],
    "narrative-tenses": [
        fill("While she ___, the doorbell rang. (cook)", "was cooking", "Past Continuous фон."),
        mc("After he ___ the letter, he smiled.", ["was reading", "had read", "reads"], "had read", "Earlier past — Past Perfect."),
        err("I was sat down when she entered.", "I sat down when she entered.", "Событие — Past Simple.", ["I was sitting when she entered."]),
        xf("Фон: The sun ___ . (shine — continuous)", "was shining", "was + V-ing."),
        fill("By then the guests ___ already left.", "had", "Past Perfect."),
        match("Narrative", ["Past Simple", "Past Continuous", "Past Perfect"], "Simple=события; Continuous=фон; Perfect=раньше", "Сетка времён."),
        mc("He ___ the news and immediately ___.", ["heard / called", "was hearing / called", "had heard / was calling"], "heard / called", "Цепочка событий."),
        fill("She ___ waiting for an hour when he arrived.", "had been", "Past Perfect Continuous."),
        order("Соберите: had / finished / before / we / arrived / they", "They had finished before we arrived.", "Past Perfect + before."),
        err("While I walked home, it was starting to rain. (фон длительный)", "While I was walking home, it started to rain.", "Continuous фон + Simple событие."),
    ],
    "unreal-past": [
        fill("I'd rather you ___ now. (leave)", "left", "Would rather + Past."),
        mc("It's time we ___.", ["go", "went", "going"], "went", "It's time + Past."),
        err("It's high time you go to bed.", "It's high time you went to bed.", "High time + Past."),
        xf("Вставьте форму после I'd sooner: I'd sooner ___ at home. (stay)", "stay", "Would sooner + V1."),
        fill("Suppose he ___ late — what then? (be)", "were", "Suppose + Past.", ["was"]),
        match(
            "Unreal past",
            ["I'd rather", "It's time", "Past form"],
            "I'd rather=рамка; It's time=рамка; Past form=форма",
            "Структуры.",
        ),
        mc("I'd rather you ___ that.", ["don't mention", "didn't mention", "not mention"], "didn't mention", "rather + Past."),
        fill("It's about time he ___ apologised.", "had", "about time + Past Perfect возможен.", ["apologised"]),
        order("Соберите: went / time / it's / we / home", "It's time we went home.", "It's time + Past."),
        err("I'd rather you to stay.", "I'd rather you stayed.", "rather + Past, не to."),
    ],
    "relative-advanced": [
        fill("She's the author ___ novels I admire.", "whose", "whose + N."),
        mc("The day ___ we met was rainy.", ["which", "when", "whose"], "when", "when для времени.", ["on which"]),
        err("This is the office that I work.", "This is the office where I work.", "where / in which."),
        xf("Вставьте местоимение после many of: many of ___ were late", "whom", "of whom.", ["which"]),
        fill("The reason ___ I'm calling is urgent.", "why", "why.", ["that"]),
        match("Advanced relative", ["whose", "of which", "whereby"], "whose=принадлежность; of which=вещи; whereby=способ", "Расширенные."),
        mc("I spoke to the manager, ___ was helpful.", ["that", "who", "which"], "who", "Non-defining who."),
        fill("There were ten candidates, none of ___ passed.", "whom", "none of whom."),
        order("Соберите: whose / the / woman / car / stolen / was", "the woman whose car was stolen", "whose."),
        err("The house which roof is red is ours.", "The house whose roof is red is ours.", "whose."),
    ],
}

TOPIC_TEST_ADV: dict[str, list] = {
    "present-perfect-vs-past-simple": [
        fill("Вставьте нужную форму (see): I ___ that film last week. (see)", "saw", "last week → Past."),
        mc("Выберите верную пару форм: She ___ just ___ the email.", ["has / sent", "sent / has", "have / send"], "has / sent", "just → Perfect."),
        err("He has went home.", "He has gone home.", "have + V3."),
        xf("Вставьте Present Perfect (since 2018): We ___ here. (live)", "have lived", "since → Perfect."),
        fill("Вставьте нужную форму (get): They ___ married in 2015. (get)", "got", "год → Past."),
        match("Соедините маркер и время", ["ago", "already", "in 2010"], "ago=Past; already=Perfect; in 2010=Past", "Выбор."),
        mc("Выберите вспомогательный глагол: ___ you finish the report yesterday?", ["Have", "Did", "Has"], "Did", "yesterday → Did."),
        fill("Вставьте нужную форму (see): I ___ never ___ such chaos. (see)", "have seen", "never → Perfect."),
        order("Соберите: yet / replied / hasn't / she", "She hasn't replied yet.", "yet → Perfect."),
        err("Did you ever been abroad?", "Have you ever been abroad?", "ever → Perfect."),
    ],
    "present-perfect-continuous": [
        fill("Вставьте вспомогательный глагол: I ___ been studying for two hours.", "have", "have been + V-ing."),
        order("Соберите: been / she / has / working / all day", "She has been working all day.", "Perfect Continuous."),
        err("We have been wait long.", "We have been waiting long.", "V-ing."),
        xf("Начните вопрос How long: ___ you been learning French?", "Have", "Have + been."),
        fill("Вставьте форму to be: It has ___ snowing since dawn.", "been", "been + V-ing."),
        match("Форма", ["has", "been", "raining"], "has=aux; been=perfect; raining=V-ing", "PPC."),
        mc("Выберите вспомогательный глагол: They ___ been travelling a lot lately.", ["has", "have", "are"], "have", "They + have."),
        fill("Вставьте форму to be: He hasn't ___ sleeping well.", "been", "hasn't been + V-ing."),
        order("Слова: waiting / been / have / we", "We have been waiting.", "have been + V-ing."),
        err("She have been cooking.", "She has been cooking.", "She + has."),
    ],
    "past-perfect": [
        fill("Вставьте вспомогательный глагол: She ___ already left when I rang.", "had", "had + V3."),
        mc("Выберите форму Past Perfect: I knew I ___ that man before.", ["saw", "had seen", "have seen"], "had seen", "Earlier past."),
        err("After the film has ended, we went home.", "After the film had ended, we went home.", "had."),
        xf("Вставьте Past Perfect (by midnight): They ___ . (leave)", "had left", "By + Past Perfect."),
        fill("Вставьте вспомогательный глагол: He realised he ___ forgotten the password.", "had", "had + V3."),
        match("Past Perfect", ["had", "written", "before"], "had=aux; written=V3; before=маркер", "had + V3."),
        mc("Выберите форму Past Perfect: We ___ dinner before they arrived.", ["have", "had had", "has"], "had had", "had + had."),
        fill("Вставьте вспомогательный глагол: Until then I ___ never flown.", "had", "had never + V3."),
        order("Соберите: had / the / train / left / already", "The train had already left.", "had + already."),
        err("She had ate before noon.", "She had eaten before noon.", "eat — eaten."),
    ],
    "future-continuous": [
        fill("Вставьте модальный глагол (will/would): At noon tomorrow I ___ be sitting on a beach.", "will", "will be + V-ing."),
        mc("Выберите модальный глагол (will/would): ___ you be working late?", ["Do", "Will", "Are"], "Will", "Will + be."),
        err("They will be watch the match.", "They will be watching the match.", "V-ing."),
        xf("Отрицание: She will be joining us.", "She won't be joining us.", "won't be + V-ing.", ["She will not be joining us."]),
        fill("Вставьте модальный глагол (will/would): This time next week we ___ be travelling.", "will", "will be."),
        match("FC", ["will", "be", "driving"], "will=aux; be=cont; driving=V-ing", "will be + V-ing."),
        mc("Выберите модальный глагол (will/would): Don't disturb him — he ___ be sleeping.", ["will", "is", "was"], "will", "will be."),
        fill("Вставьте форму to be: I won't ___ using the office tomorrow.", "be", "won't be + V-ing."),
        order("Соберите: be / will / they / waiting", "They will be waiting.", "will be + V-ing."),
        err("Will be she coming?", "Will she be coming?", "Will + S + be."),
    ],
    "second-conditional": [
        fill("Вставьте вспомогательный глагол: If I ___ more free time, I'd take up piano. (have)", "had", "If + Past."),
        mc("Выберите модальный глагол (will/would): If she were here, she ___ know.", ["will", "would", "would have"], "would", "would + V."),
        err("If I will be you, I'd refuse.", "If I were you, I'd refuse.", "If I were you."),
        xf("2nd вопрос: What ___ you do if you lost your job?", "would", "would + V."),
        fill("Вставьте форму to be: If it ___ snow, we'd ski. (be)", "were", "were.", ["was"]),
        match("2nd", ["If + Past", "would + V", "now/unreal"], "If+Past=условие; would=результат; now=смысл", "Нереальное."),
        mc("Выберите модальный глагол (will/would): I ___ buy it if it weren't so expensive.", ["will", "would", "would have"], "would", "would + V."),
        fill("Вставьте нужную форму (live): If we ___ nearer, we'd visit more. (live)", "lived", "Past в if."),
        order("Соберите: would / help / if / I / could / I", "I would help if I could.", "would + if Past."),
        err("If he would be taller, he would play basketball.", "If he were taller, he would play basketball.", "were в if."),
    ],
    "third-conditional": [
        fill("Вставьте вспомогательный глагол: If you ___ warned me, I wouldn't have gone.", "had", "had + V3."),
        mc("Выберите форму Third Conditional: She would have passed if she ___ harder.", ["studied", "had studied", "would study"], "had studied", "If + Past Perfect."),
        err("If I would have seen you, I would have waved.", "If I had seen you, I would have waved.", "had + V3."),
        xf("Third Conditional: вставьте would: If they had asked → I ___ have agreed.", "would", "would have."),
        fill("Вставьте вспомогательный глагол: We wouldn't ___ got lost if we'd used the map. (have)", "have", "would have + V3."),
        match("3rd", ["had + V3", "would have + V3", "past unreal"], "had+V3=условие; would have=результат; past unreal=смысл", "Структура."),
        mc("Выберите форму Third Conditional: If he ___ the email, he would have replied.", ["saw", "had seen", "has seen"], "had seen", "Past Perfect."),
        fill("Вставьте модальный глагол (will/would): I ___ have called if I'd had your number.", "would", "would have."),
        order("Соберите: had / if / left / earlier / we / would have caught / the train", "If we had left earlier, we would have caught the train.", "3rd."),
        err("If you told me, I would have helped. (прошлое условие)", "If you had told me, I would have helped.", "had told."),
    ],
    "modals-possibility": [
        fill("Вставьте модальный глагол: That ___ be true — I'm not sure. (might)", "might", "might + V.", ["may", "could"]),
        mc("Выберите модальный глагол must: He ___ be joking.", ["must", "must to", "can to"], "must", "Сильный вывод."),
        err("She can be French — she doesn't speak a word of French.", "She can't be French — …", "can't."),
        xf("Прошлый вывод: They ___ have left. (must)", "must", "must have."),
        fill("Вставьте модальный глагол: You ___ have left your phone on the bus. (might)", "might", "might have + V3."),
        match("Possibility", ["must", "may", "can't"], "must=почти уверен; may=возможно; can't=нет", "Шкала."),
        mc("Выберите модальный глагол: It ___ rain, but I doubt it.", ["must", "might", "can't"], "might", "Слабая возможность."),
        fill("Вставьте форму to be: He can't ___ serious.", "be", "can't + be."),
        order("Соберите: be / must / exhausted / you", "You must be exhausted.", "must be."),
        err("They musts have arrived.", "They must have arrived.", "must без -s."),
    ],
    "reported-statements": [
        fill("Вставьте форму to be: He said he ___ busy. (be)", "was", "am/is → was."),
        mc("Выберите модальный глагол (will/would): 'I will help' → She said she ___ help.", ["will", "would", "helps"], "would", "will → would."),
        err("They told that they were ready.", "They said that they were ready.", "say that / tell someone."),
        xf("Косвенная речь: вставьте сдвиг: 'We have finished' → They said they ___ finished.", "had", "have → had."),
        fill("Вставьте модальный глагол (will/would): She told me she ___ come. (would)", "would", "will → would."),
        match("Reporting", ["said", "told me", "that-clause"], "said=без объекта; told me=с объектом; that-clause=содержание", "Глаголы."),
        mc("Выберите модальный глагол: 'I can swim' → He said he ___ swim.", ["can", "could", "will"], "could", "can → could."),
        fill("Вставьте форму to be: I explained that I ___ delayed. (be → was)", "was", "be → was."),
        order("Соберите: said / was / she / tired / she", "She said she was tired.", "said + clause."),
        err("He said he goes tomorrow. (из 'I will go')", "He said he would go.", "will → would."),
    ],
    "reported-questions": [
        fill("Вставьте нужную форму (want): She asked what I ___. (want)", "wanted", "Past в косвенном."),
        mc("Выберите пропущенное слово: He asked ___ I was free.", ["do", "if", "what"], "if", "Yes/No → if/whether."),
        err("I asked where did she live.", "I asked where she lived.", "Прямой порядок."),
        xf("Косвенный вопрос: вставьте форму: 'Can you drive?' → She asked if I ___ drive.", "could", "can → could."),
        fill("Вставьте форму to be: They asked whether we ___ ready.", "were", "be → were."),
        match("Косвенный вопрос", ["asked", "wh-word", "S + V"], "asked=глагол; wh=тип; S+V=порядок", "Без aux впереди."),
        mc("Выберите модальный глагол (will/would): She wondered how long it ___ take.", ["will", "would", "takes"], "would", "will → would."),
        fill("Вставьте форму to be: He asked me where the keys ___.", "were", "be → were."),
        order("Соберите: asked / if / I / needed / help / she", "She asked if I needed help.", "asked if."),
        err("He asked what was my name.", "He asked what my name was.", "Прямой порядок."),
    ],
    "passive-all-simple": [
        fill("Вставьте форму to be: The window ___ broken last night.", "was", "was + V3."),
        mc("Выберите форму пассива: These rules ___ strictly.", ["follow", "are followed", "followed"], "are followed", "Present Passive."),
        err("The letter written by Ana.", "The letter was written by Ana.", "was + V3."),
        xf("Перепишите в Passive: They cancelled the show.", "The show was cancelled.", "was + V3."),
        fill("Вставьте форму to be: Visitors ___ not allowed after 6. (be)", "are", "are + V3."),
        match("Passive simple", ["is", "was", "were"], "is=present; was=sg past; were=pl past", "be формы."),
        mc("Выберите форму to be: My bike ___ stolen.", ["was", "were", "is being"], "was", "Past Passive."),
        fill("Вставьте форму to be: The emails ___ sent every Monday.", "are", "are + V3."),
        order("Соберите: built / was / bridge / the / in / 1990", "The bridge was built in 1990.", "was + V3."),
        err("The rooms was painted.", "The rooms were painted.", "Мн. — were."),
    ],
    "defining-nondefining": [
        fill("Вставьте вопросительное / относительное слово: My sister, ___ lives abroad, is visiting.", "who", "Non-defining who."),
        mc("Выберите вопросительное / относительное слово: The laptop ___ costs less is better for me.", ["who", "that", "where"], "that", "Defining that/which.", ["which"]),
        err("London which is huge attracts tourists. (нужны запятые)", "London, which is huge, attracts tourists.", "Non-defining + commas."),
        xf("Составьте defining relative clause: the people + live next door", "the people who live next door", "who без запятых."),
        fill("Вставьте вопросительное / относительное слово: This is the street ___ I grew up.", "where", "where."),
        match(
            "Запятые",
            ["defining (без запятых)", "non-defining (с запятыми)", "that в non-defining"],
            "defining (без запятых)=без; non-defining (с запятыми)=с; that в non-defining=нельзя",
            "Правила.",
        ),
        mc("Выберите вопросительное / относительное слово: Her car, ___ is red, is new.", ["that", "which", "who"], "which", "Non-defining which."),
        fill("Вставьте вопросительное / относительное слово: Students ___ fail can resit.", "who", "Defining."),
        order("Соберите: which / Berlin / is / capital / the / of / Germany", "Berlin, which is the capital of Germany", "Non-defining."),
        err("The man, that I met, was kind.", "The man, who I met, was kind.", "who в non-defining.", ["The man whom I met was kind."]),
    ],
    "gerund-vs-infinitive": [
        fill("Вставьте пропущенное слово: She avoid to talk. → She avoids ___.", "talking", "avoid + -ing."),
        mc("Выберите пропущенное слово: I hope ___ soon.", ["arriving", "to arrive", "arrive"], "to arrive", "hope + to."),
        err("I suggested her to wait.", "I suggested that she wait.", "Suggest + that / -ing.", ["I suggested waiting."]),
        xf("Какая форма после finish: finish + ? (-ing / to)", "finish + -ing", "finish + gerund."),
        fill("Вставьте предлог: He agreed ___ help.", "to", "agree + to."),
        match(
            "Паттерны",
            ["avoid", "hope", "look forward to"],
            "avoid=-ing; hope=to; look forward to=-ing",
            "После глагола.",
        ),
        mc("Выберите пропущенное слово: They keep ___ the same mistake.", ["to make", "making", "make"], "making", "keep + -ing."),
        fill("Вставьте предлог: I want ___ leave early.", "to", "want + to."),
        order("Соберите: swimming / enjoys / she", "She enjoys swimming.", "enjoy + -ing."),
        err("I look forward to meet you.", "I look forward to meeting you.", "to + -ing."),
    ],
    "wish-past-simple": [
        fill("Вставьте пропущенное слово: I wish I ___ the answer.", "knew", "Wish + Past."),
        mc("Выберите форму to be: I wish it ___ so cold.", ["isn't", "weren't", "won't"], "weren't", "weren't.", ["wasn't"]),
        err("I wish I can drive.", "I wish I could drive.", "could."),
        xf("Перепишите желание с wish: I don't have a car → I wish I ___ a car.", "had", "had."),
        fill("Вставьте нужную форму (live): She wishes he ___ nearer. (live)", "lived", "Past."),
        match("Wish present", ["wish", "Past form", "now"], "wish=рамка; Past=форма; now=смысл", "Сожаление о настоящем."),
        mc("Выберите форму to be: I wish they ___ here.", ["are", "were", "be"], "were", "were."),
        fill("Вставьте модальный глагол: I wish I ___ speak better English. (can)", "could", "could."),
        order("Соберите: wish / I / weren't / so / busy", "I wish I weren't so busy.", "wish + weren't."),
        err("I wish I am richer.", "I wish I were richer.", "were."),
    ],
    "question-tags": [
        fill("Вставьте форму to be: It's cold, ___ it?", "isn't", "be tag."),
        mc("Выберите вспомогательный глагол: You don't mind, ___ you?", ["do", "don't", "are"], "do", "don't → do."),
        err("She can drive, doesn't she?", "She can drive, can't she?", "can → can't."),
        xf("Добавьте question tag: They've left, ___ they?", "haven't", "have → haven't."),
        fill("Вставьте форму to be: I'm early, ___ I?", "aren't", "aren't I."),
        match("Tags", ["positive→neg tag", "negative→pos tag", "aux matches"], "positive→neg tag=утв→отриц; negative→pos tag=отриц→утв; aux matches=aux как в утверждении", "Логика."),
        mc("Выберите модальный глагол: Let's start, ___ we?", ["will", "shall", "do"], "shall", "shall we."),
        fill("Вставьте модальный глагол (will/would): He won't mind, ___ he?", "will", "won't → will."),
        order("Соберите: she / doesn't / like / tea / does / she", "She doesn't like tea, does she?", "tag."),
        err("You are ready, are you? (утверждение)", "You are ready, aren't you?", "Positive → negative tag."),
    ],
    "word-order-b1": [
        order("Соберите: asked / where / lived / I / she", "She asked where I lived.", "Косвенный вопрос."),
        fill("Вставьте форму to be: If I ___ you, I'd wait. (be)", "were", "2nd."),
        mc("Выберите:", ["Never I have seen it.", "Never have I seen it.", "I never have seen it."], "Never have I seen it.", "Инверсия опциональна на B1 edge.", ["I have never seen it."]),
        err("She avoid to talk.", "She avoids talking.", "avoid + -ing."),
        xf("Перепишите желание с wish: I don't know → I wish I ___.", "knew", "Past."),
        fill("Вставьте вспомогательный глагол: By 2018 they ___ moved.", "had", "Past Perfect."),
        match("B1", ["have been + V-ing", "had + V3", "would + V"], "PPC; Past Perfect; 2nd", "Формы."),
        order("Слова: yet / called / hasn't / he", "He hasn't called yet.", "yet."),
        fill("Вставьте форму to be: I'd rather you ___ quiet. (be)", "were", "rather + Past.", ["was"]),
        err("He suggested to go.", "He suggested going.", "suggest + -ing."),
    ],
    # --- B2 tests ---
    "mixed-conditionals": [
        fill("Вставьте модальный глагол (will/would): If I had saved more, I ___ be freer now.", "would", "past → present."),
        mc("Выберите форму to be: If she ___ so busy, she would have joined us yesterday.", ["isn't", "weren't", "hadn't been"], "weren't", "present unreal → past result.", ["wasn't"]),
        err("If I would have trained, I would be fitter now.", "If I had trained, I would be fitter now.", "had + V3."),
        xf("Mixed Conditional: вставьте would: If we had left earlier → we ___ be there now.", "would", "would + V."),
        fill("Вставьте форму to be: If he ___ more confident, he would have passed the viva.", "were", "Mixed: устойчивая черта сейчас → прошлый результат; were + would have.", ["was"]),
        match("Mixed", ["had + V3 → would + V", "Past → present", "now"], "had + V3 → would + V=структура; Past → present=сдвиг времени; now=маркер результата", "Mixed."),
        mc("Выберите Past Perfect: If I ___ known your address then, I would email you now.", ["had", "have", "would have"], "had", "Прошлое условие — If I had known; результат сейчас — would + V."),
        fill("Вставьте вспомогательный глагол: She would still live here if they ___ offered remote work.", "had", "had + V3."),
        order("Соберите: would / be / happier / if / he / had / stayed", "He would be happier if he had stayed.", "mixed."),
        err("If I knew her then, I would have said hi.", "If I had known her then, I would have said hi.", "had known."),
    ],
    "wish-if-only": [
        fill("Вставьте вспомогательный глагол: If only I ___ known!", "had", "If only + Past Perfect."),
        mc("Выберите модальный глагол (will/would): I wish you ___ stop staring.", ["will", "would", "can"], "would", "wish + would."),
        err("I wish I would have a car.", "I wish I had a car.", "had, не would have для владения."),
        xf("Вставьте Past Perfect после wish (сожаление о прошлом): I wish I ___ gone.", "had", "had + V3."),
        fill("Вставьте форму to be: If only it ___ so noisy. (not be)", "weren't", "weren't.", ["wasn't"]),
        match("Wish", ["were", "had + V3", "would + V"], "настоящее; прошлое; поведение", "Нюансы."),
        mc("Выберите пропущенное слово: If only we ___ more time yesterday.", ["have", "had", "had had"], "had had", "Past Perfect.", ["had"]),
        fill("Вставьте модальный глагол (will/would): I wish he ___ arrive on time. (would)", "would", "would + V."),
        order("Соберите: wish / I / hadn't / bought / it", "I wish I hadn't bought it.", "wish + Past Perfect."),
        err("If only I can ski.", "If only I could ski.", "could."),
    ],
    "modals-deduction": [
        fill("Вставьте модальный глагол must: He ___ have left — his coat is gone. (must)", "must", "must have."),
        mc("Выберите модальный глагол can: That ___ be true; I saw it myself.", ["might not", "can't", "must not"], "can't", "can't + V."),
        err("She must to have forgotten.", "She must have forgotten.", "must have."),
        xf("Вставьте модальный вывод о прошлом (might have): They ___ have missed the turn.", "might", "might have."),
        fill("Вставьте вспомогательный глагол: You can't ___ seen her — she was with me. (have)", "have", "can't have."),
        match("Deduction", ["must have", "might have", "can't have"], "уверен; возможно; невозможно", "Past deduction."),
        mc("Выберите модальный глагол must: The lights are on — someone ___ be home.", ["can't", "must", "shouldn't"], "must", "must be."),
        fill("Вставьте вспомогательный глагол: She may ___ been delayed. (have)", "have", "may have."),
        order("Соберите: have / must / they / heard", "They must have heard.", "must have + V3."),
        err("He can have done it — he was overseas all week.", "He can't have done it — …", "can't have."),
    ],
    "past-modals": [
        fill("Вставьте модальный глагол should: You ___ have warned me. (should)", "should", "should have."),
        mc("Выберите модальный глагол should: We ___ have taken the earlier train.", ["should", "must to", "ought"], "should", "should have.", ["ought to"]),
        err("You should to have asked.", "You should have asked.", "should have."),
        xf("Вставьте needn't have (действие было лишним): You ___ have bought so much.", "needn't", "needn't have."),
        fill("Вставьте вспомогательный глагол: They might ___ left already. (have)", "have", "might have."),
        match("Past modals", ["should have", "needn't have", "could have"], "упрёк; зря; возможность", "have + V3."),
        mc("Выберите модальный глагол must: I ___ have left my wallet at home.", ["must", "must to", "should to"], "must", "must have."),
        fill("Вставьте вспомогательный глагол: She needn't ___ rushed. (have)", "have", "needn't have."),
        order("Соберите: have / should / we / checked", "We should have checked.", "should have."),
        err("He must has called.", "He must have called.", "have."),
    ],
    "passive-perfect-infinitive": [
        fill("Вставьте предлог: He is believed ___ have left.", "to", "to have + V3."),
        mc("Выберите предлог: The files seem ___ have been deleted.", ["to", "for", "that"], "to", "to have been."),
        err("She is said that she is abroad.", "She is said to be abroad.", "be said to."),
        xf("Перепишите reporting passive: People think he lied → He is thought ___ lied.", "to have", "to have."),
        fill("Вставьте вспомогательный глагол: Costs are reported to ___ risen.", "have", "to have + V3."),
        match("Perfect inf.", ["to have", "been", "stolen"], "perfect; passive; V3", "to have been + V3."),
        mc("Выберите предлог: They are expected ___ finish soon.", ["to", "for", "that"], "to", "expected to."),
        fill("Вставьте вспомогательный глагол: He was alleged to ___ taken bribes.", "have", "to have."),
        order("Соберите: to / said / is / be / she / ill", "She is said to be ill.", "said to."),
        err("It is thought him to be lying.", "He is thought to be lying.", "личная."),
    ],
    "causative-have-get": [
        fill("Вставьте вспомогательный глагол: I ___ my car serviced yesterday.", "had", "had + O + V3."),
        mc("Выберите пропущенное слово: She got her passport ___.", ["renew", "renewed", "renewing"], "renewed", "get + O + V3."),
        err("I made my nails done.", "I had my nails done.", "have/get + O + V3."),
        xf("Перепишите в causative: Someone painted our house → We ___ our house painted.", "had", "had."),
        fill("Вставьте нужную форму (fit): We're having a new kitchen ___. (fit)", "fitted", "having + O + V3.", ["installed"]),
        match("Causative", ["have/get", "object", "V3"], "have/get=каузатив; object=объект; V3=причастие", "Have sth done."),
        mc("Выберите нужную форму (active): He had the assistant ___ the forms. (active)", ["sign", "signed", "signing"], "sign", "have + sb + V1."),
        fill("Вставьте нужную форму (repair): They got the roof ___. (repair)", "repaired", "get + O + V3."),
        order("Соберите: had / cut / she / her / hair", "She had her hair cut.", "had + O + V3."),
        err("I have repaired my bike at the shop. (услуга)", "I had my bike repaired at the shop.", "causative."),
    ],
    "participle-clauses": [
        fill("Вставьте форму to be: ___ tired, he went straight to bed. (Being)", "Being", "Being + adj."),
        mc("Выберите пропущенное слово: ___ the news, she cried.", ["Hearing", "Heard", "Hear"], "Hearing", "V-ing."),
        err("Finished the test, he left. (perfect better)", "Having finished the test, he left.", "Having + V3."),
        xf("Сократите relative clause: the people who live here → the people ___ here", "living", "V-ing."),
        fill("Вставьте нужную форму (know): Not ___ the answer, I guessed. (know)", "knowing", "Not + V-ing."),
        match("Participles", ["V-ing", "V3", "Having + V3"], "active; passive sense; perfect", "Clauses."),
        mc("Выберите пропущенное слово: ___ by the results, they celebrated.", ["Delighting", "Delighted", "Delight"], "Delighted", "V3."),
        fill("Вставьте нужную форму (send): The email ___ yesterday needs a reply. (send)", "sent", "reduced passive."),
        order("Соберите: opening / the / window / she / smiled", "Opening the window, she smiled.", "V-ing clause."),
        err("Walked home, I saw a fox.", "Walking home, I saw a fox.", "V-ing."),
    ],
    "inversion-intro": [
        fill("Вставьте вспомогательный глагол: Never ___ I seen such chaos. (have)", "have", "Never have + S."),
        mc("Выберите пропущенное слово: Not only ___ late, he was rude.", ["he was", "was he", "he is"], "was he", "Not only + inversion."),
        err("Seldom we meet nowadays.", "Seldom do we meet nowadays.", "Seldom do."),
        xf("Сделайте инверсию Had + S: If I had known → ___ I known", "Had", "Had + S."),
        fill("Вставьте вспомогательный глагол: Little ___ they know. (do)", "did", "Little did."),
        match("Inversion", ["Never", "Not only", "Only then"], "Never=отриц. наречие; Not only=коррел.; Only then=ограничение", "Intro."),
        mc("Выберите модальный глагол should: Under no circumstances ___ you open it.", ["you should", "should you", "you"], "should you", "should + S."),
        fill("Вставьте вспомогательный глагол: No sooner ___ I sat down than the phone rang. (have)", "had", "No sooner had."),
        order("Соберите: have / never / I / felt / worse", "Never have I felt worse.", "Never have."),
        err("Only then I understood.", "Only then did I understand.", "Only then + did."),
    ],
    "cleft-sentences": [
        fill("Вставьте вопросительное / относительное слово: ___ I need is a break.", "What", "Wh-cleft."),
        mc("Выберите вопросительное / относительное слово: It was Ana ___ called.", ["which", "who", "what"], "who", "It-cleft."),
        err("What I want are peace.", "What I want is peace.", "is."),
        xf("Вставьте связку it-cleft: It was in 2019 ___ we met.", "that", "that."),
        fill("Вставьте вопросительное / относительное слово: The person ___ helped was Jo.", "who", "who."),
        match("Cleft", ["What … is", "It was … who/that", "focus"], "What … is=wh-cleft; It was … who/that=it-cleft; focus=акцент", "Emphasis."),
        mc("Выберите вопросительное / относительное слово: It was the alarm ___ woke us.", ["who", "that", "what"], "that", "that."),
        fill("Вставьте вопросительное / относительное слово: ___ worries me is the cost.", "What", "What … is."),
        order("Соберите: was / it / Tom / who / replied", "It was Tom who replied.", "It-cleft."),
        err("All what she said was true.", "All she said was true.", "All (that)."),
    ],
    "narrative-tenses": [
        fill("Вставьте нужную форму (talk): While we ___, someone knocked. (talk)", "were talking", "Past Continuous."),
        mc("Выберите пропущенное слово: After she ___ the note, she smiled.", ["was reading", "had read", "reads"], "had read", "Past Perfect."),
        err("I was entered the room when the phone rang.", "I entered the room when the phone rang.", "Simple event.", ["I was entering…"]),
        xf("Вставьте Past Continuous (фон): Birds ___ . (sing)", "were singing", "were + V-ing."),
        fill("Вставьте вспомогательный глагол: By then everyone ___ left.", "had", "had + V3."),
        match("Narrative", ["Simple", "Continuous", "Perfect"], "события; фон; раньше", "Tenses."),
        mc("Выберите верную пару форм: He ___ the news and ___ immediately.", ["heard / left", "was hearing / left", "had heard / was leaving"], "heard / left", "sequence."),
        fill("Вставьте вспомогательный глагол: They ___ been waiting an hour when the bus came.", "had", "Past Perfect Continuous."),
        order("Соберите: had / started / before / we / arrived / it", "It had started before we arrived.", "Past Perfect."),
        err("While I walked, it was beginning to rain. (лучше)", "While I was walking, it began to rain.", "Continuous + Simple."),
    ],
    "unreal-past": [
        fill("Вставьте Past Simple после I'd rather you: I'd rather you ___ here. (stay)", "stayed", "rather + Past."),
        mc("Выберите пропущенное слово: It's high time you ___.", ["leave", "left", "leaving"], "left", "high time + Past."),
        err("It's time we go.", "It's time we went.", "Past."),
        xf("Вставьте форму после I'd sooner: I'd sooner ___ alone. (be)", "be", "sooner + V1."),
        fill("Вставьте форму to be: Suppose they ___ late. (be)", "were", "Suppose + Past.", ["was"]),
        match("Unreal", ["I'd rather + Past", "It's time + Past", "suppose + Past"], "I'd rather + Past=предпочтение; It's time + Past=пора; suppose + Past=гипотеза", "Unreal past."),
        mc("Выберите пропущенное слово: I'd rather you ___ that secret.", ["don't tell", "didn't tell", "not to tell"], "didn't tell", "rather + Past."),
        fill("Вставьте нужную форму (apologise): It's about time he ___. (apologise)", "apologised", "Past.", ["apologized"]),
        order("Соберите: went / time / it's / home / we", "It's time we went home.", "It's time."),
        err("I'd rather you to leave.", "I'd rather you left.", "Past, не to."),
    ],
    "relative-advanced": [
        fill("Вставьте вопросительное / относительное слово: She's the writer ___ books I collect.", "whose", "whose."),
        mc("Выберите вопросительное / относительное слово: That's the year ___ we graduated.", ["which", "when", "whose"], "when", "when.", ["in which"]),
        err("This is the desk that I work.", "This is the desk where I work.", "where."),
        xf("Вставьте местоимение после many of: many of ___ applied", "whom", "of whom."),
        fill("Вставьте вопросительное / относительное слово: The reason ___ we left is clear.", "why", "why.", ["that"]),
        match("Advanced", ["whose", "of which", "whereby"], "принадлежность; вещи; способ", "Relatives."),
        mc("Выберите вопросительное / относительное слово: I met the CEO, ___ was inspiring.", ["that", "who", "which"], "who", "non-defining who."),
        fill("Вставьте вопросительное / относительное слово: Ten people applied, none of ___ were suitable.", "whom", "none of whom."),
        order("Соберите: whose / phone / the / man / rang", "the man whose phone rang", "whose."),
        err("A house which windows are large…", "A house whose windows are large…", "whose."),
    ],
}
