"""A2–C2 on-topic practice/test pads keyed by module slug."""

from app.seed.helpers import err, fill, match, mc, order, xf

TOPIC_PRACTICE_UPPER: dict[str, list] = {
    "present-simple-vs-continuous": [
        mc("Usually she ___ tea, but today she ___ coffee.", ["drinks / is drinking", "is drinking / drinks", "drink / drink"], "drinks / is drinking", "Привычка vs сегодня."),
        fill("Listen! Someone ___ at the door. (knock)", "is knocking", "Listen! → Continuous."),
        err("She is knowing the answer.", "She knows the answer.", "Know — Simple."),
        err("He go to school every day.", "He goes to school every day.", "Привычка — Simple 3sg."),
        xf("Сейчас: I work → Continuous", "I am working", "be + V-ing."),
        fill("He ___ with friends this month. (live)", "is living", "Временная ситуация."),
        mc("Water ___ at 100°C.", ["is boiling", "boils", "boil"], "boils", "Научный факт — Simple."),
        match("Выбор времени", ["every day", "right now", "this week"], "every day=Simple; right now=Continuous; this week=часто Continuous", "Маркеры."),
        order("Соберите: at the moment / packing / am / I", "I am packing at the moment.", "Continuous + маркер."),
        fill("I ___ the rule now. (understand)", "understand", "Состояние — Simple."),
    ],
    "past-continuous": [
        mc("She ___ TV when I called.", ["watched", "was watching", "watches"], "was watching", "Past Continuous фон."),
        fill("While we ___, it started to rain. (walk)", "were walking", "while + Past Continuous."),
        err("I was cook dinner at 7.", "I was cooking dinner at 7.", "was/were + V-ing."),
        xf("Вопрос: They were waiting.", "Were they waiting?", "Were + S + V-ing."),
        fill("He ___ not ___ attention. (pay)", "was not paying", "was + not + V-ing.", ["wasn't paying"]),
        mc("At midnight I ___ still ___.", ["worked / working", "was / working", "was / work"], "was / working", "was + V-ing."),
        order("Соберите: were / playing / they / football", "They were playing football.", "S + were + V-ing."),
        match("Past Continuous", ["was", "reading", "when"], "was=be past; reading=V-ing; when=обрыв", "Фон + прерывание."),
        fill("What ___ you ___ at 9? (do)", "were doing", "were + V-ing."),
        err("She were sleeping.", "She was sleeping.", "She + was."),
    ],
    "present-perfect-intro": [
        fill("I ___ already finished. (have)", "have", "have + V3."),
        mc("She ___ just left.", ["have", "has", "is"], "has", "She + has."),
        err("I have saw that film.", "I have seen that film.", "have + V3."),
        xf("Отрицание: They have arrived.", "They haven't arrived.", "haven't + V3.", ["They have not arrived."]),
        fill("___ you ever been to Rome?", "Have", "Have + S + V3."),
        mc("He ___ lost his keys.", ["have", "has", "is"], "has", "has + V3."),
        order("Соберите: never / have / I / tried / sushi", "I have never tried sushi.", "have + never + V3."),
        match("Present Perfect", ["have", "eaten", "already"], "have=aux; eaten=V3; already=маркер", "have + V3."),
        fill("We ___ not ___ the news yet. (hear)", "have not heard", "haven't + V3.", ["haven't heard"]),
        err("She has went home.", "She has gone home.", "go — gone."),
    ],
    "will-vs-going-to": [
        mc("I think it ___ rain later.", ["is going to", "will", "goes to"], "will", "Мнение/предсказание — will.", ["is going to"]),
        fill("We've already decided: we ___ going to stay.", "are", "Заранее принятый план — going to."),
        err("I will going to help.", "I am going to help.", "Не смешивайте will и going to."),
        xf("Спонтанно: The phone is ringing. → I ___ get it.", "will", "will + V."),
        fill("Look at those clouds — it ___ going to snow.", "is", "Примета — going to."),
        mc("Perhaps I ___ call her tonight.", ["will", "am going", "going to"], "will", "Perhaps + will."),
        order("Соберите: will / you / me / help", "Will you help me?", "Will + S + V."),
        match("Будущее", ["will", "going to", "I think"], "will=часто мнение; going to=план/примета; I think=маркер will", "Выбор формы."),
        fill("Don't worry — I ___ pick you up. (will)", "will", "will + V1."),
        err("He going to will leave.", "He is going to leave.", "Одна конструкция."),
    ],
    "comparatives": [
        order("Соберите: than / bigger / is / this / that", "This is bigger than that.", "сравнительная + than."),
        fill("This bag is ___ than that one. (light)", "lighter", "прил. + er."),
        err("She is more taller than me.", "She is taller than me.", "Не double comparative."),
        mc("English is ___ than I thought.", ["easy", "easier", "easiest"], "easier", "Сравнение двух."),
        fill("He works ___ than before. (hard)", "harder", "наречие + er."),
        xf("good → сравнительная", "better", "good — better."),
        match("Сравните", ["good", "better", "best"], "good=base; better=comp; best=super", "Неправильные формы."),
        order("Соберите: more / interesting / is / this / book", "This book is more interesting.", "long adj → more."),
        fill("My flat is ___ comfortable than yours.", "more", "more + long adj."),
        err("This car is expensiver.", "This car is more expensive.", "long adj → more."),
    ],
    "superlatives": [
        fill("This is the ___ building in town. (tall)", "tallest", "the + -est."),
        mc("She is the ___ student in the class.", ["better", "best", "good"], "best", "good — best."),
        err("He is most tallest player.", "He is the tallest player.", "Не double superlative; нужен the."),
        xf("interesting → превосходная", "the most interesting", "long adj → the most."),
        fill("It's the ___ day of my life. (happy)", "happiest", "y → iest."),
        match("Превосходная", ["the", "worst", "film"], "the=артикль; worst=super; film=N", "the + superlative."),
        mc("Which is the ___ option?", ["more cheap", "cheapest", "cheaper"], "cheapest", "Из многих — -est."),
        fill("This is ___ most expensive hotel here.", "the", "the most."),
        order("Соберите: the / in / fastest / runner / is / he / school / the", "He is the fastest runner in the school.", "the + -est + in."),
        err("She is the more intelligent of all.", "She is the most intelligent of all.", "Превосходная — most."),
    ],
    "countable-uncountable": [
        mc("How ___ sugar do you need?", ["many", "much", "few"], "much", "Неисчисляемое."),
        fill("There isn't ___ milk.", "any", "Отрицание + any.", ["much"]),
        err("I need an advice.", "I need advice.", "advice неисчисляемое.", ["I need some advice."]),
        xf("apple → неисчисляемое? нет →", "apples / an apple", "Исчисляемое.", ["an apple", "apples"]),
        fill("There are ___ chairs.", "some", "Мн. исчисляемые + some.", ["many", "a few"]),
        match("Исчисляемость", ["bread", "apple", "water"], "bread=uncount; apple=count; water=uncount", "Тип существительного."),
        mc("I bought ___ furniture.", ["a", "some", "many"], "some", "furniture неисчисляемое."),
        fill("How ___ books did you read?", "many", "Исчисляемые — many."),
        order("Соберите: much / haven't / time / we / got", "We haven't got much time.", "much + uncount."),
        err("Informations are useful.", "Information is useful.", "information неисчисляемое."),
    ],
    "quantifiers-a2": [
        mc("There isn't ___ milk.", ["some", "any", "many"], "any", "Отрицание + any."),
        fill("We have ___ friends in Spain.", "some", "Утверждение + some.", ["a few", "many"]),
        err("I don't have some money.", "I don't have any money.", "Отрицание — any."),
        xf("Много (uncount): ___ time", "much time", "much + uncount.", ["a lot of time"]),
        fill("Only ___ people came.", "a few", "a few + count."),
        match("Quantifiers", ["much", "many", "a few"], "much=uncount; many=count; a few=count+", "Исчисляемость."),
        mc("There's ___ traffic today.", ["many", "much", "a few"], "much", "traffic неисчисляемое."),
        fill("She has ___ little patience.", "a", "a little + uncount.", ["very"]),
        order("Соберите: any / there / aren't / tickets", "There aren't any tickets.", "any в отрицании."),
        err("How much apples?", "How many apples?", "Apples — many."),
    ],
    "modals-must-should-have-to": [
        fill("You ___ park here. (mustn't)", "mustn't", "Запрет.", ["must not"]),
        mc("You ___ see a doctor.", ["should", "should to", "must to"], "should", "Совет — should + V1."),
        err("I must to go now.", "I must go now.", "После must нет to."),
        xf("Обязанность: wear a uniform → You ___ wear a uniform.", "have to", "have to + V.", ["must", "need to"]),
        fill("She ___ work on Sundays. (have to)", "has to", "He/she + has to."),
        match("Модальные", ["must", "should", "mustn't"], "must=обязанность; should=совет; mustn't=запрет", "Значения."),
        mc("You ___ be quiet in the library.", ["must", "must to", "should to"], "must", "Сильное правило."),
        fill("We don't ___ get up early tomorrow.", "have to", "Нет необходимости."),
        order("Соберите: should / you / more / sleep", "You should sleep more.", "should + V1."),
        err("He shoulds study harder.", "He should study harder.", "should без -s."),
    ],
    "zero-first-conditional": [
        fill("If it rains, we ___ stay home. (will)", "will", "First conditional."),
        order("Соберите: will / if / you / ask / I / help", "If you ask, I will help.", "If + Present, will."),
        err("If I will see him, I will call.", "If I see him, I will call.", "If + Present."),
        mc("If you heat ice, it ___.", ["will melt", "melts", "melted"], "melts", "Zero — Present + Present."),
        fill("If she ___, tell her I'm out. (call)", "calls", "If + Present."),
        xf("First: If we leave now → we ___ catch the bus.", "will", "will + V."),
        match("First conditional", ["If", "Present", "will"], "If=условие; Present=в if; will=результат", "Структура."),
        mc("If I ___ free, I will come.", ["will be", "am", "was"], "am", "If + Present."),
        fill("Water ___ if you freeze it. (boil? no → turn to ice)", "turns to ice", "Zero conditional.", ["freezes", "becomes ice"]),
        err("If it will rain, we cancel.", "If it rains, we will cancel.", "If + Present, will."),
    ],
    "relative-who-which-that": [
        fill("The woman ___ called you is my boss.", "who", "who для людей.", ["that"]),
        mc("This is the book ___ I bought.", ["who", "which", "where"], "which", "which/that для вещей.", ["that"]),
        err("The man which lives next door is kind.", "The man who lives next door is kind.", "Люди — who.", ["The man that lives next door is kind."]),
        xf("Соедините: I met a girl. She speaks Japanese.", "I met a girl who speaks Japanese.", "who."),
        fill("The café ___ we met is closed.", "where", "where — место."),
        match("Relative", ["who", "which", "where"], "who=people; which=things; where=place", "Defining clauses."),
        mc("That's the dog ___ bit me.", ["who", "which", "whose"], "which", "Животное/вещь — which/that.", ["that"]),
        fill("People ___ arrive late wait outside.", "who", "who + V."),
        order("Соберите: that / film / the / won / award / an", "the film that won an award", "N + that + clause."),
        err("I have a friend which can help.", "I have a friend who can help.", "Друг — who."),
    ],
    "used-to": [
        fill("He used ___ live here.", "to", "used to + V1."),
        mc("I ___ play tennis when I was a child.", ["used to", "use to", "am used to"], "used to", "Прошлая привычка."),
        err("She used to smoking.", "She used to smoke.", "used to + V1."),
        xf("Отрицание: They used to argue.", "They didn't use to argue.", "didn't use to.", ["They used not to argue."]),
        fill("___ you use to walk to school?", "Did", "Did + S + use to."),
        match("Used to", ["used to", "live", "abroad"], "used to=маркер; live=V1; abroad=place", "Прошлое состояние."),
        mc("We ___ go camping every summer.", ["used to", "are used to", "use"], "used to", "Повторявшееся прошлое."),
        fill("I didn't ___ to like olives.", "use", "didn't use to."),
        order("Соберите: to / used / early / get up / she", "She used to get up early.", "used to + V."),
        err("He uses to work here.", "He used to work here.", "used, не uses."),
    ],
    "passive-present-past": [
        xf("Passive: They clean the room.", "The room is cleaned.", "Present Passive."),
        fill("The letter ___ sent yesterday. (be)", "was", "Past Passive."),
        err("The house built in 1990.", "The house was built in 1990.", "Нужен was/were."),
        mc("English ___ here.", ["speaks", "is spoken", "spoken"], "is spoken", "Present Passive."),
        fill("These phones ___ in Korea. (make, present)", "are made", "are + V3."),
        match("Passive", ["is", "cleaned", "daily"], "is=be; cleaned=V3; daily=маркер", "be + V3."),
        order("Соберите: was / the / repaired / car", "The car was repaired.", "S + was + V3."),
        mc("The windows ___ every week.", ["clean", "are cleaned", "cleaned"], "are cleaned", "Present Passive."),
        fill("My bike ___ stolen last night. (be)", "was", "was + V3."),
        err("The cakes is eaten.", "The cakes are eaten.", "Мн. — are."),
    ],
    "adverbs-frequency-manner": [
        fill("She ___ late for work. (be / never)", "is never", "be + частота."),
        mc("He speaks English ___.", ["good", "well", "goodly"], "well", "Manner — well."),
        err("She careful drives.", "She drives carefully.", "Adv после V / -ly."),
        xf("Переставьте: always / he / arrives / early", "He always arrives early.", "Частота перед V."),
        fill("They finished the test ___. (quick)", "quickly", "adj → adv."),
        match("Наречия", ["always", "carefully", "well"], "always=частота; carefully=образ; well=образ", "Типы."),
        mc("I ___ drink coffee in the evening.", ["hardly ever", "ever hardly", "hard ever"], "hardly ever", "Частота."),
        fill("Please speak ___. (slow)", "slowly", "Manner."),
        order("Соберите: loudly / laughing / are / they", "They are laughing loudly.", "V-ing + manner."),
        err("He runs fastly.", "He runs fast.", "fast — одна форма."),
    ],
    "word-order-a2": [
        order("Соберите: yet / finished / haven't / I", "I haven't finished yet.", "yet в конце Perfect."),
        fill("She ___ already ___ home. (go)", "has gone", "already + Perfect."),
        mc("Правильный порядок:", ["Never I have seen it.", "I have never seen it.", "I never have seen it."], "I have never seen it.", "have + never + V3."),
        err("I going am to the shop.", "I am going to the shop.", "be + going."),
        xf("Переставьте: carefully / the / read / email", "Read the email carefully.", "V + O + manner."),
        fill("___ you ever visited Spain?", "Have", "Have + S + V3."),
        match("Порядок A2", ["If", "it rains", "I will stay"], "If=условие; it rains=Present; I will stay=результат", "First conditional."),
        order("Слова: than / older / is / my / brother / me", "My brother is older than me.", "comp + than."),
        fill("There isn't ___ bread left.", "any", "any в отрицании."),
        err("Does she can swim?", "Can she swim?", "Модальный сам образует вопрос."),
    ],
}

TOPIC_TEST_UPPER: dict[str, list] = {
    "present-simple-vs-continuous": [
        mc("She usually ___ to work, but today she ___.", ["drives / is walking", "is driving / walks", "drive / walk"], "drives / is walking", "Привычка vs сегодня."),
        fill("I ___ a headache. (have — состояние)", "have", "have владение/состояние — Simple."),
        err("I am going to the gym every Monday.", "I go to the gym every Monday.", "Привычка — Simple."),
        xf("Сейчас: Look! He ___ . (run)", "is running", "Look! → Continuous."),
        fill("They ___ in Lisbon. (live — постоянно)", "live", "Постоянный факт."),
        match("Маркеры", ["always", "now", "this week"], "always=Simple; now=Continuous; this week=часто Continuous", "Выбор."),
        mc("___ you understanding me?", ["Do", "Are", "Is"], "Do", "understand — Simple."),
        fill("We ___ dinner at the moment. (have)", "are having", "have = есть → Continuous ok."),
        order("Соберите: working / from home / is / she / today", "She is working from home today.", "Continuous + today."),
        err("He is want a new phone.", "He wants a new phone.", "want — Simple."),
    ],
    "past-continuous": [
        fill("While I ___, the phone rang.", "was cooking", "Interrupted action."),
        mc("They ___ when the lights went out.", ["studied", "were studying", "study"], "were studying", "Фон."),
        err("I were watching TV.", "I was watching TV.", "I + was."),
        xf("Отрицание: She was listening.", "She wasn't listening.", "wasn't + V-ing.", ["She was not listening."]),
        fill("What ___ you ___ at 6? (do)", "were doing", "were + V-ing."),
        match("Структура", ["was", "raining", "hard"], "was=be; raining=V-ing; hard=manner", "Past Continuous."),
        mc("At 10 p.m. we ___ still ___.", ["are / working", "were / working", "was / work"], "were / working", "were + V-ing."),
        fill("He ___ not ___ to me. (listen)", "was not listening", "wasn't listening.", ["wasn't listening"]),
        order("Соберите: sleeping / was / the / baby", "The baby was sleeping.", "S + was + V-ing."),
        err("Were she working?", "Was she working?", "She + Was."),
    ],
    "present-perfect-intro": [
        fill("She ___ just left. (have)", "has", "has just + V3."),
        mc("___ you finished yet?", ["Do", "Have", "Has"], "Have", "Have + S + V3."),
        err("I have wrote three emails.", "I have written three emails.", "write — written."),
        xf("Вопрос: They have left.", "Have they left?", "Have + S + V3."),
        fill("I ___ never ___ sushi. (eat)", "have eaten", "have + never + V3."),
        match("Perfect", ["has", "gone", "already"], "has=aux; gone=V3; already=маркер", "has + V3."),
        mc("We ___ lived here since 2018.", ["has", "have", "are"], "have", "We + have."),
        fill("He hasn't ___ the report yet. (finish)", "finished", "hasn't + V3."),
        order("Соберите: ever / you / have / Japan / visited", "Have you ever visited Japan?", "Have + ever + V3."),
        err("She have lost her keys.", "She has lost her keys.", "She + has."),
    ],
    "will-vs-going-to": [
        fill("I ___ help you with that. (спонтанно)", "will", "will + V."),
        mc("They ___ move next month — it's decided.", ["will", "are going to", "go to"], "are going to", "План."),
        err("She will to call later.", "She will call later.", "will + V1."),
        xf("Примета: The baby is crying. → He ___ wake up Dad.", "is going to", "going to."),
        fill("Perhaps it ___ be sunny.", "will", "Perhaps + will."),
        match("Выбор", ["will", "going to", "Look!"], "will=мнение/спонтанно; going to=план; Look!=примета going to", "Контраст."),
        mc("Don't worry — I ___ be fine.", ["will", "am going", "going"], "will", "Обещание/предсказание."),
        fill("We ___ going to start at 9.", "are", "are going to."),
        order("Соберите: will / rain / it / tomorrow", "It will rain tomorrow.", "will + V."),
        err("I am will buy it.", "I will buy it.", "Только will.", ["I am going to buy it."]),
    ],
    "comparatives": [
        fill("My suitcase is ___ than yours. (heavy)", "heavier", "y → ier."),
        mc("This task is ___ difficult than that one.", ["more", "most", "much"], "more", "more + long adj."),
        err("He is taller that me.", "He is taller than me.", "than."),
        xf("bad → сравнительная", "worse", "bad — worse."),
        fill("She runs ___ than I do. (fast)", "faster", "comp adv."),
        match("Сравнение", ["smaller", "than", "mine"], "smaller=comp; than=связь; mine=объект", "adj + than."),
        mc("Today is ___ than yesterday.", ["cold", "colder", "coldest"], "colder", "Два дня."),
        fill("This film is ___ interesting.", "more", "more + long."),
        order("Соберите: less / expensive / is / this / hotel", "This hotel is less expensive.", "less + adj."),
        err("More better is wrong here → use", "better", "Не more better."),
    ],
    "superlatives": [
        fill("It's the ___ café in the street. (busy)", "busiest", "y → iest."),
        mc("This is the ___ meal I've had.", ["better", "best", "good"], "best", "the best."),
        err("She is tallest girl.", "She is the tallest girl.", "Нужен the."),
        xf("far → превосходная (BrE)", "the furthest", "far — furthest.", ["the farthest"]),
        fill("He bought the ___ expensive watch.", "most", "the most."),
        match("Superlative", ["the", "smallest", "room"], "the=арт.; smallest=super; room=N", "the + -est."),
        mc("Who is the ___ player in the team?", ["good", "better", "best"], "best", "Из группы."),
        fill("Winter is the ___ season here. (cold)", "coldest", "the + -est."),
        order("Соберите: most / the / beautiful / place / is / this", "This is the most beautiful place.", "the most + adj."),
        err("It's the more exciting film of all.", "It's the most exciting film of all.", "most."),
    ],
    "countable-uncountable": [
        fill("I'd like ___ water, please.", "some", "some + uncount."),
        mc("There aren't ___ eggs.", ["much", "many", "a little"], "many", "Исчисляемые."),
        err("She gave me a useful information.", "She gave me useful information.", "Без a.", ["She gave me some useful information."]),
        xf("rice — исчисляемое?", "no / uncountable", "rice неисчисляемое.", ["uncountable", "no"]),
        fill("How ___ chairs do we need?", "many", "count → many."),
        match("Тип", ["milk", "cup", "news"], "milk=uncount; cup=count; news=uncount", "Исчисляемость."),
        mc("We need ___ flour.", ["a", "some", "many"], "some", "uncount."),
        fill("There is ___ apple on the plate.", "an", "count ед."),
        order("Соберите: advice / some / need / I", "I need some advice.", "some + uncount."),
        err("The furnitures are new.", "The furniture is new.", "furniture неисчисляемое."),
        fill("We need ___ rice.", "some", "uncount + some.", ["—"]),
    ],
    "quantifiers-a2": [
        fill("There are only ___ biscuits left.", "a few", "a few + count."),
        mc("We have ___ time, hurry!", ["little", "a few", "many"], "little", "little = мало uncount."),
        err("I need any help. (утверждение)", "I need some help.", "Утверждение — some."),
        xf("Отрицание: some →", "any", "any в отрицании/вопросе."),
        fill("___ of the students passed.", "Most", "most of + the.", ["Many", "Some"]),
        match("Квантификаторы", ["a little", "a few", "lots of"], "a little=uncount; a few=count; lots of=оба", "Выбор."),
        mc("Is there ___ cheese left?", ["some", "any", "a few"], "any", "Вопрос — any.", ["some"]),
        fill("He doesn't eat ___ meat.", "much", "much + uncount в отриц.", ["any"]),
        order("Соберите: many / how / people / came", "How many people came?", "How many + count."),
        err("There is a few milk.", "There is a little milk.", "milk — a little."),
    ],
    "modals-must-should-have-to": [
        fill("You ___ wear a seatbelt. (закон)", "must", "must + V1.", ["have to"]),
        mc("You ___ talk to her — it's a good idea.", ["must", "should", "mustn't"], "should", "Совет."),
        err("She musts leave now.", "She must leave now.", "must без -s."),
        xf("Запрет: You ___ touch that.", "mustn't", "mustn't + V.", ["must not"]),
        fill("Do we ___ pay now? (have to)", "have to", "have to в вопросе."),
        match("Значения", ["must", "have to", "should"], "must=сильная обязанность; have to=внешняя; should=совет", "Нюансы."),
        mc("You ___ smoke here.", ["mustn't", "don't must", "shouldn't to"], "mustn't", "Запрет."),
        fill("He ___ to leave early today. (have)", "has", "has to."),
        order("Соберите: should / see / a / you / dentist", "You should see a dentist.", "should + V."),
        err("I don't must go.", "I don't have to go.", "Нет необходимости — don't have to."),
    ],
    "zero-first-conditional": [
        fill("If you ___ ice, it melts. (heat)", "heat", "Zero — Present + Present."),
        mc("If she studies, she ___ pass.", ["will", "would", "passes"], "will", "First — will."),
        err("If he will come, tell me.", "If he comes, tell me.", "If + Present."),
        xf("First: If I miss the bus → I ___ take a taxi.", "will", "will + V."),
        fill("If it ___ cold, we stay in. (be — zero)", "is", "Zero."),
        match("First", ["If", "Present", "will + V"], "If=рамка; Present=условие; will + V=результат", "Структура."),
        mc("If plants don't get water, they ___.", ["will die", "die", "died"], "die", "Zero — общий факт.", ["will die"]),
        fill("If you need help, I ___ come.", "will", "First."),
        order("Соберите: rains / if / it / cancel / we / will", "If it rains, we will cancel.", "If + Present, will."),
        err("If you will press this, the light turns on.", "If you press this, the light turns on.", "Zero/First — Present в if."),
    ],
    "relative-who-which-that": [
        fill("That's the teacher ___ helped me.", "who", "who.", ["that"]),
        mc("The laptop ___ I use is old.", ["who", "which", "where"], "which", "which/that.", ["that"]),
        err("The city who I love is Prague.", "The city which I love is Prague.", "Город — which/that.", ["The city that I love is Prague."]),
        xf("Объедините: Here's the key. It opens the door.", "Here's the key that opens the door.", "that/which."),
        fill("The park ___ we jog is nearby.", "where", "where."),
        match("Местоимения", ["who", "which", "that"], "who=люди; which=вещи; that=оба в defining", "Relative."),
        mc("I know a place ___ serves great coffee.", ["who", "that", "whose"], "that", "that/which.", ["which"]),
        fill("Students ___ study pass.", "who", "who."),
        order("Соберите: which / the / car / bought / we", "the car which we bought", "N + which + clause."),
        err("A woman which called left a message.", "A woman who called left a message.", "who."),
    ],
    "used-to": [
        fill("We ___ to live by the sea.", "used", "used to + V."),
        mc("___ he use to smoke?", ["Does", "Did", "Is"], "Did", "Did + use to."),
        err("I am used to get up early. (прошлая привычка)", "I used to get up early.", "used to + V1 для прошлого."),
        xf("Отрицание: She used to cry.", "She didn't use to cry.", "didn't use to."),
        fill("They used to ___ football here. (play)", "play", "used to + V1."),
        match("Used to", ["Did", "use to", "swim"], "Did=aux; use to=форма; swim=V1", "Вопрос."),
        mc("I ___ like vegetables, but now I do.", ["used to not", "didn't use to", "don't used to"], "didn't use to", "Отрицание."),
        fill("He used ___ work nights.", "to", "used to."),
        order("Соберите: to / used / travel / a lot / we", "We used to travel a lot.", "used to + V."),
        err("She use to be shy.", "She used to be shy.", "used."),
    ],
    "passive-present-past": [
        fill("The room ___ cleaned every day.", "is", "is + V3."),
        mc("My phone ___ yesterday.", ["stole", "was stolen", "stolen"], "was stolen", "Past Passive."),
        err("The emails sends daily.", "The emails are sent daily.", "are + V3."),
        xf("Passive: Someone locked the door.", "The door was locked.", "was + V3."),
        fill("These cars ___ in Japan. (produce, present)", "are produced", "are + V3."),
        match("Passive", ["was", "built", "in 1900"], "was=be past; built=V3; in 1900=время", "Past Passive."),
        mc("Glass ___ from sand.", ["makes", "is made", "made"], "is made", "Present Passive."),
        fill("The windows ___ broken in the storm. (be)", "were", "were + V3."),
        order("Соберите: is / spoken / English / here", "English is spoken here.", "S + is + V3."),
        err("The cake were eaten.", "The cake was eaten.", "Ед. — was."),
    ],
    "adverbs-frequency-manner": [
        fill("He ___ forgets my birthday. (never)", "never", "Частота перед V."),
        mc("Please drive ___.", ["careful", "carefully", "carefulness"], "carefully", "Manner."),
        err("She speaks English very good.", "She speaks English very well.", "well, не good."),
        xf("Переставьте: sometimes / late / is / the / bus", "The bus is sometimes late.", "be + частота."),
        fill("They work ___. (hard)", "hard", "hard — одна форма."),
        match("Частота", ["always", "often", "rarely"], "always=всегда; often=часто; rarely=редко", "Шкала."),
        mc("I can ___ hear you.", ["hard", "hardly", "hardily"], "hardly", "hardly = едва."),
        fill("She smiled ___. (happy)", "happily", "adj → adv."),
        order("Соберите: quietly / opened / he / the / door", "He opened the door quietly.", "V + O + manner."),
        err("We go usually there.", "We usually go there.", "Частота перед смысловым V."),
    ],
    "word-order-a2": [
        order("Соберите: already / have / they / left", "They have already left.", "have + already + V3."),
        fill("I haven't seen her ___.", "yet", "yet в отрицании."),
        mc("Выберите верное:", ["Where you have been?", "Where have you been?", "Where have been you?"], "Where have you been?", "Wh + have + S."),
        err("She didn't went.", "She didn't go.", "Didn't + V1."),
        xf("Passive порядок: cleaned / is / room / the", "The room is cleaned.", "S + be + V3."),
        fill("If you call, I ___ answer.", "will", "will во 2-й части."),
        match("A2 порядок", ["Have", "you", "finished"], "Have=aux; you=S; finished=V3", "Perfect вопрос."),
        order("Слова: carefully / check / please / the / form", "Please check the form carefully.", "V + O + manner."),
        fill("He is ___ taller than his brother.", "much", "much + comparative.", ["far"]),
        err("Always she is busy.", "She is always busy.", "Частота после be."),
    ],
}
