"""On-topic practice/test pads keyed by module slug.

CEFR-wide generic pads used to inject the same tips into every thin module
(e.g. «I am agree» into articles). These banks keep variety but stay on-topic.
"""

from __future__ import annotations

from app.seed.helpers import err, fill, match, mc, order, xf

# ---------------------------------------------------------------------------
# Legacy CEFR-wide pad prompts (for scrubbing existing DBs). Do not re-inject
# unless the prompt is also listed under TOPIC_* for that slug.
# ---------------------------------------------------------------------------

LEGACY_GENERIC_PRACTICE_PROMPTS: frozenset[str] = frozenset(
    {
        "I ___ a student.",
        "She ___ my sister. (be)",
        "He don't like tea.",
        "Соберите: name / is / my / Anna",
        "They ___ from Spain. (be)",
        "___ you ready?",
        "Сделайте вопрос: You speak English.",
        "There ___ a book on the table.",
        "She can sings.",
        "Местоимения",
        "Вставьте вспомогательный глагол: We ___ breakfast at 8. (have)",
        "Слова: the / park / in / play / children",
        "This is ___ bag.",
        "___ is cold today.",
        "I am agree.",
        "She ___ TV when I called.",
        "Вставьте have/has (Present Perfect): I ___ already finished.",
        "Вставьте have/has (Present Perfect): I ___ already finished.",
        "He go to school every day.",
        "Соберите: than / bigger / is / this / that",
        "If it rains, we ___ stay home. (will)",
        "There isn't ___ milk.",
        "Сделайте отрицание: She can drive.",
        "He used ___ live here.",
        "She is knowing the answer.",
        "Сравните",
        "I wish I ___ taller.",
        "By 2019 they ___ left. (have)",
        "If I will see him, I will call.",
        "Соберите: been / have / waiting / I / for hours",
        "You ___ be tired after that trip. (must)",
        "She asked where I ___.",
        "Passive: They built the bridge.",
        "Перепишите в Passive: They built the bridge.",
        "I'd rather you ___ now. (leave)",
        "He suggested to go.",
        "Wish",
        "Not only ___ late, he forgot the key.",
        "I'd sooner ___ at home. (stay)",
        "Вставьте форму после I'd sooner: I'd sooner ___ at home. (stay)",
        "Despite of the rain, we went.",
        "Соберите: had / I / known / I / would have called",
        "She is thought ___ be abroad. (to)",
        "It's time we ___.",
        "Causative: Someone cleaned my car.",
        "Перепишите в causative (have/get something done): Someone cleaned my car.",
        "Little ___ she know the truth. (do, past)",
        "I look forward to meet you.",
        "Инверсия",
        "Were it not ___ the delay, we would start.",
        "It is essential that he ___ on time. (be)",
        "I regret to tell you this earlier.",
        "Соберите: so / complex / was / the / plan / that / we / paused",
        "Far ___ it from me to insist. (be)",
        "On no account ___ you open that.",
        "Nominalise: They refused → their ___",
        "Сделайте номинализацию: They refused → their ___",
        "Such ___ the noise that we left. (be)",
        "She explained me the rule.",
        "Fronting",
        "___ that as it may, we proceed.",
        "Suffice ___ to say we disagreed.",
        "The data is conflicting each other.",
        "Соберите: hard / as / tried / she / she / failed",
        "Выберите may в идиоме Come what ___: Come what ___, we finish tonight.",
        "He is as brilliant a writer ___ she is.",
        "Inversion: If she had known → ___ she known",
        "Strange ___ it seem, it worked. (as)",
        "I can't help to laugh.",
        "Hedges",
    }
)

LEGACY_GENERIC_TEST_PROMPTS: frozenset[str] = frozenset(
    {
        "Вставьте нужную форму (he): ___ name is Tom. (he)",
        "There ___ two chairs.",
        "She haven't a car.",
        "Соберите: like / I / apples",
        "Вставьте нужную форму (help): Can you ___ me? (help)",
        "Вставьте вопросительное / относительное слово: ___ is your phone?",
        "Отрицание: I can swim.",
        "Вставьте предлог: The keys are ___ the table.",
        "He living in Rome.",
        "Be",
        "Вставьте вспомогательный глагол: ___ you got a pen?",
        "Слова: bus / the / takes / she",
        "Выберите форму to be: These ___ my books.",
        "Вставьте нужную форму (close): Please ___ the door. (close)",
        "I no understand.",
        "Вставьте вспомогательный глагол: She ___ just left. (have)",
        "Вставьте форму Past Continuous: While I ___, the phone rang.",
        "I am going to the gym every Monday.",
        "Соберите: will / if / you / ask / I / help",
        "This bag is ___ than that one. (light)",
        "How ___ sugar do you need?",
        "Passive: They clean the room.",
        "Перепишите в Passive: They clean the room.",
        "You ___ park here. (mustn't)",
        "She didn't went.",
        "Quantifiers",
        "She said she ___ tired. (be, past)",
        "If I ___ rich, I would travel.",
        "He has went home.",
        "Соберите: been / she / has / working / all day",
        "The letter ___ sent yesterday. (be)",
        "I wish it ___ raining.",
        "'I am busy' → He said he ___ busy.",
        "Косвенная речь: вставьте сдвиг времени: 'I am busy' → He said he ___ busy.",
        "You look tired. You ___ have slept badly. (must)",
        "She avoid to talk.",
        "Relative",
        "No sooner ___ we arrived than it rained. (have)",
        "I'd prefer ___ alone.",
        "He is used to wake up early.",
        "Соберите: should / under / no / circumstances / you / lie",
        "She had the report ___ . (write, causative)",
        "Выберите пропущенное слово: It's high time you ___.",
        "Reporting: 'Don't go' → He told me ___ go.",
        "Hardly ___ the film started when the lights failed. (have)",
        "I suggested her to wait.",
        "Causative",
        "Вставьте may: Be that as it ___, we continue.",
        "Вставьте may: Be that as it ___, we continue.",
        "___ the cost, the project went ahead.",
        "I demand that he leaves now.",
        "Соберите: known / had / we / we / would have waited",
        "It was suggested that the plan ___ revised. (be)",
        "Выберите пропущенное слово: Only then ___ the mistake.",
        "Noun: decide → ___",
        "Such ___ his anger that he left. (be)",
        "She congratulated me to win.",
        "Emphasis",
        "Try as she ___, she couldn't open it.",
        "Выберите модальный глагол should: ___ it rain, the event moves indoors.",
        "The committee have not yet reached its decision.",
        "Соберите: though / brilliant / the / idea / was / it / failed",
        "Вставьте пропущенное слово: Suffice ___ to say the talks stalled.",
        "Выберите форму to be: He spoke as if he ___ the owner.",
        "Сделайте фронтирование PP + инверсию: The yacht sailed into the bay. → Into the bay ___ the yacht.",
        "Come what ___, keep the channel open.",
        "I resent to be ignored.",
        "Concession",
    }
)

# Prompts that must never appear in any grammar module (false-friend tips / orphan tips).
BANNED_PROMPTS: frozenset[str] = frozenset(
    {
        "I am agree.",
    }
)


# ---------------------------------------------------------------------------
# A1 topic pads
# ---------------------------------------------------------------------------

TOPIC_PRACTICE: dict[str, list] = {
    "to-be": [
        mc("I ___ a student.", ["am", "is", "are"], "am", "I + am."),
        fill("She ___ my sister. (be)", "is", "She + is."),
        order("Соберите: name / is / my / Anna", "My name is Anna.", "Притяжательное + N + be."),
        fill("They ___ from Spain. (be)", "are", "They + are."),
        mc("___ you ready?", ["Is", "Are", "Am"], "Are", "You + are."),
        fill("___ is cold today.", "It", "Погода — It + be."),
        match("Формы be", ["I", "he", "they"], "I=am; he=is; they=are", "Согласование be."),
        err("He are tired.", "He is tired.", "He + is."),
        fill("We ___ not late. (be)", "are", "We + are.", ["aren't", "are not"]),
        xf("Сделайте вопрос: She is a doctor.", "Is she a doctor?", "Be перед подлежащим."),
    ],
    "pronouns-possessives": [
        mc("This is ___ bag.", ["me", "my", "mine"], "my", "my + N."),
        fill("Вставьте нужную форму (he): ___ name is Tom. (he)", "His", "His + N."),
        err("This is me book.", "This is my book.", "Нужно притяжательное my."),
        match("Местоимения", ["I", "he", "they"], "I=я; he=он; they=они", "Базовые forms."),
        fill("The bag is ___. (she)", "hers", "hers без существительного."),
        mc("___ are students.", ["We", "Our", "Us"], "We", "Подлежащее."),
        order("Соберите: is / car / her / this", "This is her car.", "her + N."),
        xf("Напишите притяжательное перед существительным: I → ?", "my", "I → my."),
        fill("Вставьте нужную форму (you): Is this pen ___? (you)", "yours", "yours без N."),
        err("Its raining. (погода)", "It's raining.", "it's = it is."),
    ],
    "demonstratives": [
        mc("___ book is mine. (рядом, одно)", ["These", "This", "Those"], "This", "Близко + ед.ч."),
        fill("___ shoes are new. (здесь)", "These", "Близко + мн.ч."),
        err("That cars are expensive.", "Those cars are expensive.", "Мн.ч. → those."),
        order("Соберите: is / that / my / umbrella", "That is my umbrella.", "That + is + …"),
        fill("I don't like ___ music. (та, издалека)", "that", "Далеко + ед.ч."),
        mc("Look at ___ birds over there!", ["this", "these", "those"], "those", "Далеко + мн."),
        xf("Сделайте множественное число: this box → ?", "these boxes", "this→these."),
        match("Указательные", ["this", "these", "those"], "this=близко ед.; these=близко мн.; those=далеко мн.", "Дистанция и число."),
        fill("___ is a good idea.", "This", "Ед.ч. рядом."),
        err("These is my friend.", "This is my friend.", "Один друг — this is."),
    ],
    "present-simple": [
        err("He don't like tea.", "He doesn't like tea.", "He/she + doesn't."),
        xf("Сделайте вопрос: You speak English.", "Do you speak English?", "Do + S + V1."),
        fill("Вставьте вспомогательный глагол: We ___ breakfast at 8. (have)", "have", "We + have."),
        order("Слова: the / park / in / play / children", "Children play in the park.", "S + V + place."),
        err("She go to work by bus.", "She goes to work by bus.", "3sg + -s."),
        mc("___ he play football?", ["Do", "Does", "Is"], "Does", "He + Does."),
        fill("They ___ not eat meat.", "do", "don't = do not.", ["don't"]),
        match("Present Simple", ["She", "works", "here"], "She=S; works=V; here=place", "S+V+place."),
        xf("Отрицание: I like coffee.", "I don't like coffee.", "don't + V1.", ["I do not like coffee."]),
        fill("The shop ___ at 9. (open)", "opens", "Расписание + 3sg."),
    ],
    "present-continuous": [
        fill("Quiet! The baby ___ . (sleep)", "is sleeping", "Сейчас — Continuous."),
        mc("They ___ lunch right now.", ["have", "are having", "has"], "are having", "right now."),
        err("I working at the moment.", "I am working at the moment.", "Нужен am/is/are."),
        xf("Вопрос: She is reading.", "Is she reading?", "Be на первое место."),
        fill("We ___ not ___ TV now. (watch)", "are not watching", "are + not + V-ing.", ["aren't watching"]),
        mc("Look! It ___.", ["rains", "is raining", "rain"], "is raining", "Look! → Continuous."),
        order("Соберите: are / waiting / you / for me", "Are you waiting for me?", "Be + S + V-ing."),
        match("Continuous", ["am", "writing", "now"], "am=be; writing=V-ing; now=marker", "be + V-ing."),
        err("He are playing outside.", "He is playing outside.", "He + is."),
        fill("She ___ with us this week. (stay)", "is staying", "Временная ситуация."),
    ],
    "there-is-are": [
        fill("There ___ a book on the table.", "is", "There is + ед.ч."),
        mc("There ___ two bags.", ["is", "are", "be"], "are", "There are + мн."),
        err("There is five chairs.", "There are five chairs.", "Мн.ч. → are."),
        xf("Вопрос: There is a café here.", "Is there a café here?", "Is there…?"),
        fill("There ___ any milk. (отриц.)", "isn't", "Неисчисляемое — isn't.", ["is not"]),
        order("Соберите: are / there / any / tickets", "Are there any tickets?", "Are there + any."),
        match("There", ["There is", "a lamp", "There are"], "There is=ед.; a lamp=ед.; There are=мн.", "Согласование."),
        mc("___ there a message?", ["Is", "Are", "Do"], "Is", "Ед.ч."),
        fill("There ___ some apples.", "are", "Мн.ч. + some."),
        err("It is a park near here.", "There is a park near here.", "Существование — there is."),
    ],
    "can-ability": [
        err("She can sings.", "She can sing.", "После can — V1."),
        xf("Сделайте отрицание: She can drive.", "She can't drive.", "can't + V1.", ["She cannot drive."]),
        fill("___ you swim?", "Can", "Can + S + V1?"),
        mc("I ___ speak Italian.", ["can", "cans", "am can"], "can", "Can не меняется."),
        err("We can to help.", "We can help.", "После can нет to."),
        order("Соберите: can / she / dance", "Can she dance?", "Can + S + V."),
        fill("They ___ not come today. (can)", "can", "can + not.", ["can't"]),
        match("Can", ["can", "swim", "well"], "can=modal; swim=V1; well=наречие", "Модальный + голый инфинитив."),
        mc("He ___ drive, but she ___.", ["can / can't", "cans / can't", "can / doesn't can"], "can / can't", "Одна форма can."),
        fill("Вставьте модальный глагол can: Birds ___ fly.", "can", "Способность."),
    ],
    "imperatives": [
        mc("___ down, please.", ["Sits", "Sit", "Sitting"], "Sit", "Императив — V1."),
        fill("___ open the window. (запрет)", "Don't", "Don't + V."),
        err("To come here.", "Come here.", "Без to."),
        order("Соберите: the / door / close", "Close the door.", "V + object."),
        fill("___ go home. (вместе)", "Let's", "Let's + V."),
        xf("Запрет: Touch the wire.", "Don't touch the wire.", "Don't + V."),
        match("Императив", ["Open", "the book", "please"], "Open=V; the book=O; please=вежливость", "Просьба."),
        mc("Please ___ me.", ["helps", "help", "helping"], "help", "Please + V1."),
        fill("___ careful with that.", "Be", "Be + adj."),
        err("Let's to start.", "Let's start.", "После let's нет to."),
    ],
    "question-words": [
        mc("___ do you live?", ["When", "Where", "Who"], "Where", "Место — where."),
        fill("___ is your name?", "What", "What + be."),
        err("Why you are sad?", "Why are you sad?", "Wh + be + S."),
        xf("Спросите о времени: The train leaves.", "When does the train leave?", "When + does + S + V."),
        fill("___ bag is this?", "Whose", "Чей."),
        mc("___ many sisters have you got?", ["How", "What", "Which"], "How", "How many."),
        order("Соберите: where / you / do / work", "Where do you work?", "Wh + do + S + V."),
        match("Wh-слова", ["who", "where", "when"], "who=кто; where=где; when=когда", "Базовый набор."),
        fill("___ one do you want, red or blue?", "Which", "Выбор из набора."),
        err("What you doing?", "What are you doing?", "Нужен be в Continuous."),
    ],
    "prepositions-place": [
        mc("The cat is ___ the box.", ["on", "in", "at"], "in", "Внутри — in."),
        fill("The picture is ___ the wall.", "on", "На поверхности — on."),
        err("She is in home.", "She is at home.", "at home."),
        fill("Meet me ___ the station.", "at", "Точка — at."),
        mc("The café is ___ the bank and the shop.", ["between", "next", "under"], "between", "Между."),
        order("Соберите: under / the / are / keys / chair / the", "The keys are under the chair.", "S + be + prep."),
        xf("Рядом с парком: The hotel is ___ the park.", "The hotel is next to the park.", "next to."),
        match("Место", ["in", "on", "at"], "in=внутри; on=на; at=точка", "Базовая тройка."),
        fill("He sits ___ me.", "next to", "Рядом.", ["beside"]),
        err("The book is in the table.", "The book is on the table.", "На поверхности — on."),
    ],
    "prepositions-time": [
        mc("See you ___ Monday.", ["in", "on", "at"], "on", "День — on."),
        fill("The film starts ___ 8.", "at", "Часы — at."),
        err("I was born on 1999.", "I was born in 1999.", "Год — in."),
        fill("We met ___ the morning.", "in", "in the morning."),
        mc("She called me ___ night.", ["in", "on", "at"], "at", "at night."),
        order("Соберите: on / birthday / my / is / party / the", "The party is on my birthday.", "on + дата/день."),
        xf("В июле: We travel ___ July.", "We travel in July.", "Месяц — in."),
        match("Время", ["at 7", "on Friday", "in May"], "at 7=часы; on Friday=день; in May=месяц", "at/on/in."),
        fill("I'll be back ___ two weeks.", "in", "Через период — in."),
        err("The class ends on 5 p.m.", "The class ends at 5 p.m.", "Часы — at."),
    ],
    "have-got": [
        fill("I ___ got two brothers.", "have", "I have got."),
        mc("___ she got a bike?", ["Have", "Has", "Does"], "Has", "Has she got…"),
        err("He haven't got a pen.", "He hasn't got a pen.", "He + hasn't got."),
        xf("Отрицание: We have got time.", "We haven't got time.", "haven't got."),
        fill("She ___ got long hair.", "has", "She has got."),
        mc("I ___ breakfast at 8.", ["have got", "have", "has got"], "have", "Приём пищи — have."),
        order("Соберите: got / you / have / a / minute", "Have you got a minute?", "Have you got…"),
        match("Have got", ["I've got", "a car", "She hasn't got"], "I've got=утв.; a car=объект; She hasn't got=отриц.", "Владение."),
        fill("They ___ got any milk.", "haven't", "Отрицание для they."),
        err("Do you have got a map?", "Have you got a map?", "Не смешивайте do и have got."),
    ],
    "past-simple-be": [
        fill("I ___ at home yesterday.", "was", "I + was."),
        mc("They ___ happy.", ["was", "were", "are"], "were", "They + were."),
        err("Was you tired?", "Were you tired?", "You + were."),
        xf("Отрицание: He was late.", "He wasn't late.", "wasn't.", ["He was not late."]),
        fill("___ she at the party?", "Was", "Was + she…"),
        mc("We ___ not ready.", ["was", "were", "did"], "were", "We were not."),
        order("Соберите: were / where / you", "Where were you?", "Wh + were + S."),
        match("Was/were", ["I", "you", "it"], "I=was; you=were; it=was", "Прошедшее be."),
        fill("It ___ cold last night.", "was", "It + was."),
        err("They was in London.", "They were in London.", "They + were."),
    ],
    "going-to": [
        fill("I ___ going to call her.", "am", "I am going to."),
        mc("Look at the clouds! It ___ rain.", ["goes to", "is going to", "will going"], "is going to", "Примета."),
        err("We going to move.", "We are going to move.", "Нужен are."),
        xf("Вопрос: She is going to cook.", "Is she going to cook?", "Is + she + going to."),
        fill("They are not ___ to stay.", "going", "be + going to."),
        mc("___ you going to help?", ["Is", "Are", "Do"], "Are", "Are you going to…"),
        order("Соберите: to / going / buy / is / he / a car", "He is going to buy a car.", "be + going to + V."),
        match("Going to", ["am", "going to", "start"], "am=be; going to=marker; start=V", "Намерение."),
        fill("She ___ going to be a nurse.", "is", "She is going to."),
        err("He is go to leave.", "He is going to leave.", "going to + V."),
    ],
    "adjectives-a1": [
        mc("It's a ___ day.", ["nice", "nicely", "nices"], "nice", "Прилагательное без -ly здесь."),
        fill("She looks ___. (tired)", "tired", "look + adj."),
        err("a house big", "a big house", "Adj перед N."),
        xf("Соберите: red / small / car", "a small red car", "размер → цвет."),
        fill("The soup tastes ___. (good)", "good", "taste + adj."),
        mc("These bags are ___.", ["heavy", "heavies", "heavily"], "heavy", "Без -s."),
        order("Соберите: interesting / really / film / an", "a really interesting film", "усилитель + adj."),
        match("Прилагательные", ["tall", "happy", "new"], "tall=рост; happy=настроение; new=возраст", "Качества."),
        fill("It's ___ cold today.", "very", "very + adj.", ["really"]),
        err("two olds cars", "two old cars", "Прилагательное не получает -s."),
    ],
    "word-order-a1": [
        order("Соберите: she / tea / drinks / often", "She often drinks tea.", "S + частота + V."),
        fill("They ___ in London. (live)", "live", "S + V + place."),
        mc("Правильный порядок:", ["Likes she coffee?", "Does she like coffee?", "She does like coffee?"], "Does she like coffee?", "Do/Does + S + V1."),
        err("I every day go there.", "I go there every day.", "Частота в конце или перед V."),
        order("Слова: is / the / on / book / table / the", "The book is on the table.", "S + be + prep + place."),
        fill("___ you speak English?", "Do", "Do + you + V1."),
        xf("Переставьте: rarely / he / smiles", "He rarely smiles.", "Наречие частоты перед смысловым V."),
        match("Части предложения", ["She", "reads", "books"], "She=S; reads=V; books=O", "SVO."),
        fill("We ___ breakfast at home. (have)", "have", "S + V + O + place."),
        err("Goes he to school?", "Does he go to school?", "Do/Does в вопросе."),
    ],
}

TOPIC_TEST: dict[str, list] = {
    "to-be": [
        fill("Вставьте форму to be: He ___ a teacher. (be)", "is", "He + is."),
        mc("Выберите форму to be: These ___ my books.", ["is", "are", "am"], "are", "These + are."),
        err("You is late.", "You are late.", "You + are."),
        order("Соберите: from / are / they / Spain", "They are from Spain.", "S + are + prep."),
        match("Be", ["I", "she", "we"], "I=am; she=is; we=are", "Согласование be."),
        fill("Вставьте форму to be: ___ they ready?", "Are", "Are + they."),
        mc("Выберите форму to be: ___ she a doctor?", ["Is", "Are", "Am"], "Is", "She + Is."),
        xf("Отрицание: We are ready.", "We are not ready.", "not после are.", ["We're not ready.", "We aren't ready."]),
        fill("Вставьте форму to be: I ___ not hungry.", "am", "I am not."),
        err("They is at home.", "They are at home.", "They + are."),
    ],
    "pronouns-possessives": [
        fill("Вставьте нужную форму (he): ___ name is Tom. (he)", "His", "His + N."),
        mc("Выберите местоимение: The keys are ___.", ["our", "ours", "us"], "ours", "Без N — ours."),
        err("This is she's bag.", "This is her bag.", "her + N."),
        xf("Напишите притяжательное перед существительным: they → ?", "their", "they → their."),
        fill("Вставьте нужную форму (I): Is this cup ___? (I)", "mine", "mine."),
        match("Притяжательные", ["my", "your", "his"], "my=мой; your=твой; his=его", "Перед N."),
        mc("Выберите местоимение: ___ live in Berlin.", ["They", "Their", "Them"], "They", "Подлежащее."),
        fill("Вставьте местоимение: We like ___ new flat.", "our", "our + N."),
        order("Соберите: is / mine / this / pen", "This pen is mine.", "N + be + mine."),
        err("Him name is Paul.", "His name is Paul.", "His, не him."),
    ],
    "demonstratives": [
        fill("Вставьте нужную форму (рядом): ___ flowers smell nice. (рядом)", "These", "Близко + мн."),
        mc("Выберите вопросительное / относительное слово: ___ building over there is new.", ["This", "That", "These"], "That", "Далеко + ед."),
        err("This are my parents.", "These are my parents.", "Мн. — these are."),
        xf("Сделайте единственное число: those men → ?", "that man", "those→that."),
        fill("Вставьте вопросительное / относительное слово: Can you see ___ star?", "that", "Далеко."),
        match("this/that", ["this", "that", "these"], "this=близко ед.; that=далеко ед.; these=близко мн.", "Дистанция."),
        mc("Выберите нужную форму (ближайшая): I prefer ___ option. (ближайшая)", ["that", "this", "those"], "this", "Близко."),
        fill("Вставьте нужную форму (здесь): ___ are my friends from work. (здесь)", "These", "Близко + мн."),
        order("Соберите: those / expensive / are / shoes", "Those shoes are expensive.", "those + N + be."),
        err("That are nice photos.", "Those are nice photos.", "Мн. — those."),
    ],
    "present-simple": [
        fill("Вставьте нужную форму (go): She ___ to school by bike. (go)", "goes", "3sg -es."),
        mc("Выберите вспомогательный глагол: ___ they work here?", ["Does", "Do", "Are"], "Do", "They + Do."),
        err("He living in Rome.", "He lives in Rome.", "Привычка — Simple."),
        xf("Отрицание: She plays tennis.", "She doesn't play tennis.", "doesn't + V1.", ["She does not play tennis."]),
        fill("Вставьте нужную форму (drink): I ___ coffee every morning. (drink)", "drink", "I + V1."),
        match("do/does", ["Do", "you", "swim"], "Do=aux; you=S; swim=V", "Вопрос."),
        mc("Выберите форму Present Simple: The sun ___ in the east.", ["rise", "rises", "is rise"], "rises", "Факт + 3sg."),
        fill("Вставьте вспомогательный глагол: We ___ not watch TV much.", "do", "don't.", ["don't"]),
        order("Соберите: always / early / she / arrives", "She always arrives early.", "S + frequency + V."),
        err("Does they like pizza?", "Do they like pizza?", "They + Do."),
    ],
    "present-continuous": [
        fill("Вставьте нужную форму (have): He ___ a shower now. (have)", "is having", "now → Continuous."),
        mc("Выберите форму to be: ___ you wearing a coat?", ["Do", "Are", "Is"], "Are", "Are + V-ing."),
        err("They watching a film.", "They are watching a film.", "Нужен are."),
        xf("Отрицание: I'm cooking.", "I'm not cooking.", "not после be.", ["I am not cooking."]),
        fill("Вставьте нужную форму (rain): It ___ hard at the moment. (rain)", "is raining", "at the moment."),
        match("Сейчас", ["is", "running", "now"], "is=be; running=V-ing; now=маркер", "Continuous."),
        mc("Выберите нужную форму (временный план на вечер): We ___ dinner tonight at home. (временный план на вечер)", ["cook", "are cooking", "cooks"], "are cooking", "Временная ситуация."),
        fill("Вставьте нужную форму (work): She ___ not ___ today. (work)", "is not working", "is + not + V-ing.", ["isn't working"]),
        order("Соберите: listening / is / music / to / she", "She is listening to music.", "S + be + V-ing."),
        err("Is they sleeping?", "Are they sleeping?", "They + Are."),
    ],
    "there-is-are": [
        fill("Вставьте there is/are: ___ a pharmacy nearby?", "Is there", "Ед.ч. вопрос."),
        mc("Выберите форму to be: There ___ some water.", ["is", "are", "be"], "is", "Неисчисляемое."),
        err("There aren't a problem.", "There isn't a problem.", "Ед. — isn't."),
        xf("Отрицание: There are some eggs.", "There aren't any eggs.", "aren't + any.", ["There are not any eggs."]),
        fill("Вставьте форму to be: There ___ three rooms.", "are", "Мн.ч."),
        match("Согласование", ["is", "are", "a book"], "is=ед.; are=мн.; a book=ед. объект", "There + be."),
        mc("Выберите форму to be: ___ there any emails?", ["Is", "Are", "Do"], "Are", "Emails — мн."),
        fill("Вставьте форму to be: There ___ no time.", "is", "Time неисчисляемое."),
        order("Соберите: is / there / on / a / plate / the / apple", "There is an apple on the plate.", "There is + N + place."),
        err("Are there a bus?", "Is there a bus?", "A bus — ед."),
    ],
    "can-ability": [
        fill("Вставьте нужную форму (help): Can you ___ me? (help)", "help", "can + V1."),
        mc("Выберите модальный глагол can: She ___ ski very well.", ["cans", "can", "is can"], "can", "Без -s."),
        err("He cans cook well.", "He can cook well.", "Нет формы cans."),
        xf("Отрицание: I can swim.", "I can't swim.", "can't.", ["I cannot swim."]),
        fill("Вставьте модальный глагол can: ___ I open the window?", "Can", "Разрешение."),
        match("Форма", ["can", "not", "drive"], "can=modal; not=отриц.; drive=V1", "can't drive."),
        mc("Выберите модальный глагол can: We ___ hear the music.", ["can't", "don't can", "aren't can"], "can't", "Отрицание."),
        fill("Вставьте модальный глагол can: He ___ speak three languages.", "can", "Способность."),
        order("Соберите: can / fast / run / they", "They can run fast.", "S + can + V."),
        err("Can she to cook?", "Can she cook?", "Без to."),
    ],
    "imperatives": [
        fill("Вставьте нужную форму (close): Please ___ the door. (close)", "close", "Императив."),
        mc("Выберите вспомогательный глагол: ___ talk during the exam.", ["Don't", "Doesn't", "Not"], "Don't", "Запрет."),
        err("Opening your books.", "Open your books.", "V1, не -ing."),
        xf("Запрет: Be late.", "Don't be late.", "Don't + be."),
        fill("Вставьте нужную форму (вместе): ___ start now. (вместе)", "Let's", "Let's."),
        match("Команда", ["Turn", "left", "please"], "Turn=V; left=направление; please=вежливость", "Инструкция."),
        mc("Выберите вспомогательный глагол: ___ your homework.", ["Does", "Do", "Doing"], "Do", "Do + N."),
        fill("Вставьте форму to be: ___ quiet, please.", "Be", "Be + adj."),
        order("Соберите: wait / here / don't", "Don't wait here.", "Don't + V + place."),
        err("Please to sit down.", "Please sit down.", "Без to."),
    ],
    "question-words": [
        fill("Вставьте вопросительное / относительное слово: ___ is your phone?", "Where", "Место."),
        mc("Выберите вопросительное / относительное слово: ___ did you call?", ["Who", "Whose", "Which"], "Who", "Кто."),
        err("When you arrive?", "When do you arrive?", "Нужен do."),
        xf("Спросите о причине: She is angry.", "Why is she angry?", "Why + be + S."),
        fill("Вставьте вопросительное / относительное слово: ___ much is this?", "How", "How much."),
        match("Вопросы", ["what", "why", "how"], "what=что; why=почему; how=как", "Wh-слова."),
        mc("Выберите вопросительное / относительное слово: ___ coat is on the chair?", ["Who", "Whose", "Whom"], "Whose", "Чей."),
        fill("Вставьте вопросительное / относительное слово: ___ are you from?", "Where", "Where from."),
        order("Соберите: what / want / you / do", "What do you want?", "Wh + do + S + V."),
        err("How many milk do you need?", "How much milk do you need?", "Неисчисляемое — much."),
    ],
    "prepositions-place": [
        fill("Вставьте предлог: The keys are ___ the table.", "on", "on + surface."),
        mc("Выберите предлог: She works ___ the hospital.", ["on", "in", "at"], "in", "in + building (внутри).", ["at"]),
        err("They live at Paris.", "They live in Paris.", "Город — in."),
        xf("За шкафом: The bag is ___ the wardrobe.", "The bag is behind the wardrobe.", "behind."),
        fill("Вставьте предлог: The dog is ___ the sofa.", "under", "under."),
        match("Предлоги", ["in", "on", "under"], "in=в; on=на; under=под", "Место."),
        mc("Выберите предлог: Wait ___ the entrance.", ["in", "on", "at"], "at", "Точка."),
        fill("Вставьте предлог: He stands ___ the door.", "at", "at the door.", ["by"]),
        order("Соберите: next / bank / the / to / is / shop / the", "The shop is next to the bank.", "next to."),
        err("I am on school now.", "I am at school now.", "at school."),
    ],
    "prepositions-time": [
        fill("Вставьте предлог: The meeting is ___ Friday.", "on", "День — on."),
        mc("Выберите предлог: I get up ___ 7 a.m.", ["in", "on", "at"], "at", "Часы — at."),
        err("See you in Saturday.", "See you on Saturday.", "День — on."),
        xf("В 2020: She finished school ___ 2020.", "She finished school in 2020.", "Год — in."),
        fill("Вставьте предлог: He jogs ___ the evening.", "in", "in the evening."),
        match("Время", ["at noon", "on Tuesday", "in winter"], "at noon=точка; on Tuesday=день; in winter=период", "at/on/in."),
        mc("Выберите предлог: We arrived ___ midnight.", ["in", "on", "at"], "at", "at midnight."),
        fill("Вставьте предлог: Her birthday is ___ 12 June.", "on", "Дата — on."),
        order("Соберите: in / July / holiday / our / is", "Our holiday is in July.", "in + месяц."),
        err("The shop opens on 9.", "The shop opens at 9.", "Часы — at."),
    ],
    "have-got": [
        fill("Вставьте вспомогательный глагол: ___ you got a pen?", "Have", "Have you got…"),
        mc("Выберите вспомогательный глагол: She ___ got blue eyes.", ["have", "has", "is"], "has", "has got."),
        err("I has got a dog.", "I have got a dog.", "I + have got."),
        xf("Краткая: She has got a map.", "She's got a map.", "She's got."),
        fill("Вставьте вспомогательный глагол: We ___ got much money.", "haven't", "haven't got."),
        match("Владение", ["have got", "has got", "haven't got"], "have got=I/you/we; has got=he/she; haven't got=отриц.", "Формы."),
        mc("Выберите вспомогательный глагол: ___ he got your email?", ["Have", "Has", "Does"], "Has", "Has he got…"),
        fill("Вставьте вспомогательный глагол: I ___ a shower after work.", "have", "have a shower."),
        order("Соберите: got / hasn't / she / a / ticket", "She hasn't got a ticket.", "hasn't got."),
        err("They hasn't got time.", "They haven't got time.", "They + haven't."),
    ],
    "past-simple-be": [
        fill("Вставьте форму to be: She ___ in Madrid last year.", "was", "She + was."),
        mc("Выберите форму to be: ___ you at home?", ["Was", "Were", "Did"], "Were", "You + Were."),
        err("I were hungry.", "I was hungry.", "I + was."),
        xf("Вопрос: They were friends.", "Were they friends?", "Were + they."),
        fill("Вставьте форму to be: It ___ not easy.", "was", "wasn't.", ["wasn't"]),
        match("Прошедшее be", ["was", "were", "wasn't"], "was=I/he/she/it; were=you/we/they; wasn't=отриц.", "Формы."),
        mc("Выберите форму to be: We ___ on holiday in May.", ["was", "were", "are"], "were", "We + were."),
        fill("Вставьте форму to be: ___ he late again?", "Was", "Was he…"),
        order("Соберите: weren't / they / ready", "They weren't ready.", "weren't."),
        err("Did she was there?", "Was she there?", "Без did."),
    ],
    "going-to": [
        fill("Вставьте форму to be: We ___ going to travel in June.", "are", "We are going to."),
        mc("Выберите форму to be: He ___ going to study law.", ["am", "is", "are"], "is", "He + is."),
        err("I going to buy milk.", "I am going to buy milk.", "Нужен am."),
        xf("Отрицание: They're going to wait.", "They're not going to wait.", "not после be.", ["They aren't going to wait.", "They are not going to wait."]),
        fill("Вставьте форму to be: ___ she going to call?", "Is", "Is she going to…"),
        match("План", ["are", "going to", "visit"], "are=be; going to=маркер; visit=V", "be going to."),
        mc("Выберите форму to be: It ___ going to snow.", ["am", "is", "are"], "is", "It + is."),
        fill("Вставьте be going to: You are ___ to love this film.", "going", "going to + V."),
        order("Соберите: going / am / I / to / rest", "I am going to rest.", "I am going to + V."),
        err("Are he going to come?", "Is he going to come?", "He + Is."),
    ],
    "adjectives-a1": [
        fill("Вставьте нужную форму (clean): The room is ___. (clean)", "clean", "be + adj."),
        mc("Выберите прилагательное: They bought a ___ car.", ["new", "newly", "news"], "new", "Adj перед N."),
        err("She is a teacher good.", "She is a good teacher.", "Adj перед N."),
        xf("очень / tall / he / is", "He is very tall.", "very + adj."),
        fill("Вставьте нужную форму (cold): I feel ___. (cold)", "cold", "feel + adj."),
        match("Описание", ["big", "old", "happy"], "big=размер; old=возраст; happy=состояние", "Adj."),
        mc("Выберите прилагательное: It's a ___ story.", ["sad", "sadly", "sads"], "sad", "Adj."),
        fill("Вставьте нужную форму (great): The coffee smells ___. (great)", "great", "smell + adj."),
        order("Соберите: blue / beautiful / a / dress", "a beautiful blue dress", "мнение → цвет."),
        err("The children are happies.", "The children are happy.", "Без -s."),
    ],
    "word-order-a1": [
        order("Соберите: usually / breakfast / I / eat / at 8", "I usually eat breakfast at 8.", "S + frequency + V + O + time."),
        fill("Выберите вспомогательный глагол: ___ she work here?", "Does", "Does + he/she + V1."),
        mc("Выберите верное:", ["Where you live?", "Where do you live?", "Where live you?"], "Where do you live?", "Wh + do + S + V."),
        err("Speaks he French?", "Does he speak French?", "Do/Does в вопросе."),
        order("Слова: never / late / is / she", "She is never late.", "be + частота."),
        fill("Вставьте предлог: They live ___ Moscow.", "in", "in + city."),
        xf("Переставьте: tomorrow / we / leave", "We leave tomorrow.", "Время обычно в конце."),
        match("Роли", ["Do", "you", "swim"], "Do=aux; you=S; swim=V", "Вопрос Present Simple."),
        fill("Вставьте нужную форму (speak): He ___ English well. (speak)", "speaks", "S + V + adv."),
        err("Often she is late.", "She is often late.", "Частота после be."),
    ],
}


def _merge(*maps: dict[str, list]) -> dict[str, list]:
    out: dict[str, list] = {}
    for mapping in maps:
        for slug, items in mapping.items():
            out.setdefault(slug, []).extend(items)
    return out


from app.seed.topic_banks_adv import TOPIC_PRACTICE_ADV, TOPIC_TEST_ADV
from app.seed.topic_banks_c import TOPIC_PRACTICE_C, TOPIC_TEST_C
from app.seed.topic_banks_upper import TOPIC_PRACTICE_UPPER, TOPIC_TEST_UPPER

TOPIC_PRACTICE = _merge(TOPIC_PRACTICE, TOPIC_PRACTICE_UPPER, TOPIC_PRACTICE_ADV, TOPIC_PRACTICE_C)
TOPIC_TEST = _merge(TOPIC_TEST, TOPIC_TEST_UPPER, TOPIC_TEST_ADV, TOPIC_TEST_C)
