"""C1–C2 on-topic practice/test pads keyed by module slug."""

from app.seed.helpers import err, fill, match, mc, order, xf

TOPIC_PRACTICE_C: dict[str, list] = {
    "inversion-full": [
        mc("Were it not ___ the delay, we would start.", ["for", "to", "that"], "for", "Were it not for."),
        fill("On no account ___ you open that.", "should", "On no account + should."),
        err("Only after the meeting I understood.", "Only after the meeting did I understand.", "Only after + inversion."),
        order("Соберите: so / complex / was / the / plan / that / we / paused", "So complex was the plan that we paused.", "So + adj + be + S."),
        fill("Hardly ___ the film started when the lights failed. (have)", "had", "Hardly had + S."),
        match("Full inversion", ["Never", "have", "I seen"], "Never=front; have=aux; I seen=clause", "Negative fronting."),
        mc("Little ___ they realise the risk.", ["they did", "did they", "they do"], "did they", "Little did + S."),
        fill("Such ___ the noise that we left. (be)", "was", "Such was + N."),
        order("Слова: under / no / circumstances / should / you / panic", "Under no circumstances should you panic.", "Инверсия."),
        err("Not until later I noticed.", "Not until later did I notice.", "Not until + did."),
    ],
    "fronting-emphasis": [
        fill("___ the bay sailed the yacht.", "Into", "Full inversion after fronted PP."),
        mc("What I can't stand ___ the noise.", ["are", "is", "be"], "is", "Wh-cleft + is."),
        err("Standing in the corner the man was.", "Standing in the corner was the man.", "Fronting + inversion.", ["The man was standing in the corner."]),
        xf("Объясните фронтирование объекта одной фразой: His advice I ignored.", "object fronting for emphasis", "O перед S+V."),
        fill("Far ___ it from me to insist. (be)", "be", "Far be it."),
        match("Fronting", ["Into the bay", "sailed", "the yacht"], "Into the bay=front; sailed=V; the yacht=S", "Полная инверсия."),
        mc("Rarely ___ such clarity.", ["we see", "do we see", "we do see"], "do we see", "Rarely + inversion."),
        fill("___ was his anger that he left.", "Such", "Such was."),
        order("Соберите: on the wall / hung / a / portrait", "On the wall hung a portrait.", "PP fronting."),
        err("Here the bus comes.", "Here comes the bus.", "Here + V + S."),
    ],
    "subjunctive-mandative": [
        fill("It is essential that he ___ on time. (be)", "be", "Subjunctive."),
        mc("I demand that he ___ now.", ["leaves", "leave", "left"], "leave", "Mandative subjunctive."),
        err("I demand that he leaves now.", "I demand that he leave now.", "Subjunctive leave."),
        xf("Вставьте subjunctive после suggested that: She suggested that he ___ earlier. (arrive)", "arrive", "base form."),
        fill("It was suggested that the plan ___ revised. (be)", "be", "Mandative subjunctive."),
        match("Subjunctive", ["essential that", "base form", "should + V"], "essential that=рамка; base=AmE; should=BrE alt", "Варианты."),
        mc("They insisted that she ___ present.", ["was", "be", "is"], "be", "insist that + subjunctive."),
        fill("It is vital that everyone ___ informed. (be)", "be", "be."),
        order("Соберите: that / he / be / told / immediately", "that he be told immediately", "passive subjunctive."),
        err("The boss recommended that she applies.", "The boss recommended that she apply.", "apply."),
    ],
    "impersonal-passive": [
        fill("It is said that the talks ___. (fail — Present Perfect)", "have failed", "It is said that + clause."),
        mc("She is believed ___ abroad.", ["to be", "be", "that is"], "to be", "be believed to."),
        err("They are said that they left.", "They are said to have left.", "be said to + perfect inf."),
        xf("Перепишите reporting passive: People think he lied → He is thought ___ lied.", "to have", "to have + V3."),
        fill("It was reported that costs ___ risen.", "had", "that-clause sequence."),
        match("Impersonal", ["It is said that", "He is said to", "to have + V3"], "It-that=безличная; He is said to=личная; perfect inf=раньше", "Два паттерна."),
        mc("The minister is expected ___ resign.", ["to", "for", "that"], "to", "be expected to."),
        fill("He is alleged to ___ taken funds.", "have", "to have + V3."),
        order("Соберите: to / considered / be / is / safe / it", "It is considered to be safe.", "impersonal."),
        err("It is thought him guilty.", "He is thought to be guilty.", "личная конструкция."),
    ],
    "hedging-modality": [
        fill("It would appear ___ the claim holds.", "that", "hedge + that."),
        mc("___ might be argued that the data are thin.", ["It", "There", "One"], "It", "It might be argued."),
        err("I am sure maybe he is wrong. (ослабьте)", "He may be wrong.", "hedge без противоречия."),
        xf("Ослабьте утверждение (hedge): The plan will fail → The plan ___ fail.", "may / might / could", "modal hedge."),
        fill("There ___ to be a delay. (seem)", "seems", "There seems to be."),
        match("Hedges", ["It would appear", "that", "the claim holds"], "It would appear=hedge; that=linker; the claim holds=clause", "Дистанцирование."),
        mc("One ___ conclude that funding is tight.", ["must", "might", "will"], "might", "осторожный вывод."),
        fill("It ___ be the case that we were wrong.", "may", "may be the case."),
        order("Соберите: seem / to / the / results / suggest / a / bias", "The results seem to suggest a bias.", "seem to."),
        err("This definitely proves perhaps nothing.", "This does not necessarily prove anything.", "согласованный hedge."),
    ],
    "nominalization": [
        xf("Сделайте номинализацию: They refused → their ___", "refusal", "refuse → refusal."),
        fill("Noun: decide → ___", "decision", "decide → decision."),
        mc("The ___ of the bridge took a year.", ["construct", "construction", "constructing"], "construction", "nominalization."),
        err("Because of they arrived late, we waited.", "Because of their late arrival, we waited.", "N-фраза."),
        fill("Her ___ to help surprised us. (refuse)", "refusal", "refusal."),
        match("Noun forms", ["decide→decision", "refuse→refusal", "arrive→arrival"], "типичные суффиксы", "Номинализация."),
        mc("We discussed the ___ of the policy.", ["implement", "implementation", "implementing"], "implementation", "of + N."),
        fill("The committee noted a significant ___. (improve)", "improvement", "improvement."),
        order("Соберите: of / the / cancellation / flight / the", "the cancellation of the flight", "N of N."),
        err("Their arriving late caused problems. ( Formal nominal)", "Their late arrival caused problems.", "arrival."),
    ],
    "ellipsis-substitution": [
        fill("I ordered coffee and so ___ she.", "did", "so + aux."),
        mc("She likes tea and I ___ too.", ["am", "do", "like"], "do", "do substitution."),
        err("He can swim and so I can.", "He can swim and so can I.", "so + aux + S."),
        xf("Избегите повтора (one/so): She bought one and I bought one → I bought ___ too.", "one", "one substitution."),
        fill("If you want me to help, I will ___.", "do", "do = help.", ["help"]),
        match("Ellipsis", ["so do I", "neither did she", "one/ones"], "согласие; отрицание; замена N", "Substitution."),
        mc("I haven't finished, but she ___.", ["has", "does", "is"], "has", "aux echo."),
        fill("Would you like some? — Yes, I'd love ___.", "to", "to-ellipsis.", ["some"]),
        order("Соберите: neither / have / I", "Neither have I.", "Neither + aux + S."),
        err("I go swimming and she does go too. (лишнее)", "I go swimming and so does she.", "so does she."),
    ],
    "advanced-conditionals": [
        fill("___ it rain, the event moves indoors. (Should)", "Should", "Should it + V."),
        mc("___ he to ask, I would agree.", ["Was", "Were", "If"], "Were", "Were he to."),
        err("If should you need help, call me.", "Should you need help, call me.", "Should + S + V."),
        xf("Сделайте инверсию Had + S: If she had known → ___ she known", "Had", "Had + S + V3."),
        fill("Were it not for you, I ___ be lost.", "would", "Were it not for."),
        match("Advanced cond.", ["Should you", "Were he to", "Had I"], "Should=1st-ish; Were to=2nd; Had=3rd", "Инверсия условия."),
        mc("Had they left earlier, they ___ caught the train.", ["will have", "would have", "would"], "would have", "3rd inversion."),
        fill("___ you change your mind, email me. (Should)", "Should", "Should + S."),
        order("Соберите: known / had / we / we / would have waited", "Had we known, we would have waited.", "Had + S."),
        err("Were if it sunny, we'd go out.", "Were it sunny, we'd go out.", "Were it."),
    ],
    "complex-noun-phrases": [
        fill("The unusually ___ delay angered passengers. (long)", "long", "adv + adj + N."),
        mc("A number of factors ___ considered.", ["was", "were", "is"], "were", "a number of + pl."),
        err("The interest rates rise was sharp.", "The rise in interest rates was sharp.", "N of/in N."),
        xf("Добавьте постмодификатор: the report + published yesterday → ?", "the report published yesterday", "reduced relative."),
        fill("Several ___ of evidence support the claim.", "pieces", "pieces of."),
        match("NP structure", ["determiner", "adjective", "head noun"], "determiner=det; adjective=adj; head noun=N", "Порядок."),
        mc("The committee's ___ was unanimous.", ["decide", "decision", "decisive"], "decision", "possessive + N."),
        fill("An increasing ___ of voters abstained.", "number", "number of."),
        order("Соберите: of / the / failure / system / the", "the failure of the system", "N of N."),
        err("Many informations were leaked.", "Much information was leaked.", "uncount."),
    ],
    "reporting-verb-patterns": [
        err("She explained me the rule.", "She explained the rule to me.", "Explain sth to sb."),
        fill("He accused her ___ lying.", "of", "accuse of."),
        mc("They congratulated me ___ winning.", ["to", "on", "for"], "on", "congratulate on."),
        xf("Вставьте not to после warn: She warned me ___ go alone.", "not to", "warn + not to."),
        fill("I regret ___ you this earlier. (tell — о прошлом)", "telling", "regret + -ing."),
        match("Patterns", ["explain sth to sb", "accuse of", "congratulate on"], "explain sth to sb=to + sb; accuse of=of; congratulate on=on", "Reporting verbs."),
        mc("She insisted ___ paying.", ["on", "to", "for"], "on", "insist on + -ing."),
        fill("He apologised ___ being late.", "for", "apologise for."),
        order("Соберите: to / me / the / problem / explained / she", "She explained the problem to me.", "explain to."),
        err("I look forward to meet you.", "I look forward to meeting you.", "to + -ing."),
    ],
    # --- C2 ---
    "information-structure": [
        mc("___ that as it may, we proceed.", ["Be", "Is", "Were"], "Be", "Be that as it may."),
        fill("Suffice ___ to say we disagreed.", "it", "Suffice it to say."),
        err("The data is conflicting each other.", "The data are conflicting with each other.", "Data + are; with."),
        order("Соберите: hard / as / tried / she / she / failed", "Hard as she tried, she failed.", "Adj + as + S + V."),
        fill("Выберите may в идиоме Come what ___: Come what ___, we finish tonight.", "may", "Come what may."),
        match("Info structure", ["theme", "rheme", "end-focus"], "theme=данное; rheme=новое; end-focus=акцент в конце", "Инф. структура."),
        mc("He is as brilliant a writer ___ she is.", ["than", "as", "like"], "as", "as…as."),
        fill("Strange ___ it seem, it worked. (as)", "as", "Adj + as + S + V."),
        order("Слова: though / tired / she / was / she / continued", "Tired though she was, she continued.", "Adj + though."),
        err("I can't help to laugh.", "I can't help laughing.", "Can't help + -ing."),
    ],
    "aspect-contrasts": [
        fill("I ___ been meaning to call you. (have)", "have", "Perfect Continuous of intention."),
        mc("By next year she ___ for a decade.", ["works", "will have been working", "is working"], "will have been working", "Future Perfect Continuous."),
        err("I am knowing him for years.", "I have known him for years.", "state → Perfect."),
        xf("Вставьте Present Perfect для контраста: I lived there (finished) vs I ___ there since 2010.", "have lived / have been living", "Perfect."),
        fill("She ___ always interrupt me! (will — characteristic)", "will", "will of tendency."),
        match("Aspect", ["Simple", "Continuous", "Perfect"], "Simple=факт; Continuous=процесс; Perfect=связь с точкой", "Аспект."),
        mc("He ___ to open the door when it unlocked itself.", ["was trying", "tried", "has tried"], "was trying", "фон/попытка."),
        fill("We ___ just about to leave when he arrived.", "were", "were about to."),
        order("Соберите: have / been / expecting / this / I", "I have been expecting this.", "PPC."),
        err("I see him tomorrow for sure already arranged. (plan)", "I'm seeing him tomorrow.", "Present Continuous plan."),
    ],
    "register-metaphor": [
        fill("In formal style prefer ___ to kids.", "children", "register."),
        mc("The metaphor 'time is money' treats time as ___.", ["a liquid", "a resource", "a person"], "a resource", "conceptual metaphor."),
        err("Hi guys, hereby I beg to inform you… (смешение)", "I am writing to inform you…", "единый регистр."),
        xf("Подберите более формальный синоним: get → ___", "obtain / receive", "более формальный глагол."),
        fill("Avoid slang in reports: use ___ instead of a lot of.", "numerous / considerable / substantial", "formal quantifier."),
        match("Register", ["formal", "neutral", "informal"], "formal=офиц.; neutral=нейтр.; informal=неофиц.", "Регистр."),
        mc("Which is most formal?", ["Thanks a lot", "Thank you", "I am grateful for your assistance"], "I am grateful for your assistance", "формальность."),
        fill("The phrase 'at the end of the day' is often ___ in academic prose.", "avoided / too informal", "idiom register."),
        order("Соберите: would / appreciate / I / a / prompt / reply", "I would appreciate a prompt reply.", "formal request."),
        err("The data kinda shows a trend.", "The data appear to show a trend.", "academic hedge."),
    ],
    "advanced-cohesion": [
        fill("The plan failed; ___, funding was cut. (moreover/therefore — cause)", "therefore", "causal linker."),
        mc("___ the delay, the launch went ahead.", ["Despite", "Although", "Whereas"], "Despite", "Despite + N."),
        err("Despite of the rain, we went.", "Despite the rain, we went.", "Despite без of."),
        xf("Вставьте связку контраста: On the ___ hand…", "other", "on the other hand."),
        fill("The former option is cheaper; the ___ is safer.", "latter", "former/latter."),
        match("Cohesion", ["reference", "conjunction", "lexical chain"], "reference=it/this; conjunction=however; lexical=повтор/синоним", "Связность."),
        mc("___ having little evidence, they published.", ["In spite", "Despite", "Although"], "Despite", "Despite + -ing.", ["In spite of"]),
        fill("This brings us ___ the final point.", "to", "brings us to."),
        order("Соберите: that / said / the / risks / remain", "That said, the risks remain.", "discourse marker."),
        err("However she was tired, she continued. (нужна запятая/although)", "Although she was tired, she continued.", "Although + clause."),
    ],
    "distancing-evidentiality": [
        fill("It ___ appear that the claim holds.", "would", "distancing would."),
        mc("Reportedly, the talks ___.", ["fail", "have failed", "failing"], "have failed", "evidential adverb + Perfect."),
        err("I heard he is resigned yesterday.", "I heard he resigned yesterday.", "sequence / tense."),
        xf("Вставьте предлог: According ___ the report…", "to", "According to."),
        fill("She is ___ to have left already. (rumour — said)", "said", "be said to."),
        match("Distancing", ["Apparently", "It seems", "According to"], "Apparently=слухи/вывод; It seems=кажется; According to=по источнику", "Эвиденциальность."),
        mc("___ is claimed that costs rose.", ["It", "There", "One"], "It", "It is claimed."),
        fill("He allegedly ___ funds. (take — Past)", "took", "allegedly + Past."),
        order("Соберите: to / seem / the / figures / suggest / growth", "The figures seem to suggest growth.", "seem to."),
        err("Obviously maybe it's wrong.", "It may be wrong.", "не конфликтующие hedges."),
    ],
    "marked-word-order": [
        fill("Hard ___ she tried, she failed. (as)", "as", "Adj + as + S + V."),
        mc("___ it rain, move indoors.", ["Should", "Would", "Might"], "Should", "Should it + V."),
        err("Into the room the guests came slowly. (полная инверсия лучше)", "Into the room came the guests.", "PP + V + S."),
        xf("Сделайте фронтирование PP + инверсию: The yacht sailed into the bay. → Into the bay ___ the yacht.", "sailed", "Full inversion."),
        fill("Try as she ___, she couldn't open it.", "might", "Try as S might."),
        match("Marked order", ["fronting", "inversion", "cleft"], "fronting=вынос вперёд; inversion=инверсия; cleft=расщепление", "C2."),
        mc("Not a word ___ he say.", ["he did", "did he", "he said"], "did he", "Not a + inversion."),
        fill("Come what ___, keep the channel open.", "may", "Come what may."),
        order("Соберите: though / brilliant / the / idea / was / it / failed", "Brilliant though the idea was, it failed.", "Adj + though."),
        err("So difficult the exam was that many failed. (порядок)", "So difficult was the exam that many failed.", "So + adj + be + S."),
    ],
    "determiners-precision": [
        fill("___ few people understood the clause.", "A", "a few = некоторое число."),
        mc("She has ___ interest in politics.", ["few", "little", "a few"], "little", "little + uncount."),
        err("Both of candidates were strong.", "Both candidates were strong.", "both + N.", ["Both of the candidates were strong."]),
        xf("Все (с определённостью): ___ the students passed.", "All of", "All of the.", ["All"]),
        fill("Neither ___ the options works.", "of", "neither of."),
        match("Determiners", ["each", "every", "either"], "each=по одному; every=все как класс; either=один из двух", "Точность."),
        mc("___ student must sign.", ["All", "Every", "Both"], "Every", "every + sg."),
        fill("We have ___ enough time.", "not", "not enough.", ["hardly"]),
        order("Соберите: of / the / none / answers / correct / were", "None of the answers were correct.", "none of the."),
        err("I don't have many informations.", "I don't have much information.", "uncount."),
    ],
    "advanced-complementation": [
        fill("I resent ___ ignored. (be)", "being", "resent + -ing."),
        mc("She prevented him ___ leaving.", ["to", "from", "of"], "from", "prevent from."),
        err("I can't help to laugh.", "I can't help laughing.", "help + -ing."),
        xf("Вставьте to-infinitive после likely: He is likely ___ win.", "to", "likely to + V."),
        fill("They objected ___ the proposal. (to)", "to", "object to."),
        match("Complementation", ["verb + -ing", "verb + to-inf", "adj + to"], "verb + -ing=-ing; verb + to-inf=to-inf; adj + to=adj + to", "C2."),
        mc("He is accustomed ___ working nights.", ["to", "with", "for"], "to", "accustomed to + -ing."),
        fill("Nothing will make me ___ my mind. (change)", "change", "make + bare inf."),
        order("Соберите: on / insisted / paying / she", "She insisted on paying.", "insist on + -ing."),
        err("I suggested her to wait.", "I suggested that she wait.", "suggest + that.", ["I suggested waiting."]),
    ],
}

TOPIC_TEST_C: dict[str, list] = {
    "inversion-full": [
        fill("Вставьте may: Be that as it ___, we continue.", "may", "Be that as it may."),
        mc("Выберите пропущенное слово: Only then ___ the mistake.", ["I realised", "did I realise", "I did realise"], "did I realise", "Only then + inversion."),
        err("Rarely we see such skill.", "Rarely do we see such skill.", "Rarely + do."),
        order("Соберите: known / had / we / we / would have waited", "Had we known, we would have waited.", "Had-inversion."),
        fill("Вставьте вспомогательный глагол: No sooner ___ we sat down than the fire alarm rang. (have)", "had", "No sooner had."),
        match("Triggers", ["Never", "Only then", "Under no circumstances"], "Never=отриц. наречие; Only then=ограничение; Under no circumstances=запрет", "C1."),
        mc("Выберите пропущенное слово: ___ had I arrived when it started to snow.", ["Hardly", "Hard", "Harder"], "Hardly", "Hardly had."),
        fill("Вставьте форму to be: So rare ___ the opportunity that we took it. (be)", "was", "So + adj + was."),
        order("Слова: little / know / did / they", "Little did they know.", "Little did."),
        err("Not only she was late, she was rude.", "Not only was she late, she was rude.", "Not only + inversion."),
    ],
    "fronting-emphasis": [
        fill("Вставьте предлог: ___ the hill stood an old tower.", "On", "PP + V + S."),
        mc("Выберите форму to be: What matters most ___ patience.", ["are", "is", "be"], "is", "Wh-cleft."),
        err("Away the car sped.", "Away sped the car.", "Away + V + S.", ["The car sped away."]),
        xf("Сделайте wh-cleft: I need rest → What I need ___ rest.", "is", "What … is."),
        fill("Вставьте форму to be: Such ___ his fury that he left. (be)", "was", "Such was."),
        match("Devices", ["fronting", "cleft", "inversion"], "fronting=вынос; cleft=расщепление; inversion=инверсия", "Emphasis."),
        mc("Выберите форму to be: Here ___ the results.", ["are", "come", "is"], "are", "Here + be.", ["come"]),
        fill("Вставьте нужную форму (Far): ___ be it from me to judge. (Far)", "Far", "Far be it."),
        order("Соберите: into / walked / the / room / the / CEO", "Into the room walked the CEO.", "full inversion."),
        err("There the problem lies.", "There lies the problem.", "There + V + S."),
    ],
    "subjunctive-mandative": [
        fill("Вставьте нужную форму (leave): I demand that he ___ now. (leave)", "leave", "base form."),
        mc("Выберите форму to be: It is crucial that she ___ present.", ["is", "be", "was"], "be", "subjunctive."),
        err("They recommended that he applies again.", "They recommended that he apply again.", "apply."),
        xf("Вставьте subjunctive passive: It is important that he ___ informed. (be)", "be", "be + V3."),
        fill("Вставьте форму to be: She suggested that the meeting ___ postponed. (be)", "be", "be."),
        match("Triggers", ["demand that", "essential that", "recommend that"], "demand that=требование; essential that=оценка; recommend that=совет", "Subjunctive."),
        mc("Выберите форму to be: He insisted that payment ___ made immediately.", ["is", "be", "was"], "be", "be made."),
        fill("Вставьте форму to be: It is vital that nobody ___ late. (be)", "be", "be."),
        order("Соберите: that / she / remain / silent", "that she remain silent", "base form."),
        err("The law requires that each driver has insurance. (AmE subjunctive)", "The law requires that each driver have insurance.", "have."),
    ],
    "impersonal-passive": [
        fill("Вставьте нужную форму (resign — Perfect): It is believed that the CEO ___. (resign — Perfect)", "has resigned", "It is believed that."),
        mc("Выберите пропущенное слово: He is rumoured ___ resigned.", ["to have", "have", "that he"], "to have", "to have + V3."),
        err("It is said him to be wealthy.", "He is said to be wealthy.", "личная."),
        xf("Перепишите reporting passive: People say she left → She is said ___ left.", "to have", "to have."),
        fill("Вставьте форму to be: It was claimed that errors ___ made.", "were", "were + V3.", ["had been"]),
        match("Patterns", ["It is said that", "X is said to", "to have been + V3"], "безличная / личная / perfect passive inf", "Reporting."),
        mc("Выберите пропущенное слово: They are thought ___ hiding.", ["to be", "be", "that"], "to be", "to be + V-ing."),
        fill("Вставьте предлог: She is expected ___ arrive by noon. (to)", "to", "be expected to + V."),
        order("Соберите: to / reported / be / is / missing / he", "He is reported to be missing.", "reported to."),
        err("It is considered that he to be guilty.", "He is considered to be guilty.", "личная."),
    ],
    "hedging-modality": [
        fill("Вставьте модальный глагол (will/would): It ___ seem that we underestimated demand.", "would", "would seem."),
        mc("Выберите пропущенное слово: The results ___ suggest a weak effect.", ["appear to", "are appear", "appearing"], "appear to", "appear to."),
        err("This 100% maybe proves the theory.", "This may support the theory.", "согласованный hedge."),
        xf("Вставьте hedge-существительное: There is a ___ that costs will rise.", "possibility / chance / likelihood", "N hedge."),
        fill("Вставьте модальный глагол: One ___ argue that the sample is small.", "might", "might argue."),
        match("Hedges", ["may", "appear to", "it is possible that"], "may=модальность; appear to=кажется; it is possible that=рамка возможности", "Hedging."),
        mc("Выберите пропущенное слово: ___ is possible that we were wrong.", ["It", "There", "This"], "It", "It is possible."),
        fill("Вставьте нужную форму (seem): The data ___ to indicate a plateau. (seem)", "seem", "seem to."),
        order("Соберите: be / argued / that / it / can / funding / is / insufficient", "It can be argued that funding is insufficient.", "It can be argued."),
        err("We definitely tentatively conclude X.", "We tentatively conclude X.", "один hedge."),
    ],
    "nominalization": [
        fill("Вставьте пропущенное слово: Noun from expand → ___", "expansion", "expand → expansion."),
        mc("Выберите пропущенное слово: Their ___ was unexpected.", ["arrive", "arrival", "arriving"], "arrival", "nominal."),
        err("Due to he was ill, he stayed home.", "Due to his illness, he stayed home.", "N after due to."),
        xf("Сделайте номинализацию: fail → ___", "failure", "failure."),
        fill("Вставьте верную пару форм: The ___ of evidence is weak. (strong? → opposite N)", "weakness / paucity / lack", "N of N."),
        match("Suffixes", ["-tion", "-ment", "-al"], "decision; improvement; arrival", "Словообразование."),
        mc("Выберите пропущенное слово: We noted a sharp ___ in sales.", ["reduce", "reduction", "reducing"], "reduction", "reduction in."),
        fill("Вставьте нужную форму (promote): Her rapid ___ surprised the board. (promote)", "promotion", "promotion."),
        order("Соберите: of / the / announcement / results / the", "the announcement of the results", "N of N."),
        err("The improving of skills takes time. (natural N)", "The improvement of skills takes time.", "improvement."),
    ],
    "ellipsis-substitution": [
        fill("Вставьте модальный глагол can: She can play the piano and so ___ I.", "can", "so + aux + S."),
        mc("Выберите пропущенное слово: I need a pen. Do you have ___?", ["it", "one", "some"], "one", "one."),
        err("I like coffee and she likes.", "I like coffee and so does she.", "so does she."),
        xf("Перепишите с Neither + aux + S: I don't agree → Neither ___ I.", "do", "Neither do I."),
        fill("Вставьте вспомогательный глагол: If you ask me to stay, I will ___.", "do", "do = stay."),
        match("Substitution", ["do/does/did", "so/neither", "one/ones"], "глагол; согласие; существительное", "Ellipsis."),
        mc("Выберите вспомогательный глагол: He hasn't replied, and neither ___ she.", ["has", "does", "is"], "has", "neither + aux."),
        fill("Вставьте предлог: Want to join? I don't want ___.", "to", "to-ellipsis."),
        order("Соберите: so / did / we", "So did we.", "So + aux + S."),
        err("I am happy and so do I.", "I am happy and so am I.", "be → am."),
    ],
    "advanced-conditionals": [
        fill("Вставьте модальный глагол should: ___ you need anything, call me. (Should)", "Should", "Should + S."),
        mc("Выберите форму to be: ___ they to offer more, would you accept?", ["Was", "Were", "If"], "Were", "Were they to."),
        err("Had if I known, I would have stayed.", "Had I known, I would have stayed.", "Had + S."),
        xf("Вставьте предлог: Were it not ___ your help, we'd fail.", "for", "Were it not for."),
        fill("Вставьте нужную форму (sound): Should the alarm ___, evacuate. (sound)", "sound", "Should + S + V."),
        match("Forms", ["Should + S + V", "Were + S + to", "Had + S + V3"], "Should + S + V=should-инверсия; Were + S + to=were-инверсия; Had + S + V3=had-инверсия", "C1."),
        mc("Выберите модальный глагол (will/would): Had she asked, I ___ helped.", ["will have", "would have", "would"], "would have", "3rd."),
        fill("Вставьте предлог: Were he ___ resign, chaos would follow. (to)", "to", "Were he to."),
        order("Соберите: rain / should / it / cancel / we / will", "Should it rain, we will cancel.", "Should it."),
        err("Were if she ready, we'd start.", "Were she ready, we'd start.", "Were she."),
    ],
    "complex-noun-phrases": [
        fill("Вставьте пропущенное слово: A large ___ of participants withdrew.", "number", "number of."),
        mc("Выберите пропущенное слово: The ___ of the project was delayed.", ["launching", "launch", "launched"], "launch", "N of N."),
        err("The criterias were unclear.", "The criteria were unclear.", "criteria pl."),
        xf("Соберите premodification: surprisingly + high + costs → ?", "surprisingly high costs", "adv + adj + N."),
        fill("Вставьте нужную форму (piece): Several ___ of advice were ignored. (piece)", "pieces", "pieces of."),
        match("NP", ["premodifiers", "head", "postmodifiers"], "перед / ядро / после", "Сложные NP."),
        mc("Выберите пропущенное слово: The board approved the CEO's ___.", ["resign", "resignation", "resigned"], "resignation", "possessive + N."),
        fill("Вставьте верную пару форм: An alarming ___ of errors appeared.", "number / rate / proportion", "N of N."),
        order("Соберите: in / interest / rates / the / rise", "the rise in interest rates", "N in N."),
        err("Many evidences support this.", "Much evidence supports this.", "evidence uncount."),
    ],
    "reporting-verb-patterns": [
        fill("Вставьте предлог: She congratulated me ___ winning.", "on", "on."),
        mc("Выберите since или for: He blamed me ___ the delay.", ["to", "for", "on"], "for", "blame for."),
        err("She congratulated me to win.", "She congratulated me on winning.", "congratulate on."),
        xf("Вставьте from после discourage: They discouraged us ___ applying.", "from", "from + -ing."),
        fill("Вставьте since или for: I apologise ___ the confusion.", "for", "apologise for."),
        match("Verbs", ["accuse of", "prevent from", "thank for"], "accuse of=of; prevent from=from; thank for=for", "Patterns."),
        mc("Выберите предлог: They warned us ___ the risks.", ["of", "to", "on"], "of", "warn of/about.", ["about"]),
        fill("Вставьте нужную форму (forget — -ing): He admitted ___ the password. (forget — -ing)", "forgetting", "admit + -ing."),
        order("Соберите: me / to / the / rule / explained / she", "She explained the rule to me.", "explain to."),
        err("I regret to tell you this earlier. (о прошлом)", "I regret telling you this earlier.", "regret + -ing."),
    ],
    "information-structure": [
        fill("Вставьте пропущенное слово: Suffice ___ to say the talks stalled.", "it", "Suffice it to say."),
        mc("Выберите модальный глагол should: ___ it rain, the event moves indoors.", ["Should", "Would", "Might"], "Should", "Should it."),
        err("The committee have not yet reached its decision. (unit BrE)", "The committee has not yet reached its decision.", "has for unit."),
        xf("Вставьте as/though в concession fronting: Hard ___ she tried, she failed.", "as", "Hard as."),
        fill("Вставьте модальный глагол: Come what ___, keep going.", "may", "Come what may."),
        match("C2 frames", ["Be that as it may", "Suffice it to say", "Come what may"], "Be that as it may=уступка; Suffice it to say=сжатие; Come what may=что бы ни", "Info structure."),
        mc("Выберите форму to be: He spoke as if he ___ the owner.", ["is", "were", "was"], "were", "as if + were."),
        fill("Вставьте пропущенное слово: Strange ___ it may seem, it works.", "as", "Adj + as."),
        order("Соберите: though / exhausted / she / was / she / smiled", "Exhausted though she was, she smiled.", "though fronting."),
        err("I resent to be ignored.", "I resent being ignored.", "resent + -ing."),
    ],
    "aspect-contrasts": [
        fill("Вставьте модальный глагол (will/would): By 2030 they ___ have been operating for 50 years.", "will", "Future Perfect Continuous."),
        mc("Выберите нужную форму (habit change): I ___ to the gym lately. (habit change)", ["go", "have been going", "went"], "have been going", "PPC lately."),
        err("I am living here since 2012.", "I have been living here since 2012.", "since → Perfect."),
        xf("Выберите глагол для временного vs постоянного: stay / live — что для temporary?", "I'm staying vs I live", "Continuous vs Simple."),
        fill("Вставьте модальный глагол (will/would): She ___ forever leave her keys on the table! (will)", "will", "will of habit/annoyance."),
        match("Aspect choice", ["ongoing", "completed", "habitual"], "Continuous; Perfect/Simple; Simple/will", "Контрасты."),
        mc("Выберите пропущенное слово: He ___ the report all morning.", ["writes", "has been writing", "wrote"], "has been writing", "PPC."),
        fill("Вставьте предлог: We were ___ to leave.", "about", "about to."),
        order("Соберите: been / meaning / have / I / to / ask", "I have been meaning to ask.", "PPC meaning."),
        err("I see what you mean yesterday.", "I saw / I could see what you meant yesterday.", "Past."),
    ],
    "register-metaphor": [
        fill("Вставьте пропущенное слово: Replace 'kids' in a report with ___.", "children", "formal."),
        mc("Выберите верную пару форм: Time is money maps time onto ___.", ["weather", "money/resource", "food"], "money/resource", "metaphor."),
        err("Wanna submit the manuscript ASAP lol.", "Please submit the manuscript as soon as possible.", "formal."),
        xf("Замените informal «a lot of» на формальный вариант → ?", "a considerable number of / substantial", "register upgrade."),
        fill("Вставьте верную пару форм: Prefer ___ to 'get worse' in academic text.", "deteriorate / worsen", "formal verb."),
        match("Style", ["slang", "neutral", "academic"], "slang=сленг; neutral=нейтр.; academic=академич.", "Register."),
        mc("Most academic:", ["The results are kinda weird", "The results are somewhat unexpected", "Results = wow"], "The results are somewhat unexpected", "hedged academic."),
        fill("Вставьте верную пару форм: Avoid mixing Dear Sir with 'Cheers, Tom' — keep ___ consistent.", "register / tone", "consistency."),
        order("Соберите: grateful / I / would / be / for / clarification", "I would be grateful for clarification.", "formal."),
        err("The metaphor swam across the data ocean wildly. (mixed)", "Avoid mixed metaphors; state the trend plainly.", "clarity."),
    ],
    "advanced-cohesion": [
        fill("Вставьте верную пару форм: Sales fell; ___, costs rose. (contrast)", "meanwhile / by contrast / however", "contrast linker."),
        mc("Выберите пропущенное слово: ___ the evidence, the claim is weak.", ["Given", "Although", "Despite of"], "Given", "Given + N."),
        err("In spite the rain, we went.", "In spite of the rain, we went.", "in spite of."),
        xf("Вставьте additive linker: In ___, …", "addition", "In addition."),
        fill("Вставьте пропущенное слово: The latter point follows from the ___.", "former", "former/latter."),
        match("Links", ["however", "therefore", "moreover"], "contrast; result; addition", "Cohesion."),
        mc("Выберите пропущенное слово: ___ this, progress was slow.", ["Despite", "Although", "Whereas"], "Despite", "Despite + N/pronoun."),
        fill("Вставьте предлог: This leads ___ a clear conclusion.", "to", "leads to."),
        order("Соберите: said / that / funding / remains / uncertain", "That said, funding remains uncertain.", "That said."),
        err("Although of the delay, we continued.", "In spite of the delay, we continued.", "Although + clause OR in spite of + N."),
    ],
    "distancing-evidentiality": [
        fill("Вставьте вспомогательный глагол: Reportedly, she ___ already left.", "has", "Reportedly + Perfect."),
        mc("Выберите пропущенное слово: ___ to witnesses, the door was open.", ["According", "Accorded", "Accordingly"], "According", "According to."),
        err("I am hearing that he resigns tomorrow as hard fact.", "He is said to be resigning tomorrow. / Reportedly…", "distancing."),
        xf("Вставьте seems/appears: The plan ___ to have failed.", "seems / appears", "seem to have."),
        fill("Вставьте верную пару форм: He is ___ to be preparing a statement. (rumour)", "said / rumoured", "be said to."),
        match("Evidentials", ["allegedly", "reportedly", "apparently"], "allegedly=якобы; reportedly=по сообщениям; apparently=по-видимому", "Distancing."),
        mc("Выберите пропущенное слово: It ___ that negotiations stalled.", ["is appeared", "appears", "appearing"], "appears", "It appears."),
        fill("Вставьте форму Past Simple: She allegedly ___ the files. (delete — Past)", "deleted", "allegedly + Past."),
        order("Соберите: to / appear / the / allegations / be / unfounded", "The allegations appear to be unfounded.", "appear to."),
        err("Obviously it might definitely be wrong.", "It might be wrong.", "один маркер."),
    ],
    "marked-word-order": [
        fill("Вставьте модальный глагол: Try as she ___, the lock held.", "might", "Try as S might."),
        mc("Выберите пропущенное слово: Not until dusk ___ the search end.", ["the search did", "did the search", "ended the search"], "did the search", "Not until + inversion."),
        err("So tired she was that she slept.", "So tired was she that she slept.", "So + adj + be + S."),
        xf("Вставьте глагол при фронтировании PP: On the desk ___ a letter.", "lay / was", "PP + V + S."),
        fill("Вставьте пропущенное слово: Hard ___ we tried, we failed.", "as", "Hard as."),
        match("Marked", ["inversion", "fronting", "clefting"], "inversion=инверсия; fronting=вынос; clefting=расщепление", "C2."),
        mc("Выберите вспомогательный глагол: Barely ___ he spoken when the door opened.", ["had", "he had", "did"], "had", "Barely had."),
        fill("Вставьте модальный глагол: Come what ___, we proceed.", "may", "Come what may."),
        order("Соберите: though / simple / the / fix / was / it / worked", "Simple though the fix was, it worked.", "though."),
        err("Into the hall the guests came. (инверсия)", "Into the hall came the guests.", "V before S."),
    ],
    "determiners-precision": [
        fill("Вставьте quantifier (some/any/much…): ___ of the two keys opens the safe.", "Either", "either of."),
        mc("Выберите quantifier (some/any/much…): She showed ___ patience.", ["few", "little", "a few"], "little", "uncount."),
        err("Every students must register.", "Every student must register.", "every + sg."),
        xf("Почти ничего: ___ any progress", "hardly / scarcely", "hardly any."),
        fill("Вставьте предлог: Both ___ the proposals have merit.", "of", "both of."),
        match("Precision", ["each", "every", "all"], "each=индивидуально; every=класс; all=совокупность", "Determiners."),
        mc("Выберите quantifier (some/any/much…): There was ___ hope left.", ["few", "little", "a few"], "little", "little hope."),
        fill("Вставьте форму to be: Neither candidate ___ convincing. (be)", "was", "neither + sg."),
        order("Соберите: of / the / most / applicants / were / overqualified", "Most of the applicants were overqualified.", "most of the."),
        err("I need few informations.", "I need little / a little information.", "uncount."),
    ],
    "advanced-complementation": [
        fill("Вставьте предлог: I object ___ being interrupted.", "to", "object to + -ing."),
        mc("Выберите пропущенное слово: Nothing could make him ___ his mind.", ["to change", "change", "changing"], "change", "make + bare inf."),
        err("She prevented me to enter.", "She prevented me from entering.", "prevent from."),
        xf("Вставьте предлог: capable ___ solving", "of", "capable of."),
        fill("Вставьте предлог: He is likely ___ resign.", "to", "likely to."),
        match("Frames", ["keep + -ing", "manage + to", "stop + sb + from"], "keep + -ing=-ing; manage + to=to-inf; stop + sb + from=from + -ing", "Patterns."),
        mc("Выберите пропущенное слово: I can't help ___ concerned.", ["to feel", "feeling", "feel"], "feeling", "can't help + -ing."),
        fill("Вставьте предлог: They discouraged us ___ applying.", "from", "discourage from."),
        order("Соберите: on / congratulated / winning / me / they", "They congratulated me on winning.", "on + -ing."),
        err("I suggested her to wait.", "I suggested waiting / that she wait.", "suggest patterns."),
    ],
}
