def _w(
    word: str,
    transcription: str,
    translation: str,
    part_of_speech: str,
    example: str,
    example_translation: str,
) -> dict:
    return {
        "word": word,
        "transcription": transcription,
        "translation": translation,
        "part_of_speech": part_of_speech,
        "example": example,
        "example_translation": example_translation,
    }


def _topic(slug: str, title: str, description: str, level_code: str, words: list[dict]) -> dict:
    return {
        "slug": slug,
        "title": title,
        "description": description,
        "level_code": level_code,
        "words": words,
    }


TOPICS = [
    _topic(
        "everyday-objects",
        "Предметы вокруг нас",
        "Мебель, вещи в комнате и на столе — словарь, с которым начинается бытовая речь.",
        "A1",
        [
            _w("chair", "/tʃeə/", "стул", "noun", "Please take that empty chair.", "Пожалуйста, возьми тот свободный стул."),
            _w("table", "/ˈteɪ.bəl/", "стол", "noun", "Leave the keys on the table.", "Оставь ключи на столе."),
            _w("lamp", "/læmp/", "лампа", "noun", "The lamp near the sofa is broken.", "Лампа у дивана сломана."),
            _w("window", "/ˈwɪn.dəʊ/", "окно", "noun", "A cold wind came through the window.", "Через окно дул холодный ветер."),
            _w("door", "/dɔː/", "дверь", "noun", "Someone is knocking at the door.", "Кто-то стучит в дверь."),
            _w("key", "/kiː/", "ключ", "noun", "I left my key in the kitchen.", "Я оставил ключ на кухне."),
            _w("phone", "/fəʊn/", "телефон", "noun", "Her phone rang during the film.", "Её телефон зазвонил во время фильма."),
            _w("bag", "/bæɡ/", "сумка", "noun", "This bag is too heavy for me.", "Эта сумка слишком тяжёлая для меня."),
            _w("book", "/bʊk/", "книга", "noun", "That book has a blue cover.", "У той книги синяя обложка."),
            _w("pen", "/pen/", "ручка", "noun", "I write with a black pen.", "Я пишу чёрной ручкой."),
            _w("clock", "/klɒk/", "часы", "noun", "The clock in the hall is five minutes slow.", "Часы в прихожей отстают на пять минут."),
            _w("mirror", "/ˈmɪr.ə/", "зеркало", "noun", "She checked her hair in the mirror.", "Она поправила волосы перед зеркалом."),
            _w("pillow", "/ˈpɪl.əʊ/", "подушка", "noun", "I sleep better with a thin pillow.", "Мне лучше спится на тонкой подушке."),
            _w("towel", "/ˈtaʊ.əl/", "полотенце", "noun", "Hang the wet towel on the rail.", "Повесь мокрое полотенце на перекладину."),
            _w("bottle", "/ˈbɒt.əl/", "бутылка", "noun", "This bottle of water is still cold.", "Эта бутылка воды ещё холодная."),
            _w("knife", "/naɪf/", "нож", "noun", "Use a small knife for the bread.", "Для хлеба возьми маленький нож."),
            _w("plate", "/pleɪt/", "тарелка", "noun", "Put the cake on a clean plate.", "Положи торт на чистую тарелку."),
            _w("cup", "/kʌp/", "чашка", "noun", "He drinks tea from a large cup.", "Он пьёт чай из большой чашки."),
        ],
    ),
    _topic(
        "family-people",
        "Семья и люди",
        "Родственные связи и ближайшее окружение: кто есть кто и как их назвать.",
        "A1",
        [
            _w("mother", "/ˈmʌð.ə/", "мама", "noun", "My mother cooks dinner on Sundays.", "Моя мама готовит обед по воскресеньям."),
            _w("father", "/ˈfɑː.ðə/", "папа", "noun", "His father works in a bank.", "Его папа работает в банке."),
            _w("sister", "/ˈsɪs.tə/", "сестра", "noun", "I have a younger sister.", "У меня есть младшая сестра."),
            _w("brother", "/ˈbrʌð.ə/", "брат", "noun", "Her brother plays football.", "Её брат играет в футбол."),
            _w("grandmother", "/ˈɡræn.mʌð.ə/", "бабушка", "noun", "Grandmother tells long stories.", "Бабушка рассказывает длинные истории."),
            _w("grandfather", "/ˈɡræn.fɑː.ðə/", "дедушка", "noun", "Grandfather walks in the park every morning.", "Дедушка каждое утро гуляет в парке."),
            _w("uncle", "/ˈʌŋ.kəl/", "дядя", "noun", "Uncle Tom lives by the sea.", "Дядя Том живёт у моря."),
            _w("aunt", "/ɑːnt/", "тётя", "noun", "Aunt Maria sent us a postcard.", "Тётя Мария прислала нам открытку."),
            _w("cousin", "/ˈkʌz.ən/", "двоюродный брат или сестра", "noun", "My cousin is the same age as me.", "Мой двоюродный брат одного возраста со мной."),
            _w("husband", "/ˈhʌz.bənd/", "муж", "noun", "Her husband is a teacher.", "Её муж — учитель."),
            _w("wife", "/waɪf/", "жена", "noun", "His wife speaks three languages.", "Его жена говорит на трёх языках."),
            _w("daughter", "/ˈdɔː.tə/", "дочь", "noun", "Their daughter starts school in September.", "Их дочь идёт в школу в сентябре."),
            _w("son", "/sʌn/", "сын", "noun", "Their son is six years old.", "Их сыну шесть лет."),
            _w("neighbour", "/ˈneɪ.bə/", "сосед", "noun", "Our neighbour waters the plants.", "Наш сосед поливает растения."),
            _w("friend", "/frend/", "друг", "noun", "A good friend called me last night.", "Хороший друг позвонил мне вчера вечером."),
            _w("baby", "/ˈbeɪ.bi/", "малыш", "noun", "The baby is sleeping upstairs.", "Малыш спит наверху."),
            _w("parent", "/ˈpeə.rənt/", "родитель", "noun", "Each parent signed the form.", "Каждый родитель подписал бланк."),
        ],
    ),
    _topic(
        "food-drink",
        "Еда и напитки",
        "Продукты, напитки и простые фразы за столом.",
        "A1",
        [
            _w("bread", "/bred/", "хлеб", "noun", "We bought fresh bread this morning.", "Мы купили свежий хлеб этим утром."),
            _w("cheese", "/tʃiːz/", "сыр", "noun", "I like cheese with tomatoes.", "Я люблю сыр с помидорами."),
            _w("apple", "/ˈæp.əl/", "яблоко", "noun", "She packed an apple for lunch.", "Она положила яблоко на обед."),
            _w("banana", "/bəˈnɑː.nə/", "банан", "noun", "The banana is still green.", "Банан ещё зелёный."),
            _w("water", "/ˈwɔː.tə/", "вода", "noun", "Drink a glass of water first.", "Сначала выпей стакан воды."),
            _w("tea", "/tiː/", "чай", "noun", "Would you like some tea?", "Хочешь чаю?"),
            _w("coffee", "/ˈkɒf.i/", "кофе", "noun", "He drinks coffee without sugar.", "Он пьёт кофе без сахара."),
            _w("milk", "/mɪlk/", "молоко", "noun", "There is no milk in the fridge.", "В холодильнике нет молока."),
            _w("soup", "/suːp/", "суп", "noun", "The soup needs a little salt.", "В суп нужно чуть-чуть соли."),
            _w("rice", "/raɪs/", "рис", "noun", "We eat rice with vegetables.", "Мы едим рис с овощами."),
            _w("chicken", "/ˈtʃɪk.ɪn/", "курица", "noun", "Mum roasted chicken for dinner.", "Мама запекла курицу на ужин."),
            _w("egg", "/eɡ/", "яйцо", "noun", "I had an egg for breakfast.", "На завтрак у меня было яйцо."),
            _w("butter", "/ˈbʌt.ə/", "сливочное масло", "noun", "Spread some butter on the toast.", "Намажь тост маслом."),
            _w("juice", "/dʒuːs/", "сок", "noun", "Orange juice is on the table.", "Апельсиновый сок стоит на столе."),
            _w("salad", "/ˈsæl.əd/", "салат", "noun", "This salad has cucumbers and oil.", "В этом салате огурцы и масло."),
            _w("potato", "/pəˈteɪ.təʊ/", "картофель", "noun", "Boil one potato for the soup.", "Свари одну картофелину для супа."),
            _w("tomato", "/təˈmɑː.təʊ/", "помидор", "noun", "Cut the tomato into thin slices.", "Нарежь помидор тонкими ломтиками."),
            _w("sugar", "/ˈʃʊɡ.ə/", "сахар", "noun", "I don't take sugar in tea.", "Я не кладу сахар в чай."),
        ],
    ),
    _topic(
        "travel-city",
        "Путешествия и город",
        "Вокзалы, аэропорт, улицы и то, что нужно туристу в незнакомом городе.",
        "A2",
        [
            _w("airport", "/ˈeə.pɔːt/", "аэропорт", "noun", "We reached the airport two hours early.", "Мы добрались до аэропорта на два часа раньше."),
            _w("station", "/ˈsteɪ.ʃən/", "вокзал", "noun", "The main station is next to the river.", "Главный вокзал стоит у реки."),
            _w("ticket", "/ˈtɪk.ɪt/", "билет", "noun", "Keep your ticket until you leave the train.", "Сохраняй билет, пока не выйдешь из поезда."),
            _w("platform", "/ˈplæt.fɔːm/", "платформа", "noun", "The train to York leaves from platform four.", "Поезд до Йорка отходит с четвёртой платформы."),
            _w("luggage", "/ˈlʌɡ.ɪdʒ/", "багаж", "noun", "All our luggage fitted in one taxi.", "Весь багаж поместился в одно такси."),
            _w("passport", "/ˈpɑːs.pɔːt/", "паспорт", "noun", "Show your passport at the desk.", "Покажите паспорт на стойке."),
            _w("map", "/mæp/", "карта", "noun", "This map marks every tram stop.", "На этой карте отмечена каждая остановка трамвая."),
            _w("hotel", "/həʊˈtel/", "отель", "noun", "Our hotel has a small courtyard.", "У нашего отеля есть маленький дворик."),
            _w("subway", "/ˈsʌb.weɪ/", "метро", "noun", "Take the subway to the old town.", "До старого города доберись на метро."),
            _w("traffic", "/ˈtræf.ɪk/", "движение, пробки", "noun", "Morning traffic moves very slowly here.", "Утреннее движение здесь очень медленное."),
            _w("pedestrian", "/pəˈdes.tri.ən/", "пешеход", "noun", "Drivers must stop for pedestrians at this crossing.", "Водители должны останавливаться для пешеходов на этом переходе."),
            _w("roundabout", "/ˈraʊnd.ə.baʊt/", "кольцевая развязка", "noun", "Leave the roundabout at the second exit.", "Съезжай с кольца на втором выезде."),
            _w("landmark", "/ˈlænd.mɑːk/", "ориентир, достопримечательность", "noun", "The clock tower is a useful landmark.", "Часовая башня — удобный ориентир."),
            _w("itinerary", "/aɪˈtɪn.ər.ər.i/", "маршрут поездки", "noun", "The itinerary includes two free afternoons.", "В маршруте есть два свободных полдня."),
            _w("boarding", "/ˈbɔː.dɪŋ/", "посадка на рейс", "noun", "Boarding starts twenty minutes before departure.", "Посадка начинается за двадцать минут до вылета."),
            _w("departure", "/dɪˈpɑː.tʃə/", "отправление", "noun", "The departure board shows a short delay.", "Табло отправления показывает небольшую задержку."),
            _w("arrival", "/əˈraɪ.vəl/", "прибытие", "noun", "His arrival is scheduled for midnight.", "Его прибытие назначено на полночь."),
        ],
    ),
    _topic(
        "work-study",
        "Работа и учёба",
        "Офис, учёба и рабочие договорённости: дедлайны, лекции, смена.",
        "A2",
        [
            _w("office", "/ˈɒf.ɪs/", "офис", "noun", "The office closes at six on Fridays.", "В пятницу офис закрывается в шесть."),
            _w("meeting", "/ˈmiː.tɪŋ/", "совещание", "noun", "The meeting lasted almost an hour.", "Совещание длилось почти час."),
            _w("deadline", "/ˈded.laɪn/", "срок сдачи", "noun", "The deadline for the report is Thursday.", "Срок сдачи отчёта — четверг."),
            _w("colleague", "/ˈkɒl.iːɡ/", "коллега", "noun", "A colleague explained the new form.", "Коллега объяснил новую форму."),
            _w("intern", "/ˈɪn.tɜːn/", "стажёр", "noun", "The intern answers the office phone.", "Стажёр отвечает на офисный телефон."),
            _w("lecture", "/ˈlek.tʃə/", "лекция", "noun", "Today's lecture is about climate maps.", "Сегодняшняя лекция — о климатических картах."),
            _w("homework", "/ˈhəʊm.wɜːk/", "домашнее задание", "noun", "I finished the homework before dinner.", "Я сделал домашнее задание до ужина."),
            _w("textbook", "/ˈtekst.bʊk/", "учебник", "noun", "Chapter three of the textbook is short.", "Третья глава учебника короткая."),
            _w("schedule", "/ˈʃed.juːl/", "расписание", "noun", "Check the schedule before you book a room.", "Проверь расписание, прежде чем бронировать аудиторию."),
            _w("interview", "/ˈɪn.tə.vjuː/", "собеседование", "noun", "Her interview starts at ten o'clock.", "Её собеседование начинается в десять."),
            _w("salary", "/ˈsæl.ər.i/", "зарплата", "noun", "The salary is paid on the last Friday.", "Зарплату выплачивают в последнюю пятницу."),
            _w("resume", "/ˈrez.ju.meɪ/", "резюме", "noun", "Update your resume before you apply.", "Обнови резюме, прежде чем откликаться."),
            _w("assignment", "/əˈsaɪn.mənt/", "задание", "noun", "This assignment is only two pages long.", "Это задание всего на две страницы."),
            _w("campus", "/ˈkæm.pəs/", "кампус", "noun", "The library sits in the centre of campus.", "Библиотека стоит в центре кампуса."),
            _w("seminar", "/ˈsem.ɪ.nɑː/", "семинар", "noun", "We discuss short texts in the seminar.", "На семинаре мы разбираем короткие тексты."),
            _w("manager", "/ˈmæn.ɪ.dʒə/", "руководитель", "noun", "Ask the manager if the shift can change.", "Спроси у руководителя, можно ли сменить смену."),
            _w("overtime", "/ˈəʊ.və.taɪm/", "сверхурочные", "noun", "He worked two hours of overtime yesterday.", "Вчера он отработал два часа сверхурочно."),
        ],
    ),
    _topic(
        "health-body",
        "Здоровье и тело",
        "Части тела, симптомы и визит к врачу — практичный словарь A2.",
        "A2",
        [
            _w("headache", "/ˈhed.eɪk/", "головная боль", "noun", "Bright screens give me a headache.", "От ярких экранов у меня болит голова."),
            _w("fever", "/ˈfiː.və/", "жар", "noun", "She stayed in bed because of a fever.", "Она осталась в постели из-за жара."),
            _w("cough", "/kɒf/", "кашель", "noun", "A dry cough kept him awake.", "Сухой кашель не давал ему спать."),
            _w("stomachache", "/ˈstʌm.ək.eɪk/", "боль в животе", "noun", "He skipped lunch because of a stomachache.", "Он пропустил обед из-за боли в животе."),
            _w("shoulder", "/ˈʃəʊl.də/", "плечо", "noun", "I hurt my shoulder during the game.", "Я повредил плечо во время игры."),
            _w("wrist", "/rɪst/", "запястье", "noun", "She wears a thin bracelet on her wrist.", "На запястье у неё тонкий браслет."),
            _w("ankle", "/ˈæŋ.kəl/", "лодыжка", "noun", "He twisted his ankle on the stairs.", "Он подвернул лодыжку на лестнице."),
            _w("throat", "/θrəʊt/", "горло", "noun", "My throat is sore this morning.", "Сегодня утром у меня болит горло."),
            _w("prescription", "/prɪˈskrɪp.ʃən/", "рецепт", "noun", "The doctor wrote a prescription for drops.", "Врач выписал рецепт на капли."),
            _w("pharmacy", "/ˈfɑː.mə.si/", "аптека", "noun", "The pharmacy on the corner opens at eight.", "Аптека на углу открывается в восемь."),
            _w("bandage", "/ˈbæn.dɪdʒ/", "бинт", "noun", "Wrap a clean bandage around the cut.", "Обмотай порез чистым бинтом."),
            _w("allergy", "/ˈæl.ə.dʒi/", "аллергия", "noun", "She has an allergy to peanuts.", "У неё аллергия на арахис."),
            _w("appointment", "/əˈpɔɪnt.mənt/", "приём у врача", "noun", "I booked an appointment for Friday morning.", "Я записался на приём в пятницу утром."),
            _w("symptom", "/ˈsɪmp.təm/", "симптом", "noun", "A high temperature is a common symptom.", "Высокая температура — частый симптом."),
            _w("injury", "/ˈɪn.dʒər.i/", "травма", "noun", "The injury healed after three weeks.", "Травма зажила через три недели."),
            _w("exercise", "/ˈek.sə.saɪz/", "физическая нагрузка", "noun", "Light exercise helps her back.", "Лёгкая нагрузка помогает её спине."),
            _w("recovery", "/rɪˈkʌv.ər.i/", "выздоровление", "noun", "Full recovery may take a month.", "Полное выздоровление может занять месяц."),
        ],
    ),
    _topic(
        "feelings-personality",
        "Чувства и характер",
        "Как назвать настроение, отношение к людям и устойчивые черты характера.",
        "B1",
        [
            _w("anxious", "/ˈæŋk.ʃəs/", "тревожный", "adjective", "He felt anxious before the results.", "Он тревожился перед объявлением результатов."),
            _w("confident", "/ˈkɒn.fɪ.dənt/", "уверенный", "adjective", "She sounded confident in the interview.", "На собеседовании она говорила уверенно."),
            _w("jealous", "/ˈdʒel.əs/", "ревнивый", "adjective", "He became jealous of her success.", "Он стал ревновать её к успеху."),
            _w("ambitious", "/æmˈbɪʃ.əs/", "амбициозный", "adjective", "An ambitious intern asked for extra tasks.", "Амбициозный стажёр попросил дополнительные задачи."),
            _w("stubborn", "/ˈstʌb.ən/", "упрямый", "adjective", "My stubborn brother refused to rest.", "Мой упрямый брат отказался отдыхать."),
            _w("reliable", "/rɪˈlaɪ.ə.bəl/", "надёжный", "adjective", "She is the most reliable person on the team.", "Она самый надёжный человек в команде."),
            _w("impatient", "/ɪmˈpeɪ.ʃənt/", "нетерпеливый", "adjective", "The impatient driver honked twice.", "Нетерпеливый водитель дважды сигналил."),
            _w("grateful", "/ˈɡreɪt.fəl/", "благодарный", "adjective", "I am grateful for your honest advice.", "Я благодарен за твой честный совет."),
            _w("ashamed", "/əˈʃeɪmd/", "пристыженный", "adjective", "He was ashamed of the rude comment.", "Ему было стыдно за грубый комментарий."),
            _w("disappointed", "/ˌdɪs.əˈpɔɪn.tɪd/", "разочарованный", "adjective", "We were disappointed by the cancelled flight.", "Мы были разочарованы отменой рейса."),
            _w("enthusiastic", "/ɪnˌθjuː.ziˈæs.tɪk/", "восторженный", "adjective", "The class was enthusiastic about the project.", "Класс с энтузиазмом взялся за проект."),
            _w("considerate", "/kənˈsɪd.ər.ət/", "внимательный к другим", "adjective", "A considerate neighbour keeps the hall quiet.", "Внимательный сосед не шумит в подъезде."),
            _w("moody", "/ˈmuː.di/", "переменчивый в настроении", "adjective", "He gets moody when he is tired.", "Он становится капризным, когда устаёт."),
            _w("optimistic", "/ˌɒp.tɪˈmɪs.tɪk/", "оптимистичный", "adjective", "She stayed optimistic after the first setback.", "Она осталась оптимисткой после первой неудачи."),
            _w("insecure", "/ˌɪn.sɪˈkjʊə/", "неуверенный в себе", "adjective", "He felt insecure about his accent.", "Он чувствовал неуверенность из-за акцента."),
            _w("embarrassed", "/ɪmˈbær.əst/", "смущённый", "adjective", "I was embarrassed when I said the wrong name.", "Мне было неловко, когда я назвал не то имя."),
            _w("determined", "/dɪˈtɜː.mɪnd/", "целеустремлённый", "adjective", "She is determined to finish the course.", "Она твёрдо намерена закончить курс."),
        ],
    ),
    _topic(
        "nature-environment",
        "Природа и среда",
        "Экосистемы, климат и слова, без которых не обсудить новости об окружающей среде.",
        "B1",
        [
            _w("drought", "/draʊt/", "засуха", "noun", "The drought dried up the shallow lake.", "Засуха пересушила мелкое озеро."),
            _w("flood", "/flʌd/", "наводнение", "noun", "A sudden flood closed the coastal road.", "Внезапное наводнение перекрыло прибрежную дорогу."),
            _w("habitat", "/ˈhæb.ɪ.tæt/", "среда обитания", "noun", "This wetland is a habitat for rare birds.", "Это болото — среда обитания редких птиц."),
            _w("species", "/ˈspiː.ʃiːz/", "вид", "noun", "Several species of frogs live near the pond.", "Возле пруда живут несколько видов лягушек."),
            _w("pollution", "/pəˈluː.ʃən/", "загрязнение", "noun", "Air pollution is worse on still days.", "Загрязнение воздуха сильнее в безветренные дни."),
            _w("recycle", "/ˌriːˈsaɪ.kəl/", "перерабатывать", "verb", "We recycle glass in the blue bin.", "Мы сдаём стекло в синий контейнер."),
            _w("ecosystem", "/ˈiː.kəʊˌsɪs.təm/", "экосистема", "noun", "A coral reef is a fragile ecosystem.", "Коралловый риф — хрупкая экосистема."),
            _w("glacier", "/ˈɡlæs.i.ə/", "ледник", "noun", "The glacier has retreated over twenty years.", "Ледник отступил за двадцать лет."),
            _w("wildlife", "/ˈwaɪld.laɪf/", "дикая природа", "noun", "Night buses disturb the local wildlife.", "Ночные автобусы беспокоят местную дикую природу."),
            _w("deforestation", "/diːˌfɒr.ɪˈsteɪ.ʃən/", "вырубка лесов", "noun", "Deforestation increases the risk of landslides.", "Вырубка лесов повышает риск оползней."),
            _w("compost", "/ˈkɒm.pɒst/", "компост", "noun", "Garden waste turns into compost in a year.", "Садовые отходы за год превращаются в компост."),
            _w("renewable", "/rɪˈnjuː.ə.bəl/", "возобновляемый", "adjective", "The town invested in renewable energy.", "Город вложился в возобновляемую энергию."),
            _w("emission", "/ɪˈmɪʃ.ən/", "выброс", "noun", "New buses cut carbon emissions.", "Новые автобусы сокращают выбросы углерода."),
            _w("biodiversity", "/ˌbaɪ.əʊ.daɪˈvɜː.sə.ti/", "биоразнообразие", "noun", "Hedgerows support farmland biodiversity.", "Живые изгороди поддерживают биоразнообразие полей."),
            _w("wetland", "/ˈwet.lænd/", "водно-болотное угодье", "noun", "The wetland stores water after heavy rain.", "Болото удерживает воду после сильного дождя."),
            _w("conservation", "/ˌkɒn.səˈveɪ.ʃən/", "охрана природы", "noun", "Local conservation groups plant native trees.", "Местные природоохранные группы сажают местные деревья."),
            _w("landfill", "/ˈlænd.fɪl/", "свалка", "noun", "Less food waste means a smaller landfill.", "Меньше пищевых отходов — меньше нагрузка на свалку."),
        ],
    ),
    _topic(
        "media-technology",
        "Медиа и технологии",
        "Интернет, устройства и язык новостей: от пароля до вирусного ролика.",
        "B1",
        [
            _w("podcast", "/ˈpɒd.kɑːst/", "подкаст", "noun", "I listen to a history podcast on the train.", "В поезде я слушаю исторический подкаст."),
            _w("stream", "/striːm/", "транслировать", "verb", "They stream the concert for a small fee.", "Они транслируют концерт за небольшую плату."),
            _w("algorithm", "/ˈæl.ɡə.rɪ.ðəm/", "алгоритм", "noun", "The algorithm keeps showing similar videos.", "Алгоритм снова показывает похожие видео."),
            _w("notification", "/ˌnəʊ.tɪ.fɪˈkeɪ.ʃən/", "уведомление", "noun", "I turned off notifications after ten.", "После десяти я отключил уведомления."),
            _w("browser", "/ˈbraʊ.zə/", "браузер", "noun", "Open the page in another browser.", "Открой страницу в другом браузере."),
            _w("download", "/ˌdaʊnˈləʊd/", "скачивать", "verb", "Download the file before the link expires.", "Скачай файл, пока ссылка не истекла."),
            _w("upload", "/ˌʌpˈləʊd/", "загружать", "verb", "Upload the photos to the shared folder.", "Загрузи фото в общую папку."),
            _w("password", "/ˈpɑːs.wɜːd/", "пароль", "noun", "Never write your password on a sticky note.", "Никогда не пиши пароль на стикере."),
            _w("software", "/ˈsɒft.weə/", "программное обеспечение", "noun", "The new software needs more memory.", "Новой программе нужно больше памяти."),
            _w("headline", "/ˈhed.laɪn/", "заголовок", "noun", "The headline promised more than the article.", "Заголовок обещал больше, чем сама статья."),
            _w("influencer", "/ˈɪn.flu.ən.sə/", "инфлюенсер", "noun", "The influencer disclosed the paid review.", "Инфлюенсер указал, что обзор рекламный."),
            _w("subscription", "/səbˈskrɪp.ʃən/", "подписка", "noun", "I cancelled the unused subscription.", "Я отменил неиспользуемую подписку."),
            _w("viral", "/ˈvaɪə.rəl/", "вирусный", "adjective", "A short clip went viral overnight.", "Короткий ролик за ночь стал вирусным."),
            _w("device", "/dɪˈvaɪs/", "устройство", "noun", "Charge the device before the flight.", "Заряди устройство перед рейсом."),
            _w("wireless", "/ˈwaɪə.ləs/", "беспроводной", "adjective", "The café offers free wireless internet.", "В кафе есть бесплатный беспроводной интернет."),
            _w("update", "/ˈʌp.deɪt/", "обновление", "noun", "Install the update and then restart.", "Установи обновление и перезапусти устройство."),
            _w("storage", "/ˈstɔː.rɪdʒ/", "хранилище", "noun", "Cloud storage filled up after the trip.", "Облачное хранилище заполнилось после поездки."),
        ],
    ),
    _topic(
        "business-money",
        "Бизнес и деньги",
        "Финансовые и корпоративные понятия B2: от выручки до банкротства.",
        "B2",
        [
            _w("revenue", "/ˈrev.ən.juː/", "выручка", "noun", "Ticket revenue rose after the price cut.", "Выручка с билетов выросла после снижения цены."),
            _w("profit", "/ˈprɒf.ɪt/", "прибыль", "noun", "The shop made a small profit in March.", "В марте магазин получил небольшую прибыль."),
            _w("investment", "/ɪnˈvest.mənt/", "инвестиция", "noun", "The city seeks private investment in housing.", "Город ищет частные инвестиции в жильё."),
            _w("shareholder", "/ˈʃeəˌhəʊl.də/", "акционер", "noun", "Shareholders will vote on the merger.", "Акционеры проголосуют по слиянию."),
            _w("invoice", "/ˈɪn.vɔɪs/", "счёт-фактура", "noun", "Please pay the invoice within fourteen days.", "Оплатите счёт в течение четырнадцати дней."),
            _w("budget", "/ˈbʌdʒ.ɪt/", "бюджет", "noun", "The project is already over budget.", "Проект уже вышел за бюджет."),
            _w("interest", "/ˈɪn.trəst/", "процент", "noun", "The bank lowered the interest on savings.", "Банк снизил процент по вкладам."),
            _w("inflation", "/ɪnˈfleɪ.ʃən/", "инфляция", "noun", "High inflation reduced real wages.", "Высокая инфляция снизила реальную зарплату."),
            _w("merger", "/ˈmɜː.dʒə/", "слияние", "noun", "The merger created one national carrier.", "Слияние создало одного национального перевозчика."),
            _w("asset", "/ˈæs.et/", "актив", "noun", "The warehouse is the firm's largest asset.", "Склад — крупнейший актив фирмы."),
            _w("liability", "/ˌlaɪ.əˈbɪl.ə.ti/", "обязательство", "noun", "Unpaid taxes became a serious liability.", "Неуплаченные налоги стали серьёзным обязательством."),
            _w("dividend", "/ˈdɪv.ɪ.dend/", "дивиденд", "noun", "The board approved a modest dividend.", "Совет одобрил скромный дивиденд."),
            _w("equity", "/ˈek.wə.ti/", "собственный капитал", "noun", "They raised equity instead of taking a loan.", "Они привлекли капитал, а не брали кредит."),
            _w("forecast", "/ˈfɔː.kɑːst/", "прогноз", "noun", "The sales forecast looks weaker than last year.", "Прогноз продаж слабее, чем в прошлом году."),
            _w("overhead", "/ˈəʊ.və.hed/", "накладные расходы", "noun", "Rent is the main overhead for the studio.", "Аренда — главные накладные расходы студии."),
            _w("cash flow", "/ˈkæʃ fləʊ/", "денежный поток", "noun", "Slow payments damaged the company's cash flow.", "Медленные платежи подорвали денежный поток компании."),
            _w("bankruptcy", "/ˈbæŋk.rəpt.si/", "банкротство", "noun", "The airline avoided bankruptcy by selling routes.", "Авиакомпания избежала банкротства, продав маршруты."),
        ],
    ),
    _topic(
        "society-law",
        "Общество и право",
        "Суд, законы и общественные институты: словарь для новостей и эссе B2.",
        "B2",
        [
            _w("legislation", "/ˌledʒ.ɪˈsleɪ.ʃən/", "законодательство", "noun", "New legislation limits night-time deliveries.", "Новое законодательство ограничивает ночные доставки."),
            _w("verdict", "/ˈvɜː.dɪkt/", "вердикт", "noun", "The jury reached a unanimous verdict.", "Присяжные вынесли единогласный вердикт."),
            _w("jury", "/ˈdʒʊə.ri/", "присяжные", "noun", "The jury listened to three days of evidence.", "Присяжные три дня слушали доказательства."),
            _w("defendant", "/dɪˈfen.dənt/", "обвиняемый", "noun", "The defendant denied every charge.", "Обвиняемый отрицал каждое обвинение."),
            _w("plaintiff", "/ˈpleɪn.tɪf/", "истец", "noun", "The plaintiff asked for financial compensation.", "Истец потребовал денежную компенсацию."),
            _w("testimony", "/ˈtes.tɪ.mə.ni/", "показания", "noun", "Her testimony contradicted the written report.", "Её показания противоречили письменному отчёту."),
            _w("amendment", "/əˈmend.mənt/", "поправка", "noun", "Parliament passed an amendment on data privacy.", "Парламент принял поправку о защите данных."),
            _w("suffrage", "/ˈsʌf.rɪdʒ/", "избирательное право", "noun", "Equal suffrage was won after a long campaign.", "Равное избирательное право завоевали после долгой кампании."),
            _w("protest", "/ˈprəʊ.test/", "протест", "noun", "A peaceful protest filled the square.", "Мирный протест заполнил площадь."),
            _w("inequality", "/ˌɪn.ɪˈkwɒl.ə.ti/", "неравенство", "noun", "The report measured inequality in housing.", "В докладе измерили неравенство в жилье."),
            _w("welfare", "/ˈwel.feə/", "социальное обеспечение", "noun", "Welfare payments rose with the cost of living.", "Социальные выплаты выросли вместе со стоимостью жизни."),
            _w("custody", "/ˈkʌs.tə.di/", "опека; содержание под стражей", "noun", "The court granted the mother custody.", "Суд передал опеку матери."),
            _w("bail", "/beɪl/", "залог", "noun", "He was released on bail until the hearing.", "Его отпустили под залог до слушания."),
            _w("treaty", "/ˈtriː.ti/", "международный договор", "noun", "The two states signed a border treaty.", "Два государства подписали пограничный договор."),
            _w("constitution", "/ˌkɒn.stɪˈtʃuː.ʃən/", "конституция", "noun", "The constitution guarantees a fair trial.", "Конституция гарантирует справедливый суд."),
            _w("prejudice", "/ˈpredʒ.ə.dɪs/", "предрассудок", "noun", "The campaign challenged racial prejudice.", "Кампания бросила вызов расовым предрассудкам."),
            _w("statute", "/ˈstætʃ.uːt/", "закон, статут", "noun", "The statute came into force in May.", "Закон вступил в силу в мае."),
        ],
    ),
    _topic(
        "academic-abstract",
        "Академическая и абстрактная лексика",
        "Слова эссе и исследований: гипотеза, оговорка, валидность, рамка анализа.",
        "C1",
        [
            _w("hypothesis", "/haɪˈpɒθ.ə.sɪs/", "гипотеза", "noun", "The first hypothesis did not survive the data.", "Первая гипотеза не выдержала проверки данными."),
            _w("paradigm", "/ˈpær.ə.daɪm/", "парадигма", "noun", "The paper challenges the dominant paradigm.", "Статья оспаривает господствующую парадигму."),
            _w("implication", "/ˌɪm.plɪˈkeɪ.ʃən/", "следствие, импликация", "noun", "The implication is that earlier models were too narrow.", "Следствие в том, что прежние модели были слишком узкими."),
            _w("discrepancy", "/dɪˈskrep.ən.si/", "расхождение", "noun", "A discrepancy appeared between the two surveys.", "Между двумя опросами обнаружилось расхождение."),
            _w("premise", "/ˈprem.ɪs/", "предпосылка", "noun", "The argument rests on a shaky premise.", "Довод держится на шаткой предпосылке."),
            _w("discourse", "/ˈdɪs.kɔːs/", "дискурс", "noun", "Political discourse shifted after the report.", "Политический дискурс сместился после доклада."),
            _w("nuance", "/ˈnjuː.ɑːns/", "нюанс", "noun", "The translation missed an important nuance.", "В переводе потерялся важный нюанс."),
            _w("caveat", "/ˈkæv.i.æt/", "оговорка", "noun", "The authors added a caveat about sample size.", "Авторы добавили оговорку о размере выборки."),
            _w("thesis", "/ˈθiː.sɪs/", "диссертация; тезис", "noun", "Her thesis examines urban heat islands.", "Её диссертация посвящена городским островам тепла."),
            _w("methodology", "/ˌmeθ.əˈdɒl.ə.dʒi/", "методология", "noun", "The methodology section explains the interviews.", "В разделе методологии объясняются интервью."),
            _w("correlation", "/ˌkɒr.əˈleɪ.ʃən/", "корреляция", "noun", "Correlation is not the same as cause.", "Корреляция — это не то же самое, что причина."),
            _w("anomaly", "/əˈnɒm.ə.li/", "аномалия", "noun", "One anomaly distorted the yearly average.", "Одна аномалия исказила годовое среднее."),
            _w("abstraction", "/æbˈstræk.ʃən/", "абстракция", "noun", "The model is useful, but it is an abstraction.", "Модель полезна, но это абстракция."),
            _w("contingency", "/kənˈtɪn.dʒən.si/", "непредвиденное обстоятельство", "noun", "The plan includes a contingency for power cuts.", "В плане есть запасной вариант на случай отключения электричества."),
            _w("dichotomy", "/daɪˈkɒt.ə.mi/", "дихотомия", "noun", "The old dichotomy between work and rest no longer holds.", "Старая дихотомия работы и отдыха больше не работает."),
            _w("inference", "/ˈɪn.fər.əns/", "вывод", "noun", "That inference goes beyond the evidence.", "Этот вывод выходит за пределы доказательств."),
            _w("validity", "/vəˈlɪd.ə.ti/", "валидность", "noun", "They questioned the validity of the test.", "Они усомнились в валидности теста."),
            _w("framework", "/ˈfreɪm.wɜːk/", "рамка, концептуальная основа", "noun", "The chapter offers a simple analytical framework.", "Глава предлагает простую аналитическую рамку."),
        ],
    ),
]
