/** Common learner words → Russian gloss for hover tips in prompts/lessons. */
export const GLOSSARY: Record<string, string> = {
  a: "неопределённый артикль",
  an: "неопределённый артикль (перед гласной)",
  the: "определённый артикль",
  i: "я",
  you: "ты / вы",
  he: "он",
  she: "она",
  it: "оно / это",
  we: "мы",
  they: "они",
  me: "мне / меня",
  him: "ему / его",
  her: "ей / её",
  us: "нам / нас",
  them: "им / их",
  my: "мой",
  your: "твой / ваш",
  his: "его",
  its: "его / её (нейтр.)",
  our: "наш",
  their: "их",
  mine: "мой (абсолютное)",
  yours: "твой / ваш (абсолютное)",
  ours: "наш (абсолютное)",
  theirs: "их (абсолютное)",
  this: "этот / эта (близко)",
  that: "тот / та (далеко)",
  these: "эти (близко)",
  those: "те (далеко)",
  am: "форма to be (I)",
  is: "форма to be (he/she/it)",
  are: "форма to be (you/we/they)",
  was: "был / была (Past)",
  were: "были (Past)",
  be: "быть",
  been: "been (Perfect)",
  being: "being",
  have: "иметь / вспомог. have",
  has: "имеет / вспомог. has",
  had: "имел / had",
  do: "делать / вспомог. do",
  does: "делает / вспомог. does",
  did: "делал / вспомог. did",
  doing: "делая / doing",
  done: "сделано",
  can: "мочь / уметь",
  could: "мог / мог бы",
  will: "буду / will",
  would: "бы / would",
  should: "следует",
  must: "должен",
  may: "можно / может быть",
  might: "возможно",
  shall: "shall",
  need: "нуждаться",
  want: "хотеть",
  like: "нравиться",
  love: "любить",
  know: "знать",
  think: "думать",
  see: "видеть",
  saw: "видел",
  seen: "увиденный",
  look: "смотреть / выглядеть",
  watch: "смотреть (фильм и т.п.)",
  hear: "слышать",
  listen: "слушать",
  speak: "говорить",
  say: "сказать",
  said: "сказал",
  tell: "рассказать / сказать кому-то",
  ask: "спрашивать / просить",
  answer: "отвечать / ответ",
  go: "идти / ехать",
  goes: "идёт",
  went: "ходил / ездил",
  gone: "ушедший",
  come: "приходить",
  came: "пришёл",
  get: "получать / становиться",
  got: "получил",
  make: "делать / создавать",
  made: "сделал",
  take: "брать",
  took: "взял",
  taken: "взятый",
  give: "давать",
  gave: "дал",
  given: "данный",
  put: "класть",
  find: "находить",
  found: "нашёл",
  leave: "уходить / оставлять",
  left: "ушёл / левый",
  live: "жить",
  work: "работать / работа",
  study: "учиться",
  learn: "учить(ся)",
  teach: "учить (кого-то)",
  read: "читать",
  write: "писать",
  wrote: "написал",
  written: "написанный",
  buy: "покупать",
  bought: "купил",
  sell: "продавать",
  pay: "платить",
  eat: "есть",
  ate: "ел",
  eaten: "съеденный",
  drink: "пить",
  sleep: "спать",
  open: "открывать / открытый",
  close: "закрывать",
  closed: "закрытый",
  start: "начинать",
  finish: "заканчивать",
  help: "помогать / помощь",
  try: "пытаться",
  use: "использовать",
  call: "звонить / называть",
  wait: "ждать",
  meet: "встречать",
  play: "играть",
  run: "бегать",
  walk: "ходить пешком",
  drive: "водить",
  fly: "летать",
  travel: "путешествовать",
  stay: "оставаться",
  move: "переезжать / двигаться",
  feel: "чувствовать",
  felt: "чувствовал",
  keep: "держать / продолжать",
  let: "позволять",
  seem: "казаться",
  become: "становиться",
  became: "стал",
  bring: "приносить",
  brought: "принёс",
  send: "отправлять",
  sent: "отправил",
  show: "показывать",
  break: "ломать",
  broken: "сломанный",
  build: "строить",
  built: "построил",
  choose: "выбирать",
  chose: "выбрал",
  chosen: "выбранный",
  cut: "резать",
  draw: "рисовать",
  fall: "падать",
  fell: "упал",
  fallen: "упавший",
  grow: "расти",
  grew: "рос",
  grown: "выросший",
  hold: "держать",
  lose: "терять",
  lost: "потерял / потерянный",
  mean: "значить",
  meant: "значил",
  rise: "подниматься",
  rose: "поднялся",
  sit: "сидеть",
  sat: "сидел",
  stand: "стоять",
  stood: "стоял",
  understand: "понимать",
  understood: "понял",
  win: "побеждать",
  won: "выиграл",
  not: "не",
  no: "нет / никакой",
  yes: "да",
  and: "и",
  or: "или",
  but: "но",
  because: "потому что",
  if: "если",
  when: "когда",
  while: "пока / в то время как",
  before: "до / прежде чем",
  after: "после",
  then: "тогда / затем",
  so: "так / поэтому",
  than: "чем",
  as: "как / в роли",
  of: "… (родительный / of)",
  in: "в",
  on: "на",
  at: "у / в (точке)",
  to: "к / в / инфинитив",
  for: "для / в течение",
  from: "из / от",
  with: "с",
  without: "без",
  about: "о / около",
  into: "в (внутрь)",
  onto: "на (на поверхность)",
  over: "над / через",
  under: "под",
  between: "между",
  among: "среди",
  through: "через",
  during: "во время",
  until: "до тех пор пока",
  since: "с / с тех пор как",
  by: "к / у / кем-то",
  up: "вверх",
  down: "вниз",
  out: "наружу",
  off: "прочь / выключено",
  away: "прочь",
  back: "назад / спина",
  here: "здесь",
  there: "там",
  where: "где",
  why: "почему",
  how: "как",
  what: "что / какой",
  who: "кто",
  which: "который",
  whose: "чей",
  whom: "кому / кого",
  some: "несколько / немного",
  any: "какой-либо / любой",
  many: "много (исчисл.)",
  much: "много (неисчисл.)",
  more: "больше",
  most: "больше всего",
  few: "мало",
  little: "мало / маленький",
  lot: "много",
  all: "все / весь",
  every: "каждый",
  each: "каждый (по отдельности)",
  both: "оба",
  other: "другой",
  another: "ещё один",
  same: "тот же",
  different: "другой / разный",
  new: "новый",
  old: "старый",
  young: "молодой",
  good: "хороший",
  bad: "плохой",
  better: "лучше",
  best: "лучший",
  worse: "хуже",
  worst: "худший",
  big: "большой",
  small: "маленький",
  long: "длинный",
  short: "короткий",
  high: "высокий",
  low: "низкий",
  early: "ранний / рано",
  late: "поздний / поздно",
  right: "правильный / правый",
  wrong: "неправильный",
  true: "верный / истинный",
  false: "ложный",
  ready: "готовый",
  busy: "занятый",
  free: "свободный",
  happy: "счастливый",
  sad: "грустный",
  tired: "уставший",
  hungry: "голодный",
  thirsty: "хочется пить",
  hot: "горячий / жаркий",
  cold: "холодный",
  warm: "тёплый",
  cool: "прохладный",
  clean: "чистый",
  dirty: "грязный",
  easy: "лёгкий",
  hard: "трудный / твёрдый",
  difficult: "сложный",
  important: "важный",
  interesting: "интересный",
  beautiful: "красивый",
  nice: "приятный / милый",
  great: "отличный / великий",
  next: "следующий",
  last: "прошлый / последний",
  first: "первый",
  second: "второй",
  third: "третий",
  today: "сегодня",
  yesterday: "вчера",
  tomorrow: "завтра",
  now: "сейчас",
  always: "всегда",
  usually: "обычно",
  often: "часто",
  sometimes: "иногда",
  never: "никогда",
  already: "уже",
  yet: "ещё / уже (в вопросе/отриц.)",
  still: "всё ещё",
  just: "только что / просто",
  soon: "скоро",
  ago: "назад (по времени)",
  once: "однажды / один раз",
  twice: "дважды",
  again: "снова",
  also: "также",
  too: "тоже / слишком",
  very: "очень",
  really: "действительно",
  quite: "довольно",
  only: "только",
  even: "даже",
  almost: "почти",
  enough: "достаточно",
  please: "пожалуйста",
  thanks: "спасибо",
  thank: "благодарить",
  sorry: "извините",
  hello: "привет",
  hi: "привет",
  goodbye: "до свидания",
  yes: "да",
  people: "люди",
  person: "человек",
  man: "мужчина",
  men: "мужчины",
  woman: "женщина",
  women: "женщины",
  child: "ребёнок",
  children: "дети",
  boy: "мальчик",
  girl: "девочка",
  friend: "друг",
  family: "семья",
  mother: "мать",
  father: "отец",
  parents: "родители",
  brother: "брат",
  sister: "сестра",
  son: "сын",
  daughter: "дочь",
  husband: "муж",
  wife: "жена",
  baby: "малыш",
  colleague: "коллега",
  colleagues: "коллеги",
  teacher: "учитель",
  teachers: "учителя",
  student: "студент / ученик",
  students: "студенты / ученики",
  doctor: "врач",
  doctors: "врачи",
  engineer: "инженер",
  manager: "менеджер",
  neighbour: "сосед",
  neighbours: "соседи",
  neighbor: "сосед",
  neighbors: "соседи",
  job: "работа",
  office: "офис",
  laptop: "ноутбук",
  sofa: "диван",
  piano: "пианино",
  report: "отчёт",
  email: "письмо (эл.)",
  emails: "письма (эл.)",
  storm: "шторм / буря",
  visitor: "посетитель",
  visitors: "посетители",
  canada: "Канада",
  lisbon: "Лиссабон",
  madrid: "Мадрид",
  school: "школа",
  university: "университет",
  class: "урок / класс",
  lesson: "урок",
  homework: "домашнее задание",
  book: "книга",
  books: "книги",
  pen: "ручка",
  paper: "бумага",
  phone: "телефон",
  computer: "компьютер",
  car: "машина",
  bus: "автобус",
  train: "поезд",
  plane: "самолёт",
  bike: "велосипед",
  home: "дом / домой",
  house: "дом (здание)",
  room: "комната",
  door: "дверь",
  window: "окно",
  windows: "окна",
  table: "стол",
  chair: "стул",
  bed: "кровать",
  kitchen: "кухня",
  bathroom: "ванная",
  city: "город",
  town: "городок",
  street: "улица",
  shop: "магазин",
  store: "магазин",
  market: "рынок",
  restaurant: "ресторан",
  cafe: "кафе",
  hotel: "отель",
  hospital: "больница",
  bank: "банк",
  park: "парк",
  country: "страна / сельская местность",
  world: "мир",
  water: "вода",
  food: "еда",
  bread: "хлеб",
  milk: "молоко",
  coffee: "кофе",
  tea: "чай",
  apple: "яблоко",
  apples: "яблоки",
  fruit: "фрукты",
  meat: "мясо",
  fish: "рыба",
  breakfast: "завтрак",
  lunch: "обед",
  dinner: "ужин",
  money: "деньги",
  time: "время",
  day: "день",
  week: "неделя",
  month: "месяц",
  year: "год",
  hour: "час",
  minute: "минута",
  morning: "утро",
  afternoon: "день (после полудня)",
  evening: "вечер",
  night: "ночь",
  weather: "погода",
  sun: "солнце",
  rain: "дождь",
  snow: "снег",
  wind: "ветер",
  name: "имя",
  age: "возраст",
  language: "язык",
  english: "английский",
  russian: "русский",
  word: "слово",
  sentence: "предложение",
  question: "вопрос",
  problem: "проблема",
  idea: "идея",
  story: "история",
  news: "новости",
  music: "музыка",
  film: "фильм",
  movie: "фильм",
  game: "игра",
  sport: "спорт",
  bag: "сумка",
  key: "ключ",
  keys: "ключи",
  ticket: "билет",
  map: "карта",
  photo: "фото",
  picture: "картинка",
  color: "цвет",
  colour: "цвет",
  red: "красный",
  blue: "синий",
  green: "зелёный",
  yellow: "жёлтый",
  black: "чёрный",
  white: "белый",
  one: "один",
  two: "два",
  three: "три",
  four: "четыре",
  five: "пять",
  six: "шесть",
  seven: "семь",
  eight: "восемь",
  nine: "девять",
  ten: "десять",
  hundred: "сто",
  thousand: "тысяча",
  spain: "Испания",
  london: "Лондон",
  past: "прошлое / прошедшее",
  present: "настоящее",
  future: "будущее",
  perfect: "Perfect (время)",
  simple: "Simple (время)",
  continuous: "Continuous (время)",
  passive: "пассивный залог",
  active: "активный залог",
  singular: "единственное число",
  plural: "множественное число",
  subject: "подлежащее",
  object: "дополнение",
  verb: "глагол",
  noun: "существительное",
  adjective: "прилагательное",
  adverb: "наречие",
  article: "артикль",
  preposition: "предлог",
  pronoun: "местоимение",
  clinic: "клиника",
  shop: "магазин",
  birds: "птицы",
  box: "коробка",
  boxes: "коробки",
  tomato: "помидор",
  tomatoes: "помидоры",
  sheep: "овца / овцы",
  feet: "ноги / футы",
  foot: "нога / фут",
  news: "новости",
  sugar: "сахар",
  room: "комната",
  letter: "письмо",
  gym: "спортзал",
  monday: "понедельник",
  tuesday: "вторник",
  wednesday: "среда",
  thursday: "четверг",
  friday: "пятница",
  saturday: "суббота",
  sunday: "воскресенье",
};

const SKIP = new Set([
  "a",
  "an",
  "the",
  "to",
  "of",
  "in",
  "on",
  "at",
  "for",
  "and",
  "or",
  "but",
  "is",
  "are",
  "am",
  "be",
  "do",
  "does",
  "did",
  "not",
  "i",
]);

export function lookupGloss(raw: string): string | null {
  const key = raw
    .toLowerCase()
    .replace(/^[^a-z']+|[^a-z']+$/gi, "")
    .replace(/'s$/, "")
    .replace(/n't$/, " not");
  if (!key || key.length < 2) return null;
  if (SKIP.has(key) && key.length <= 3) {
    // still show short function words — useful for beginners
  }
  return GLOSSARY[key] || null;
}
