/**
 * Offline EN→RU glosses for hover tips on **lesson example** English only
 * (`LessonView` examples / compare rows — not quiz prompts or app chrome).
 *
 * Regenerated / extended via `frontend/scripts/build_glossary.py`
 * from vocabulary harvested in lesson seeds (`ex(en, ru)`, compare left/right).
 */
export const GLOSSARY: Record<string, string> = {
  a: "неопределённый артикль",
  about: "о / около",
  above: "над / выше",
  abroad: "за границей",
  accent: "акцент",
  accepted: "принял / принятый",
  access: "доступ",
  according: "согласно",
  accuracy: "точность",
  accused: "обвинил / обвинённый",
  across: "через / поперёк",
  active: "активный залог",
  actually: "на самом деле",
  adapter: "адаптер",
  add: "добавлять",
  adjective: "прилагательное",
  adverb: "наречие",
  advice: "совет",
  after: "после",
  afternoon: "день (после полудня)",
  again: "снова",
  against: "против",
  age: "возраст",
  ago: "назад (по времени)",
  agreed: "согласился",
  airport: "аэропорт",
  aisle: "проход (между рядами)",
  aligned: "выровненный",
  all: "все / весь",
  alleged: "предполагаемый / мнимый",
  allegedly: "якобы",
  almost: "почти",
  along: "вдоль / вместе",
  already: "уже",
  also: "также",
  always: "всегда",
  am: "форма to be (I)",
  among: "среди",
  an: "неопределённый артикль (перед гласной)",
  and: "и",
  angered: "рассердил / разозлённый",
  ankle: "лодыжка",
  anna: "Анна",
  announced: "объявил",
  announcement: "объявление",
  annoying: "раздражающий",
  anomaly: "аномалия",
  another: "ещё один",
  answer: "отвечать / ответ",
  answering: "отвечая / ответ",
  any: "какой-либо / любой",
  anyone: "кто-нибудь / любой",
  anything: "что-нибудь / что угодно",
  apologised: "извинился",
  app: "приложение",
  appear: "появляться / казаться",
  appears: "появляется / кажется",
  apple: "яблоко",
  apples: "яблоки",
  applied: "применил / подал заявку",
  april: "апрель",
  arabic: "арабский",
  archive: "архив",
  archived: "архивированный",
  are: "форма to be (you/we/they)",
  arguably: "можно сказать / спорно",
  arguing: "споря / ссорясь",
  arrive: "прибывать",
  arrived: "прибыл",
  arrives: "прибывает",
  artefact: "артефакт",
  article: "артикль",
  articles: "статьи / артикли",
  artist: "художник / артист",
  as: "как / в роли",
  ask: "спрашивать / просить",
  asked: "спросил / попросил",
  assay: "анализ / проба",
  at: "у / в (точке)",
  ate: "ел",
  attributed: "приписал / отнесённый",
  audit: "аудит / проверка",
  aunt: "тётя",
  automatic: "автоматический",
  autopilot: "автопилот",
  avoid: "избегать",
  avoided: "избежал",
  aware: "осведомлённый",
  away: "прочь",
  babies: "младенцы",
  baby: "малыш",
  back: "назад / спина",
  backfilled: "заполнил задним числом",
  backlog: "очередь невыполненного",
  backpack: "рюкзак",
  backup: "резервная копия",
  bad: "плохой",
  badge: "значок / бейдж",
  bag: "сумка",
  baked: "испечённый / пёк",
  baker: "пекарь",
  balcony: "балкон",
  bank: "банк",
  barge: "баржа",
  bass: "бас / окунь",
  batch: "партия / пакет",
  bathroom: "ванная",
  batteries: "батарейки",
  battery: "батарейка / аккумулятор",
  be: "быть",
  beach: "пляж",
  beacon: "маяк / маячок",
  beam: "луч / балка",
  beautiful: "красивый",
  became: "стал",
  because: "потому что",
  become: "становиться",
  bed: "кровать",
  been: "been (Perfect)",
  before: "до / прежде чем",
  begun: "начатый (begun)",
  being: "being",
  believed: "верил / полагал",
  belong: "принадлежать",
  below: "ниже / под",
  bergen: "Берген",
  beside: "рядом с",
  best: "лучший",
  beta: "бета (версия)",
  better: "лучше",
  between: "между",
  big: "большой",
  bigger: "больше",
  bike: "велосипед",
  bikes: "велосипеды",
  bill: "счёт / законопроект",
  binder: "папка / скоросшиватель",
  birds: "птицы",
  birthday: "день рождения",
  biscuit: "печенье",
  bit: "немного / бит",
  bite: "кусать / укус",
  black: "чёрный",
  blamed: "обвинил / винил",
  blood: "кровь",
  blotting: "промокание / blotting",
  blue: "синий",
  board: "доска / борт",
  boarded: "сел (на транспорт)",
  boat: "лодка / судно",
  boiling: "кипящий / кипячение",
  boils: "кипит",
  bolts: "болты",
  book: "книга",
  booked: "забронировал",
  books: "книги",
  boot: "ботинок / багажник",
  born: "рожденный",
  boss: "начальник",
  both: "оба",
  bought: "купил",
  bounced: "отскочил / отклонили (чек)",
  bowls: "миски",
  box: "коробка",
  boxed: "в коробке / упакованный",
  boxes: "коробки",
  boy: "мальчик",
  branch: "ветка / филиал",
  bread: "хлеб",
  break: "ломать",
  breakfast: "завтрак",
  bridge: "мост",
  bridges: "мосты",
  briefing: "брифинг / инструктаж",
  bright: "яркий",
  bring: "приносить",
  brittle: "хрупкий",
  broken: "сломанный",
  brother: "брат",
  brought: "принёс",
  brown: "коричневый",
  build: "строить",
  building: "здание / строительство",
  built: "построил",
  bulletin: "бюллетень",
  bus: "автобус",
  buses: "автобусы",
  busy: "занятый",
  but: "но",
  buy: "покупать",
  by: "к / у / кем-то",
  cafe: "кафе",
  cairo: "Каир",
  call: "звонить / называть",
  called: "назвал / позвонил",
  calls: "звонки / зовёт",
  calm: "спокойный / спокойствие",
  came: "пришёл",
  can: "мочь / уметь",
  canada: "Канада",
  cancel: "отменять",
  cancelled: "отменённый",
  cannot: "не могу / нельзя",
  canvas: "холст / парусина",
  caption: "подпись (к изображению)",
  captions: "субтитры / подписи",
  car: "машина",
  careful: "осторожный",
  carefully: "осторожно",
  carriage: "вагон / экипаж",
  carry: "нести / возить",
  cars: "машины",
  cart: "тележка",
  cash: "наличные",
  casual: "повседневный / непринуждённый",
  cat: "кот / кошка",
  cats: "кошки",
  caught: "поймал",
  cause: "причина / вызывать",
  caused: "вызвал",
  cellar: "погреб / подвал",
  ceremony: "церемония",
  chair: "стул",
  chairs: "стулья",
  challenged: "оспорил / бросил вызов",
  change: "менять / сдача",
  changing: "меняя / смена",
  channel: "канал",
  chapter: "глава",
  chapters: "главы",
  charger: "зарядное устройство",
  chart: "график / таблица",
  cheap: "дешёвый",
  cheaper: "дешевле",
  cheapest: "самый дешёвый",
  check: "проверять / чек",
  checked: "проверил",
  child: "ребёнок",
  children: "дети",
  chocolate: "шоколад",
  choir: "хор",
  choose: "выбирать",
  chose: "выбрал",
  chosen: "выбранный",
  cinema: "кинотеатр",
  circulated: "распространил / циркулировал",
  city: "город",
  claim: "утверждать / претензия",
  class: "урок / класс",
  clause: "пункт / придаточное",
  clean: "чистый",
  cleaned: "убрал / почистил",
  cleanly: "чисто / аккуратно",
  cleared: "очистил / разрешил",
  clears: "очищает",
  clerk: "клерк / служащий",
  client: "клиент",
  clinic: "клиника",
  clips: "зажимы / клипы",
  close: "закрывать",
  closed: "закрытый",
  closer: "ближе / ближе к",
  closes: "закрывает",
  closing: "закрытие / закрывающий",
  clouds: "облака",
  coach: "тренер / автобус",
  coaches: "тренеры / вагоны",
  coast: "побережье",
  coastal: "прибрежный",
  coat: "пальто / слой",
  code: "код",
  coffee: "кофе",
  cold: "холодный",
  colleague: "коллега",
  colleagues: "коллеги",
  college: "колледж",
  color: "цвет",
  colour: "цвет",
  come: "приходить",
  commenced: "начался / приступил",
  compulsory: "обязательный",
  computer: "компьютер",
  concert: "концерт",
  contact: "контакт / связаться",
  continuous: "Continuous (время)",
  contractor: "подрядчик",
  contradict: "противоречить",
  cook: "готовить / повар",
  cooked: "приготовил / варёный",
  cooking: "готовка",
  cooks: "готовит / повара",
  cool: "прохладный",
  copied: "скопировал",
  copies: "копии / копирует",
  cork: "пробка",
  corpus: "корпус (текстов)",
  correspondence: "переписка",
  corridor: "коридор",
  could: "мог / мог бы",
  count: "считать / граф",
  counter: "прилавок / счётчик",
  country: "страна / сельская местность",
  course: "курс / блюдо",
  courtyard: "двор",
  covers: "покрывает / обложки",
  cracked: "треснувший / взломанный",
  crashed: "разбился / рухнул",
  crate: "ящик (грузовой)",
  crates: "ящики",
  crew: "экипаж / команда",
  cross: "пересекать / крест",
  crossing: "переход / пересечение",
  crossings: "переходы",
  crumbs: "крошки",
  crying: "плачущий / плач",
  cup: "чашка",
  curator: "куратор",
  cured: "вылечил / засолил",
  customs: "таможня",
  cut: "резать",
  cycle: "цикл / ездить на велосипеде",
  cyclist: "велосипедист",
  dad: "папа",
  damaged: "повреждённый",
  damp: "сырой / влажный",
  dark: "тёмный / темнота",
  date: "дата / свидание",
  dated: "датированный / устаревший",
  daughter: "дочь",
  dawn: "рассвет",
  day: "день",
  daylight: "дневной свет",
  days: "дни",
  deadline: "срок сдачи",
  decided: "решил",
  decision: "решение",
  deck: "палуба / колода",
  decline: "отклонять / спад",
  declined: "отклонил / отказался",
  delay: "задержка",
  delayed: "задержанный",
  demanded: "потребовал",
  depot: "депо / склад",
  designers: "дизайнеры",
  desirable: "желательный",
  desk: "письменный стол",
  did: "делал / вспомог. did",
  dies: "умирает",
  different: "другой / разный",
  difficult: "сложный",
  dinner: "ужин",
  diplomatic: "дипломатический",
  dirty: "грязный",
  discussed: "обсудил",
  distrust: "недоверие / не доверять",
  distrusts: "не доверяет",
  dive: "нырять / погружение",
  do: "делать / вспомог. do",
  doctor: "врач",
  doctors: "врачи",
  documentary: "документальный фильм",
  does: "делает / вспомог. does",
  dog: "собака",
  doing: "делая / doing",
  done: "сделано",
  door: "дверь",
  doors: "двери",
  doubt: "сомнение / сомневаться",
  down: "вниз",
  draft: "черновик / сквозняк",
  drafts: "черновики",
  draw: "рисовать",
  drawer: "ящик (стола)",
  dream: "сон / мечта",
  dried: "высушенный / высох",
  drilling: "сверление",
  drink: "пить",
  drinking: "питьё / пьющий",
  drinks: "напитки / пьёт",
  drive: "водить",
  driver: "водитель",
  driving: "вождение",
  drone: "дрон",
  dropped: "уронил / снизился",
  drum: "барабан",
  dry: "сухой / сушить",
  during: "во время",
  dusk: "сумерки",
  each: "каждый (по отдельности)",
  earlier: "раньше",
  early: "ранний / рано",
  easier: "легче",
  easily: "легко",
  east: "восток / восточный",
  easy: "лёгкий",
  eat: "есть",
  eaten: "съеденный",
  eats: "ест",
  editing: "редактирование",
  editor: "редактор",
  editorial: "редакционный / передовица",
  eggs: "яйца",
  eight: "восемь",
  either: "либо / тоже (отриц.)",
  electrician: "электрик",
  email: "письмо (эл.)",
  emailed: "написал по email",
  emails: "письма (эл.)",
  empty: "пустой",
  emulsion: "эмульсия",
  encore: "бис / на бис",
  end: "конец / заканчивать",
  engine: "двигатель",
  engineer: "инженер",
  english: "английский",
  enjoy: "наслаждаться",
  enough: "достаточно",
  entire: "весь / целый",
  entries: "записи / входы",
  error: "ошибка",
  errors: "ошибки",
  escort: "эскорт / сопровождать",
  essay: "эссе / сочинение",
  essential: "существенный / необходимый",
  estimated: "оценённый / примерно",
  even: "даже",
  evening: "вечер",
  event: "событие",
  ever: "когда-либо",
  every: "каждый",
  everyone: "все / каждый",
  exam: "экзамен",
  exams: "экзамены",
  excellent: "отличный",
  exhibit: "экспонат / выставлять",
  expect: "ожидать",
  expensive: "дорогой",
  expiry: "истечение срока",
  explain: "объяснять",
  explained: "объяснил",
  express: "выражать / экспресс",
  extension: "расширение / добавочный",
  extra: "дополнительный",
  eyes: "глаза",
  fail: "провалиться / не удаться",
  failed: "провалился / не удалось",
  failure: "неудача / отказ",
  fall: "падать",
  fallen: "упавший",
  false: "ложный",
  family: "семья",
  fan: "фанат / вентилятор",
  far: "далеко",
  faster: "быстрее",
  father: "отец",
  fatigue: "усталость",
  fee: "плата / сбор",
  feel: "чувствовать",
  feels: "чувствует / ощущается",
  feet: "ноги / футы",
  fell: "упал",
  fellowship: "стипендия / братство",
  fellowships: "стипендии",
  felt: "чувствовал",
  fennel: "фенхель",
  ferry: "паром",
  few: "мало",
  fiddle: "скрипка / возиться",
  field: "поле / область",
  fifty: "пятьдесят",
  figures: "цифры / фигуры",
  file: "файл / подпиливать",
  filed: "подал / подшил",
  files: "файлы",
  film: "фильм",
  films: "фильмы",
  final: "финальный / итог",
  finally: "наконец",
  finance: "финансы / финансировать",
  find: "находить",
  fine: "штраф / хорошо",
  finish: "заканчивать",
  finished: "закончил",
  first: "первый",
  fish: "рыба",
  five: "пять",
  fixed: "починил / фиксированный",
  flagged: "отметил флажком",
  flask: "фляга / колба",
  flat: "квартира / плоский",
  flight: "рейс / полёт",
  flip: "перевернуть",
  flooded: "затопленный",
  floodlights: "прожекторы",
  flour: "мука",
  fly: "летать",
  flying: "летающий / полёт",
  fob: "брелок / обмануть",
  fog: "туман",
  folds: "складки / складывает",
  food: "еда",
  fool: "дурак / обманывать",
  foot: "нога / фут",
  football: "футбол",
  footnotes: "сноски",
  for: "для / в течение",
  forget: "забывать",
  forgotten: "забытый",
  forty: "сорок",
  found: "нашёл",
  foundry: "литейный цех",
  four: "четыре",
  frame: "рамка / кадр",
  free: "свободный",
  freeze: "замерзать / замораживать",
  french: "французский",
  friday: "пятница",
  fridays: "пятницы",
  fridge: "холодильник",
  friend: "друг",
  friends: "друзья",
  from: "из / от",
  front: "перед / фронт",
  froze: "замёрз / заморозил",
  frozen: "замёрзший / замороженный",
  fruit: "фрукты",
  full: "полный",
  funders: "спонсоры / фонды",
  funny: "смешной",
  furniture: "мебель",
  future: "будущее",
  game: "игра",
  garden: "сад",
  gasket: "прокладка (уплотнение)",
  gate: "ворота / выход (в аэропорту)",
  gather: "собирать",
  gave: "дал",
  generator: "генератор",
  german: "немецкий",
  get: "получать / становиться",
  gets: "получает / становится",
  getting: "получая / становясь",
  girl: "девочка",
  give: "давать",
  given: "данный",
  glass: "стекло / стакан",
  go: "идти / ехать",
  goes: "идёт",
  going: "идущий / собирающийся",
  gone: "ушедший",
  good: "хороший",
  goodbye: "до свидания",
  got: "получил",
  grade: "оценка / класс",
  grandma: "бабушка",
  grandparents: "бабушка и дедушка",
  great: "отличный / великий",
  green: "зелёный",
  grew: "рос",
  grey: "серый",
  grow: "расти",
  grown: "выросший",
  gym: "спортзал",
  had: "имел / had",
  hair: "волосы",
  half: "половина",
  hall: "зал / холл",
  halt: "остановка / остановить",
  hands: "руки",
  hang: "висеть / вешать",
  happier: "счастливее",
  happily: "счастливо",
  happy: "счастливый",
  harbour: "гавань / порт",
  hard: "трудный / твёрдый",
  hardly: "едва / почти не",
  has: "имеет / вспомог. has",
  hatch: "люк / вылупляться",
  hate: "ненавидеть",
  hates: "ненавидит",
  have: "иметь / вспомог. have",
  having: "имея / having",
  he: "он",
  headaches: "головные боли",
  hear: "слышать",
  heard: "слышал",
  heat: "жара / нагревать",
  heating: "отопление",
  heights: "высоты",
  hello: "привет",
  help: "помогать / помощь",
  helped: "помог",
  her: "ей / её",
  here: "здесь",
  hi: "привет",
  high: "высокий",
  higher: "выше",
  him: "ему / его",
  his: "его",
  hold: "держать",
  home: "дом / домой",
  homework: "домашнее задание",
  honour: "честь / чтить",
  hook: "крючок",
  hop: "прыгать / хмель",
  hope: "надеяться / надежда",
  hopes: "надежды / надеется",
  hoping: "надеясь",
  horse: "лошадь",
  hospital: "больница",
  hot: "горячий / жаркий",
  hotel: "отель",
  hour: "час",
  hours: "часы (время)",
  house: "дом (здание)",
  housing: "жильё",
  how: "как",
  however: "однако",
  hub: "узел / хаб",
  hull: "корпус (судна)",
  hum: "жужжать / гул",
  hundred: "сто",
  hung: "повесил / висел",
  hungry: "голодный",
  hunting: "охота",
  hurry: "спешить / спешка",
  hurt: "причинять боль / больно",
  husband: "муж",
  i: "я",
  i'd: "я бы / я имел",
  i'll: "я буду",
  i'm: "я есть",
  i've: "я имею",
  ice: "лёд",
  idea: "идея",
  if: "если",
  ignored: "проигнорировал",
  ill: "больной",
  impeller: "крыльчатка",
  important: "важный",
  in: "в",
  inaccurate: "неточный",
  informal: "неформальный",
  information: "информация",
  ink: "чернила",
  inquiry: "запрос / расследование",
  ins: "входы / инсайды",
  inside: "внутри",
  insist: "настаивать",
  insisted: "настоял",
  insistence: "настойчивость",
  inspected: "осмотрел / проверил",
  inspection: "осмотр / проверка",
  instability: "нестабильность",
  interesting: "интересный",
  intern: "стажёр",
  interrupt: "прерывать",
  interrupted: "прервал",
  interview: "интервью / собеседование",
  into: "в (внутрь)",
  invoice: "счёт-фактура",
  invoices: "счета-фактуры",
  irritated: "раздражённый",
  is: "форма to be (he/she/it)",
  issued: "выдал / выпущенный",
  it: "оно / это",
  it'll: "это будет",
  its: "его / её (нейтр.)",
  jacket: "куртка / пиджак",
  jammed: "заклинило / застрял",
  jar: "банка",
  jazz: "джаз",
  job: "работа",
  july: "июль",
  june: "июнь",
  just: "только что / просто",
  keep: "держать / продолжать",
  key: "ключ",
  keys: "ключи",
  kids: "дети / ребята",
  killed: "убил",
  kimchi: "кимчи",
  kind: "добрый / вид",
  kitchen: "кухня",
  knew: "знал",
  knighthood: "рыцарское звание",
  knocked: "постучал / сбил",
  knots: "узлы",
  know: "знать",
  known: "известный / известный",
  lab: "лаборатория",
  labelled: "с этикеткой / помеченный",
  lamp: "лампа",
  landed: "приземлился",
  landings: "посадки",
  lane: "полоса / переулок",
  language: "язык",
  lapse: "промах / истечение",
  laptop: "ноутбук",
  last: "прошлый / последний",
  late: "поздний / поздно",
  later: "позже",
  launch: "запуск / запускать",
  law: "закон",
  lay: "класть / лежал",
  laying: "укладка / кладя",
  leak: "утечка",
  leaked: "протёк / утекли данные",
  leaking: "протекающий",
  learn: "учить(ся)",
  leave: "уходить / оставлять",
  leaves: "листья / уходит",
  leaving: "уходя / отъезд",
  ledger: "гроссбух / реестр",
  left: "ушёл / левый",
  legal: "юридический / законный",
  lens: "линза / объектив",
  less: "меньше",
  lesson: "урок",
  let: "позволять",
  letter: "письмо",
  liable: "ответственный / склонный",
  licence: "лицензия",
  lift: "лифт / поднимать",
  light: "свет / лёгкий",
  lights: "огни / фонари",
  like: "нравиться",
  likely: "вероятно",
  likes: "нравится / лайки",
  line: "линия / очередь",
  lining: "подкладка",
  link: "ссылка / связь",
  links: "ссылки / связи",
  lisbon: "Лиссабон",
  listed: "перечисленный / в списке",
  listen: "слушать",
  listening: "слушание / слушающий",
  lit: "зажжённый / осветил",
  little: "мало / маленький",
  live: "жить",
  lived: "жил",
  lives: "живёт / жизни",
  living: "жизнь / живущий",
  load: "груз / загружать",
  lobby: "вестибюль / лобби",
  local: "местный",
  lock: "замок / запирать",
  locked: "запертый",
  locker: "шкафчик",
  locking: "запирание",
  loft: "чердак / лофт",
  log: "журнал / бревно",
  logged: "записанный / вошёл",
  logging: "ведение журнала / лесозаготовка",
  logs: "журналы / брёвна",
  london: "Лондон",
  long: "длинный",
  look: "смотреть / выглядеть",
  looking: "смотрящий / выглядящий",
  looks: "выглядит / взгляды",
  loomed: "навис / замаячил",
  lose: "терять",
  lost: "потерял / потерянный",
  lot: "много",
  love: "любить",
  lovely: "прелестный / чудесный",
  low: "низкий",
  lunch: "обед",
  machine: "машина / аппарат",
  made: "сделал",
  madrid: "Мадрид",
  main: "главный",
  make: "делать / создавать",
  man: "мужчина",
  manager: "менеджер",
  many: "много (исчисл.)",
  map: "карта",
  mara: "Мара",
  march: "март / марш",
  mark: "отметка / отмечать",
  marked: "отмеченный",
  marker: "маркер",
  market: "рынок",
  master: "мастер / главный",
  masts: "мачты",
  matched: "совпал / подобрал",
  math: "математика",
  maths: "математика",
  may: "можно / может быть",
  me: "мне / меня",
  mean: "значить",
  meant: "значил",
  measured: "измерил",
  measurement: "измерение",
  measurements: "измерения",
  meat: "мясо",
  medicine: "лекарство / медицина",
  meet: "встречать",
  meeting: "встреча / собрание",
  mek: "Мек",
  melting: "таяние / тающий",
  melts: "тает",
  men: "мужчины",
  message: "сообщение",
  messages: "сообщения",
  met: "встретил",
  method: "метод",
  metro: "метро",
  might: "возможно",
  milk: "молоко",
  mind: "разум / возражать",
  mine: "мой (абсолютное)",
  minute: "минута",
  minutes: "минуты / протокол",
  mislabels: "неверно маркирует",
  mismatch: "несоответствие",
  miss: "скучать / промахнуться",
  missed: "пропустил / скучал",
  missing: "отсутствующий / пропавший",
  mistake: "ошибка",
  mix: "смешивать / смесь",
  moment: "момент",
  monday: "понедельник",
  money: "деньги",
  month: "месяц",
  moon: "луна",
  more: "больше",
  morning: "утро",
  most: "больше всего",
  mother: "мать",
  move: "переезжать / двигаться",
  movie: "фильм",
  much: "много (неисчисл.)",
  mugs: "кружки",
  mum: "мама",
  mural: "настенная роспись",
  museum: "музей",
  mushroom: "гриб",
  music: "музыка",
  must: "должен",
  muted: "приглушённый",
  my: "мой",
  name: "имя",
  names: "имена / называет",
  narva: "Нарва",
  near: "рядом / около",
  nearer: "ближе",
  need: "нуждаться",
  needed: "нужный / понадобился",
  needs: "нуждается / нужды",
  negatives: "отрицания / негативы",
  neighbor: "сосед",
  neighbors: "соседи",
  neighbour: "сосед",
  neighbours: "соседи",
  neither: "ни тот ни другой",
  never: "никогда",
  new: "новый",
  news: "новости",
  next: "следующий",
  nice: "приятный / милый",
  night: "ночь",
  nights: "ночи",
  nine: "девять",
  no: "нет / никакой",
  nobody: "никто",
  noise: "шум",
  noisy: "шумный",
  noon: "полдень",
  north: "север / северный",
  not: "не",
  notebooks: "блокноты",
  noticed: "заметил",
  noun: "существительное",
  novel: "роман / новый",
  now: "сейчас",
  number: "число / номер",
  numbers: "числа / номера",
  nurse: "медсестра / няня",
  object: "дополнение",
  objected: "возразил",
  objection: "возражение",
  objections: "возражения",
  obtain: "получить / добиться",
  obvious: "очевидный",
  odd: "странный / нечётный",
  of: "… (родительный / of)",
  off: "прочь / выключено",
  offer: "предложение / предлагать",
  offered: "предложил",
  office: "офис",
  offline: "офлайн",
  often: "часто",
  oil: "масло / нефть",
  old: "старый",
  oldest: "самый старый",
  omission: "пропуск / упущение",
  on: "на",
  once: "однажды / один раз",
  one: "один",
  ones: "те / ones",
  online: "онлайн",
  only: "только",
  onto: "на (на поверхность)",
  open: "открывать / открытый",
  opened: "открыл",
  opening: "открытие / отверстие",
  opens: "открывает",
  opposite: "противоположный / напротив",
  option: "вариант / опция",
  or: "или",
  orders: "заказы / приказы",
  osaka: "Осака",
  oslo: "Осло",
  other: "другой",
  our: "наш",
  ours: "наш (абсолютное)",
  out: "наружу",
  outside: "снаружи",
  over: "над / через",
  overnight: "на ночь / за ночь",
  override: "переопределить / отменить",
  own: "свой / владеть",
  pack: "упаковывать / пачка",
  package: "пакет / посылка",
  packed: "упакованный",
  packing: "упаковка",
  paid: "оплатил / оплаченный",
  painted: "покрасил / нарисованный",
  painting: "картина / покраска",
  paintings: "картины",
  paper: "бумага",
  parapet: "парапет",
  parents: "родители",
  paris: "Париж",
  park: "парк",
  parked: "припаркованный",
  parts: "части / детали",
  party: "вечеринка / партия",
  pass: "проходить / передавать",
  passed: "прошёл / передал",
  passengers: "пассажиры",
  passes: "проходит / пропуска",
  passing: "проходящий / передача",
  passive: "пассивный залог",
  past: "прошлое / прошедшее",
  pasta: "паста",
  path: "путь / тропа",
  patience: "терпение",
  pavement: "тротуар",
  pay: "платить",
  payment: "платёж",
  pen: "ручка",
  people: "люди",
  perfect: "Perfect (время)",
  perished: "погиб / испортился",
  permitting: "разрешая / разрешение",
  person: "человек",
  personal: "личный",
  persuaded: "убедил",
  phone: "телефон",
  phones: "телефоны",
  photo: "фото",
  piano: "пианино",
  picked: "выбрал / поднял",
  picture: "картинка",
  piece: "кусок / штука",
  pier: "пирс / пристань",
  pilot: "пилот",
  pilots: "пилоты",
  pinned: "закрепил булавкой",
  plane: "самолёт",
  plates: "тарелки / пластины",
  platform: "платформа",
  play: "играть",
  played: "играл",
  player: "игрок",
  playing: "играя / игра",
  please: "пожалуйста",
  plumber: "сантехник",
  plural: "множественное число",
  police: "полиция",
  porto: "Порту",
  post: "почта / пост",
  postcard: "открытка",
  posting: "размещение / отправка",
  postpone: "откладывать",
  postponement: "отсрочка",
  postponing: "откладывая",
  pour: "лить / наливать",
  practical: "практический",
  practising: "практикуясь / репетируя",
  prefer: "предпочитать",
  preposition: "предлог",
  present: "настоящее",
  press: "нажимать / пресса",
  print: "печатать / оттиск",
  printed: "напечатанный",
  printer: "принтер",
  private: "частный / личный",
  problem: "проблема",
  projector: "проектор",
  promised: "пообещал",
  pronoun: "местоимение",
  proofed: "вычитал / проверил",
  proofs: "корректуры / доказательства",
  proved: "доказал",
  provided: "предоставил / при условии",
  published: "опубликованный",
  pulley: "блок / шкив",
  pump: "насос / качать",
  put: "класть",
  putting: "кладя / ставя",
  quarter: "четверть / квартал",
  quay: "причал / набережная",
  question: "вопрос",
  questions: "вопросы",
  queuing: "стоя в очереди",
  quieter: "тише",
  quietly: "тихо",
  quite: "довольно",
  radio: "радио",
  rail: "рельс / перила",
  rain: "дождь",
  rained: "шёл дождь",
  raining: "идёт дождь",
  rains: "дожди / идёт дождь",
  ran: "бежал",
  rarely: "редко",
  rather: "скорее / довольно",
  raw: "сырой",
  read: "читать",
  reader: "читатель",
  reading: "чтение / читающий",
  ready: "готовый",
  realised: "осознал",
  really: "действительно",
  receipt: "чек / квитанция",
  received: "получил",
  reception: "ресепшен / приём",
  reconciling: "сверяя / примиряя",
  record: "запись / рекорд",
  red: "красный",
  reflect: "отражать / размышлять",
  refusal: "отказ",
  rehearsing: "репетируя",
  rejected: "отклонённый",
  release: "выпуск / выпускать",
  reliable: "надёжный",
  remain: "оставаться",
  remaining: "оставшийся",
  remains: "остаётся / останки",
  remarks: "замечания",
  remember: "помнить",
  remembered: "вспомнил",
  reminded: "напомнил",
  renew: "обновлять / продлевать",
  repaint: "перекрашивать",
  repainted: "перекрасил",
  repaired: "починил",
  repairs: "ремонт / чинит",
  reply: "ответ / отвечать",
  report: "отчёт",
  reported: "сообщил",
  reportedly: "по сообщениям",
  reprinted: "перепечатанный",
  requested: "запросил",
  resigned: "ушёл в отставку",
  restaurant: "ресторан",
  restored: "восстановил",
  results: "результаты",
  retired: "на пенсии / ушёл",
  return: "возвращаться / возврат",
  reviewers: "рецензенты",
  revision: "пересмотр / редакция",
  rewritten: "переписанный",
  rice: "рис",
  ridden: "проехавший (ridden)",
  ridge: "хребет / гребень",
  right: "правильный / правый",
  ring: "кольцо / звонить",
  rings: "кольца / звонит",
  rise: "подниматься",
  river: "река",
  riverside: "берег реки",
  road: "дорога",
  roadworks: "дорожные работы",
  rome: "Рим",
  room: "комната",
  rose: "поднялся",
  roster: "расписание / список смен",
  round: "круглый / раунд",
  route: "маршрут",
  ruined: "разрушенный / испорченный",
  rule: "правило / править",
  rumour: "слух",
  rumoured: "по слухам",
  run: "бегать",
  russian: "русский",
  rust: "ржавчина",
  sad: "грустный",
  sag: "провисать",
  sagged: "провис",
  said: "сказал",
  sail: "парус / плыть под парусом",
  sailed: "отплыл",
  sale: "распродажа / продажа",
  salt: "соль",
  sam: "Сэм",
  same: "тот же",
  sample: "образец",
  samples: "образцы",
  sandbar: "песчаная отмель",
  sat: "сидел",
  saturday: "суббота",
  save: "спасать / сохранять",
  saved: "спас / сохранил",
  saw: "видел",
  say: "сказать",
  scanner: "сканер",
  scarcely: "едва",
  school: "школа",
  screen: "экран",
  sea: "море",
  sealed: "запечатанный",
  seals: "печати / тюлени",
  seat: "место / сиденье",
  seats: "места",
  second: "второй",
  security: "безопасность / охрана",
  see: "видеть",
  seeking: "ищущий / в поисках",
  seem: "казаться",
  seems: "кажется",
  seen: "увиденный",
  seldom: "редко",
  sell: "продавать",
  sells: "продаёт",
  send: "отправлять",
  sending: "отправка / отправляющий",
  sensor: "датчик",
  sensors: "датчики",
  sent: "отправил",
  sentence: "предложение",
  sequel: "продолжение",
  series: "серия / сериал",
  serious: "серьёзный",
  seven: "семь",
  shall: "shall",
  share: "делиться / доля",
  sharpest: "самый острый",
  she: "она",
  she'll: "она будет",
  sheep: "овца / овцы",
  shelf: "полка",
  shift: "смена / сдвигать",
  shifted: "сдвинул / сменил",
  shifts: "смены / сдвигает",
  ship: "корабль / отправлять",
  shocked: "шокированный",
  shoes: "обувь",
  shop: "магазин",
  short: "короткий",
  shortage: "нехватка",
  shot: "выстрел / кадр",
  should: "следует",
  show: "показывать",
  shower: "душ / ливень",
  shut: "закрыть / закрытый",
  side: "сторона",
  sign: "знак / подписывать",
  signal: "сигнал",
  signed: "подписал",
  signs: "знаки / подписывает",
  simple: "Simple (время)",
  sin: "грех",
  since: "с / с тех пор как",
  sing: "петь",
  singular: "единственное число",
  siren: "сирена",
  sister: "сестра",
  sisters: "сёстры",
  sit: "сидеть",
  sitting: "сидящий / заседание",
  six: "шесть",
  skeleton: "скелет",
  skip: "пропускать",
  skipper: "шкипер / капитан",
  skippers: "шкиперы",
  skips: "пропускает",
  sky: "небо",
  slack: "слабый / простой",
  sleep: "спать",
  sleeping: "спящий / сон",
  sleeps: "спит",
  slides: "слайды / скользит",
  slow: "медленный",
  slowly: "медленно",
  small: "маленький",
  smelled: "пах / понюхал",
  smelling: "пахнущий",
  smoke: "дым / курить",
  smoking: "курение",
  snow: "снег",
  snowed: "шёл снег",
  so: "так / поэтому",
  sockets: "розетки",
  sofa: "диван",
  solicitor: "адвокат (брит.)",
  solo: "соло / один",
  some: "несколько / немного",
  someone: "кто-то",
  sometimes: "иногда",
  son: "сын",
  song: "песня",
  soon: "скоро",
  sooner: "скорее / раньше",
  sorry: "извините",
  sorting: "сортировка",
  soup: "суп",
  space: "пространство / космос",
  spain: "Испания",
  spanish: "испанский",
  spare: "запасной / щадить",
  speak: "говорить",
  speaks: "говорит",
  spilled: "разлил",
  split: "разделить / раскол",
  spoke: "говорил",
  spoken: "сказанный / spoken",
  sport: "спорт",
  spots: "пятна / места",
  spotted: "заметил / в крапинку",
  sprained: "растянул (связку)",
  spring: "весна / пружина",
  stacked: "сложенный штабелем",
  staff: "персонал",
  stained: "испачканный / с пятном",
  stale: "чёрствый / несвежий",
  stamp: "марка / штамп",
  stand: "стоять",
  standing: "стоящий / положение",
  stands: "стоит / стенды",
  start: "начинать",
  started: "начал",
  starts: "начинает / старты",
  station: "вокзал / станция",
  stay: "оставаться",
  stayed: "остался",
  staying: "оставаясь / пребывание",
  stays: "остаётся",
  steel: "сталь",
  stew: "рагу / тушёное",
  still: "всё ещё",
  stills: "кадры / всё ещё (редко)",
  stock: "запас / акции",
  stole: "украл",
  stolen: "украденный",
  stood: "стоял",
  stop: "останавливать / остановка",
  stopped: "остановился",
  stops: "останавливается / остановки",
  store: "магазин",
  storm: "шторм / буря",
  story: "история",
  street: "улица",
  streets: "улицы",
  stuck: "застрявший",
  student: "студент / ученик",
  students: "студенты / ученики",
  studied: "учил(ся)",
  studies: "учёба / изучает",
  studio: "студия",
  study: "учиться",
  subject: "подлежащее",
  subtitle: "субтитры / подзаголовок",
  sugar: "сахар",
  suggest: "предлагать / советовать",
  suggested: "предложил",
  suitcase: "чемодан",
  sun: "солнце",
  sunday: "воскресенье",
  sundays: "воскресенья",
  supermarket: "супермаркет",
  suppose: "полагать / допустим",
  surprised: "удивлённый",
  surveyor: "землемер / инспектор",
  survive: "выживать",
  sushi: "суши",
  suspect: "подозревать / подозреваемый",
  swept: "подмёл / смело",
  swim: "плавать",
  switch: "переключатель / переключать",
  switched: "переключил",
  table: "стол",
  tables: "столы / таблицы",
  tail: "хвост",
  take: "брать",
  taken: "взятый",
  takes: "берёт / занимает",
  taking: "беря / съёмка",
  talk: "говорить / разговор",
  talking: "говорящий / разговор",
  tall: "высокий",
  taller: "выше",
  tallest: "самый высокий",
  tanks: "баки / танки",
  tartu: "Тарту",
  task: "задача",
  taxi: "такси",
  tea: "чай",
  teach: "учить (кого-то)",
  teacher: "учитель",
  teachers: "учителя",
  teaches: "учит",
  team: "команда",
  teenager: "подросток",
  tell: "рассказать / сказать кому-то",
  ten: "десять",
  tend: "иметь тенденцию / ухаживать",
  tender: "нежный / тендер",
  tennis: "теннис",
  terminated: "прекращённый / уволенный",
  terrible: "ужасный",
  test: "тест / проверять",
  tested: "протестировал",
  tests: "тесты",
  texted: "написал SMS",
  than: "чем",
  thank: "благодарить",
  thanks: "спасибо",
  that: "тот / та (далеко)",
  the: "определённый артикль",
  their: "их",
  theirs: "их (абсолютное)",
  them: "им / их",
  then: "тогда / затем",
  there: "там",
  these: "эти (близко)",
  they: "они",
  think: "думать",
  third: "третий",
  thirsty: "хочется пить",
  this: "этот / эта (близко)",
  those: "те (далеко)",
  though: "хотя / однако",
  thought: "думал / мысль",
  thousand: "тысяча",
  threatened: "угрожал",
  three: "три",
  through: "через",
  throw: "бросать",
  thrown: "брошенный",
  thursday: "четверг",
  thursdays: "четверги",
  ticket: "билет",
  tickets: "билеты",
  tide: "прилив / отлив",
  tidy: "аккуратный / убирать",
  tight: "тугой / тесный",
  time: "время",
  timetable: "расписание",
  tin: "жесть / банка",
  tins: "банки",
  tired: "уставший",
  to: "к / в / инфинитив",
  today: "сегодня",
  tokens: "жетоны / токены",
  tokyo: "Токио",
  told: "сказал / рассказал",
  tom: "Том",
  tomato: "помидор",
  tomatoes: "помидоры",
  tomorrow: "завтра",
  tone: "тон",
  tonight: "сегодня вечером",
  too: "тоже / слишком",
  took: "взял",
  top: "верх / верхний",
  tore: "порвал",
  touch: "трогать / касание",
  town: "городок",
  track: "путь / отслеживать",
  traffic: "движение / трафик",
  trail: "тропа / след",
  train: "поезд",
  trains: "поезда / тренирует",
  tram: "трамвай",
  transfer: "перевод / пересадка",
  travel: "путешествовать",
  tree: "дерево",
  tried: "пытался",
  trip: "поездка",
  true: "верный / истинный",
  try: "пытаться",
  tuesday: "вторник",
  turn: "поворачивать / очередь",
  turned: "повернул / оказался",
  turns: "поворачивает / очереди",
  turpentine: "скипидар",
  tv: "телевизор",
  twelve: "двенадцать",
  twenty: "двадцать",
  twice: "дважды",
  two: "два",
  unable: "неспособный",
  uncontested: "бесспорный",
  uncut: "неразрезанный",
  under: "под",
  underpass: "подземный переход",
  understand: "понимать",
  understood: "понял",
  undertaking: "обязательство / предприятие",
  union: "союз",
  university: "университет",
  unless: "если не",
  unlogged: "незаписанный",
  unredacted: "без цензуры / полный текст",
  unsent: "неотправленный",
  unstable: "нестабильный",
  until: "до тех пор пока",
  unused: "неиспользованный",
  unverified: "непроверенный",
  up: "вверх",
  updated: "обновлённый",
  upstairs: "наверху",
  us: "нам / нас",
  usb: "USB",
  use: "использовать",
  used: "использовал / подержанный",
  useful: "полезный",
  useless: "бесполезный",
  uses: "использует / применения",
  using: "используя",
  usually: "обычно",
  valley: "долина",
  varnish: "лак",
  vault: "свод / хранилище",
  vent: "отверстие / вымещать",
  verb: "глагол",
  verbal: "устный / словесный",
  versions: "версии",
  very: "очень",
  vest: "жилет",
  visit: "посещать / визит",
  visited: "посетил",
  visiting: "посещая",
  visitor: "посетитель",
  visitors: "посетители",
  visits: "визиты / посещает",
  vital: "жизненно важный",
  vote: "голос / голосовать",
  wagged: "вилял (хвостом)",
  wait: "ждать",
  waited: "ждал",
  waiting: "ожидание / ждущий",
  waits: "ждёт",
  waives: "отказывается (от права)",
  walk: "ходить пешком",
  walked: "шёл пешком",
  walking: "ходьба / идущий",
  wall: "стена",
  wallet: "кошелёк",
  want: "хотеть",
  wanted: "хотел / разыскиваемый",
  wanting: "желающий / недостаток",
  wants: "хочет",
  warm: "тёплый",
  warned: "предупредил",
  was: "был / была (Past)",
  washer: "шайба / стиралка",
  watch: "смотреть (фильм и т.п.)",
  watched: "смотрел",
  watches: "часы / смотрит",
  watching: "смотрящий / просмотр",
  water: "вода",
  way: "путь / способ",
  we: "мы",
  we'd: "мы бы",
  we'll: "мы будем",
  we're: "мы есть",
  we've: "мы имеем",
  wear: "носить (одежду)",
  weather: "погода",
  wednesday: "среда",
  week: "неделя",
  weekend: "выходные",
  weekends: "выходные дни",
  weeks: "недели",
  well: "хорошо / колодец",
  went: "ходил / ездил",
  were: "были (Past)",
  west: "запад / западный",
  wet: "мокрый",
  what: "что / какой",
  when: "когда",
  where: "где",
  whether: "ли / whether",
  which: "который",
  while: "пока / в то время как",
  white: "белый",
  who: "кто",
  whole: "весь / целый",
  whom: "кому / кого",
  whose: "чей",
  why: "почему",
  wife: "жена",
  will: "буду / will",
  win: "побеждать",
  wind: "ветер",
  window: "окно",
  windows: "окна",
  winter: "зима",
  wish: "желать / желание",
  wishes: "желает / пожелания",
  with: "с",
  withdraw: "снимать / отзывать",
  withdrawal: "снятие / вывод",
  withdrew: "снял / отозвал",
  without: "без",
  witness: "свидетель / свидетельствовать",
  woman: "женщина",
  women: "женщины",
  won: "выиграл",
  wonder: "удивляться / интересно",
  wondered: "задумался / удивился",
  word: "слово",
  work: "работать / работа",
  worked: "работал",
  working: "работающий / работа",
  works: "работает / работы",
  world: "мир",
  worse: "хуже",
  worst: "худший",
  would: "бы / would",
  wrecked: "разбитый / разрушенный",
  write: "писать",
  writing: "письмо / писание",
  written: "написанный",
  wrong: "неправильный",
  wrote: "написал",
  year: "год",
  years: "годы",
  yeast: "дрожжи",
  yellow: "жёлтый",
  yes: "да",
  yesterday: "вчера",
  yet: "ещё / уже (в вопросе/отриц.)",
  yoghurt: "йогурт",
  york: "Йорк",
  you: "ты / вы",
  you'll: "ты будешь",
  you're: "ты есть",
  young: "молодой",
  youngest: "самый младший",
  your: "твой / ваш",
  yours: "твой / ваш (абсолютное)",
};

/** Normalize a surface token to a glossary key (offline lookup only). */
export function lookupGloss(raw: string): string | null {
  const stripped = raw
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/^[^a-z']+|[^a-z']+$/gi, "");

  if (!stripped) return null;

  const direct = GLOSSARY[stripped];
  if (direct) return direct;

  // Possessive: teacher's → teacher
  if (stripped.endsWith("'s")) {
    const base = stripped.slice(0, -2);
    if (GLOSSARY[base]) return GLOSSARY[base];
  }

  // Negatives: doesn't → does + not; won't/can't special-cased
  if (stripped.endsWith("n't")) {
    const head = stripped.slice(0, -3);
    const mapped =
      head === "wo" ? "will" : head === "ca" ? "can" : head === "sha" ? "shall" : head;
    const g = GLOSSARY[mapped];
    const notG = GLOSSARY.not || "не";
    if (g) return `${g} + ${notG}`;
    return notG;
  }

  // Common clitic contractions
  const clitics: Record<string, string> = {
    "i'm": "i",
    "i've": "i",
    "i'll": "i",
    "i'd": "i",
    "you're": "you",
    "you've": "you",
    "you'll": "you",
    "you'd": "you",
    "he's": "he",
    "she's": "she",
    "it's": "it",
    "we're": "we",
    "we've": "we",
    "we'll": "we",
    "we'd": "we",
    "they're": "they",
    "they've": "they",
    "they'll": "they",
    "they'd": "they",
    "that's": "that",
    "there's": "there",
    "here's": "here",
    "who's": "who",
    "what's": "what",
    "where's": "where",
    "let's": "let",
  };
  const via = clitics[stripped];
  if (via && GLOSSARY[via]) return GLOSSARY[via];

  return null;
}
